import type { EducationGuideDefinition, GuideItem } from "@/lib/education-guide-batch";

export type AcademicExtraSection = {
  id: string;
  type: "text" | "cards" | "steps";
  heading: string;
  intro?: string;
  body?: string;
  items?: GuideItem[];
};

export type AcademicGuideDefinition = EducationGuideDefinition & {
  extraSections: AcademicExtraSection[];
};

function alts(label: string, project: string): EducationGuideDefinition["alts"] {
  return {
    hero: `${label} yazımı için kaynak, not, tablo ve İlkOku çalışma ekranı bulunan akademik çalışma masası`,
    ideaFlow: `${label} konusunun araştırma sorusuna ve akademik metin planına dönüşümünü gösteren eğitim akışı`,
    structure: `${label} metninin araştırma, kanıt ve bölüm düzenini gösteren akademik yapı diyagramı`,
    anatomy: `${label} eserinin soru, yöntem, kaynak, kanıt ve yorum parçalarını gösteren akademik eser anatomisi`,
    pageSetup: `${label} yazımı için kaynak yönetimi, notlar, sürümler ve çalışma dosyalarının düzenlendiği akademik çalışma alanı`,
    project: `${project} adlı örnek akademik projenin araştırma sorusu, kaynakları, yöntem ve taslak planını gösteren çalışma panosu`,
    finalCta: `${label} taslağını tamamlayıp İlkOku Yazar Alanı'nda düzenlemeye hazırlanan akademik çalışma ortamı`,
  };
}

const definitions: AcademicGuideDefinition[] = [
  {
    category: "Akademik",
    slug: "makale",
    label: "Makale",
    title: "Akademik Makale Nasıl Yazılır?",
    description: "Araştırma sorusundan literatür taramasına, yöntem, bulgu, tartışma, atıf ve gönderim kontrolüne kadar adım adım akademik makale yazma eğitimi.",
    summary: "Bir konuyu anlatmakla yetinme; araştırılabilir soruyu, izlenebilir yöntemi, güvenilir kanıtı ve sınırları açık bir akademik argümana dönüştür.",
    alts: alts("Akademik Makale", "Kentsel Isı Adaları ve Yaya Deneyimi"),
    orientationHeading: "Akademik makale, bilgi biriktiren metin değil savunulabilir araştırma iddiasıdır",
    orientationBody: "Makalenin merkezinde ‘ne biliyoruz?’ kadar ‘bu çalışmanın eklediği şey nedir?’ sorusu bulunur. Okur; araştırma sorusunu, yöntemi, kanıtı, yorumun sınırlarını ve kaynak izini görebilmelidir. Güçlü akademik yazı, iddiasını kanıttan daha büyük kurmaz.",
    ideaHeading: "Makale konusunu araştırılabilir probleme dönüştür",
    ideaIntro: "Geniş bir ilgi alanını, veri veya kaynakla cevaplanabilecek dar bir soruya indir.",
    ideaItems: [
      { title: "Literatür boşluğu", text: "Çalışmaların cevaplamadığı, çeliştiği veya güncel bağlamda yeniden sınanması gereken noktayı bul." },
      { title: "Gözlenen problem", text: "Sahada, kurumda, arşivde veya veri setinde tekrar eden bir sorunu araştırma sorusuna çevir." },
      { title: "Kuram sınaması", text: "Bir kavramın farklı örneklem, dönem veya bağlamda nasıl çalıştığını sınamayı düşün." },
      { title: "Yöntem fırsatı", text: "Yeni veri, karşılaştırma veya ölçüm biçiminin hangi soruyu daha iyi cevaplayabileceğini sor." },
    ],
    ideaFlowHeading: "Konudan araştırma sorusuna, sorudan katkı iddiasına geç",
    ideaFlowBody: "‘Kentlerde sıcaklık artışı’ yalnız konudur. ‘Yaz aylarında gölgesiz yaya akslarında yüzey sıcaklığı ile yaya bekleme süresi arasında nasıl bir ilişki vardır?’ araştırma sorusudur. Ardından hangi veriyle, hangi yöntemle ve hangi sınırlar içinde cevap vereceğini tanımlarsın.",
    contrastHeading: "Akademik makaleyi benzer metinlerden ayır",
    contrastIntro: "Biçim benzer görünse bile kanıt standardı farklıdır.",
    contrastItems: [
      { title: "Makale ≠ deneme", text: "Kişisel düşünce serbestçe ilerlemez; iddialar kaynak, yöntem ve kanıtla sınanır." },
      { title: "Makale ≠ rapor özeti", text: "Veriyi sıralamak yerine araştırma sorusuna cevap veren argüman kurar." },
      { title: "Makale ≠ literatür dökümü", text: "Kaynakları tek tek anlatmak yerine aralarındaki ilişkiyi ve boşluğu sentezler." },
    ],
    routeHeading: "Akademik makaleyi 10 aşamada kur",
    routeIntro: "Yazıya başlamadan önce araştırma mantığını görünür hale getir.",
    routeItems: [
      { title: "1 · Problem", text: "Araştırılmaya değer sorunun bağlamını ve önemini tanımla." },
      { title: "2 · Araştırma sorusu", text: "Tek, açık ve cevaplanabilir ana soruyu yaz." },
      { title: "3 · Literatür taraması", text: "Ana kavramları, uzlaşıları, çelişkileri ve boşluğu haritala." },
      { title: "4 · Katkı", text: "Çalışmanın neyi yeni, daha net veya farklı göstereceğini sınırlarıyla yaz." },
      { title: "5 · Yöntem", text: "Örneklem, veri, araç, prosedür ve analiz biçimini belirle." },
      { title: "6 · Analiz", text: "Soruyu cevaplayacak işlemleri önceden tanımla ve uygula." },
      { title: "7 · Bulgular", text: "Verinin gösterdiğini yorumdan ayırarak sun." },
      { title: "8 · Tartışma", text: "Bulguyu literatür, kuram ve alternatif açıklamalarla ilişkilendir." },
      { title: "9 · Sınırlılıklar", text: "Çalışmanın neyi söyleyemediğini açıkça belirt." },
      { title: "10 · Gönderim", text: "Dergi kapsamı, biçim, etik beyan ve kaynakça kontrolünü tamamla." },
    ],
    structureHeading: "Makalenin bölümleri birbirini kanıt zinciriyle taşısın",
    structureIntro: "Her bölüm bir önceki sorunun doğal devamı olmalı.",
    structureItems: [
      { title: "Giriş", text: "Problem → mevcut bilgi → boşluk → soru → katkı zincirini kur." },
      { title: "Literatür / çerçeve", text: "Kavram ve bulguları tematik olarak sentezle." },
      { title: "Yöntem", text: "Bir başkasının çalışmayı anlayıp değerlendirebileceği açıklığı sağla." },
      { title: "Bulgular", text: "Analizin ürettiği sonucu düzenli ve ölçülü biçimde sun." },
      { title: "Tartışma", text: "Sonucun ne anlama geldiğini, neyle uyumlu veya çelişkili olduğunu açıkla." },
      { title: "Sonuç", text: "Katkı, sınır ve sonraki araştırma yönünü kısa biçimde kapat." },
    ],
    structureCaption: "Akademik makale yapısı, soru ile sonuç arasında izlenebilir bir kanıt zinciri kurar.",
    anatomyHeading: "Makalenin anatomisi: soru, yöntem, kanıt, yorum ve sınır",
    anatomyBody: "- **Araştırma sorusu:** Metnin gerçekten cevapladığı şey.\n- **Literatür boşluğu:** Çalışmanın neden gerekli olduğunu gösterir.\n- **Yöntem:** Kanıtın nasıl üretildiğini açıklar.\n- **Bulgular:** Verinin veya kaynak analizinin ortaya koyduğu sonuç.\n- **Tartışma:** Bulguyu bağlama ve literatüre yerleştirir.\n- **Sınırlılık:** Sonucun genellenebileceği sınırı belirtir.\n- **Atıf izi:** Her dış iddianın kaynağını görünür kılar.",
    practiceHeading: "Makale yazarken beş ayrı çalışma dosyası tut",
    practiceIntro: "Kaynak, veri ve argümanı tek belgede boğma.",
    practiceItems: [
      { title: "Kaynak matrisi", text: "Kaynak, yöntem, örneklem, temel bulgu ve senin çalışmanla ilişkisini sütunlarda izle." },
      { title: "İddia–kanıt tablosu", text: "Her önemli iddianın hangi veri veya kaynağa dayandığını eşleştir." },
      { title: "Yöntem günlüğü", text: "Analiz kararlarını ve değişikliklerini tarihli kaydet." },
      { title: "Sınırlılık listesi", text: "Her yorumun nerede aşırı genellemeye kayabileceğini not et." },
      { title: "Kaynakça yöneticisi", text: "Atıf verisini en baştan düzenli tut; son gün elle toplamaya çalışma." },
    ],
    pageSetupCaption: "Akademik makale çalışma düzeni, kaynak ile iddiayı ve yöntem kararıyla sonucu birbirine bağlar.",
    workspaceHeading: "Makale dosyanı kanıt izlenebilirliğiyle düzenle",
    workspaceIntro: "Revizyonda her cümlenin nereden geldiğini bulabilmelisin.",
    workspaceItems: [
      { title: "Bölüm amacı", text: "Her bölümün cevapladığı soruyu üst notta yaz." },
      { title: "Kaynak kodu", text: "Notlarını tam bibliyografik kayıtla eşleştir." },
      { title: "Tablo–metin bağı", text: "Her tablo veya şeklin hangi iddiayı desteklediğini belirt." },
      { title: "Sürüm disiplini", text: "Analiz ve metin değişikliklerini ayrı sürümlerde tut." },
    ],
    craftHeading: "Akademik makalenin asıl zanaatı: iddianın büyüklüğünü kanıtın gücüne uydurmak",
    craftBody: "Veri ‘ilişki’ gösteriyorsa ‘neden oldu’ deme; sınırlı bir örneklem varsa evrene yayma; tek kaynağı literatür uzlaşısı gibi sunma. Akademik güven, büyük cümleden değil ölçülü ve izlenebilir cümleden doğar.",
    extraSections: [
      {
        id: "literatur-stratejisi",
        type: "steps",
        heading: "Literatür taramasını arama kutusundan sistematik senteze taşı",
        intro: "Amaç çok kaynak toplamak değil, alanın düşünce haritasını kurmaktır.",
        items: [
          { title: "Anahtar kavramları çıkar", text: "Sorudaki kavramların eş ve yakın terimlerini yaz." },
          { title: "Arama dizilerini kaydet", text: "Hangi veri tabanında hangi terimlerle aradığını izlenebilir tut." },
          { title: "Dahil etme ölçütü koy", text: "Hangi kaynakların neden içeri girdiğini veya dışarıda kaldığını belirle." },
          { title: "Tematik sentez yap", text: "Kaynakları yazar sırasıyla değil görüş, yöntem ve bulgu kümeleriyle birleştir." },
        ],
      },
      {
        id: "yontem-bulgu-yorum",
        type: "cards",
        heading: "Yöntem, bulgu ve yorumu birbirine karıştırma",
        intro: "Akademik metinde üç katmanın sınırı açık olmalıdır.",
        items: [
          { title: "Yöntem", text: "Ne yaptığını ve neden o yolu seçtiğini açıkla." },
          { title: "Bulgu", text: "Analizin doğrudan ürettiği sonucu sun." },
          { title: "Yorum", text: "Bulgudan hangi anlamın çıkarılabileceğini tartış." },
          { title: "Alternatif açıklama", text: "Aynı bulgunun başka neyle açıklanabileceğini sınamadan geçme." },
        ],
      },
      {
        id: "etik-atif-seffaflik",
        type: "cards",
        heading: "Araştırma etiği, atıf ve şeffaflık son kontrol değil yazımın parçasıdır",
        intro: "Kaynağı ve araştırma kararlarını baştan izlenebilir tut.",
        items: [
          { title: "Doğru atıf", text: "Başkasının düşüncesini yalnız kelimeleri değiştirerek kaynak göstermeden kullanma." },
          { title: "Etik onay / onam", text: "Gerekli araştırmalarda izin ve katılımcı onamını yöntemden önce planla." },
          { title: "Çıkar çatışması", text: "Finansman ve ilişki beyanlarını gizleme." },
          { title: "Veri şeffaflığı", text: "Mümkün olduğunda veri, kod, materyal ve analiz kararlarını erişilebilir veya açıklanabilir kıl." },
        ],
      },
    ],
    draftHeading: "İlk taslakta önce mantık zincirini tamamla",
    draftIntro: "Cümleleri cilalamadan önce soru–yöntem–bulgu–tartışma ilişkisinin çalıştığını gör.",
    draftItems: [
      { title: "Girişe son şeklini verme", text: "Analiz tamamlanmadan katkı cümlesini kesinleştirme." },
      { title: "Bulguyu yorumdan ayır", text: "İlk taslakta bile veri ile çıkarımı ayrı paragraflarda tut." },
      { title: "Her paragrafta tek iş", text: "Ana cümle, kanıt, açıklama ve geçiş düzenini koru." },
      { title: "Kaynağı anında ekle", text: "‘Sonra koyarım’ diye atıf boşluğu bırakma." },
    ],
    revisionHeading: "Makale revizyonunu dört ayrı turda yap",
    revisionIntro: "İçerik, kanıt, dil ve biçimi aynı anda düzeltmeye çalışma.",
    revisionItems: [
      { title: "Argüman turu", text: "Soru gerçekten cevaplanıyor mu ve sonuç katkı iddiasını aşıyor mu?" },
      { title: "Kanıt turu", text: "Her iddianın yeterli veri veya kaynak dayanağı var mı?" },
      { title: "Paragraf turu", text: "Her paragrafın tek görevi ve açık geçişi var mı?" },
      { title: "Kaynak / biçim turu", text: "Atıf, kaynakça, tablo, şekil ve dergi kuralları tutarlı mı?" },
    ],
    projectName: "Kentsel Isı Adaları ve Yaya Deneyimi",
    projectBody: "**Soru:** Yaz aylarında gölgesiz yaya akslarında yüzey sıcaklığı ile yaya bekleme süresi arasında nasıl bir ilişki vardır?\n\n**Veri:** Üç farklı mahallede aynı saat diliminde yüzey sıcaklığı ölçümü + anonim yaya gözlemi.\n\n**Literatür boşluğu:** Isı ölçümleri yaygın; gündelik yaya davranışıyla birlikte ele alan yerel çalışma sınırlı.\n\n**Yöntem:** Karşılaştırmalı gözlemsel tasarım; aynı gün ve saat aralıkları; standart gözlem formu.\n\n**Sınır:** İlişki gözlemlenir; nedensellik iddia edilmez.",
    projectCaption: "Örnek makale projesi, araştırma sorusu ile veri ve iddia düzeyi arasındaki dengeyi gösterir.",
    sampleHeading: "Örnek akademik paragraf: iddia + kanıt + sınır",
    sampleBody: "Gölgesiz duraklarda medyan bekleme süresi daha kısa gözlenmiştir. Ancak bu fark, yalnız yüzey sıcaklığına bağlanamaz; hat sıklığı ve yolcu yoğunluğu gibi değişkenler de davranışı etkileyebilir. Bu nedenle bulgu, sıcaklıkla ilişkili bir davranış örüntüsü olarak yorumlanmıştır.",
    finalHeading: "Gönderim öncesi bilimsel ve editoryal kontrolü tamamla",
    finalIntro: "Metni yalnız yazım hatası için değil araştırma iddiasının güvenilirliği için de denetle.",
    finalItems: [
      { title: "Soru–sonuç uyumu", text: "Sonuç gerçekten araştırma sorusunu cevaplıyor mu?" },
      { title: "Atıf bütünlüğü", text: "Dış iddialar kaynaklı, kaynakça kayıtları tam mı?" },
      { title: "Etik / beyan", text: "Gerekli izin, finansman ve çıkar çatışması beyanları hazır mı?" },
      { title: "Dergi uyumu", text: "Kapsam, kelime sınırı, biçim ve dosya gereklilikleri karşılanıyor mu?" },
    ],
    outputsHeading: "Bu eğitimden altı somut çıktı ile çık",
    outputsIntro: "Makaleyi yalnız anlamak değil, gerçek araştırma dosyasını kurmak hedeflenir.",
    outputItems: [
      { title: "1 araştırma sorusu", text: "Dar, açık ve cevaplanabilir ana sorunu yaz." },
      { title: "1 literatür matrisi", text: "En az temel kaynakları tema, yöntem ve bulguyla karşılaştır." },
      { title: "1 yöntem özeti", text: "Örneklem, veri, prosedür ve analiz planını yaz." },
      { title: "1 iddia–kanıt tablosu", text: "Ana sonuçların hangi kanıta dayandığını eşleştir." },
      { title: "1 örnek sonuç paragrafı", text: "Bulguyu ölçülü akademik dille yaz." },
      { title: "1 sınırlılık listesi", text: "Çalışmanın söyleyemediği şeyleri açıkla." },
    ],
    mastersIntro: "Araştırma sorusu, argüman, açıklık ve akademik yazı disiplinini farklı kaynaklardan incele.",
    masters: [
      { title: "Wayne C. Booth ve çalışma arkadaşları", text: "Araştırma sorusunu probleme ve savunulabilir iddiaya dönüştürme yaklaşımını incele." },
      { title: "John W. Creswell", text: "Araştırma tasarımı ile soru, veri ve yöntem uyumunu incele." },
      { title: "Umberto Eco", text: "Kaynak çalışma, konu sınırı ve araştırma disiplinine dair yaklaşımını incele." },
    ],
    faq: [
      { question: "Makalenin girişini önce mi yazmalıyım?", answer: "Taslak giriş erken yazılabilir; ancak analiz ve tartışma tamamlandıktan sonra boşluk ve katkı cümleleri yeniden kontrol edilmelidir." },
      { question: "Çok kaynak kullanmak makaleyi güçlü yapar mı?", answer: "Tek başına hayır. Kaynakların uygun, güvenilir ve araştırma sorusuyla ilişkili olması; ayrıca sentezlenmesi gerekir." },
      { question: "Olumsuz veya beklenmedik sonuç yazılır mı?", answer: "Evet. Sonuç beklentiyi desteklemiyorsa bunu gizlemek yerine yöntem ve sınırlılıklarla birlikte dürüstçe raporlamak gerekir." },
    ],
    finalCaption: "Akademik makale, iddiası kanıtından büyük olmadığında ve araştırma yolu okur tarafından izlenebildiğinde güvenilir hale gelir.",
    ctaHeading: "Makale araştırma dosyanı kur",
    ctaText: "Sorun, literatür haritan ve yöntem planın hazırsa İlkOku Yazar Alanı'nda makale taslağını oluşturmaya başla.",
  },
  {
    category: "Akademik",
    slug: "arastirma",
    label: "Araştırma",
    title: "Akademik Araştırma Nasıl Yapılır ve Yazılır?",
    description: "Araştırma probleminden tasarıma, örneklem, veri toplama, analiz, etik, raporlama ve yeniden üretilebilirliğe kadar adım adım akademik araştırma eğitimi.",
    summary: "Merakı sistemli araştırmaya dönüştür: doğru soruyu kur, uygun yöntemi seç, veriyi izlenebilir biçimde üret ve sonucu sınırlarıyla raporla.",
    alts: alts("Akademik Araştırma", "Uzaktan Çalışma ve Günlük Odak Süresi"),
    orientationHeading: "Araştırma, sonuca ulaşma tekniği değil güvenilir soru sorma ve sınama sürecidir",
    orientationBody: "Araştırmacı istediği sonucu kanıtlamaya değil, soruyu en uygun veri ve yöntemle sınamaya çalışır. İyi tasarım; soru, örneklem, ölçüm, analiz ve yorum arasında uyum kurar. Yöntem seçimi sonuçtan sonra değil, veri toplanmadan önce düşünülür.",
    ideaHeading: "Araştırma problemini gözlem, çelişki ve boşluktan çıkar",
    ideaIntro: "Önce sorunun neden araştırmaya değer olduğunu kanıtla.",
    ideaItems: [
      { title: "Gözlenen örüntü", text: "Tekrarlanan ama açıklaması belirsiz bir davranış, süreç veya sonuç seç." },
      { title: "Çelişen bulgular", text: "Literatürde farklı sonuç veren çalışmaların neden ayrıştığını sor." },
      { title: "Eksik grup / bağlam", text: "Mevcut bilginin kapsamadığı örneklem, coğrafya veya zaman aralığını araştır." },
      { title: "Uygulama sorunu", text: "Gerçek hayatta karar vermeyi zorlaştıran bilgi eksikliğini ölçülebilir soruya dönüştür." },
    ],
    ideaFlowHeading: "Meraktan araştırma tasarımına geç",
    ideaFlowBody: "‘Uzaktan çalışmak verimli mi?’ çok geniştir. ‘Haftada en az üç gün uzaktan çalışan bilgi çalışanlarında toplantı yoğunluğu ile kesintisiz odak bloklarının süresi nasıl ilişkilidir?’ sorusu ise örneklem, değişken ve veri toplama planı kurmaya izin verir.",
    contrastHeading: "Araştırmayı bilgi toplamaktan ayır",
    contrastIntro: "Kaynak veya veri yığını araştırma tasarımı değildir.",
    contrastItems: [
      { title: "Araştırma ≠ internet taraması", text: "Kaynak bulmak başlangıçtır; yöntemli soru ve analiz gerekir." },
      { title: "Araştırma ≠ anket yapmak", text: "Anket yalnız veri toplama aracıdır; tasarımın kendisi değildir." },
      { title: "Araştırma ≠ sonuç aramak", text: "Hipotezi desteklemeyen veri de araştırmanın sonucudur." },
    ],
    routeHeading: "Araştırmayı 11 aşamada kur",
    routeIntro: "Veriyi toplamadan önce tasarım kararlarını görünür hale getir.",
    routeItems: [
      { title: "1 · Problem", text: "Bilgi açığını ve önemini tanımla." },
      { title: "2 · Soru / hipotez", text: "Araştırmanın neyi sınayacağını açıkça yaz." },
      { title: "3 · Literatür", text: "Kavramları, ölçümleri ve önceki sonuçları haritala." },
      { title: "4 · Tasarım", text: "Nicel, nitel, karma, deneysel, gözlemsel veya uygun başka yaklaşımı seç." },
      { title: "5 · Örneklem", text: "Kimden, nereden, ne kadar ve neden veri toplanacağını belirle." },
      { title: "6 · Ölçüm / veri kaynağı", text: "Değişkenleri veya nitel veriyi nasıl üreteceğini tanımla." },
      { title: "7 · Etik", text: "Onam, gizlilik, risk ve veri güvenliği kararlarını planla." },
      { title: "8 · Veri toplama", text: "Protokole sadık ve kayıtlı biçimde uygula." },
      { title: "9 · Analiz", text: "Soruyla uyumlu analiz yöntemini kullan." },
      { title: "10 · Yorum", text: "Bulguyu alternatif açıklamalar ve sınırlılıklarla değerlendir." },
      { title: "11 · Raporlama", text: "Yöntem ve sonucu başkasının değerlendirebileceği açıklıkta yaz." },
    ],
    structureHeading: "Araştırma dosyasını karar zinciri olarak kur",
    structureIntro: "Her tasarım kararı bir önceki sorudan türesin.",
    structureItems: [
      { title: "Problem", text: "Neyi bilmiyoruz?" },
      { title: "Soru", text: "Tam olarak neyi öğrenmek istiyoruz?" },
      { title: "Tasarım", text: "Bu soruyu hangi araştırma mantığı cevaplar?" },
      { title: "Veri", text: "Hangi gözlem veya kayıt kanıt oluşturur?" },
      { title: "Analiz", text: "Veriyi hangi işlem anlamlı hale getirir?" },
      { title: "Yorum", text: "Sonuç ne söyler, ne söylemez?" },
    ],
    structureCaption: "Araştırmanın yapısı, yöntem araçlarından önce soru ile kanıt arasında mantıksal uyum kurar.",
    anatomyHeading: "Araştırmanın anatomisi: tasarım kararlarını görünür kıl",
    anatomyBody: "- **Problem:** Bilgi açığı.\n- **Araştırma sorusu / hipotez:** Sınanacak ifade.\n- **Evren ve örneklem:** Sonucun kimi temsil ettiği.\n- **Ölçüm / veri üretimi:** Kanıtın nasıl elde edildiği.\n- **Analiz:** Veriye uygulanan işlem.\n- **Etik:** Katılımcı ve veri sorumluluğu.\n- **Sınırlılık:** Sonucun geçerli olduğu sınır.",
    practiceHeading: "Araştırma için beş kontrol dosyası tut",
    practiceIntro: "Tasarımı hafızaya değil kayda bağla.",
    practiceItems: [
      { title: "Araştırma protokolü", text: "Soru, örneklem, veri, analiz ve etik adımları tek belgede sabitle." },
      { title: "Değişken / kod kitabı", text: "Her ölçüm veya kodun tanımını, birimini ve kaynağını yaz." },
      { title: "Karar günlüğü", text: "Tasarım ve analiz değişikliklerinin nedenini tarihli tut." },
      { title: "Veri sözlüğü", text: "Dosya, sütun, eksik değer ve dönüşüm kurallarını açıkla." },
      { title: "Sapma kaydı", text: "Planlanan yöntemden ayrıldıysan neyin neden değiştiğini kaydet." },
    ],
    pageSetupCaption: "Araştırma çalışma düzeni, soru ile veri arasındaki tüm kararları geriye dönük izlenebilir kılar.",
    workspaceHeading: "Araştırma klasörünü ham veri ile yorumu ayıracak biçimde düzenle",
    workspaceIntro: "Orijinal veri, temizlenmiş veri, analiz ve rapor birbirine karışmasın.",
    workspaceItems: [
      { title: "01-protokol", text: "Onaylı veya güncel araştırma planını sakla." },
      { title: "02-ham-veri", text: "Üzerine yazma; orijinal veriyi değişmeden koru." },
      { title: "03-temiz-veri", text: "Dönüşüm ve temizlik sonrası çalışma kopyasını tut." },
      { title: "04-analiz", text: "Kod, çıktı ve yorum notlarını sürümlü sakla." },
    ],
    craftHeading: "Araştırmanın asıl zanaatı: soru ile yöntem arasında uyum kurmak",
    craftBody: "Nedensel bir soru gözlemsel veriyle sınırsız biçimde cevaplanamaz; küçük ve seçilmiş örneklem tüm nüfusu temsil etmeyebilir; öz-bildirim ile gerçek davranış aynı şey değildir. Yöntem seçiminin gücü ve sınırı, sonuç cümlesinin sınırını belirler.",
    extraSections: [
      {
        id: "tasarim-secimi",
        type: "cards",
        heading: "Araştırma tasarımını sorunun yapısına göre seç",
        intro: "Yöntemi alışkanlıktan değil araştırma sorusundan türet.",
        items: [
          { title: "Betimleyici", text: "Bir durumun dağılımını, sıklığını veya özelliklerini ortaya koyar." },
          { title: "İlişkisel", text: "Değişkenlerin birlikte değişip değişmediğini inceler; tek başına nedensellik kurmaz." },
          { title: "Deneysel / yarı deneysel", text: "Müdahale ve karşılaştırmayla nedensel çıkarımı güçlendirmeyi amaçlar." },
          { title: "Nitel", text: "Deneyim, anlam, süreç ve bağlamı derinlemesine anlamaya odaklanır." },
          { title: "Karma", text: "Nicel ve nitel veriyi tek sorunun farklı katmanlarını cevaplamak için birlikte kullanır." },
        ],
      },
      {
        id: "orneklem-ve-olcum",
        type: "steps",
        heading: "Örneklem ve ölçüm hatasını veri toplamadan önce azalt",
        intro: "Kötü ölçümü büyük veriyle telafi edemezsin.",
        items: [
          { title: "Hedef evreni tanımla", text: "Sonucu hangi gruba genellemek istediğini açıkla." },
          { title: "Örnekleme yolunu yaz", text: "Katılımcı veya birimlerin araştırmaya nasıl girdiğini belirt." },
          { title: "Ölçüm geçerliliğini sorgula", text: "Araç gerçekten ölçmek istediğin kavramı ölçüyor mu?" },
          { title: "Pilot uygula", text: "Sorular, süreç ve veri akışındaki sorunları küçük ölçekte test et." },
          { title: "Eksik veri planı yap", text: "Eksik veya hatalı kayıtları nasıl ele alacağını önceden düşün." },
        ],
      },
      {
        id: "etik-veri-yonetimi",
        type: "cards",
        heading: "Etik ve veri yönetimini araştırmanın omurgasına yerleştir",
        intro: "Katılımcı hakları ve veri güvenliği sonradan eklenen formalite değildir.",
        items: [
          { title: "Bilgilendirilmiş onam", text: "Katılımcı neye katıldığını ve haklarını anlayabilmeli." },
          { title: "Gizlilik", text: "Kişisel veya hassas verinin kimlikten ayrılması ve erişim kontrolünü planla." },
          { title: "Veri saklama", text: "Dosyaların nerede, ne kadar süre ve kimlerin erişimiyle tutulacağını belirle." },
          { title: "Yeniden üretilebilirlik", text: "Mümkünse analiz adımlarını, kodu ve veri dönüşümlerini tekrar edilebilir kıl." },
        ],
      },
    ],
    draftHeading: "Araştırma raporunun ilk taslağını sonuçtan geriye doğru kur",
    draftIntro: "Önce ne yaptığını ve ne bulduğunu açıklaştır, sonra giriş ve bağlamı keskinleştir.",
    draftItems: [
      { title: "Yöntemi yaz", text: "Prosedür hafızadayken ayrıntıları kaydet." },
      { title: "Bulguları düzenle", text: "Araştırma sorusuna göre tablo, tema veya analiz çıktısını sırala." },
      { title: "Tartışmayı yaz", text: "Bulguyu literatür ve alternatif açıklamalarla sınırla." },
      { title: "Girişi yenile", text: "Araştırmanın gerçekten yaptığı katkıya göre problemi tekrar yaz." },
    ],
    revisionHeading: "Araştırma revizyonunda tasarım hatasını dil düzeltmesinden önce ara",
    revisionIntro: "Güzel yazılmış zayıf yöntem, güçlü araştırma değildir.",
    revisionItems: [
      { title: "Soru–yöntem testi", text: "Seçilen yöntem soruyu gerçekten cevaplayabilir mi?" },
      { title: "Örneklem testi", text: "Sonuç cümlesi örneklemin temsil gücünü aşıyor mu?" },
      { title: "Analiz testi", text: "İşlem önceden tanımlı ve veri türüyle uyumlu mu?" },
      { title: "Şeffaflık testi", text: "Değişiklikler, dışlanan veriler ve beklenmedik sonuçlar açık mı?" },
    ],
    projectName: "Uzaktan Çalışma ve Günlük Odak Süresi",
    projectBody: "**Soru:** Haftada en az üç gün uzaktan çalışan bilgi çalışanlarında toplantı yoğunluğu ile kesintisiz odak bloklarının süresi nasıl ilişkilidir?\n\n**Tasarım:** Dört haftalık günlük çalışma kaydı + takvim verisi + kısa haftalık görüşme.\n\n**Örneklem:** Farklı ekiplerden gönüllü katılımcılar; genelleme sınırı açıkça belirtilir.\n\n**Analiz:** Toplantı süresi ile odak bloklarının ilişkisi; görüşmelerle bağlamsal açıklama.\n\n**Etik:** Takvim başlıkları değil yalnız süre verisi alınır; kişisel toplantı içeriği toplanmaz.",
    projectCaption: "Örnek araştırma, soru, veri kaynağı, mahremiyet ve yorum sınırını birlikte planlar.",
    sampleHeading: "Örnek yöntem cümlesi: yeniden anlaşılabilir açıklık",
    sampleBody: "Katılımcılar dört hafta boyunca 30 dakikadan uzun kesintisiz odak bloklarını günlük forma kaydetti. Takvim entegrasyonundan yalnız toplam toplantı süresi ve toplantı sayısı alındı; toplantı başlıkları ve katılımcı adları kaydedilmedi.",
    finalHeading: "Araştırmayı kapatmadan önce şeffaflık kontrolü yap",
    finalIntro: "Sonuç kadar araştırma yolunun açıklığı da değerlidir.",
    finalItems: [
      { title: "Protokol", text: "Plan ile uygulama arasındaki farklar kayıtlı mı?" },
      { title: "Veri", text: "Dosyalar, kod kitabı ve dönüşümler anlaşılır mı?" },
      { title: "Etik", text: "Onam, gizlilik ve saklama kararları yerine getirildi mi?" },
      { title: "Sınır", text: "Raporun genelleme ve nedensellik dili tasarımla uyumlu mu?" },
    ],
    outputsHeading: "Bu eğitimden yedi somut çıktı ile çık",
    outputsIntro: "Araştırma fikrini uygulanabilir protokole dönüştür.",
    outputItems: [
      { title: "1 problem cümlesi", text: "Bilgi açığını ve önemini yaz." },
      { title: "1 araştırma sorusu", text: "Cevaplanabilir ana soruyu kur." },
      { title: "1 tasarım özeti", text: "Yaklaşım ve gerekçesini belirt." },
      { title: "1 örneklem planı", text: "Kimden, nasıl ve neden veri alınacağını yaz." },
      { title: "1 veri toplama planı", text: "Araç, süreç ve pilot adımlarını belirle." },
      { title: "1 analiz planı", text: "Soruyu hangi işlemle cevaplayacağını yaz." },
      { title: "1 etik/veri notu", text: "Onam, gizlilik ve saklama kararlarını kaydet." },
    ],
    mastersIntro: "Araştırma tasarımı, geçerlilik, nitel/nicel yöntem ve şeffaflık yaklaşımını karşılaştırmalı incele.",
    masters: [
      { title: "John W. Creswell", text: "Araştırma sorusu ile nicel, nitel ve karma tasarım uyumunu incele." },
      { title: "Robert K. Yin", text: "Tasarım mantığı, kanıt zinciri ve vaka temelli araştırma disiplinini incele." },
      { title: "Donald T. Campbell", text: "Nedensel çıkarım, geçerlilik ve araştırma tasarımı sorunlarına yaklaşımını incele." },
    ],
    faq: [
      { question: "Önce yöntemi mi araştırma sorusunu mu seçmeliyim?", answer: "Önce problem ve araştırma sorusu netleşmeli; yöntem bu soruyu en güvenilir biçimde cevaplayacak araç olarak seçilmelidir." },
      { question: "Hipotezim çıkmazsa araştırma başarısız mı olur?", answer: "Hayır. İyi tasarlanmış bir çalışmada hipotezin desteklenmemesi de bilgi üretir; sonuç dürüstçe raporlanmalıdır." },
      { question: "Pilot çalışma gerekli mi?", answer: "Her çalışmada zorunlu değildir, ancak yeni ölçüm, anket, kodlama veya veri toplama sürecinde ciddi hataları erkenden yakalayabilir." },
    ],
    finalCaption: "İyi araştırma, yalnız cevabı değil cevaba nasıl ulaşıldığını da denetlenebilir hale getirir.",
    ctaHeading: "Araştırma protokolünü oluşturmaya başla",
    ctaText: "Problemin ve araştırma sorun hazırsa İlkOku Yazar Alanı'nda araştırma dosyanı adım adım kur.",
  },
  {
    category: "Akademik",
    slug: "tez",
    label: "Tez",
    title: "Tez Nasıl Yazılır?",
    description: "Konu sınırından tez önerisine, literatür, yöntem, bölüm mimarisi, veri, revizyon ve savunmaya kadar adım adım tez yazma eğitimi.",
    summary: "Uzun akademik çalışmayı bölüm yığınına dönüştürme; tek araştırma probleminden doğan, kaynak ve yöntemle desteklenen bütünlüklü bir tez mimarisi kur.",
    alts: alts("Tez", "Kıyı Kentlerinde Mevsimsel Nüfus ve Kamusal Alan Kullanımı"),
    orientationHeading: "Tez, uzun makale değil uzun soluklu araştırma sistemidir",
    orientationBody: "Tezde yalnız nihai metni değil aylar süren kaynak, veri, danışman geri bildirimi ve bölüm ilişkisini yönetirsin. Başarı, çok sayfa yazmak değil; ana araştırma sorusunu her bölümde ilerleten tutarlı bir kanıt zinciri kurmaktır.",
    ideaHeading: "Tez konusunu yönetilebilir araştırma alanına indir",
    ideaIntro: "Konu heyecan verici olduğu kadar zaman, veri ve erişim açısından yapılabilir olmalıdır.",
    ideaItems: [
      { title: "Sürdürülebilir merak", text: "Aylarca çalışabileceğin ve alt sorular üretebilen bir problem seç." },
      { title: "Kaynak erişimi", text: "Gerekli arşiv, veri, saha veya katılımcıya gerçekçi erişimi değerlendir." },
      { title: "Literatür boşluğu", text: "Tezin mevcut bilgiye hangi sınırlı ama açık katkıyı yapacağını belirle." },
      { title: "Kapsam sınırı", text: "Dönem, coğrafya, örneklem, kavram veya yöntem sınırı koy." },
    ],
    ideaFlowHeading: "Geniş tez konusunu ana soru ve alt sorulara böl",
    ideaFlowBody: "‘Turizm ve kent yaşamı’ tez konusu değildir. ‘Mevsimsel nüfus artışı, kıyı kentlerinde kamusal alan kullanım zamanlarını nasıl değiştiriyor?’ ana sorusu; zaman, kullanıcı grubu, mekân ve veri türü bakımından alt sorulara ayrılabilir.",
    contrastHeading: "Tezi makale ve rapordan ayır",
    contrastIntro: "Uzunluk değil araştırma kapsamı ve bütünlük fark yaratır.",
    contrastItems: [
      { title: "Tez ≠ uzun makale", text: "Daha geniş literatür, yöntem gerekçesi ve bölüm mimarisi taşır." },
      { title: "Tez ≠ proje raporu", text: "Yalnız yapılan işi anlatmaz; akademik problem ve katkıyı savunur." },
      { title: "Tez ≠ kaynak derlemesi", text: "Literatürü araştırma sorusuna hizmet eden kavramsal çerçeveye dönüştürür." },
    ],
    routeHeading: "Tezi 12 aşamada yönet",
    routeIntro: "Yazım takvimi ile araştırma takvimini birlikte kur.",
    routeItems: [
      { title: "1 · Alan ve problem", text: "Araştırma alanını ve bilgi açığını tanımla." },
      { title: "2 · Kapsam", text: "Yapılabilir sınırları koy." },
      { title: "3 · Ana soru / alt sorular", text: "Tezin cevap mimarisini kur." },
      { title: "4 · Öneri", text: "Amaç, önem, literatür, yöntem ve planı danışmana sunulabilir hale getir." },
      { title: "5 · Literatür sistemi", text: "Kaynakları tema ve kavramlara göre haritala." },
      { title: "6 · Kavramsal / kuramsal çerçeve", text: "Analizde kullanacağın kavram ilişkilerini tanımla." },
      { title: "7 · Yöntem", text: "Veri, örneklem, etik ve analiz kararlarını netleştir." },
      { title: "8 · Veri / saha", text: "Protokole uygun biçimde araştırmayı uygula." },
      { title: "9 · Bölüm taslakları", text: "Her bölümün tez ana sorusuna katkısını yaz." },
      { title: "10 · Bütünleştirme", text: "Bölümler arasındaki tekrar, kopukluk ve çelişkiyi temizle." },
      { title: "11 · Danışman revizyonu", text: "Geri bildirimi görev listesine çevir ve sürümle uygula." },
      { title: "12 · Savunma", text: "Ana katkı, yöntem, bulgu, sınır ve eleştirilere cevap hazırlığını tamamla." },
    ],
    structureHeading: "Tezi bölüm başlıklarıyla değil ana sorunun alt görevleriyle kur",
    structureIntro: "Her bölüm tezin ana iddiasında bir işi tamamlamalı.",
    structureItems: [
      { title: "Giriş", text: "Problem, soru, önem, kapsam ve tez haritası." },
      { title: "Literatür", text: "Alanı ve boşluğu tematik sentezle kur." },
      { title: "Çerçeve", text: "Kavram ve kuramları analiz aracına dönüştür." },
      { title: "Yöntem", text: "Araştırma tasarımını ve etik sınırları açıkla." },
      { title: "Analiz / bulgular", text: "Alt sorulara göre kanıtı düzenle." },
      { title: "Tartışma ve sonuç", text: "Bulguları birleştir, katkı ve sınırları göster." },
    ],
    structureCaption: "Tez yapısı, her bölümün ana araştırma sorusuna ölçülebilir katkı yaptığı bir mimari olmalıdır.",
    anatomyHeading: "Tezin anatomisi: tek çalışma içinde araştırma sistemi",
    anatomyBody: "- **Ana soru:** Tezin yönünü sabitler.\n- **Alt sorular:** Bölümlerin ve analizlerin görevini tanımlar.\n- **Literatür haritası:** Tezin hangi bilgi alanına girdiğini gösterir.\n- **Çerçeve:** Kavramları analiz aracına dönüştürür.\n- **Yöntem:** Kanıt üretim sistemidir.\n- **Bölüm mimarisi:** Uzun metinde yön kaybını önler.\n- **Katkı ve sınır:** Savunulabilir son iddiayı belirler.",
    practiceHeading: "Tez sürecinde altı yaşayan dosya tut",
    practiceIntro: "Uzun projede bellek yerine sistem kullan.",
    practiceItems: [
      { title: "Tez pusulası", text: "Ana soru, katkı, kapsam ve yöntem özetini tek sayfada tut." },
      { title: "Literatür matrisi", text: "Kaynakları bölüm, tema ve kavramlarla eşleştir." },
      { title: "Bölüm sözleşmesi", text: "Her bölüm için amaç, girdi, çıktı ve ana iddiayı yaz." },
      { title: "Danışman geri bildirim listesi", text: "Yorumları kaybetmeden durum ve sürümle takip et." },
      { title: "Karar günlüğü", text: "Kapsam, yöntem ve analiz değişikliklerinin nedenini yaz." },
      { title: "Savunma soruları", text: "Zayıf noktaları süreç boyunca soru listesine ekle." },
    ],
    pageSetupCaption: "Tez çalışma düzeni, aylar süren kaynak, bölüm, veri ve geri bildirim akışını tek sistemde izlenebilir tutar.",
    workspaceHeading: "Tez klasörünü bölüm değil araştırma iş akışına göre düzenle",
    workspaceIntro: "Metin, kaynak, veri ve danışman revizyonu birbirine karışmasın.",
    workspaceItems: [
      { title: "00-pusula-ve-plan", text: "Soru, katkı, takvim ve bölüm haritası." },
      { title: "01-literatur", text: "Kaynak PDF'leri, notlar ve matris." },
      { title: "02-yontem-veri", text: "Etik, saha, veri ve analiz dosyaları." },
      { title: "03-bolumler", text: "Her bölümü ayrı sürüm ve net adla yönet." },
      { title: "04-danisman", text: "Geri bildirim ve yanıt listesini sakla." },
    ],
    craftHeading: "Tezin asıl zanaatı: uzun metinde tek araştırma omurgasını kaybetmemek",
    craftBody: "Tez ilerledikçe yeni kaynak ve bulgular kapsamı büyütmek ister. Her yeni parçaya ‘ana soruyu cevaplıyor mu?’ diye sor. Cevap hayırsa değerli olsa bile tez dışında bırakmak çoğu zaman güç kazandırır.",
    extraSections: [
      {
        id: "tez-onerisi",
        type: "steps",
        heading: "Tez önerisini çalışmanın erken prototipi olarak kullan",
        intro: "Öneri yalnız resmi belge değil, projenin yapılabilirlik testidir.",
        items: [
          { title: "Problem ve önem", text: "Neyi bilmiyoruz ve bilmek neden önemli?" },
          { title: "Soru ve katkı", text: "Ne soruyorsun ve çalışmanın ekleyeceği şey ne?" },
          { title: "Kaynak durumu", text: "Yeterli literatür ve veri erişimi var mı?" },
          { title: "Yöntem", text: "Soru ile seçilen araştırma yolu gerçekten uyumlu mu?" },
          { title: "Takvim ve risk", text: "Etik izin, saha, veri ve yazım için gerçekçi süre var mı?" },
        ],
      },
      {
        id: "bolum-mimarisi",
        type: "cards",
        heading: "Her bölüm için bir görev tanımı yaz",
        intro: "Bölüm uzunluğu değil araştırma işlevi önemlidir.",
        items: [
          { title: "Bölüm sorusu", text: "Bu bölüm ana sorunun hangi parçasını cevaplıyor?" },
          { title: "Girdi", text: "Hangi kaynak, veri veya kavram bu bölüme giriyor?" },
          { title: "Çıktı", text: "Okur bölüm sonunda ne öğrenmiş olmalı?" },
          { title: "Köprü", text: "Sonraki bölüm neden bu sonuçtan sonra gelmeli?" },
        ],
      },
      {
        id: "savunma-hazirligi",
        type: "steps",
        heading: "Savunmaya metin bittikten sonra değil süreç boyunca hazırlan",
        intro: "Savunma, tezin mantığını kısa ve açık biçimde sahiplenme sınavıdır.",
        items: [
          { title: "3 dakikalık tez özeti", text: "Problem, soru, yöntem, ana bulgu ve katkıyı kısa anlat." },
          { title: "Yöntem gerekçesi", text: "Neden bu yöntemi seçtiğini ve alternatiflerin neden daha zayıf kaldığını açıkla." },
          { title: "En güçlü eleştiri", text: "Çalışmana gelebilecek en ciddi itirazı kendin yaz." },
          { title: "Sınırlılık cevabı", text: "Savunmak yerine sınırı kabul edip etkisini açıklamayı öğren." },
          { title: "Sonraki çalışma", text: "Tezin cevaplayamadığı ama açtığı yeni soruyu belirt." },
        ],
      },
    ],
    draftHeading: "Tez taslağını baştan sona tek seferde yazmaya çalışma",
    draftIntro: "Bölümleri ayrı üret ama düzenli olarak ana omurgaya geri bağla.",
    draftItems: [
      { title: "Bölüm iskeleti", text: "Yazmadan önce alt başlık ve ana iddia akışını çıkar." },
      { title: "Kaynaklı ham taslak", text: "Mükemmel dil beklemeden iddia ve kanıtı yerleştir." },
      { title: "Bölüm özeti", text: "Her bölüm sonunda ana sonucun iki cümlelik özetini yaz." },
      { title: "Bütünlük kontrolü", text: "Her iki–üç bölümde ana soru ve kavram kullanımını yeniden karşılaştır." },
    ],
    revisionHeading: "Tez revizyonunu mikro değil makrodan başlat",
    revisionIntro: "Önce yapı ve araştırma mantığını düzelt; cümle cilasını en sona bırak.",
    revisionItems: [
      { title: "Kapsam testi", text: "Tezin birden fazla tez olmaya çalıştığı yerler var mı?" },
      { title: "Bölüm testi", text: "Her bölüm ana soruya gerçek bir katkı yapıyor mu?" },
      { title: "Tekrar testi", text: "Aynı literatür veya bulgu farklı bölümlerde gereksiz tekrar ediyor mu?" },
      { title: "Katkı testi", text: "Sonuç bölümündeki iddia gerçekten çalışmanın kanıtından çıkıyor mu?" },
    ],
    projectName: "Kıyı Kentlerinde Mevsimsel Nüfus ve Kamusal Alan Kullanımı",
    projectBody: "**Ana soru:** Mevsimsel nüfus artışı, küçük kıyı kentlerinde kamusal alan kullanım zamanlarını ve kullanıcı gruplarını nasıl değiştiriyor?\n\n**Alt sorular:** Sabah/akşam farkı nedir? Yerel ve ziyaretçi kullanımı nasıl ayrışır? Hangi mekânlar baskı altında kalır?\n\n**Yöntem:** Üç kamusal alanda dönemsel gözlem + kısa kullanıcı görüşmeleri + belediye nüfus/hareket verisi.\n\n**Bölüm mantığı:** Literatür → kent bağlamı → yöntem → mekân bazlı analiz → karşılaştırma → tartışma.\n\n**Katkı sınırı:** Tek kent üzerinden evrensel genelleme yapılmaz; mevsimsellik ve mekânsal kullanım ilişkisi ayrıntılandırılır.",
    projectCaption: "Örnek tez, ana soru, alt sorular ve bölüm mimarisini tek araştırma omurgasında birleştirir.",
    sampleHeading: "Örnek tez bölüm sözleşmesi",
    sampleBody: "**Bölüm 4 — Sahil Meydanı Analizi**\nAmaç: Mevsimsel nüfus artışının gün içi kullanıcı profiline etkisini göstermek.\nGirdi: Gözlem çizelgeleri, görüşme kodları, belediye yaya sayımı.\nÇıktı: Sabah ve akşam kullanımının kullanıcı grupları bazında nasıl ayrıştığını açıklayan üç temel bulgu.",
    finalHeading: "Teslim ve savunma öncesi tez bütünlüğünü denetle",
    finalIntro: "Son kontrol yalnız biçim değil araştırma mimarisidir.",
    finalItems: [
      { title: "Ana soru", text: "Girişteki soru sonuçta açıkça cevaplanıyor mu?" },
      { title: "Bölüm zinciri", text: "Her bölüm bir sonrakini hazırlıyor ve tekrarları azaltıyor mu?" },
      { title: "Kaynak / etik", text: "Atıf, izin, ekler ve veri beyanları tamam mı?" },
      { title: "Savunma özeti", text: "Çalışmanın katkısını ve sınırını kısa ve açık anlatabiliyor musun?" },
    ],
    outputsHeading: "Bu eğitimden sekiz somut çıktı ile çık",
    outputsIntro: "Tez fikrini yönetilebilir araştırma sistemine dönüştür.",
    outputItems: [
      { title: "1 tez pusulası", text: "Ana soru, katkı, kapsam ve yöntemi tek sayfada topla." },
      { title: "1 alt soru seti", text: "Ana soruyu yönetilebilir araştırma görevlerine böl." },
      { title: "1 literatür matrisi", text: "Temaları ve boşluğu görünür kıl." },
      { title: "1 tez önerisi iskeleti", text: "Problem, soru, yöntem ve takvimi yaz." },
      { title: "1 bölüm haritası", text: "Her bölümün görevini tanımla." },
      { title: "1 yöntem planı", text: "Veri, örneklem, etik ve analizi sabitle." },
      { title: "1 danışman revizyon listesi", text: "Geri bildirimi uygulanabilir görevlere çevir." },
      { title: "1 savunma özeti", text: "Tezi kısa ve savunulabilir biçimde anlat." },
    ],
    mastersIntro: "Uzun araştırma projesi yönetimi, kaynak disiplini ve akademik argüman kurmayı birlikte incele.",
    masters: [
      { title: "Umberto Eco", text: "Tez konusu seçimi, kaynak kullanımı ve araştırma disiplinini incele." },
      { title: "Wayne C. Booth ve çalışma arkadaşları", text: "Araştırma probleminden savunulabilir iddiaya geçişi incele." },
      { title: "Howard S. Becker", text: "Akademik yazıda üretim, revizyon ve yazma alışkanlıklarına yaklaşımını incele." },
    ],
    faq: [
      { question: "Tez konusu ne kadar dar olmalı?", answer: "Süren, veri erişimin ve yöntemin içinde gerçekten cevaplanabilecek kadar dar; akademik katkı üretmeye yetecek kadar anlamlı olmalıdır." },
      { question: "Bölümleri sırayla mı yazmalıyım?", answer: "Zorunlu değil. Yöntem ve analiz bölümleri erken yazılabilir; ancak düzenli bütünlük kontrolü yaparak ana sorudan kopmamak gerekir." },
      { question: "Danışman her şeyi düzeltmeli mi?", answer: "Hayır. Danışman yön, eleştiri ve akademik denetim sağlar; araştırma kararlarını anlamak ve metnin sorumluluğunu taşımak araştırmacının görevidir." },
    ],
    finalCaption: "Tez, sayfa sayısı arttığında değil tüm bölümler aynı araştırma sorusunu birlikte cevapladığında tamamlanır.",
    ctaHeading: "Tez çalışma sistemini kur",
    ctaText: "Ana sorun ve kapsamın netleştiyse İlkOku Yazar Alanı'nda tez dosyanı bölüm bölüm oluşturmaya başla.",
  },
  {
    category: "Akademik",
    slug: "bildiri",
    label: "Bildiri",
    title: "Akademik Bildiri Nasıl Hazırlanır?",
    description: "Konferans çağrısından özet yazımına, araştırma seçimi, süre planı, slayt, sunum metni ve soru-cevap hazırlığına kadar adım adım akademik bildiri eğitimi.",
    summary: "Araştırmanın tamamını sahneye taşımaya çalışma; tek güçlü katkıyı, sınırlı sürede anlaşılır kanıt ve iyi kurulmuş sunum akışıyla aktar.",
    alts: alts("Akademik Bildiri", "On Dakikada Bir Mahalle Haritası"),
    orientationHeading: "Bildiri, makalenin yüksek sesle okunmuş hali değildir",
    orientationBody: "Dinleyici metne geri dönemez. Bu nedenle bildiri tek ana mesaj, kontrollü bilgi yoğunluğu, konuşulabilir cümleler ve görünür kanıt ister. Konferans kapsamına uymak, araştırmanın hangi parçasını sunacağını seçmek kadar önemlidir.",
    ideaHeading: "Bildiri konusunu tek sunulabilir katkıya indir",
    ideaIntro: "Bir oturum süresinde aktarılabilecek araştırma parçasını seç.",
    ideaItems: [
      { title: "Yeni bulgu", text: "Araştırmanın en güçlü ve tartışmaya değer tek sonucunu merkeze al." },
      { title: "Yöntem yeniliği", text: "Yeni veya uyarlanmış bir yöntemin neyi daha iyi gösterdiğini anlat." },
      { title: "Karşılaştırma", text: "İki vaka, dönem veya yaklaşım arasındaki belirgin farkı sun." },
      { title: "Kavramsal öneri", text: "Mevcut tartışmayı açıklayan sınırlı ve açık bir kavramsal katkı kur." },
    ],
    ideaFlowHeading: "Araştırmadan konferans mesajına geç",
    ideaFlowBody: "Tezinin veya makalenin tamamını sunmak yerine ‘Dinleyici salondan tek neyi hatırlasın?’ sorusunu cevapla. Bu cümle bildirinin başlık, özet, slayt ve sonuç seçimlerini yönetsin.",
    contrastHeading: "Bildiriyi makale ve ders sunumundan ayır",
    contrastIntro: "Aynı araştırma, sözlü ortamda farklı biçimde kurulmalıdır.",
    contrastItems: [
      { title: "Bildiri ≠ makale okuması", text: "Konuşma dili, süre ve dinleyici yönlendirmesi gerekir." },
      { title: "Bildiri ≠ tüm araştırma", text: "Tek ana katkıyı seçmek çoğu zaman daha güçlüdür." },
      { title: "Bildiri ≠ slayt gösterisi", text: "Slayt konuşmanın yerine geçmez; kanıtı görünür kılar." },
    ],
    routeHeading: "Bildiriyi 9 aşamada hazırla",
    routeIntro: "Çağrı metninden soru-cevap provasına kadar üretimi planla.",
    routeItems: [
      { title: "1 · Çağrı uyumu", text: "Konferans tema, kapsam, format ve son tarihini çözümle." },
      { title: "2 · Ana mesaj", text: "Tek katkı cümlesini yaz." },
      { title: "3 · Özet", text: "Problem, yöntem, temel bulgu ve katkıyı kelime sınırında kur." },
      { title: "4 · Kabul sonrası kapsam", text: "Sunacağın veri ve örneği daralt." },
      { title: "5 · Konuşma akışı", text: "Dakikalara bölünmüş bölüm planı oluştur." },
      { title: "6 · Slayt", text: "Her slayda tek iş ver; okunamayacak tabloyu çıkar." },
      { title: "7 · Konuşma metni", text: "Yüksek sesle doğal okunacak geçişler yaz." },
      { title: "8 · Süre provası", text: "Gerçek tempoyla kaydet ve taşan bölümleri kes." },
      { title: "9 · Soru-cevap", text: "Yöntem, sınır ve ana bulguya gelecek zor soruları hazırla." },
    ],
    structureHeading: "Bildiriyi dinleyicinin takip edebileceği tek yol olarak kur",
    structureIntro: "Sözlü sunumda yön tabelaları görünür olmalıdır.",
    structureItems: [
      { title: "Açılış", text: "Problem ve neden önemli olduğunu ilk dakikada açıkla." },
      { title: "Soru", text: "Bugün tam olarak neyi göstereceğini söyle." },
      { title: "Minimum bağlam", text: "Yalnız sonucu anlamaya gereken literatürü ver." },
      { title: "Yöntem", text: "Güven için gerekli kadar açıkla." },
      { title: "Ana bulgu", text: "En güçlü veri, örnek veya görselle sonucu göster." },
      { title: "Sonuç", text: "Tek katkı cümlesini yeniden kur ve sınırı belirt." },
    ],
    structureCaption: "Bildiri yapısı, sınırlı sürede tek akademik mesajın kaybolmadan ilerlemesini sağlar.",
    anatomyHeading: "Bildirinin anatomisi: ana mesaj, süre, ses ve görsel kanıt",
    anatomyBody: "- **Başlık:** Çalışmanın gerçek odağı.\n- **Özet:** Kabul için araştırmanın yoğunlaştırılmış argümanı.\n- **Ana mesaj:** Dinleyicinin hatırlaması gereken tek cümle.\n- **Konuşma akışı:** Süreye göre bölümleme.\n- **Slayt:** Görsel kanıt ve yön desteği.\n- **Geçiş:** Dinleyicinin nerede olduğunu hatırlatır.\n- **Soru-cevap:** Çalışmanın sınırlarını savunma alanı.",
    practiceHeading: "Bildiri için beş prova dosyası tut",
    practiceIntro: "Sunum kalitesi yazı kadar zaman ve ses yönetimidir.",
    practiceItems: [
      { title: "Dakika planı", text: "Her bölüm için hedef süre belirle." },
      { title: "Slayt amacı", text: "Her slaydın tek cümlelik görevini yaz." },
      { title: "Telaffuz listesi", text: "İsim, terim ve kısaltmaların söylenişini not et." },
      { title: "Zor soru listesi", text: "Yöntem ve sınır eleştirilerine kısa cevap hazırla." },
      { title: "Prova kaydı", text: "Ses, hız, tekrar ve dolgu kelimelerini dinle." },
    ],
    pageSetupCaption: "Bildiri çalışma düzeni, araştırma içeriğini süre, slayt ve sözlü anlatım kararlarıyla birlikte yönetir.",
    workspaceHeading: "Bildiri dosyanı konuşma akışıyla eşleştir",
    workspaceIntro: "Slayt ve metnin numaraları senkron olsun.",
    workspaceItems: [
      { title: "Slayt no + amaç", text: "Her slayta konuşmadaki görevini yaz." },
      { title: "Süre işareti", text: "5., 10. ve son dakika gibi kontrol noktaları koy." },
      { title: "Kesilebilir bölüm", text: "Süre daralırsa hangi örneğin güvenle atılacağını belirle." },
      { title: "Yedek slayt", text: "Soru-cevap için ayrıntılı yöntem veya ek tabloyu sona koy." },
    ],
    craftHeading: "Bildirinin asıl zanaatı: akademik doğruluğu dinlenebilir sadelikle birleştirmek",
    craftBody: "Basitleştirmek, bulguyu bozmak değildir. Uzun tanımı tek örnekle, karmaşık tabloyu tek mesajlı görselle ve literatür listesini yalnız gerekli karşılaştırmayla değiştir. Ama belirsizlik, sınırlılık ve kaynak gerektiren iddiaları sırf akıcılık için silme.",
    extraSections: [
      {
        id: "ozet-yazimi",
        type: "steps",
        heading: "Bildiri özetini başlık değil mini araştırma argümanı olarak yaz",
        intro: "Hakem çoğu zaman yalnız özet üzerinden çalışmanın değerini değerlendirir.",
        items: [
          { title: "Problem", text: "Alan ve bilgi açığını birkaç cümlede kur." },
          { title: "Amaç / soru", text: "Çalışmanın neyi incelediğini açıkça söyle." },
          { title: "Yöntem", text: "Veri, örneklem ve yaklaşımı yeterli ayrıntıyla belirt." },
          { title: "Ana bulgu", text: "Mümkünse belirsiz vaat yerine gerçek temel sonucu yaz." },
          { title: "Katkı", text: "Bu sonucun oturum temasına ve alana ne eklediğini kapat." },
        ],
      },
      {
        id: "slayt-ve-veri",
        type: "cards",
        heading: "Slaytı veri deposu değil görsel kanıt olarak kullan",
        intro: "Dinleyici aynı anda okuyup seni uzun süre dinleyemez.",
        items: [
          { title: "Tek mesaj", text: "Her slaytta bir ana sonuç veya soru olsun." },
          { title: "Büyük veri", text: "Tablodaki her hücreyi göstermek yerine konuştuğun örüntüyü öne çıkar." },
          { title: "Kaynak notu", text: "Dış görsel ve verinin kaynağını görünür tut." },
          { title: "Erişilebilirlik", text: "Okunabilir yazı, yeterli kontrast ve açıklayıcı etiket kullan." },
        ],
      },
      {
        id: "soru-cevap",
        type: "steps",
        heading: "Soru-cevap bölümünü akademik savunmanın kısa biçimi olarak prova et",
        intro: "Her soruya cevap vermek değil, bildiğin ve bilmediğin sınırı yönetmek gerekir.",
        items: [
          { title: "Soruyu yeniden kur", text: "Gerekirse doğru anladığını teyit et." },
          { title: "Kısa cevap", text: "Önce doğrudan yanıtı ver, sonra gerekçeyi ekle." },
          { title: "Sınırı kabul et", text: "Verinin cevaplamadığı noktada tahmin yürütme." },
          { title: "Takip yolu", text: "İyi eleştiriyi gelecekteki analiz veya araştırma yönüne çevir." },
        ],
      },
    ],
    draftHeading: "İlk bildiri taslağını okuyarak değil konuşarak yaz",
    draftIntro: "Metin kulağa doğal gelmeli ve süre içinde tamamlanmalıdır.",
    draftItems: [
      { title: "Ana mesajı başa koy", text: "Dinleyici sunumun yönünü erken anlasın." },
      { title: "Literatürü sıkıştır", text: "Yalnız bulguyu anlamak için gereken kaynak ilişkilerini bırak." },
      { title: "Sayıyı azalt", text: "Arka arkaya çok oran ve tarih yerine en anlamlı karşılaştırmayı seç." },
      { title: "Geçiş yaz", text: "‘Şimdi yönteme geçiyorum’ gibi yön cümlelerini gerektiğinde açıkça kullan." },
    ],
    revisionHeading: "Bildiri revizyonunu saatle ve ses kaydıyla yap",
    revisionIntro: "Ekranda kısa görünen metin konuşmada uzun sürebilir.",
    revisionItems: [
      { title: "Süre testi", text: "Normal konuşma hızında hedef sürenin altında bitiyor musun?" },
      { title: "Hafıza testi", text: "Dinleyici finalde tek ana mesajı söyleyebilir mi?" },
      { title: "Slayt testi", text: "Konuşmayı dinlemeden slaytın neyi gösterdiği anlaşılabiliyor mu?" },
      { title: "Sınır testi", text: "Sunum, araştırmanın kaldırabileceğinden daha büyük sonuç iddia ediyor mu?" },
    ],
    projectName: "On Dakikada Bir Mahalle Haritası",
    projectBody: "**Ana mesaj:** Yaya davranışındaki üç tekrar eden örüntü, mahalle meydanının tasarım kararlarıyla ilişkilidir.\n\n**Süre:** 10 dakika.\n\n**Akış:** 1 dk problem → 1 dk soru → 1 dk yöntem → 5 dk üç bulgu → 1 dk tartışma → 1 dk sonuç.\n\n**Slayt:** Her bulgu için tek harita + bir kısa gözlem notu.\n\n**Yedek:** Örneklem ayrıntısı ve kodlama tablosu soru-cevap için sona eklenir.",
    projectCaption: "Örnek bildiri, araştırmanın tamamını değil tek ana mesajı süre ve görsel kanıtla taşır.",
    sampleHeading: "Örnek bildiri açılışı: problem + vaat",
    sampleBody: "Bu meydanı her gün binlerce kişi kullanıyor; fakat insanların nerede durduğu ile bankların nerede olduğu aynı haritayı çizmiyor. Önümüzdeki on dakikada, üç aylık gözlemde tekrar eden üç yaya örüntüsünü ve bunların tasarım için ne söylediğini göstereceğim.",
    finalHeading: "Sunumdan önce teknik ve akademik kontrol yap",
    finalIntro: "Dosya çalışsa bile argüman çalışmıyorsa bildiri hazır değildir.",
    finalItems: [
      { title: "Süre", text: "En az iki gerçek zamanlı prova yapıldı mı?" },
      { title: "Kaynak", text: "Dış veri, görsel ve alıntılar kaynaklı mı?" },
      { title: "Dosya", text: "Sunum formatı, yazı tipleri, video ve yedek PDF kontrol edildi mi?" },
      { title: "Q&A", text: "Yöntem, sınır ve örneklem üzerine zor sorular prova edildi mi?" },
    ],
    outputsHeading: "Bu eğitimden yedi somut çıktı ile çık",
    outputsIntro: "Araştırmanı konferans sunumuna dönüştür.",
    outputItems: [
      { title: "1 ana mesaj", text: "Dinleyicinin hatırlaması gereken cümleyi yaz." },
      { title: "1 bildiri özeti", text: "Problem, yöntem, bulgu ve katkıyı yoğunlaştır." },
      { title: "1 dakika planı", text: "Sunum süresini bölümlere ayır." },
      { title: "1 slayt haritası", text: "Slaytların tek tek görevini yaz." },
      { title: "1 konuşma taslağı", text: "Konuşulabilir cümlelerle metni kur." },
      { title: "1 prova kaydı", text: "Süre ve ses sorunlarını işaretle." },
      { title: "1 zor soru listesi", text: "Savunma noktalarını hazırla." },
    ],
    mastersIntro: "Açık akademik anlatım, görsel veri sunumu ve sözlü savunma tekniklerini birlikte incele.",
    masters: [
      { title: "Edward Tufte", text: "Veriyi gereksiz süsten arındırarak görsel kanıt haline getirme yaklaşımını incele." },
      { title: "Nancy Duarte", text: "Sunum akışı ve dinleyici yönlendirmesi üzerine yapı ilkelerini incele." },
      { title: "Michael Alley", text: "Bilimsel sunumlarda mesaj odaklı slayt ve sözlü anlatım yaklaşımını incele." },
    ],
    faq: [
      { question: "Bildiride makaledeki tüm yöntem ayrıntılarını anlatmalı mıyım?", answer: "Hayır. Sonucun güvenilirliğini değerlendirmek için gereken temel tasarım ve örneklem bilgilerini ver; ayrıntıyı yedek slayta taşıyabilirsin." },
      { question: "Sunum metnini ezberlemek gerekir mi?", answer: "Zorunlu değil. Akışı ve ana geçişleri iyi bilmek, kelime kelime ezberden daha doğal ve dayanıklı olabilir." },
      { question: "Süre yetmiyorsa hızlı konuşmalı mıyım?", answer: "Hayır. İçeriği azaltmak, anlaşılabilirliği bozacak hızlanmadan daha doğru çözümdür." },
    ],
    finalCaption: "İyi bildiri, araştırmanın tamamını sıkıştırmaz; tek güçlü katkıyı dinleyicinin takip edebileceği biçimde görünür kılar.",
    ctaHeading: "Bildirini konferans akışına dönüştür",
    ctaText: "Ana mesajın ve özetin hazırsa İlkOku Yazar Alanı'nda bildiri metnini ve sunum akışını oluşturmaya başla.",
  },
  {
    category: "Akademik",
    slug: "vaka-analizi",
    label: "Vaka Analizi",
    title: "Akademik Vaka Analizi Nasıl Yazılır?",
    description: "Vaka seçiminden sınır koymaya, veri üçgenlemesine, kronoloji, kanıt zinciri, açıklama, etik ve raporlamaya kadar adım adım akademik vaka analizi eğitimi.",
    summary: "Tek bir örneği hikâye gibi anlatma; vakayı neden seçtiğini, sınırlarını, kanıt kaynaklarını ve hangi analitik soruya cevap verdiğini görünür kıl.",
    alts: alts("Vaka Analizi", "Bir Mahalle Kütüphanesinin Dönüşümü"),
    orientationHeading: "Vaka analizi, ilginç bir olay anlatısı değil sınırları tanımlı analitik incelemedir",
    orientationBody: "Vaka; kişi, kurum, olay, proje, yer veya süreç olabilir. Güçlü analiz, vakanın nerede başlayıp bittiğini, neden bu vakanın seçildiğini ve iddiaların hangi farklı kanıt kaynaklarına dayandığını açıklar.",
    ideaHeading: "Vakayı analitik değerine göre seç",
    ideaIntro: "‘İlginç’ olması yetmez; araştırma sorusuna bilgi sağlamalıdır.",
    ideaItems: [
      { title: "Tipik vaka", text: "Yaygın bir örüntünün nasıl işlediğini ayrıntılı gösterir." },
      { title: "Aykırı vaka", text: "Genel beklentiye uymayan sonuç üzerinden açıklamayı sınar." },
      { title: "Kritik vaka", text: "Bir teori veya iddia için güçlü sınama koşulu sunar." },
      { title: "Dönüşüm vakası", text: "Önce–sonra değişimini süreç içinde incelemeye izin verir." },
    ],
    ideaFlowHeading: "Vakayı hikâyeden araştırma birimine dönüştür",
    ideaFlowBody: "‘Bir kütüphanenin yenilenmesi’ olaydır. ‘Mahalle kütüphanesinin ortak çalışma alanına dönüşmesi, farklı yaş gruplarının mekân kullanımını nasıl değiştirdi?’ sorusu; vaka sınırı, zaman aralığı ve kanıt kaynakları belirlemeye izin verir.",
    contrastHeading: "Vaka analizini anekdot ve örnekten ayır",
    contrastIntro: "Tek örnek kullanmak tek başına vaka çalışması değildir.",
    contrastItems: [
      { title: "Vaka ≠ anekdot", text: "Sistemli veri toplama ve analiz gerekir." },
      { title: "Vaka ≠ örnek kutusu", text: "Metinde fikri süslemek değil araştırma sorusunu incelemek için seçilir." },
      { title: "Vaka ≠ kronoloji", text: "Olay sırası önemlidir ama analitik açıklamanın yerine geçmez." },
    ],
    routeHeading: "Vaka analizini 10 aşamada kur",
    routeIntro: "Önce vakanın sınırını ve kanıt planını sabitle.",
    routeItems: [
      { title: "1 · Analitik soru", text: "Vaka üzerinden neyi anlamaya çalıştığını yaz." },
      { title: "2 · Vaka seçimi", text: "Neden bu vakanın bilgi değeri taşıdığını açıkla." },
      { title: "3 · Sınır", text: "Yer, zaman, kurum, aktör ve süreç sınırlarını tanımla." },
      { title: "4 · Kaynak planı", text: "Belge, görüşme, gözlem, veri ve arşiv kaynaklarını belirle." },
      { title: "5 · Etik", text: "Gizlilik, rol çatışması ve hassas bilgiyi planla." },
      { title: "6 · Kronoloji", text: "Olay ve karar dizisini doğrulanabilir biçimde kur." },
      { title: "7 · Kodlama / tema", text: "Veride tekrar eden mekanizma ve gerilimleri çıkar." },
      { title: "8 · Üçgenleme", text: "Aynı iddiayı farklı kaynaklarla sınamaya çalış." },
      { title: "9 · Açıklama", text: "Ne oldu sorusundan nasıl ve neden oldu sorusuna geç." },
      { title: "10 · Sınır / aktarılabilirlik", text: "Bu vakadan hangi koşullarda daha genel ders çıkarılabileceğini ölçülü yaz." },
    ],
    structureHeading: "Vaka raporunu kronoloji ile analizi dengede tutarak kur",
    structureIntro: "Okur hem ne olduğunu hem bunun ne anlama geldiğini takip etsin.",
    structureItems: [
      { title: "Vaka ve bağlam", text: "Sınırları ve neden seçildiğini açıkla." },
      { title: "Araştırma sorusu", text: "Analitik odağı netleştir." },
      { title: "Yöntem ve kaynak", text: "Kanıtın nasıl toplandığını göster." },
      { title: "Kronoloji / dönemler", text: "Kritik olayları ve karar noktalarını kur." },
      { title: "Tematik analiz", text: "Kaynaklar arası örüntüleri ve çelişkileri yorumla." },
      { title: "Sonuç", text: "Mekanizma, ders, sınır ve yeni soruları yaz." },
    ],
    structureCaption: "Vaka analizi yapısı, olay sırasını analitik mekanizma ve kanıt zinciriyle birlikte taşır.",
    anatomyHeading: "Vaka analizinin anatomisi: sınır, kaynak, kronoloji ve mekanizma",
    anatomyBody: "- **Vaka birimi:** Tam olarak ne inceleniyor?\n- **Sınır:** Nerede, ne zaman ve kimlerle?\n- **Seçim gerekçesi:** Bu vaka neden analitik olarak değerli?\n- **Kanıt kaynakları:** Belge, görüşme, gözlem, veri.\n- **Kronoloji:** Kritik olay ve karar sırası.\n- **Mekanizma:** Sonucu hangi süreçler üretti?\n- **Karşı kanıt:** İlk açıklamayı zorlayan veri var mı?",
    practiceHeading: "Vaka analizi için beş kanıt dosyası tut",
    practiceIntro: "Tek kaynağın anlatıyı ele geçirmesine izin verme.",
    practiceItems: [
      { title: "Kaynak envanteri", text: "Her belge, görüşme ve gözlemi tarih ve kökenle kaydet." },
      { title: "Kronoloji", text: "Doğrulanmış olayları kaynak referansıyla sırala." },
      { title: "İddia–kaynak matrisi", text: "Her analitik iddiayı destekleyen ve çürüten kaynakları yan yana koy." },
      { title: "Aktör haritası", text: "Tarafların rol, çıkar ve karar etkisini göster." },
      { title: "Çelişki listesi", text: "Kaynakların birbirini tutmadığı noktaları özellikle sakla." },
    ],
    pageSetupCaption: "Vaka analizi çalışma düzeni, olay anlatısını kaynak, aktör ve kanıt zinciriyle sürekli karşılaştırır.",
    workspaceHeading: "Vaka dosyanı kaynak türlerini karıştırmadan düzenle",
    workspaceIntro: "Belge, görüşme ve araştırmacı yorumunu birbirinden ayır.",
    workspaceItems: [
      { title: "Belge klasörü", text: "Resmi ve kurumsal kayıtları tam künyeyle sakla." },
      { title: "Görüşme klasörü", text: "Onam, kod, tarih ve anonimlik kararlarını kaydet." },
      { title: "Gözlem günlüğü", text: "Ne gördüğün ile yorumunu ayrı satırlarda tut." },
      { title: "Analiz notu", text: "Temaları ve mekanizma hipotezlerini kaynak kodlarıyla bağla." },
    ],
    craftHeading: "Vaka analizinin asıl zanaatı: güçlü hikâyeyi güçlü kanıtla karıştırmamak",
    craftBody: "Bir katılımcının etkileyici anlatısı gerçeğin tamamı değildir. Resmi belge de tek başına tarafsız olmayabilir. Farklı kaynakların nerede birleştiğini, nerede ayrıştığını ve araştırmacının hangi çıkarımı hangi kanıttan yaptığını açıkça göster.",
    extraSections: [
      {
        id: "vaka-siniri",
        type: "cards",
        heading: "Vakanın sınırlarını yazmadan veri toplamaya başlama",
        intro: "Sınır belirsizse vaka sürekli büyür ve analiz dağılır.",
        items: [
          { title: "Mekân sınırı", text: "Hangi yer veya kurum içeri giriyor, hangisi dışarıda?" },
          { title: "Zaman sınırı", text: "Analiz hangi başlangıç ve bitiş noktasını kapsıyor?" },
          { title: "Aktör sınırı", text: "Hangi taraflar analizin parçası ve neden?" },
          { title: "Süreç sınırı", text: "Tüm kurum tarihini değil hangi karar veya dönüşüm sürecini inceliyorsun?" },
        ],
      },
      {
        id: "ucgenleme",
        type: "steps",
        heading: "Kanıt üçgenlemesini sistematik yap",
        intro: "Aynı iddiayı mümkün olduğunda farklı türden kaynaklarla sınamaya çalış.",
        items: [
          { title: "İddiayı yaz", text: "Önce tam olarak neyi söylediğini netleştir." },
          { title: "Destekleyen kaynakları bul", text: "Belge, görüşme, gözlem veya nicel veri dayanaklarını ekle." },
          { title: "Karşı kanıt ara", text: "İlk açıklamayı zayıflatabilecek veriyi özellikle ara." },
          { title: "Kaynak farkını açıkla", text: "Çelişki varsa ‘hangisi doğru?’ demeden önce neden farklı olabileceğini analiz et." },
          { title: "İddia düzeyini ayarla", text: "Kanıt karışıksa sonucu daha dar ve koşullu yaz." },
        ],
      },
      {
        id: "etik-ve-anonimlik",
        type: "cards",
        heading: "Vaka analizinde etik ve anonimlik kararlarını bağlama göre ver",
        intro: "Özellikle küçük kurum ve topluluklarda isim kaldırmak tek başına anonimlik sağlamayabilir.",
        items: [
          { title: "Yeniden tanınma riski", text: "Rol, tarih ve olay ayrıntıları kişinin kimliğini ele veriyor mu?" },
          { title: "Güç ilişkisi", text: "Araştırmacı ile katılımcı arasında iş, eğitim veya kurum bağı var mı?" },
          { title: "Hassas belge", text: "Yasal erişim ile etik kullanım aynı şey değildir; zarar riskini ayrıca değerlendir." },
          { title: "Alıntı kontrolü", text: "Bağlamdan koparılan güçlü cümleler kişiyi yanlış temsil ediyor mu?" },
        ],
      },
    ],
    draftHeading: "İlk taslakta kronolojiyi yaz ama analizi erteleme",
    draftIntro: "‘Sonra ne oldu?’ kadar ‘bu neden önemli?’ sorusunu da her bölümde cevapla.",
    draftItems: [
      { title: "Kritik olayları seç", text: "Tüm ayrıntıları değil mekanizmayı değiştiren olayları yaz." },
      { title: "Kaynak kodu ekle", text: "Olay ve iddianın yanına dayanağını ilk taslakta koy." },
      { title: "Çelişkiyi saklama", text: "Kaynaklar uyuşmuyorsa metinde görünür bırak." },
      { title: "Analitik ara sonuç", text: "Her bölüm sonunda ne öğrendiğini kısa yaz." },
    ],
    revisionHeading: "Vaka revizyonunda hikâye akıcılığından önce kanıt zincirini denetle",
    revisionIntro: "Akıcı anlatı, kanıtsız nedensellik üretmemeli.",
    revisionItems: [
      { title: "Kaynak testi", text: "Her önemli olay ve iddianın izi var mı?" },
      { title: "Nedensellik testi", text: "Sırf iki olay art arda geldi diye neden-sonuç mu kurulmuş?" },
      { title: "Karşı ses testi", text: "Vakanın yalnız tek aktörün anlatısına dönüşmüş yeri var mı?" },
      { title: "Aktarılabilirlik testi", text: "Tek vakadan çıkarılan ders koşulları belirtilmeden genelleniyor mu?" },
    ],
    projectName: "Bir Mahalle Kütüphanesinin Dönüşümü",
    projectBody: "**Soru:** Geleneksel mahalle kütüphanesinin ortak çalışma ve etkinlik merkezine dönüşmesi, farklı yaş gruplarının mekân kullanımını nasıl değiştirdi?\n\n**Sınır:** Dönüşüm kararından açılıştan sonraki ilk 12 aya kadar.\n\n**Kaynak:** Belediye kararları, kullanım sayıları, personel görüşmeleri, kullanıcı görüşmeleri, yerinde gözlem.\n\n**Kritik çelişki:** Ziyaretçi sayısı artarken sessiz çalışma alanı kullanan yaşlı kullanıcıların memnuniyeti düşüyor.\n\n**Analitik amaç:** ‘Başarı = daha çok kullanıcı’ varsayımını çoklu kullanıcı deneyimiyle sınamak.",
    projectCaption: "Örnek vaka, dönüşüm hikâyesini tek başarı ölçütüne indirmeden farklı kanıt kaynaklarıyla analiz eder.",
    sampleHeading: "Örnek vaka paragrafı: olay + kaynak + analitik gerilim",
    sampleBody: "Açılıştan sonraki altı ayda toplam ziyaretçi sayısı yüzde 38 arttı. Ancak üç ayrı gözlem gününde sessiz çalışma bölümündeki oturum süresi önceki döneme göre daha kısa kaydedildi. Personel görüşmeleri, etkinlik alanından taşan sesin özellikle öğleden sonra bu bölümü etkilediğini gösteriyor.",
    finalHeading: "Vaka raporunu kapatmadan önce kanıt ve temsil kontrolü yap",
    finalIntro: "Vakayı güçlü bir hikâyeye dönüştürürken araştırma sınırlarını kaybetme.",
    finalItems: [
      { title: "Sınır", text: "Vakanın başlangıç, bitiş ve analiz birimi açık mı?" },
      { title: "Üçgenleme", text: "Ana iddialar birden fazla kaynak türüyle sınandı mı?" },
      { title: "Etik", text: "Anonimlik ve hassas bilgi kararları gerçek bağlamda yeterli mi?" },
      { title: "Genelleme", text: "Sonuçlar tek vakanın taşıyabileceğinden daha büyük yazılmış mı?" },
    ],
    outputsHeading: "Bu eğitimden yedi somut çıktı ile çık",
    outputsIntro: "Vakayı sistemli analize dönüştür.",
    outputItems: [
      { title: "1 analitik soru", text: "Vakadan ne öğrenmek istediğini yaz." },
      { title: "1 vaka sınırı", text: "Yer, zaman, aktör ve süreci belirle." },
      { title: "1 seçim gerekçesi", text: "Bu vakanın neden anlamlı olduğunu açıkla." },
      { title: "1 kaynak envanteri", text: "Belge, görüşme, gözlem ve veriyi sırala." },
      { title: "1 kronoloji", text: "Kritik olayları kaynaklarıyla diz." },
      { title: "1 iddia–kaynak matrisi", text: "Ana açıklamaları destekleyen ve zorlayan kanıtı eşleştir." },
      { title: "1 etik not", text: "Anonimlik, onam ve hassas bilgi kararlarını yaz." },
    ],
    mastersIntro: "Vaka seçimi, kanıt zinciri ve analitik genelleme yaklaşımını farklı yöntem kaynaklarıyla incele.",
    masters: [
      { title: "Robert K. Yin", text: "Vaka tasarımı, kanıt zinciri ve çoklu kaynak kullanımı yaklaşımını incele." },
      { title: "Robert E. Stake", text: "Vakanın bağlamı, özgüllüğü ve nitel derinliği üzerine yaklaşımını incele." },
      { title: "Bent Flyvbjerg", text: "Vaka seçimi ve tekil örneklerden öğrenmenin sınırları üzerine tartışmalarını incele." },
    ],
    faq: [
      { question: "Tek vaka akademik olarak yeterli olabilir mi?", answer: "Evet, araştırma sorusu ve vaka seçimi gerekçesi uygunsa tek vaka derin analitik değer taşıyabilir; fakat genelleme biçimi dikkatle sınırlandırılmalıdır." },
      { question: "Kurum adını vermek zorunda mıyım?", answer: "Hayır. Araştırma amacı, etik onay, katılımcı riski ve yeniden tanınma olasılığına göre anonimleştirme kararı verilebilir." },
      { question: "Vaka analizinde nicel veri kullanılabilir mi?", answer: "Evet. Vaka analizi yalnız nitel olmak zorunda değildir; soruya uygunsa nicel, nitel veya karma kanıt birlikte kullanılabilir." },
    ],
    finalCaption: "Vaka analizi, olayın cazibesini değil kanıt zincirini merkeze aldığında akademik açıklamaya dönüşür.",
    ctaHeading: "Vaka analiz dosyanı kur",
    ctaText: "Analitik sorun ve vaka sınırın hazırsa İlkOku Yazar Alanı'nda kaynak ve kronoloji dosyanı oluşturmaya başla.",
  },
  {
    category: "Akademik",
    slug: "akademik-inceleme",
    label: "Akademik İnceleme",
    title: "Akademik İnceleme Nasıl Yazılır?",
    description: "İnceleme sorusundan arama stratejisine, dahil etme ölçütleri, kaynak değerlendirme, sentez, yanlılık ve şeffaf raporlamaya kadar adım adım akademik inceleme eğitimi.",
    summary: "Kaynakları peş peşe özetleme; açık bir inceleme sorusuyla literatürü sistemli biçimde ara, değerlendir, karşılaştır ve yeni bir senteze dönüştür.",
    alts: alts("Akademik İnceleme", "Dijital Okuma ve Anlama Üzerine Bulgular"),
    orientationHeading: "Akademik inceleme, kaynak özeti değil literatürden yeni bir bilgi haritası üretme işidir",
    orientationBody: "İncelemede veri setin çoğu zaman yayımlanmış çalışmalardır. Bu nedenle hangi çalışmaları nasıl bulduğun, neden dahil ettiğin, kalite ve çelişkileri nasıl değerlendirdiğin sonucu doğrudan etkiler. Sentez, kaynakları tek tek anlatmak değil aralarındaki örüntüyü açıklamaktır.",
    ideaHeading: "İnceleme sorusunu alanın gerçek belirsizliğinden çıkar",
    ideaIntro: "‘Bu konuda neler yazılmış?’ yerine karşılaştırılabilir bir soru kur.",
    ideaItems: [
      { title: "Dağınık bulgular", text: "Aynı konuda farklı yönlere giden sonuçları bir araya getir." },
      { title: "Yöntem farkı", text: "Farklı ölçüm veya tasarımların sonuçları nasıl değiştirdiğini incele." },
      { title: "Zaman içi değişim", text: "Kavram veya bulgunun dönemler içinde nasıl evrildiğini sor." },
      { title: "Eksik nüfus / bağlam", text: "Literatürün hangi grup veya coğrafyayı sistemli biçimde dışarıda bıraktığını araştır." },
    ],
    ideaFlowHeading: "Geniş literatür konusunu inceleme protokolüne dönüştür",
    ideaFlowBody: "‘Dijital okuma’ çok geniştir. ‘Üniversite öğrencilerinde uzun metinlerin ekran ve basılı ortamda okunması, anlama ve hatırlama sonuçlarını nasıl etkiliyor?’ sorusu; veri tabanı, tarih aralığı, çalışma türü ve sonuç ölçütleri için dahil etme kuralları üretir.",
    contrastHeading: "Akademik incelemeyi kaynak derlemesinden ayır",
    contrastIntro: "Kaynak sayısı değil seçim ve sentez mantığı belirleyicidir.",
    contrastItems: [
      { title: "İnceleme ≠ bibliyografya", text: "Kaynakları listelemek yerine araştırma sorusuna göre analiz eder." },
      { title: "İnceleme ≠ özet zinciri", text: "‘A dedi, B dedi’ sırası yerine tema, yöntem ve bulgu ilişkisi kurar." },
      { title: "İnceleme ≠ seçilmiş görüşler", text: "Yalnız tezini destekleyen çalışmaları toplamak seçim yanlılığı üretir." },
    ],
    routeHeading: "Akademik incelemeyi 10 aşamada kur",
    routeIntro: "Arama ve seçim kararlarını baştan tanımla.",
    routeItems: [
      { title: "1 · İnceleme sorusu", text: "Kapsamı ve karşılaştırma eksenini belirle." },
      { title: "2 · Protokol", text: "Veri tabanı, tarih, dil, çalışma türü ve dahil/dışla ölçütlerini yaz." },
      { title: "3 · Arama dizileri", text: "Kavramların eş ve yakın terimlerini birleştir." },
      { title: "4 · Tarama", text: "Başlık/özet ve ardından tam metin değerlendirmesini kayıtlı yap." },
      { title: "5 · Veri çıkarımı", text: "Her çalışmadan aynı alanları sistemli biçimde çıkar." },
      { title: "6 · Kalite değerlendirmesi", text: "Yöntem gücü ve riskleri karşılaştır." },
      { title: "7 · Sınıflandırma", text: "Çalışmaları tema, yöntem veya sonuç örüntülerine ayır." },
      { title: "8 · Sentez", text: "Uzlaşı, çelişki ve boşlukları açıklayan yapı kur." },
      { title: "9 · Yanlılık kontrolü", text: "Arama ve yayın yanlılığının sonucu nasıl etkileyebileceğini tartış." },
      { title: "10 · Raporlama", text: "Seçim akışı, yöntem ve sınırlılıkları şeffaf yaz." },
    ],
    structureHeading: "İncelemeyi kaynak sırasına değil araştırma sorusuna göre yapılandır",
    structureIntro: "Her bölüm literatür haritasında bir analitik görevi tamamlasın.",
    structureItems: [
      { title: "Problem ve kapsam", text: "İncelemenin neden gerekli olduğunu ve sınırını tanımla." },
      { title: "Yöntem", text: "Arama, seçim ve değerlendirme sürecini açıkla." },
      { title: "Literatür profili", text: "Çalışmaların dönem, yöntem ve örneklem dağılımını göster." },
      { title: "Tematik sentez", text: "Ana bulgu kümelerini karşılaştır." },
      { title: "Çelişki ve kalite", text: "Sonuç farklarının yöntem veya bağlamla ilişkisini tartış." },
      { title: "Boşluk ve sonuç", text: "Ne bildiğimizi, neyi bilmediğimizi ve sonraki araştırmayı yaz." },
    ],
    structureCaption: "Akademik inceleme yapısı, kaynakları tek tek anlatmak yerine literatürün bütün örüntüsünü görünür kılar.",
    anatomyHeading: "Akademik incelemenin anatomisi: soru, arama, seçim, değerlendirme ve sentez",
    anatomyBody: "- **İnceleme sorusu:** Hangi literatürün içeri gireceğini belirler.\n- **Arama stratejisi:** Kaynak evrenine nasıl ulaşıldığını gösterir.\n- **Dahil/dışla ölçütleri:** Seçim kararlarını sınırlar.\n- **Veri çıkarım formu:** Çalışmaları karşılaştırılabilir hale getirir.\n- **Kalite değerlendirmesi:** Tüm çalışmaların eşit ağırlıkta olmadığını gösterir.\n- **Sentez:** Uzlaşı, çelişki ve boşluğu açıklar.\n- **Yanlılık:** Görünmeyen veya dışarıda kalan literatürün etkisini tartışır.",
    practiceHeading: "İnceleme için altı izlenebilir dosya tut",
    practiceIntro: "Arama ve eleme kararlarını hafızada bırakma.",
    practiceItems: [
      { title: "Arama günlüğü", text: "Veri tabanı, tarih, sorgu ve sonuç sayısını kaydet." },
      { title: "Tarama tablosu", text: "Dahil/dışla kararını kısa gerekçeyle yaz." },
      { title: "Veri çıkarım matrisi", text: "Amaç, örneklem, yöntem, ölçüm, bulgu ve sınırlılığı aynı sütunlarda tut." },
      { title: "Kalite notu", text: "Her çalışmanın yöntemsel güçlü ve zayıf tarafını kaydet." },
      { title: "Tema haritası", text: "Kaynakları sonuç veya yöntem kümelerine bağla." },
      { title: "Çelişki listesi", text: "Literatürün uzlaşmadığı noktaları özellikle görünür tut." },
    ],
    pageSetupCaption: "Akademik inceleme çalışma düzeni, aramadan senteze kadar her seçim kararını geri izlenebilir kılar.",
    workspaceHeading: "İnceleme klasörünü arama, seçim ve sentez aşamalarına göre düzenle",
    workspaceIntro: "Aynı kaynağı farklı aşamalarda kaybetmeden takip et.",
    workspaceItems: [
      { title: "01-protokol", text: "Soru, kapsam ve dahil/dışla kuralları." },
      { title: "02-arama", text: "Sorgular ve ham sonuç listeleri." },
      { title: "03-tarama", text: "Eleme kararları ve tam metin durumu." },
      { title: "04-veri-cikarimi", text: "Karşılaştırılabilir çalışma matrisi." },
      { title: "05-sentez", text: "Tema, çelişki, kalite ve yazı taslakları." },
    ],
    craftHeading: "Akademik incelemenin asıl zanaatı: kaynakları özetlemekten sentezlemeye geçmek",
    craftBody: "Sentezde tek tek çalışmalar değil ilişkiler özne olur: Hangi yöntemler benzer sonuç veriyor? Hangi bağlamlarda sonuç değişiyor? Çelişki örneklem farkından mı, ölçümden mi, kuramsal varsayımdan mı doğuyor? Metin bu soruların cevabını örgütlemelidir.",
    extraSections: [
      {
        id: "arama-protokolu",
        type: "steps",
        heading: "Arama stratejisini tekrar edilebilir protokole dönüştür",
        intro: "Okur, yaklaşık olarak aynı aramayı yeniden yapabilsin.",
        items: [
          { title: "Kavram blokları", text: "Ana kavramların eş, yakın ve alternatif yazımlarını çıkar." },
          { title: "Veri tabanı seçimi", text: "Alan için neden uygun olduklarını belirt." },
          { title: "Sorgu kaydı", text: "Boole operatörleri ve filtrelerle tam sorguyu sakla." },
          { title: "Tarih ve filtre", text: "Aramanın yapıldığı gün, dil, dönem ve belge türünü kaydet." },
          { title: "Ek arama", text: "Kaynakça zinciri, atıf takibi veya gri literatür kullanıyorsan yöntemi belirt." },
        ],
      },
      {
        id: "kalite-degerlendirmesi",
        type: "cards",
        heading: "Çalışmaları yalnız sonuçlarına göre değil yöntem kalitesine göre de oku",
        intro: "Aynı yönde sonuç veren iki çalışma aynı kanıt gücüne sahip olmayabilir.",
        items: [
          { title: "Örneklem", text: "Seçim biçimi ve büyüklüğü araştırma sorusuna uygun mu?" },
          { title: "Ölçüm", text: "Kavramlar geçerli ve güvenilir araçlarla mı ölçülmüş?" },
          { title: "Tasarım", text: "Çalışmanın iddiası kullanılan tasarımın izin verdiği düzeyde mi?" },
          { title: "Analiz", text: "Analiz yöntemi veri ve soruyla uyumlu mu?" },
          { title: "Şeffaflık", text: "Eksik veri, dışlama ve sınırlılıklar raporlanmış mı?" },
        ],
      },
      {
        id: "sentez-ve-yanlilik",
        type: "cards",
        heading: "Sentez yaparken görünmeyen literatürü ve yanlılığı düşün",
        intro: "Yayımlanmış çalışmalar bütün araştırma evrenini temsil etmeyebilir.",
        items: [
          { title: "Yayın yanlılığı", text: "Olumlu veya anlamlı sonuçların yayımlanma olasılığı daha yüksek olabilir." },
          { title: "Dil yanlılığı", text: "Yalnız tek dilde arama yapmak bazı bağlamları dışarıda bırakabilir." },
          { title: "Veri tabanı yanlılığı", text: "Tek platform alanın tamamını kapsamayabilir." },
          { title: "Seçim yanlılığı", text: "Kendi görüşünü destekleyen çalışmaları istemeden öne çıkarıp çıkarmadığını kontrol et." },
        ],
      },
    ],
    draftHeading: "İlk inceleme taslağında kaynak isimlerini değil bulgu kümelerini merkeze al",
    draftIntro: "Paragrafların öznesi mümkün olduğunca tek tek yazarlar değil literatürdeki örüntüler olsun.",
    draftItems: [
      { title: "Tema cümlesi", text: "Paragrafın hangi ortak bulguyu veya çelişkiyi anlattığını yaz." },
      { title: "Kaynak karşılaştırması", text: "Benzer ve farklı sonuçları aynı paragrafta ilişkilendir." },
      { title: "Yöntem açıklaması", text: "Sonuç farkının olası yöntemsel nedenini göster." },
      { title: "Ara sonuç", text: "Paragraf sonunda literatürden ne öğrendiğini ve neyin açık kaldığını yaz." },
    ],
    revisionHeading: "İnceleme revizyonunda temsil ve sentez kalitesini denetle",
    revisionIntro: "Kaynak sayısı yüksek olsa bile literatür yanlış temsil edilebilir.",
    revisionItems: [
      { title: "Kapsam testi", text: "Metin protokolde tanımlanan literatür evrenini gerçekten temsil ediyor mu?" },
      { title: "Sentez testi", text: "Paragraflar özet zinciri mi, yoksa kaynaklar arası ilişki mi kuruyor?" },
      { title: "Kalite testi", text: "Zayıf ve güçlü çalışmalar aynı ağırlıkla mı sunulmuş?" },
      { title: "Boşluk testi", text: "‘Araştırma yok’ denilen yerde arama stratejisi bu sonucu destekliyor mu?" },
    ],
    projectName: "Dijital Okuma ve Anlama Üzerine Bulgular",
    projectBody: "**Soru:** Üniversite öğrencilerinde uzun akademik metinlerin ekran ve basılı ortamda okunması, anlama ve hatırlama sonuçlarını nasıl etkiliyor?\n\n**Kapsam:** Belirli tarih aralığında hakemli deneysel ve yarı deneysel çalışmalar.\n\n**Dahil etme:** Üniversite örneklemi, uzun metin okuma, ekran–basılı karşılaştırması, ölçülmüş anlama veya hatırlama sonucu.\n\n**Veri çıkarımı:** Örneklem, metin uzunluğu, cihaz, süre baskısı, ölçüm türü ve sonuç.\n\n**Sentez sorusu:** Sonuç farkları ortamdan mı, süre baskısından mı, metin türünden mi etkileniyor?",
    projectCaption: "Örnek inceleme, kaynak toplamayı açık soru, seçim ölçütü ve karşılaştırılabilir veri çıkarım sistemiyle sınırlar.",
    sampleHeading: "Örnek sentez paragrafı: çalışmalar değil örüntü merkezde",
    sampleBody: "İncelenen çalışmaların çoğu basılı okumada küçük bir anlama avantajı bildirse de bu fark özellikle süre baskısının bulunduğu tasarımlarda belirginleşmektedir. Sürenin katılımcı tarafından yönetildiği çalışmalarda ortam farkı daha zayıftır; bu durum okuma ortamı ile zaman yönetiminin birlikte değerlendirilmesi gerektiğini düşündürmektedir.",
    finalHeading: "İncelemeyi yayıma hazırlamadan önce yöntem şeffaflığını kontrol et",
    finalIntro: "Okur kaynakların nasıl bulunduğunu ve seçildiğini anlayabilmeli.",
    finalItems: [
      { title: "Arama kaydı", text: "Veri tabanları, sorgular, tarihler ve filtreler tam mı?" },
      { title: "Seçim akışı", text: "Kaç kaynağın hangi aşamada neden dışlandığı kayıtlı mı?" },
      { title: "Kalite", text: "Çalışmaların yöntemsel gücü sonuç yorumuna yansıtılmış mı?" },
      { title: "Yanlılık / sınır", text: "Dil, veri tabanı, yayın ve kapsam sınırları açık mı?" },
    ],
    outputsHeading: "Bu eğitimden sekiz somut çıktı ile çık",
    outputsIntro: "İnceleme fikrini izlenebilir literatür araştırmasına dönüştür.",
    outputItems: [
      { title: "1 inceleme sorusu", text: "Kapsamı ve karşılaştırma eksenini yaz." },
      { title: "1 protokol", text: "Dahil/dışla ve veri tabanı kurallarını belirle." },
      { title: "1 arama dizisi", text: "Ana kavramları sorguya dönüştür." },
      { title: "1 tarama tablosu", text: "Seçim kararlarını gerekçeleriyle kaydet." },
      { title: "1 veri çıkarım matrisi", text: "Çalışmaları aynı alanlarda karşılaştır." },
      { title: "1 kalite kontrol şablonu", text: "Yöntemsel gücü sistemli değerlendir." },
      { title: "1 tema haritası", text: "Uzlaşı ve çelişki kümelerini çıkar." },
      { title: "1 sentez paragrafı", text: "En az üç kaynağı tek analitik örüntüde birleştir." },
    ],
    mastersIntro: "Sistematik inceleme, kanıt sentezi ve literatür değerlendirme disiplinini yöntem kaynakları üzerinden incele.",
    masters: [
      { title: "Cochrane yaklaşımı", text: "Protokol, sistematik arama, risk değerlendirmesi ve şeffaf sentez ilkelerini incele." },
      { title: "PRISMA çerçevesi", text: "Arama ve çalışma seçim sürecinin şeffaf raporlanma mantığını incele." },
      { title: "Grant & Booth", text: "Farklı inceleme türlerinin amaç ve yöntem farklarını karşılaştır." },
    ],
    faq: [
      { question: "Akademik incelemede her bulunan kaynağı kullanmalı mıyım?", answer: "Hayır. Önceden belirlenmiş kapsam ve kalite ölçütlerine uymayan kaynaklar dışarıda bırakılabilir; kararın şeffaf olması gerekir." },
      { question: "Sistematik inceleme ile anlatı incelemesi aynı mı?", answer: "Hayır. Amaç, arama ve sentez yöntemleri farklı olabilir. Hangi inceleme türünü yaptığını ve yöntemini açıkça tanımlamalısın." },
      { question: "Literatürde çelişki varsa hangisini doğru kabul etmeliyim?", answer: "Önce tasarım, örneklem, ölçüm ve bağlam farklarını incele; çelişkinin nedenini açıklamak çoğu zaman tek taraf seçmekten daha değerlidir." },
    ],
    finalCaption: "Akademik inceleme, çok kaynak topladığında değil kaynakları şeffaf seçim ve analitik sentezle yeni bir bilgi haritasına dönüştürdüğünde tamamlanır.",
    ctaHeading: "İnceleme protokolünü kur",
    ctaText: "İnceleme sorun ve kapsamın hazırsa İlkOku Yazar Alanı'nda arama, seçim ve sentez dosyanı oluşturmaya başla.",
  },
];

export function getEducationGuideDefinition(slug: string): AcademicGuideDefinition {
  const definition = definitions.find((item) => item.slug === slug);
  if (!definition) throw new Error(`Academic education guide definition missing: ${slug}`);
  return definition;
}
