import type { EducationGuideDefinition } from "@/lib/education-guide-batch";

function alts(label: string, project: string): EducationGuideDefinition["alts"] {
  return {
    hero: `${label} yazarlığı için sahne, zamanlama ve taslak notları bulunan İlkOku çalışma masası`,
    ideaFlow: `${label} fikrinin çekirdek fikirden sahne akışına dönüşümünü gösteren eğitim şeması`,
    structure: `${label} yapısının bölüm, sahne veya sekans düzenini gösteren diyagram`,
    anatomy: `${label} eserinin temel görsel, işitsel ve dramatik parçalarını gösteren eser anatomisi`,
    pageSetup: `${label} taslağı için sahne, süre, karakter ve revizyon notlarının düzenlendiği çalışma alanı`,
    project: `${project} adlı örnek projenin araştırma, sahne ve taslak planını gösteren çalışma panosu`,
    finalCta: `${label} taslağını tamamlayıp İlkOku Yazar Alanı'nda üretime geçmeye hazırlanan çalışma ortamı`,
  };
}

const definitions: EducationGuideDefinition[] = [
  {
    category: "Senaryo ve Sahne",
    slug: "film-senaryosu",
    label: "Film Senaryosu",
    title: "Film Senaryosu Nasıl Yazılır?",
    description: "Logline'dan sahneye, sekans ve görsel anlatımdan ilk taslak ve revizyona kadar adım adım film senaryosu eğitimi.",
    summary: "Hikâyeyi açıklamak yerine görünür ve oynanabilir hale getir; karakter hedefini sahne eylemine, sahneleri de filmin ritmine dönüştür.",
    alts: alts("Film Senaryosu", "Son Peron"),
    orientationHeading: "Film senaryosu, okunacak metinden önce çekilecek filmin planıdır",
    orientationBody: "Senaryoda yalnız iyi fikir yetmez. Görüntüye dönüşmeyen açıklama, sahnede eyleme dönüşmeyen duygu ve dramatik işlevi olmayan diyalog filmi taşımaz. Yazarken sürekli şu soruyu sor: Kamera ve oyuncu bunu nasıl gösterecek?",
    ideaHeading: "Film fikrini dört yerden çıkar",
    ideaIntro: "Film fikri, tek cümlede görsel bir çatışma taşımalıdır.",
    ideaItems: [
      { title: "Görsel durum", text: "Tek bakışta anlaşılabilecek ama sonucu belirsiz bir durum seç." },
      { title: "Zor seçim", text: "Karakterin iki değer arasında kalacağı karar noktası kur." },
      { title: "Kapalı zaman", text: "Bir gece, yolculuk veya vardiya gibi sınırlı süre hikâyeyi sıkıştırabilir." },
      { title: "Mekân baskısı", text: "İstasyon, hastane, otel veya gemi gibi karakteri eyleme zorlayan bir mekân seç." },
    ],
    ideaFlowHeading: "Fikri logline'a dönüştür",
    ideaFlowBody: "Logline; kahramanı, amacını, ana engeli ve hikâyenin ayırt edici koşulunu tek cümlede görünür kılar. ‘Bir adam geçmişiyle yüzleşir’ yerine, ‘Kapanmak üzere olan bir tren istasyonunun gece görevlisi, yıllar önce kaybolan kızına ait valizi son seferde bulunca treni durdurmak için kuralları çiğner’ gibi eylem taşıyan bir çekirdek kur.",
    contrastHeading: "Film senaryosunu komşu biçimlerden ayır",
    contrastIntro: "Aynı hikâye roman, dizi veya tiyatroda başka araçlarla çalışır.",
    contrastItems: [
      { title: "Film ≠ roman", text: "İç düşünceyi açıklamak yerine davranış, görüntü, ritim ve seçimle gösterir." },
      { title: "Film ≠ dizi", text: "Tek filmlik dramatik yay ve kapanış ister; sürekli bölüm motoruna ihtiyaç duymaz." },
      { title: "Film ≠ tiyatro", text: "Kamera, kurgu ve mekân değişimi anlatımın aktif araçlarıdır." },
    ],
    routeHeading: "Film senaryosunu 8 aşamada kur",
    routeIntro: "Önce filmin omurgasını sabitle, sonra sahneleri yaz.",
    routeItems: [
      { title: "1 · Logline", text: "Kahraman + amaç + engel + ayırt edici koşulu tek cümlede yaz." },
      { title: "2 · Tema sorusu", text: "Filmin tartıştığı ahlaki veya duygusal soruyu belirle." },
      { title: "3 · Karakter dönüşümü", text: "Başlangıçtaki yanlış inanç ile finaldeki seçim arasındaki değişimi kur." },
      { title: "4 · Sekanslar", text: "Hikâyeyi sonuç üreten büyük eylem bloklarına böl." },
      { title: "5 · Sahne kartları", text: "Her sahnenin hedefini, çatışmasını ve değişimini yaz." },
      { title: "6 · İlk taslak", text: "Biçim ve ritmi koruyarak baştan sona senaryoyu tamamla." },
      { title: "7 · Masa okuması", text: "Diyalog, tempo ve gereksiz açıklamayı sesli okuyarak sınay." },
      { title: "8 · Revizyon", text: "Sahne işlevi, görsellik ve süre üzerinden yeniden yaz." },
    ],
    structureHeading: "Filmi sahne değil dramatik sonuç zinciri olarak düşün",
    structureIntro: "Her bölüm bir sonrakini zorunlu hale getirmeli.",
    structureItems: [
      { title: "Kurulum", text: "Karakterin normalini ve eksik dengesini göster." },
      { title: "Tetikleyici", text: "Eski düzeni sürdürülemez kılan olay." },
      { title: "İlk büyük seçim", text: "Karakter geri dönüşü zorlaştıran bir karar verir." },
      { title: "Baskı ve karşılık", text: "Engeller sertleşir; karakter yöntemi değiştirir." },
      { title: "Kriz", text: "En zor bedel ve en net seçim aynı noktaya gelir." },
      { title: "Final", text: "Karakterin son eylemi filmin tema sorusuna cevap verir." },
    ],
    structureCaption: "Film yapısı, dakika hesabından önce karar ve sonuçların birbirini doğurduğu dramatik zincirdir.",
    anatomyHeading: "Film senaryosunun anatomisi: sahne, eylem, görüntü ve ses",
    anatomyBody: "- **Sahne başlığı:** Nerede ve ne zaman?\n- **Eylem:** Kamera önünde görülebilen ne oluyor?\n- **Karakter hedefi:** Bu sahnede kim ne istiyor?\n- **Çatışma:** Hedefi kim veya ne bozuyor?\n- **Diyalog:** Eylemin yerine açıklama yapmamalı.\n- **Görsel motif:** Filmin tekrar eden görüntü dili.\n- **Sahne çıkışı:** Sahne sonunda bilgi, güç veya amaç ne kadar değişti?",
    practiceHeading: "Film yazarken dört çalışma dosyası tut",
    practiceIntro: "Senaryonun görünmeyen planı, sahnelerin daha hızlı yazılmasını sağlar.",
    practiceItems: [
      { title: "Logline dosyası", text: "Farklı logline sürümlerini karşılaştır." },
      { title: "Sekans haritası", text: "Her sekansın amacı ve sonucunu tek satırda gör." },
      { title: "Sahne kartları", text: "Amaç, engel, dönüş ve çıkış bilgisini ayrı tut." },
      { title: "Görsel motif listesi", text: "Tekrar eden nesne, renk, mekân ve görüntüleri takip et." },
    ],
    pageSetupCaption: "Film çalışma düzeni, sahne numarasından önce sahnenin dramatik işlevini görünür tutar.",
    workspaceHeading: "Senaryo dosyanı sahne mantığıyla düzenle",
    workspaceIntro: "Revizyonda sahneleri tek tek test edebilmek için dosyayı izlenebilir tut.",
    workspaceItems: [
      { title: "Tek sahne / tek amaç", text: "Sahne başına baskın bir dramatik hedef belirle." },
      { title: "Sekans etiketi", text: "Her sahnenin hangi sekansa hizmet ettiğini işaretle." },
      { title: "Süre notu", text: "Sayfa ve tempo ilişkisini yaklaşık süreyle kontrol et." },
      { title: "Revizyon rengi", text: "Yapı, diyalog ve görsel revizyonu ayrı geçişlerde takip et." },
    ],
    craftHeading: "Film senaryosunun asıl zanaatı: gösterilebilir eylem",
    craftBody: "‘Kendini yalnız hisseder’ yazmak yerine yalnızlığı görünür kılacak davranışı seç. Kamera zihni okuyamaz; oyuncu ise niyeti eyleme dönüştürür. Bu nedenle her önemli duygu için davranış, nesne, mekân veya seçim karşılığı ara.",
    draftHeading: "İlk taslakta filmi açıklama, oynat",
    draftIntro: "İlk hedef kusursuz diyalog değil, baştan sona çalışan bir film akışı görmek.",
    draftItems: [
      { title: "Sahneyi geç başlat", text: "Gereksiz selamlaşma ve hazırlığı at; çatışmaya yakın gir." },
      { title: "Erken çık", text: "Sahnenin dramatik sonucu oluşunca açıklama eklemeden çık." },
      { title: "Alt metni koru", text: "Karakterlerin her düşündüğünü söylemesine izin verme." },
      { title: "Sona kadar ilerle", text: "Ortadaki problemi ilk taslakta aşırı cilalama uğruna durdurma." },
    ],
    revisionHeading: "Film revizyonunu sahne işlevi üzerinden yap",
    revisionIntro: "Her sahne filmi ileri itmeli veya karakteri değiştirmeli.",
    revisionItems: [
      { title: "Sahne testi", text: "Bu sahne çıkarsa hikâyede ne kayboluyor? Hiçbir şey değilse kes." },
      { title: "Görsellik testi", text: "Bilginin mümkün olan kısmı görüntü veya davranışla aktarılıyor mu?" },
      { title: "Diyalog testi", text: "Karakterler yalnız seyirciyi bilgilendirmek için mi konuşuyor?" },
      { title: "Final testi", text: "Son seçim filmin başındaki temel soruyla bağ kuruyor mu?" },
    ],
    projectName: "Son Peron",
    projectBody: "**Kahraman:** Kapanmak üzere olan küçük bir istasyonun gece görevlisi Arda.\n\n**Tetikleyici:** Son tren öncesi emanet odasında, yıllar önce kaybolan kızına ait eski bir valiz bulunur.\n\n**Amaç:** Tren kalkmadan valizin kime ait olduğunu ve neden geri döndüğünü bulmak.\n\n**Engel:** İstasyon kapanış protokolü, görev amiri ve yalnızca birkaç dakikalık zaman.\n\n**Final seçimi:** Arda kurallara uyup son treni göndermekle, hattı durdurup yıllardır kaçtığı gerçeği açmak arasında kalır.",
    projectCaption: "Son Peron, kişisel çatışmayı görünür bir zaman baskısı ve sahne eylemiyle filme dönüştürür.",
    sampleHeading: "Örnek sahne çekirdeği: bilgi değil eylem",
    sampleBody: "Arda valizin kilidini zorlamaz. Üzerindeki solmuş bagaj etiketini çevirir. Arkasında kendi el yazısıyla tek cümle vardır: ‘Dönüş 23.40.’ Duvar saatine bakar: 23.32. Perondan son trenin fren sesi gelir.",
    finalHeading: "Senaryoyu paylaşmadan önce son kontrolü yap",
    finalIntro: "Biçim kadar dramatik okunabilirliği de temizle.",
    finalItems: [
      { title: "Logline kontrolü", text: "Bitmiş film hâlâ ilk çekirdeğin sözünü tutuyor mu?" },
      { title: "Sahne başlıkları", text: "Mekân ve zaman bilgileri tutarlı mı?" },
      { title: "Karakter adları", text: "İsim ve ilk tanıtımlar karışıyor mu?" },
      { title: "Masa okuması", text: "Diyalog ritmi ve sahne süresi sesli okumada çalışıyor mu?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Sayfayı yalnız okumak değil, kendi filmini kurmak için kullan.",
    outputItems: [
      { title: "1 logline", text: "Filmini tek cümlede anlat." },
      { title: "1 sekans haritası", text: "Büyük dramatik blokları sırala." },
      { title: "8 sahne kartı", text: "Amaç, engel ve sonucu yaz." },
      { title: "1 açılış sahnesi", text: "Görüntü ve eylemle ilk sahneyi yaz." },
    ],
    mastersIntro: "Farklı filmlerde görsel anlatı, sahne ekonomisi ve karakter hedefinin nasıl kurulduğunu incele.",
    masters: [
      { title: "Billy Wilder", text: "Sahne amacı, ekonomik anlatım ve dramatik ironiyi incele." },
      { title: "Nuri Bilge Ceylan", text: "Sessizlik, davranış ve mekânın dramatik yükünü incele." },
      { title: "Phoebe Waller-Bridge", text: "Karakter sesi, ritim ve sahne dönüşlerini incele." },
    ],
    faq: [
      { question: "Senaryoya diyalogla mı başlamalıyım?", answer: "Hayır. Önce sahnenin neyi değiştireceğini ve karakterin ne istediğini bilmek daha önemlidir." },
      { question: "Film senaryosunda her şeyi ayrıntılı tarif etmeli miyim?", answer: "Hayır. Çekim kararı vermek yerine dramatik olarak gerekli, görülebilir eylemi açık yaz." },
    ],
    finalCaption: "Film senaryosu, fikirden çekilebilir sahne akışına dönüştüğünde gerçek anlamda çalışmaya başlar.",
    ctaHeading: "Filmini sahnelere dönüştürmeye başla",
    ctaText: "Logline'ını ve sahne haritanı hazırladıysan, İlkOku Yazar Alanı'nda senaryonun ilk taslağını kur.",
  },
  {
    category: "Senaryo ve Sahne",
    slug: "dizi-senaryosu",
    label: "Dizi Senaryosu",
    title: "Dizi Senaryosu Nasıl Yazılır?",
    description: "Dizi motorundan pilot bölüme, A/B hikâyelerinden sezon yayı ve bölüm revizyonuna kadar adım adım dizi senaryosu eğitimi.",
    summary: "Tek bir iyi hikâye değil, tekrar tekrar yeni bölüm üretebilen bir dünya ve karakter motoru kur.",
    alts: alts("Dizi Senaryosu", "Gece Servisi"),
    orientationHeading: "Dizi, uzun film değil; tekrar üreten dramatik sistemdir",
    orientationBody: "Bir dizinin temel sorusu yalnız ‘pilot bölümde ne oluyor?’ değildir. Asıl soru şudur: Bu karakterler ve bu dünya neden ikinci, üçüncü ve onuncu bölümde hâlâ yeni çatışma üretebilir? Dizi motoru bunu cevaplar.",
    ideaHeading: "Dizi fikrini dört motor üzerinden kur",
    ideaIntro: "İyi dizi fikri, tek olaydan daha geniş bir tekrar potansiyeli taşır.",
    ideaItems: [
      { title: "Meslek motoru", text: "Her bölüm yeni vaka veya sorun üreten iş alanı seç." },
      { title: "Aile / ilişki motoru", text: "Aynı karakterleri sürekli yeni güç ve sadakat çatışmalarına sokan ilişki ağı kur." },
      { title: "Mekân motoru", text: "Hastane, otel, okul veya mahalle gibi yeni hikâye girişlerine açık merkez seç." },
      { title: "Sır motoru", text: "Sezon boyunca açılabilecek ama tek başına diziyi tüketmeyen uzun soru kur." },
    ],
    ideaFlowHeading: "Fikri dizi önermesine dönüştür",
    ideaFlowBody: "Dizi önermesi; ana dünya, sürekli çatışma kaynağı, baş karakter ve bölüm üretme mekanizmasını birlikte anlatır. Tek olay yerine ‘her bölüm ne üretecek?’ sorusunu cevapla.",
    contrastHeading: "Dizi senaryosunu filmden ayır",
    contrastIntro: "Pilot yalnız başlangıçtır; asıl başarı sürdürülebilirliktir.",
    contrastItems: [
      { title: "Dizi ≠ uzun film", text: "Tek bir kapanış yerine devam eden karakter ve bölüm motoru ister." },
      { title: "Pilot ≠ tanıtım broşürü", text: "Dünyayı anlatmakla kalmaz; çalışan bir bölüm örneği sunar." },
      { title: "Sezon yayı ≠ bölüm özeti", text: "Bölümlerin toplamından daha büyük karakter ve güç değişimini kurar." },
    ],
    routeHeading: "Dizi projesini 8 aşamada kur",
    routeIntro: "Önce motoru, sonra pilotu yaz.",
    routeItems: [
      { title: "1 · Dizi önermesi", text: "Dünya, ana karakter ve tekrar üreten çatışmayı tanımla." },
      { title: "2 · Format", text: "Bölüm süresi, tür, ton ve hedef izleyici kararını ver." },
      { title: "3 · Karakter ağı", text: "İlişkilerin nasıl sürekli sorun ürettiğini haritala." },
      { title: "4 · Bölüm motoru", text: "Her bölümün hangi tip olayla çalışacağını tanımla." },
      { title: "5 · Sezon yayı", text: "Ana değişim ve uzun soruyu bölüm noktalarına dağıt." },
      { title: "6 · Pilot beat sheet", text: "A, B ve gerekiyorsa C hikâyeyi sahne düzeyine indir." },
      { title: "7 · Pilot taslak", text: "Dizinin vaat ettiği deneyimi gerçekten gösteren bölümü yaz." },
      { title: "8 · Dizi bible", text: "Dünya, karakter, ton ve gelecek bölüm örneklerini derle." },
    ],
    structureHeading: "Dizi yapısını bölüm içi ve sezon üstü iki katmanda kur",
    structureIntro: "Her bölüm tatmin edici olmalı; sezon ise karakterleri daha büyük bir değişime götürmeli.",
    structureItems: [
      { title: "Cold open / açılış", text: "Bölümün tonunu ve merakını hızlı kur." },
      { title: "A hikâyesi", text: "Bölümün baskın dramatik sorusu." },
      { title: "B hikâyesi", text: "Karakter veya ilişki üzerinden ana temayı başka açıdan işler." },
      { title: "Kesişim", text: "Hikâyeler birbirini etkiler veya aynı karara bağlanır." },
      { title: "Bölüm sonucu", text: "Bir şey kapanır, yeni bir şey açılır." },
      { title: "Sezon ilerlemesi", text: "Her bölüm uzun yayı az da olsa değiştirir." },
    ],
    structureCaption: "Dizi yapısı, bölüm tatmini ile sezon devamlılığını aynı anda taşır.",
    anatomyHeading: "Dizi anatomisi: motor, karakter ağı, bölüm ve sezon yayı",
    anatomyBody: "- **Dizi motoru:** Her hafta ne yeni hikâye üretiyor?\n- **Format:** Süre, tür ve ton.\n- **Karakter ağı:** Kim kimin hedefini bozuyor?\n- **A/B hikâyeleri:** Bölüm içi paralel dramatik çizgiler.\n- **Sezon yayı:** Uzun değişim.\n- **Cliffhanger:** Devam merakı; yapay şok değil.\n- **Bible:** Dizinin üretim hafızası.",
    practiceHeading: "Dizi yazarken dört üretim dosyası tut",
    practiceIntro: "Dizi, tek metinden çok yaşayan bir sistemdir.",
    practiceItems: [
      { title: "Karakter matrisi", text: "Her karakterin diğerleriyle çıkar ve sır ilişkisini kaydet." },
      { title: "Bölüm fikir havuzu", text: "Motorun gerçekten kaç ayrı bölüm üretebildiğini test et." },
      { title: "Sezon çizelgesi", text: "Uzun yay bilgisini bölüm bazında dağıt." },
      { title: "Continuity dosyası", text: "Yaşanan olay, bilgi ve zaman tutarlılığını takip et." },
    ],
    pageSetupCaption: "Dizi çalışma düzeni, pilotun yanında sezon ve continuity bilgisini de görünür tutar.",
    workspaceHeading: "Dizi dosyanı bölüm ve sezon katmanlarıyla düzenle",
    workspaceIntro: "Pilot üzerinde çalışırken gelecek bölümlerin motorunu kaybetme.",
    workspaceItems: [
      { title: "Bölüm kartı", text: "Her bölüm için A hikâyesi, B hikâyesi ve sezon ilerlemesini yaz." },
      { title: "Karakter durum satırı", text: "Bölüm sonunda her karakterin ne bildiğini ve ne istediğini güncelle." },
      { title: "Açık sorular listesi", text: "Sezonda kapanması gereken sır ve vaatleri takip et." },
      { title: "Bible sürümü", text: "Dünya kurallarını değiştikçe güncelle." },
    ],
    craftHeading: "Dizinin asıl zanaatı: tekrar etmeden tekrar üretebilmek",
    craftBody: "Dizi motoru aynı sahneyi çoğaltmak değildir. Aynı dünya ve karakter ilişkileri, her bölümde farklı hedef ve bedeller üretmelidir. Pilot, bu motorun yalnız açıklamasını değil çalışan ilk örneğini göstermelidir.",
    draftHeading: "Pilot taslakta dünyayı anlatmaya çalışma, çalıştır",
    draftIntro: "İzleyici dizinin ne olduğunu karakterlerin eyleminden anlamalı.",
    draftItems: [
      { title: "Motoru ilk bölümde göster", text: "Dizinin tekrar üreten temel problemini pilotta gerçekten işlet." },
      { title: "Karakterleri işlevle tanıt", text: "Biyografi yerine çatışma içindeki davranışla tanıt." },
      { title: "A/B dengesini kur", text: "Yan hikâye ana temayı veya karakteri beslesin." },
      { title: "Bölüm sonunda kapı bırak", text: "Devam merakı üret ama pilotun kendi dramatik sonucunu da ver." },
    ],
    revisionHeading: "Dizi revizyonunu motor ve süreklilik üzerinden yap",
    revisionIntro: "İyi pilot, tek bölüm olarak da dizi vaadi olarak da çalışır.",
    revisionItems: [
      { title: "Motor testi", text: "Bu pilot sonrası en az 10 farklı bölüm fikri doğal çıkıyor mu?" },
      { title: "Karakter testi", text: "Ana karakterlerin hedefleri birbirini kesiyor mu?" },
      { title: "Pilot testi", text: "Dünyayı açıklamaktan çok yaşatıyor mu?" },
      { title: "Sezon testi", text: "Pilot finali uzun yayı doğal biçimde açıyor mu?" },
    ],
    projectName: "Gece Servisi",
    projectBody: "**Dünya:** Şehirlerarası otobüs terminalinde yalnız gece çalışan küçük bir sağlık birimi.\n\n**Dizi motoru:** Her gece farklı yolcu vakası gelir; ekip bu vakalar üzerinden kendi sırları ve ilişkileriyle yüzleşir.\n\n**Pilot A hikâyesi:** Kimliğini söylemeyen yaralı bir genç.\n\n**B hikâyesi:** Yeni doktor Defne'nin yıllar sonra babasının işlettiği terminale dönmesi.\n\n**Sezon yayı:** Terminalde yıllar önce kaybolan bir yolcu dosyasının Defne'nin ailesiyle bağlantısı.",
    projectCaption: "Gece Servisi, tek olay yerine sürekli yeni bölüm üreten mekân ve ekip motorunu gösterir.",
    sampleHeading: "Pilot açılışı: dünyayı açıklamadan tanıt",
    sampleBody: "Saat 02.13. Sağlık biriminin floresanı yanıp söner. Defne ilk vardiyasında çay makinesinin fişini ararken kapı açılır; iki şoför, konuşmayan bir genci içeri taşır. Masadaki telefon aynı anda çalar. Nöbetçi hemşire telefonu açmadan Defne'ye bakar: ‘Hangisini önce alırsın?’",
    finalHeading: "Pilot ve bible paylaşmadan önce son kontrol",
    finalIntro: "Dizinin hem ilk bölümünü hem devam potansiyelini görünür kıl.",
    finalItems: [
      { title: "Format", text: "Bölüm süresi ve tür tutarlı mı?" },
      { title: "Pilot", text: "Dizi motoru gerçekten çalışıyor mu?" },
      { title: "Sezon", text: "Uzun yay bölüm hikâyelerini boğuyor mu?" },
      { title: "Bible", text: "Dünya, karakter ve gelecek bölüm örnekleri net mi?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Dizi fikrini üretilebilir bir pakete dönüştür.",
    outputItems: [
      { title: "1 dizi önermesi", text: "Motoru ve dünyayı tek paragrafta anlat." },
      { title: "1 sezon çizelgesi", text: "Ana yayı bölüm noktalarına böl." },
      { title: "10 bölüm fikri", text: "Motorun sürdürülebilirliğini test et." },
      { title: "1 pilot açılışı", text: "Dünyayı çalışırken göster." },
    ],
    mastersIntro: "Dizi motoru, ensemble karakter ve bölüm/sezon dengesi için farklı yapımları çözümleyerek incele.",
    masters: [
      { title: "David Simon", text: "Sistem, karakter ağı ve uzun sezon yapısını incele." },
      { title: "Shonda Rhimes", text: "Bölüm motoru, karakter ilişkisi ve cliffhanger kullanımını incele." },
      { title: "Jesse Armstrong", text: "Güç ilişkileri, alt metin ve ensemble çatışmasını incele." },
    ],
    faq: [
      { question: "Önce pilotu mu, bible'ı mı yazmalıyım?", answer: "Önce temel motor ve karakter ağını netleştir; ardından pilotu yaz. Bible, çalışan pilotla birlikte daha sağlıklı gelişir." },
      { question: "Her bölüm cliffhanger ile mi bitmeli?", answer: "Hayır. Devam merakı önemlidir ama yapay şok yerine karakter, bilgi veya amaç değişimi yeterli olabilir." },
    ],
    finalCaption: "Dizi fikri, yalnız pilot değil yeni bölüm üreten bir dramatik sistem kurduğunda güçlenir.",
    ctaHeading: "Dizinin pilotunu kurmaya başla",
    ctaText: "Dizi motorun ve karakter ağın hazırsa, İlkOku Yazar Alanı'nda pilot bölüm taslağını oluştur.",
  },
  {
    category: "Senaryo ve Sahne",
    slug: "kisa-film-senaryosu",
    label: "Kısa Film Senaryosu",
    title: "Kısa Film Senaryosu Nasıl Yazılır?",
    description: "Tek güçlü durumdan kısa sahne akışına, görsel ekonomiden final etkisine kadar adım adım kısa film senaryosu eğitimi.",
    summary: "Az sürede çok şey anlatmaya çalışma; tek bir değişimi en güçlü görsel ve dramatik anlarına sıkıştır.",
    alts: alts("Kısa Film Senaryosu", "Üç Dakika"),
    orientationHeading: "Kısa film, uzun hikâyenin kesilmiş hali değil tek değişimin yoğunlaştırılmış biçimidir",
    orientationBody: "Kısa filmde zaman az olduğu için fikir daha net, karakter hedefi daha görünür ve gereksiz arka plan daha tehlikelidir. Tek bir durum, karar veya dönüşüm seç; filmin bütün enerjisini ona ver.",
    ideaHeading: "Kısa film fikrini sınırlamadan çıkar",
    ideaIntro: "Sınırlama kısa filmin düşmanı değil, motorudur.",
    ideaItems: [
      { title: "Tek karar", text: "Karakterin birkaç dakika içinde vermek zorunda olduğu zor seçim." },
      { title: "Tek mekân", text: "Bir oda, asansör, otobüs veya çatı üzerinden baskı üret." },
      { title: "Tek nesne", text: "Bir anahtar, telefon veya zarfı dramatik merkez yap." },
      { title: "Yanlış beklenti", text: "Seyircinin ilk yorumunu finalde yeniden anlamlandıracak durum kur." },
    ],
    ideaFlowHeading: "Fikri tek değişim cümlesine dönüştür",
    ideaFlowBody: "Kısa film çekirdeğini ‘Karakter filmin başında ne sanıyor, sonunda neyi artık aynı şekilde göremiyor?’ sorusuyla kur. Aradaki her sahne bu değişime hizmet etmeli.",
    contrastHeading: "Kısa filmi uzun metinden ayır",
    contrastIntro: "Kısalık yalnız süre değil, odak kararıdır.",
    contrastItems: [
      { title: "Kısa film ≠ özet film", text: "Birçok olayı hızlı anlatmak yerine tek dramatik ekseni yoğunlaştırır." },
      { title: "Kısa film ≠ skeç", text: "Yalnız espri veya fikir değil, dramatik değişim taşımalıdır." },
      { title: "Kısa film ≠ teaser", text: "Kendi başına tamamlanmış bir deneyim sunar." },
    ],
    routeHeading: "Kısa filmi 7 aşamada kur",
    routeIntro: "Her aşama gereksiz parçayı azaltmaya yardım eder.",
    routeItems: [
      { title: "1 · Tek çekirdek", text: "Bir durum ve bir değişim seç." },
      { title: "2 · Ana görüntü", text: "Filmi hatırlatacak tek görsel merkez belirle." },
      { title: "3 · Karakter hedefi", text: "Kısa sürede ulaşmak istediği somut şeyi tanımla." },
      { title: "4 · 5–8 beat", text: "Hikâyeyi az sayıda dramatik vuruşa böl." },
      { title: "5 · Sahne taslağı", text: "Giriş, baskı, karar ve sonucu yaz." },
      { title: "6 · İlk taslak", text: "Açıklama eklemeden filmi baştan sona tamamla." },
      { title: "7 · Sıkıştırma", text: "Her sahne ve cümleyi gereklilik testinden geçir." },
    ],
    structureHeading: "Kısa filmi dört hareketle düşün",
    structureIntro: "Az sahnede net dönüşüm.",
    structureItems: [
      { title: "Durum", text: "Normal ve hedef görünür olur." },
      { title: "Bozulma", text: "Tek olay karakteri seçim yapmaya zorlar." },
      { title: "Karar", text: "Karakter geri dönüşü zorlaştıran eylemi seçer." },
      { title: "Yeni anlam", text: "Final görüntüsü baştaki durumu başka anlamda gösterir." },
    ],
    structureCaption: "Kısa film yapısı, az sayıda vuruşla net bir algı veya karar değişimi yaratır.",
    anatomyHeading: "Kısa film anatomisi: tek durum, tek basınç, tek yankı",
    anatomyBody: "- **Ana durum:** Filmin tek cümlelik olayı.\n- **Hedef:** Karakterin hemen istediği şey.\n- **Baskı:** Zaman, kişi veya koşul.\n- **Görsel motif:** Açıklamayı azaltan tekrar.\n- **Karar anı:** Filmin ağırlık merkezi.\n- **Final görüntüsü:** Başlangıcı yeniden anlamlandıran yankı.",
    practiceHeading: "Kısa film için dört sade çalışma aracı kullan",
    practiceIntro: "Fazla dosya değil, güçlü seçim gerekir.",
    practiceItems: [
      { title: "Tek cümle kartı", text: "Filmin değişimini tek cümlede tut." },
      { title: "Beat listesi", text: "5–8 dramatik vuruşu sırala." },
      { title: "Nesne listesi", text: "Görüntüyle bilgi taşıyacak nesneleri belirle." },
      { title: "Kesme listesi", text: "Arka plan açıklaması ve tekrar eden beatleri işaretle." },
    ],
    pageSetupCaption: "Kısa film çalışma düzeni, her sahnenin tek değişime hizmet edip etmediğini görünür tutar.",
    workspaceHeading: "Kısa film dosyanı tek sayfalık haritayla yönet",
    workspaceIntro: "Bütün filmi aynı anda görebilmek kısa formatta büyük avantajdır.",
    workspaceItems: [
      { title: "Beat numarası", text: "Her dramatik vuruşu bir satırda tut." },
      { title: "Süre tahmini", text: "Sahne başına yaklaşık süre yaz." },
      { title: "Görsel bilgi", text: "Diyalog yerine görüntüyle verilen bilgiyi işaretle." },
      { title: "Final bağlantısı", text: "Her beatin final kararına nasıl hizmet ettiğini not et." },
    ],
    craftHeading: "Kısa filmin asıl zanaatı: dramatik ekonomi",
    craftBody: "Kısa filmde iyi fikir, en çok şeyi anlatan değil en az unsurla en güçlü değişimi yaratan fikirdir. Arka planı açıklamak yerine seçilmiş ayrıntıyla ima et; karakter geçmişini yalnız bugünkü kararı etkilediği kadar göster.",
    draftHeading: "İlk taslakta boşluk bırakmaktan korkma",
    draftIntro: "Seyircinin çıkarım yapabileceği bilgiyi açıklamayla doldurma.",
    draftItems: [
      { title: "Geç gir", text: "Hikâyenin başladığı ana mümkün olduğunca yakın başla." },
      { title: "Tek hedefe sadık kal", text: "Yan hikâye eklemek yerine baskıyı derinleştir." },
      { title: "Görüntüye güven", text: "Nesne, bakış ve davranışın taşıdığı bilgiyi tekrar söyleme." },
      { title: "Erken bitir", text: "Final etkisi oluşunca sonucu açıklamaya devam etme." },
    ],
    revisionHeading: "Kısa film revizyonunda her saniyeyi sorgula",
    revisionIntro: "Kısalık için değil yoğunluk için kes.",
    revisionItems: [
      { title: "Tek değişim testi", text: "Film hâlâ tek ana değişim etrafında mı?" },
      { title: "Sahne testi", text: "İki sahne aynı dramatik işi yapıyor mu?" },
      { title: "Diyalog testi", text: "Görüntünün söylediğini karakter tekrar ediyor mu?" },
      { title: "Final testi", text: "Final, açıklama olmadan anlam değişimi yaratıyor mu?" },
    ],
    projectName: "Üç Dakika",
    projectBody: "**Durum:** Apartman asansöründe kalan iki komşu, acil durum telefonunun yalnız üç dakika çalışacağını öğrenir.\n\n**Hedef:** Genç kadın Ela dışarıdaki kardeşini aramak ister; yaşlı komşu Nihat ise ambulans çağırmak ister.\n\n**Baskı:** Tek telefon, üç dakika pil.\n\n**Dönüş:** Nihat'ın ambulansı kendisi için değil, Ela'nın kardeşi için istediği anlaşılır.\n\n**Final:** Telefon kapanır; Ela ilk kez komşusunun adını sorar.",
    projectCaption: "Üç Dakika, sınırlı süre ve tek nesne üzerinden karakter değişimini sıkıştırır.",
    sampleHeading: "Örnek kısa sahne: tek nesneyle çatışma",
    sampleBody: "Telefon ekranında ‘02:58’ yanar. Ela numarayı çevirir. Nihat elini uzatır ama telefonu almaz. Yalnızca ekrana bakar. ‘Önce ambulansı ara,’ der. Ela başını kaldırmadan cevap verir: ‘Kimin için?’",
    finalHeading: "Kısa filmi paylaşmadan önce son kontrol",
    finalIntro: "Odak ve ekonomi bozulmadı mı, kontrol et.",
    finalItems: [
      { title: "Süre", text: "Tahmini süre hedef formatla uyumlu mu?" },
      { title: "Tek eksen", text: "Yan fikirler ana değişimi gölgeliyor mu?" },
      { title: "Görsel anlatı", text: "Açıklanabilecek değil gösterilebilecek şeyler gösteriliyor mu?" },
      { title: "Final", text: "Son görüntü filmin anlamını taşıyor mu?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Kısa film fikrini hemen yazılabilir hale getir.",
    outputItems: [
      { title: "1 çekirdek cümle", text: "Tek değişimi yaz." },
      { title: "1 ana görüntü", text: "Filmin görsel merkezini seç." },
      { title: "5–8 beat", text: "Bütün filmi tek sayfada sırala." },
      { title: "1 tam sahne", text: "Karar anını senaryo formatında yaz." },
    ],
    mastersIntro: "Kısa formda görsel ekonomi, ritim ve final etkisini incele.",
    masters: [
      { title: "Andrea Arnold", text: "Kısa filmde davranış ve çevrenin karakter taşımasını incele." },
      { title: "Martin McDonagh", text: "Sınırlı durum içinde çatışma ve kara mizah ekonomisini incele." },
      { title: "Alice Rohrwacher", text: "Gündelik ayrıntıdan şiirsel kısa anlatı üretimini incele." },
    ],
    faq: [
      { question: "Kısa filmde karakter geçmişini anlatmalı mıyım?", answer: "Yalnız bugünkü kararı anlamak için gerekli olan kadarını davranış ve ayrıntıyla hissettir." },
      { question: "Kısa film kaç sahne olmalı?", answer: "Sabit sayı yok; önemli olan her sahnenin tek ana değişime doğrudan hizmet etmesidir." },
    ],
    finalCaption: "Kısa film, az süreyi doldurmak değil gereksiz her şeyi çıkararak tek değişimi görünür kılmaktır.",
    ctaHeading: "Kısa filmin tek güçlü anını yaz",
    ctaText: "Beat haritan hazırsa, İlkOku Yazar Alanı'nda kısa film senaryonu oluşturmaya başla.",
  },
  {
    category: "Senaryo ve Sahne",
    slug: "tiyatro",
    label: "Tiyatro",
    title: "Tiyatro Oyunu Nasıl Yazılır?",
    description: "Sahne eyleminden alt metne, giriş-çıkışlardan perde yapısı ve masa okumasına kadar adım adım tiyatro yazarlığı eğitimi.",
    summary: "Hikâyeyi canlı sahnenin sınırları ve gücüyle kur; karakterlerin söylediklerinden çok sahnede birbirlerine ne yaptığını yaz.",
    alts: alts("Tiyatro", "Son Masa"),
    orientationHeading: "Tiyatro metni, canlı beden ve gerçek zaman için yazılır",
    orientationBody: "Sahne metni yalnız diyalog değildir. Oyuncunun bedeni, mekândaki mesafe, giriş ve çıkışlar, sessizlik ve seyircinin aynı anda gördüğü her şey dramatik malzemedir. Yazarken ‘bu sahnede ne konuşuluyor?’ kadar ‘ne yapılıyor?’ sorusunu da sor.",
    ideaHeading: "Tiyatro fikrini canlı karşılaşmadan çıkar",
    ideaIntro: "Sahne, karakterleri kaçamayacakları ilişki ve mekânlarda güçlü kılar.",
    ideaItems: [
      { title: "Kapalı buluşma", text: "Aynı yerde kalmak zorunda olan kişiler arasında çatışma kur." },
      { title: "Beklenen kişi", text: "Gelmeyen veya gelmesi korkulan biri sahnenin gerilimini taşıyabilir." },
      { title: "Paylaşılan sır", text: "Seyirci ile karakterlerin bildiği şeyleri farklılaştır." },
      { title: "Ritüel", text: "Yemek, toplantı, cenaze veya prova gibi tekrar eden eylem içinde çatışma yarat." },
    ],
    ideaFlowHeading: "Fikri sahne durumuna dönüştür",
    ideaFlowBody: "Tiyatro çekirdeğinde mekân, karakter ilişkisi ve sahnede değişecek güç dengesi birlikte bulunmalıdır. ‘İki kardeş geçmişi konuşur’ yerine, ‘Yıllardır konuşmayan iki kardeş, babalarının lokantasını kapatmadan önce son müşteriyi birlikte ağırlamak zorunda kalır’ gibi oynanabilir durum kur.",
    contrastHeading: "Tiyatroyu film ve düzyazıdan ayır",
    contrastIntro: "Sahnenin sınırlaması, tiyatronun anlatım gücüdür.",
    contrastItems: [
      { title: "Tiyatro ≠ film", text: "Kamera kesmesi yerine canlı mekân, beden ve seyirci dikkatiyle ritim kurar." },
      { title: "Tiyatro ≠ diyalog metni", text: "Konuşma kadar eylem, sessizlik, giriş ve mesafe de anlam taşır." },
      { title: "Tiyatro ≠ roman", text: "İç dünyayı anlatıcıyla değil sahne davranışı ve alt metinle görünür kılar." },
    ],
    routeHeading: "Tiyatro oyununu 8 aşamada kur",
    routeIntro: "Önce sahne durumunu, sonra konuşmayı yaz.",
    routeItems: [
      { title: "1 · Sahne çekirdeği", text: "Mekân, karakterler ve değişecek güç dengesini tanımla." },
      { title: "2 · Karakter isteği", text: "Her karakterin sahnede diğerinden ne istediğini yaz." },
      { title: "3 · Alt metin", text: "Söylenen ile istenen arasındaki farkı belirle." },
      { title: "4 · Perde / bölüm yapısı", text: "Büyük dönüşleri sahne akışına dağıt." },
      { title: "5 · Giriş-çıkış haritası", text: "Kim ne zaman gelir, ne zaman ayrılır ve denge nasıl değişir?" },
      { title: "6 · İlk taslak", text: "Eylem ve diyalogu birlikte yazarak oyunu tamamla." },
      { title: "7 · Masa okuması", text: "Metni oyuncu sesiyle test et." },
      { title: "8 · Sahne revizyonu", text: "Oynanabilirlik, tempo ve gereksiz açıklamayı temizle." },
    ],
    structureHeading: "Tiyatro yapısını güç değişimleriyle kur",
    structureIntro: "Her sahne sonunda odadaki güç dağılımı değişmelidir.",
    structureItems: [
      { title: "Toplanma", text: "Karakterler aynı dramatik alana gelir." },
      { title: "İlk çatlak", text: "Gizli hedef veya eski sorun görünür olur." },
      { title: "Güç değişimi", text: "Bir bilgi, giriş veya eylem dengeyi bozar." },
      { title: "Açığa çıkma", text: "Alt metin artık saklanamaz hale gelir." },
      { title: "Karar", text: "Karakter sahnede sonucu olan bir eylem seçer." },
      { title: "Yeni düzen", text: "Perde kapanırken ilişkiler eskisi gibi kalamaz." },
    ],
    structureCaption: "Tiyatro yapısı, konuşma sırasından çok canlı güç değişimlerinin ritmidir.",
    anatomyHeading: "Tiyatro anatomisi: beden, mekân, alt metin ve ritim",
    anatomyBody: "- **Sahne mekânı:** Kim nerede durabilir?\n- **Giriş / çıkış:** Yeni beden sahne dengesini nasıl değiştiriyor?\n- **Eylem:** Karakter sahnede ne yapıyor?\n- **Alt metin:** Ne söylüyor, aslında ne istiyor?\n- **Sessizlik:** Söylenmeyen neyi büyütüyor?\n- **Props:** Nesne yalnız dekor mu, eylem aracı mı?\n- **Seyirci bilgisi:** Seyirci kimden önce ne biliyor?",
    practiceHeading: "Tiyatro yazarken dört sahne dosyası tut",
    practiceIntro: "Metni yalnız sayfada değil sahnede düşün.",
    practiceItems: [
      { title: "Giriş-çıkış çizelgesi", text: "Sahnedeki kişi sayısının ve dengenin nasıl değiştiğini gör." },
      { title: "İstek fiilleri", text: "İkna etmek, saklamak, küçük düşürmek, tutmak gibi oynanabilir fiiller seç." },
      { title: "Alt metin notu", text: "Önemli repliklerde söylenen ve amaçlananı ayrı yaz." },
      { title: "Nesne listesi", text: "Gerçek eylem üreten sahne nesnelerini belirle." },
    ],
    pageSetupCaption: "Tiyatro çalışma düzeni, replikten önce sahnedeki eylem ve güç değişimini görünür tutar.",
    workspaceHeading: "Oyun dosyanı prova düşüncesiyle düzenle",
    workspaceIntro: "Oyuncu ve yönetmenin okuyabileceği netlikte çalış.",
    workspaceItems: [
      { title: "Sahne amacı", text: "Her sahne için baskın değişimi tek cümlede yaz." },
      { title: "Karakter fiili", text: "Karakterin karşısındakine ne yapmaya çalıştığını not et." },
      { title: "Sessizlik işareti", text: "Dramatik susuşu yalnız üç nokta yerine işleviyle düşün." },
      { title: "Masa okuma notu", text: "Takılan, yapay veya fazla açıklayıcı replikleri işaretle." },
    ],
    craftHeading: "Tiyatronun asıl zanaatı: alt metni eyleme dönüştürmek",
    craftBody: "İyi sahne diyalogu karakterlerin düşündüğünü doğrudan söylemesi değildir. Her replik bir şey yapmaya çalışır: saklamak, ikna etmek, yaralamak, oyalamak, yakınlaşmak. Aynı cümle farklı amaçla bambaşka sahne etkisi yaratır.",
    draftHeading: "İlk taslakta replik değil sahne yaz",
    draftIntro: "Konuşma akıcı olsa bile eylem değişmiyorsa sahne durur.",
    draftItems: [
      { title: "İstekle başla", text: "Her karakterin sahneye ne almak için girdiğini bil." },
      { title: "Bedeni kullan", text: "Oturma, yaklaşma, nesneye dokunma gibi eylemleri dramatik düşün." },
      { title: "Alt metni sakla", text: "Karaktere gerçek niyetini hemen söyletme." },
      { title: "Çıkışı değişimle yap", text: "Sahne bitince ilişki veya güç dengesi farklı olsun." },
    ],
    revisionHeading: "Tiyatro revizyonunu oynanabilirlik üzerinden yap",
    revisionIntro: "Masa okuması metnin ikinci yazım masasıdır.",
    revisionItems: [
      { title: "Eylem testi", text: "Sahnedeki karakterler yalnız konuşuyor mu, birbirlerine bir şey yapıyor mu?" },
      { title: "Ses testi", text: "Karakterler birbirinden ayrı duyuluyor mu?" },
      { title: "Alt metin testi", text: "En önemli şeyler doğrudan mı söyleniyor?" },
      { title: "Sahneleme testi", text: "Metin gerçek bir sahnede uygulanabilir mi?" },
    ],
    projectName: "Son Masa",
    projectBody: "**Mekân:** Kapanacağı gece eski bir lokanta.\n\n**Karakterler:** Lokantayı satan abla Selin ve yıllardır şehir dışında yaşayan kardeşi Murat.\n\n**Durum:** Son müşteri çıkmadan tapu evrakını imzalamaları gerekir.\n\n**Alt metin:** Murat lokantayı değil, babalarının ölüm gecesiyle ilgili gerçeği konuşmak ister.\n\n**Sahne motoru:** Her yeni müşteri veya mutfaktan gelen nesne, kardeşlerin sakladığı geçmişi başka açıdan açar.",
    projectCaption: "Son Masa, tek mekânda ilişki, alt metin ve sahne eylemiyle güç değişimi üretir.",
    sampleHeading: "Örnek sahne anı: replik altında başka amaç",
    sampleBody: "Selin imza kalemini masaya bırakır. ‘Müşteri gidince kapatıyoruz.’ Murat kalemi alır, kapağını takar. ‘Babam da hep erken kapatırdı.’ Selin ona bakmaz. Mutfaktan iki tabak sesi gelir. ‘O gece hariç,’ der Murat.",
    finalHeading: "Oyunu paylaşmadan önce prova öncesi kontrol",
    finalIntro: "Metni sayfa kadar sahne gözüyle de sınay.",
    finalItems: [
      { title: "Oynanabilirlik", text: "Eylemler sahnede yapılabilir mi?" },
      { title: "Karakter sesi", text: "Replikler karakterler arasında yer değiştirebilir mi?" },
      { title: "Ritim", text: "Uzun konuşmalar karşı eylem olmadan uzuyor mu?" },
      { title: "Masa okuması", text: "Sesli okumada yapay kalan yerler işaretlendi mi?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Oyunu sahneye taşınabilir hale getir.",
    outputItems: [
      { title: "1 sahne durumu", text: "Mekân + karakter + güç değişimini yaz." },
      { title: "1 giriş-çıkış haritası", text: "Sahne dengesini planla." },
      { title: "1 alt metin tablosu", text: "Söylenen ve isteneni ayır." },
      { title: "1 tam sahne", text: "Eylem ve diyalogu birlikte yaz." },
    ],
    mastersIntro: "Sahne eylemi, alt metin ve canlı ritim için farklı oyun yazarlarını incele.",
    masters: [
      { title: "Anton Çehov", text: "Gündelik konuşma altındaki istek ve gerilimi incele." },
      { title: "Harold Pinter", text: "Sessizlik, tehdit ve alt metnin sahne gücünü incele." },
      { title: "Haldun Taner", text: "Toplumsal gözlem, sahne ritmi ve karakter sesini incele." },
    ],
    faq: [
      { question: "Tiyatro metninde sahne talimatı ne kadar olmalı?", answer: "Oyuncunun dramatik eylemini anlaması için gerekli kadar; yönetmenliği metin üzerinden aşırı belirlememeye çalış." },
      { question: "Uzun monolog kullanabilir miyim?", answer: "Evet, fakat monolog da bir hedef ve değişim taşımalı; yalnız bilgi aktarmamalı." },
    ],
    finalCaption: "Tiyatro metni, replikler sahnede gerçek eyleme ve güç değişimine dönüştüğünde canlanır.",
    ctaHeading: "Oyunun ilk sahnesini kur",
    ctaText: "Sahne durumun ve karakter isteklerin hazırsa, İlkOku Yazar Alanı'nda oyunun taslağını oluşturmaya başla.",
  },
  {
    category: "Senaryo ve Sahne",
    slug: "radyo-tiyatrosu",
    label: "Radyo Tiyatrosu",
    title: "Radyo Tiyatrosu Nasıl Yazılır?",
    description: "Sesle mekân kurmaktan karakter ayrımına, efekt ve sessizlikten kayıt öncesi revizyona kadar adım adım radyo tiyatrosu eğitimi.",
    summary: "Görüntü olmadan sahne kur; ses, konuşma, efekt ve sessizliği birlikte kullanarak dinleyicinin zihninde mekân yarat.",
    alts: alts("Radyo Tiyatrosu", "Frekans 88"),
    orientationHeading: "Radyo tiyatrosunda sahne, dinleyicinin kulağında kurulur",
    orientationBody: "Görüntünün olmadığı bir anlatıda her bilgi diyalogla açıklanmak zorunda değildir. Ayak sesi, kapı yankısı, nefes, uzaklık, ortam sesi ve sessizlik de karakter ve mekân bilgisi taşır. Yazarken duyulabilir olanı düşün.",
    ideaHeading: "Radyo tiyatrosu fikrini sesten çıkar",
    ideaIntro: "Bazen hikâyenin en güçlü başlangıcı görüntü değil tek bir sestir.",
    ideaItems: [
      { title: "Tekrarlanan ses", text: "Her gece aynı saatte gelen ama kaynağı bilinmeyen ses." },
      { title: "Kapalı frekans", text: "Yalnız belirli kişilerin duyduğu yayın veya çağrı." },
      { title: "Yanlış tanınan ses", text: "Karakterin bir sesi başka biri sandığı dramatik durum." },
      { title: "Sessizlik", text: "Beklenen sesin gelmemesini olay haline getir." },
    ],
    ideaFlowHeading: "Fikri işitsel sahne çekirdeğine dönüştür",
    ideaFlowBody: "Radyo tiyatrosunda çekirdek, yalnız ‘ne oluyor?’ değil ‘dinleyici bunu hangi seslerden anlayacak?’ sorusunu da cevaplar. Görsel bilgiye yaslanan fikri, duyulabilir eylem ve mekân işaretlerine çevir.",
    contrastHeading: "Radyo tiyatrosunu tiyatro ve podcast'ten ayır",
    contrastIntro: "Ses ortak araç olsa da dramatik sözleşme farklıdır.",
    contrastItems: [
      { title: "Radyo tiyatrosu ≠ sahne tiyatrosu", text: "Beden görünmez; mekân ve eylem ses tasarımıyla anlaşılır." },
      { title: "Radyo tiyatrosu ≠ podcast sohbeti", text: "Kurmacayı dramatik sahneler ve karakter eylemiyle kurar." },
      { title: "Ses efekti ≠ açıklama", text: "Efekt yalnız bilgi değil atmosfer ve dramatik vurgu taşır." },
    ],
    routeHeading: "Radyo oyununu 7 aşamada kur",
    routeIntro: "Metni yazarken ses planını paralel kur.",
    routeItems: [
      { title: "1 · İşitsel çekirdek", text: "Hikâyeyi taşıyan ses, sessizlik veya konuşma durumunu seç." },
      { title: "2 · Karakter sesleri", text: "Karakterleri ritim, kelime seçimi ve tavırla ayır." },
      { title: "3 · Mekân sesi", text: "Her mekânın dinleyiciye nasıl duyulacağını belirle." },
      { title: "4 · Sahne beatleri", text: "Bilgi, çatışma ve ses dönüşlerini sırala." },
      { title: "5 · Sesli taslak", text: "Diyalog ve efekt işaretlerini birlikte yaz." },
      { title: "6 · Okuma provası", text: "Metni gözünü kapatarak dinle; anlaşılmayan yerleri işaretle." },
      { title: "7 · Ses revizyonu", text: "Fazla açıklama ve benzer karakter seslerini temizle." },
    ],
    structureHeading: "Radyo yapısını işitsel odak değişimleriyle kur",
    structureIntro: "Dinleyici neyi, ne zaman ve hangi ses üzerinden fark ediyor?",
    structureItems: [
      { title: "Sesle giriş", text: "Mekân veya soruyu ilk duyulabilir ayrıntıyla kur." },
      { title: "Kaynak arayışı", text: "Karakter sesin veya bilginin kaynağına yönelir." },
      { title: "Yanlış yorum", text: "Duyulan şey ilk anlamından sapar." },
      { title: "Yakınlaşma", text: "Ses mekânsal veya duygusal olarak yaklaşır." },
      { title: "Açığa çıkma", text: "Dinleyici önceki sesleri yeni anlamda duyar." },
      { title: "Yankı", text: "Final sesi hikâyenin temasını taşır." },
    ],
    structureCaption: "Radyo tiyatrosu yapısı, ses bilgisinin dinleyiciye ne zaman ve nasıl ulaştığını yönetir.",
    anatomyHeading: "Radyo tiyatrosu anatomisi: ses, mesafe, ritim ve sessizlik",
    anatomyBody: "- **Karakter sesi:** Kim olduğunu görüntüsüz ayırt ettirir.\n- **Ortam sesi:** Mekânı kurar.\n- **Efekt:** Eylemi ve vurgu anını taşır.\n- **Mesafe:** Yakın, uzak, kapı arkası gibi konum bilgisi.\n- **Sessizlik:** Beklentiyi ve duyguyu büyütür.\n- **Müzik:** Bölümleme veya ton; açıklamanın yerine geçmez.\n- **Diyalog:** Dinleyiciye anlatmak için değil karakterin eylemi için konuşur.",
    practiceHeading: "Radyo oyunu için dört ses dosyası tut",
    practiceIntro: "Yazılı metnin yanında işitsel planı da görünür yap.",
    practiceItems: [
      { title: "Ses paleti", text: "Her mekân ve karakter için ayırt edici sesleri listele." },
      { title: "Efekt çizelgesi", text: "Efektin işlevini ve sahnedeki yerini yaz." },
      { title: "Karakter ritmi", text: "Konuşma hızı, durak ve kelime alanlarını ayır." },
      { title: "Sessizlik notu", text: "Dramatik susuşun neden gerekli olduğunu belirt." },
    ],
    pageSetupCaption: "Radyo tiyatrosu çalışma düzeni, diyalogla ses tasarımını aynı dramatik akışta takip eder.",
    workspaceHeading: "Metni kayıt masasına uygun düzenle",
    workspaceIntro: "Oyuncu ve ses ekibinin aynı dramatik amacı okuyabilmesini sağla.",
    workspaceItems: [
      { title: "Diyalog sütunu", text: "Karakter repliklerini net ayır." },
      { title: "Ses işareti", text: "Efekt ve ortam sesini kısa, anlaşılır notla göster." },
      { title: "Mesafe notu", text: "Sese dramatik olarak gerekiyorsa yakınlık / uzaklık bilgisi ekle." },
      { title: "Okuma sürümü", text: "Kayıt öncesi yalnız sesle test edilen sürümü ayrı tut." },
    ],
    craftHeading: "Radyo tiyatrosunun asıl zanaatı: görüntüsüz berraklık",
    craftBody: "Dinleyiciye ‘kapıyı açıyorum’ dedirtmek yerine kapı kolu, menteşe, adım ve karakter tepkisiyle eylemi kurabilirsin. Her ses anlaşılır olmak zorunda, fakat her bilgi açıklanmak zorunda değildir.",
    draftHeading: "İlk taslağı kulakla yaz",
    draftIntro: "Sayfadaki metin güzel görünmekten önce duyulduğunda çalışmalı.",
    draftItems: [
      { title: "Gözünü kapat testi", text: "Sahneyi yalnız dinleyerek takip edip edemeyeceğini düşün." },
      { title: "Sesleri ayır", text: "Karakterleri yalnız isimden değil konuşma biçiminden tanınır yap." },
      { title: "Efekti seçici kullan", text: "Her hareketi seslendirmek yerine dramatik bilgiyi taşıyan sesi seç." },
      { title: "Sessizliği yaz", text: "Susuşun nerede gerilim veya duygu oluşturduğunu planla." },
    ],
    revisionHeading: "Radyo revizyonunu dinlenebilirlik üzerinden yap",
    revisionIntro: "Metni mutlaka sesli prova ile test et.",
    revisionItems: [
      { title: "Kim konuşuyor testi", text: "İsim etiketi olmadan karakterler ayırt ediliyor mu?" },
      { title: "Mekân testi", text: "Dinleyici nerede olduğunu anlayabiliyor mu?" },
      { title: "Açıklama testi", text: "Karakterler sadece dinleyici için mi bilgi söylüyor?" },
      { title: "Efekt testi", text: "Her ses dramatik veya mekânsal işlev taşıyor mu?" },
    ],
    projectName: "Frekans 88",
    projectBody: "**Durum:** Dağ yolunda tek başına gece araç kullanan Dilan'ın radyosu yalnız 88.0 frekansında eski bir acil yardım yayını almaya başlar.\n\n**İşitsel motor:** Yayındaki kadın, Dilan'ın geçtiği virajları birkaç dakika önceden tarif eder.\n\n**Çatışma:** Dilan bunun kayıt mı canlı yayın mı olduğunu anlamaya çalışır.\n\n**Dönüş:** Yayındaki sesin yıllar önce aynı yolda kaybolan annesine ait olduğu anlaşılır.\n\n**Final sesi:** Yayın kesildikten sonra radyodan ilk kez Dilan'ın çocukken söylediği bir tekerleme duyulur.",
    projectCaption: "Frekans 88, görüntüsüz mekân ve gerilimi yalnız ses bilgisi üzerinden kurar.",
    sampleHeading: "Örnek işitsel sahne: mekânı sesle kur",
    sampleBody: "SİLECEKLER iki kez çalışır. LASTİKLER çakıl üzerinde kayar. Radyoda statik. KADIN SESİ (uzak, kesik): ‘Üçüncü virajdan sonra... sağda kırık tabela.’ Dilan frene dokunur. Motor devri düşer. Önünde metal bir levhanın rüzgârda vurma sesi başlar.",
    finalHeading: "Kayıt öncesi son kontrolü yap",
    finalIntro: "Dinleyicinin yalnız kulağına güvenerek bütün oyunu sınay.",
    finalItems: [
      { title: "Ses ayrımı", text: "Karakterler ve mekânlar sesle ayırt ediliyor mu?" },
      { title: "Efekt planı", text: "Gereksiz kalabalık veya eksik bilgi var mı?" },
      { title: "Süre", text: "Sahnelerin işitsel temposu formatla uyumlu mu?" },
      { title: "Okuma provası", text: "Kayıt öncesi kör dinleme yapıldı mı?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Radyo oyununun ses omurgasını kur.",
    outputItems: [
      { title: "1 işitsel çekirdek", text: "Hikâyeyi taşıyan ana sesi tanımla." },
      { title: "1 ses paleti", text: "Karakter ve mekân seslerini ayır." },
      { title: "1 efekt çizelgesi", text: "Dramatik sesleri sırala." },
      { title: "1 tam sahne", text: "Diyalog + efekt + sessizlikle yaz." },
    ],
    mastersIntro: "Ses dramaturjisi, radyo oyunu ve işitsel anlatı örneklerini dinleyerek çözümle.",
    masters: [
      { title: "Orson Welles", text: "Radyo anlatısında gerçeklik hissi ve ses katmanlarını incele." },
      { title: "Samuel Beckett", text: "Ses, sessizlik ve minimal eylemin dramatik gücünü incele." },
      { title: "BBC Radio Drama", text: "Mekân sesi, oyuncu ayrımı ve kayıt dramaturjisi örneklerini karşılaştır." },
    ],
    faq: [
      { question: "Radyo tiyatrosunda anlatıcı şart mı?", answer: "Hayır. Mekân ve eylem ses, diyalog ve efektle anlaşılabiliyorsa anlatıcıya ihtiyaç olmayabilir." },
      { question: "Her hareket için efekt yazmalı mıyım?", answer: "Hayır. Yalnız dramatik bilgi, ritim veya mekân için gerekli sesleri seç." },
    ],
    finalCaption: "Radyo tiyatrosu, dinleyicinin görmediği dünyayı seslerden eksiksiz kurabildiğinde çalışır.",
    ctaHeading: "Hikâyeni sesle sahnelemeye başla",
    ctaText: "İşitsel çekirdeğin ve ses paletin hazırsa, İlkOku Yazar Alanı'nda radyo oyununun taslağını oluştur.",
  },
  {
    category: "Senaryo ve Sahne",
    slug: "podcast-senaryosu",
    label: "Podcast Senaryosu",
    title: "Podcast Senaryosu Nasıl Yazılır?",
    description: "Format seçiminden bölüm akışına, anlatıcı sesinden araştırma, segment ritmi ve kayıt öncesi revizyona kadar adım adım podcast senaryosu eğitimi.",
    summary: "Dinleyicinin dikkatini yalnız bilgiyle değil; güçlü bir anlatıcı sesi, bölüm vaadi ve iyi kurulmuş işitsel ritimle taşı.",
    alts: alts("Podcast Senaryosu", "Bir Şehrin Beş Sesi"),
    orientationHeading: "Podcast senaryosu, konuşmanın yazıya dökülmüş hali değildir",
    orientationBody: "İyi podcast bölümünde giriş vaadi, segmentler, kaynaklar, geçişler ve ses ritmi önceden düşünülür. Metin doğal duyulmalı ama yapısız olmamalıdır. Yazı, kayıtta konuşulabilir hale gelmelidir.",
    ideaHeading: "Podcast fikrini format ve dinleyici vaadinden çıkar",
    ideaIntro: "Konu geniş olabilir; bölüm vaadi dar ve net olmalı.",
    ideaItems: [
      { title: "Tek soru", text: "Bir bölümde gerçekten cevaplamak istediğin soruyu seç." },
      { title: "Karakter / tanık", text: "Bilgiyi insan deneyimi üzerinden taşı." },
      { title: "Arşiv izi", text: "Ses kaydı, mektup, haber veya belgeyi bölüm motoru yap." },
      { title: "Karşıt görüş", text: "Tek ses yerine gerilim yaratan iki açıklamayı karşılaştır." },
    ],
    ideaFlowHeading: "Konuyu bölüm vaadine dönüştür",
    ideaFlowBody: "‘İstanbul'un sesleri’ bir konu; ‘Bir semtin kimliğini beş kaybolan ses üzerinden yeniden kurabilir miyiz?’ ise bölüm vaadidir. Dinleyicinin neden sonuna kadar kalacağını tek cümlede açıklayabilmelisin.",
    contrastHeading: "Podcast senaryosunu sohbet ve radyo oyunundan ayır",
    contrastIntro: "Doğal duyulmak, plansız olmak değildir.",
    contrastItems: [
      { title: "Podcast senaryosu ≠ makale", text: "Kulak için yazılır; cümle uzunluğu ve bilgi yoğunluğu farklıdır." },
      { title: "Podcast senaryosu ≠ sohbet notu", text: "Bölüm vaadi, segment ritmi ve kaynak düzeni gerekir." },
      { title: "Podcast ≠ radyo tiyatrosu", text: "Kurgu yerine bilgi, anlatıcı veya röportaj merkezli olabilir; fakat ses dramaturjisini yine kullanır." },
    ],
    routeHeading: "Podcast bölümünü 8 aşamada kur",
    routeIntro: "Önce dinleyici vaadini, sonra metni yaz.",
    routeItems: [
      { title: "1 · Format", text: "Tek anlatıcı, röportaj, belgesel veya karma formatı seç." },
      { title: "2 · Bölüm sorusu", text: "Tek bölümde cevaplanacak soruyu daralt." },
      { title: "3 · Araştırma", text: "Kaynak, röportaj ve arşiv malzemesini topla." },
      { title: "4 · Hook", text: "İlk dakikada merak ve vaat kur." },
      { title: "5 · Segmentler", text: "Bilgi ve hikâyeyi dinlenebilir bloklara böl." },
      { title: "6 · Senaryo taslağı", text: "Konuşulabilir cümlelerle bölüm metnini yaz." },
      { title: "7 · Prova kaydı", text: "Metni okuyup doğal olmayan yerleri işaretle." },
      { title: "8 · Ses revizyonu", text: "Tempo, tekrar ve bilgi yoğunluğunu temizle." },
    ],
    structureHeading: "Podcast bölümünü dikkat dalgalarıyla kur",
    structureIntro: "Dinleyiciye düzenli aralıklarla yeni soru, örnek veya ses değişimi ver.",
    structureItems: [
      { title: "Hook", text: "Soruyu veya güçlü anı öne al." },
      { title: "Bağlam", text: "Dinleyicinin bilmesi gereken minimum bilgiyi ver." },
      { title: "İlk kanıt / hikâye", text: "Soyut konuyu somutlaştır." },
      { title: "Karşılık", text: "Yeni kaynak veya karşıt görüşle ilk yorumu zorla." },
      { title: "Birleştirme", text: "Parçaları ana soruya bağla." },
      { title: "Kapanış", text: "Soruyu kapat veya bilinçli açık bırak; dinleyici vaadini yerine getir." },
    ],
    structureCaption: "Podcast yapısı, bilginin sırasını dinleyici dikkatinin ritmiyle birleştirir.",
    anatomyHeading: "Podcast anatomisi: vaat, anlatıcı sesi, kaynak ve ritim",
    anatomyBody: "- **Format:** Bölüm nasıl işleyecek?\n- **Hook:** İlk dakikanın vaadi.\n- **Anlatıcı sesi:** Güven, ton ve kişilik.\n- **Kaynak:** İddianın dayanağı.\n- **Röportaj klibi:** İnsan sesi ve kanıt.\n- **Geçiş:** Segmentler arasında yön değişimi.\n- **Ses tasarımı:** Atmosfer ve bölümleme.",
    practiceHeading: "Podcast üretiminde dört dosya tut",
    practiceIntro: "Araştırma ile senaryoyu karıştırmadan yönet.",
    practiceItems: [
      { title: "Kaynak dosyası", text: "Her iddiayı kaynağıyla eşleştir." },
      { title: "Klip listesi", text: "Röportaj veya arşiv sesinin süre ve işlevini yaz." },
      { title: "Segment kartları", text: "Her bölüm parçasının sorusunu ve sonucunu belirle." },
      { title: "Telaffuz listesi", text: "Özel isim ve teknik terimlerin doğru söylenişini not et." },
    ],
    pageSetupCaption: "Podcast çalışma düzeni, konuşma metni ile kaynak ve ses kliplerini aynı bölüm haritasında birleştirir.",
    workspaceHeading: "Podcast metnini kayıt okunabilirliğiyle düzenle",
    workspaceIntro: "Göz için değil kulak ve nefes için yaz.",
    workspaceItems: [
      { title: "Kısa paragraflar", text: "Konuşurken nefes ve vurguya izin ver." },
      { title: "Kaynak etiketi", text: "İddianın yanında kaynağı editoryal olarak görünür tut." },
      { title: "Klip işareti", text: "Ses klibinin giriş ve çıkış noktasını belirt." },
      { title: "Tempo notu", text: "Yoğun bilgi sonrası örnek veya ses değişimi planla." },
    ],
    craftHeading: "Podcast'in asıl zanaatı: yazılı metni konuşulabilir yapmak",
    craftBody: "Sayfada doğru görünen cümle mikrofonda yapay duyulabilir. Uzun yan cümleleri böl, teknik terimi örnekle, dinleyiciye yön duygusu ver ve aynı bilgiyi farklı kelimelerle gereksiz tekrar etme.",
    draftHeading: "İlk taslağı mikrofon için yaz",
    draftIntro: "Metni yazarken yüksek sesle okuyabileceğin cümleler kur.",
    draftItems: [
      { title: "Hook'u erken ver", text: "Bölümün neden dinlenmesi gerektiğini ilk dakikada göster." },
      { title: "Bağlamı dozla", text: "Araştırmanın tamamını değil soruyu anlamaya yetecek kısmı kullan." },
      { title: "Klipleri metne yedir", text: "Röportaj sesi tekrar değil yeni bilgi veya duygu taşısın." },
      { title: "Yön cümleleri ekle", text: "Dinleyici bölümde nerede olduğunu kaybetmesin." },
    ],
    revisionHeading: "Podcast revizyonunu dinleyici kulağıyla yap",
    revisionIntro: "Prova kaydı yazılı revizyondan farklı kusurları gösterir.",
    revisionItems: [
      { title: "Nefes testi", text: "Cümleler doğal nefesle okunabiliyor mu?" },
      { title: "Bilgi yoğunluğu", text: "Arka arkaya fazla sayı, isim veya kavram var mı?" },
      { title: "Kaynak testi", text: "Önemli iddiaların dayanağı editoryal olarak açık mı?" },
      { title: "Vaad testi", text: "Bölüm kapanışında girişte verilen soru karşılık buluyor mu?" },
    ],
    projectName: "Bir Şehrin Beş Sesi",
    projectBody: "**Bölüm sorusu:** Bir semtin hafızasını kaybolan beş gündelik ses üzerinden anlatabilir miyiz?\n\n**Sesler:** Vapur düdüğü, mahalle sineması zili, seyyar satıcı çağrısı, eski tramvay freni, sabah matbaa sesi.\n\n**Kaynak:** Arşiv kayıtları + esnaf ve sakin röportajları.\n\n**Yapı:** Her ses bir hikâye açar; finalde günümüz sessizliğiyle karşılaştırılır.\n\n**Kapanış:** Dinleyiciden kendi mahallesinden kaybolan bir sesi kaydetmesi istenir.",
    projectCaption: "Bir Şehrin Beş Sesi, araştırma, röportaj ve işitsel ritmi tek bölüm sorusunda birleştirir.",
    sampleHeading: "Örnek podcast açılışı: soru + ses",
    sampleBody: "[ESKİ VAPUR DÜDÜĞÜ] Bu sesi bugün hâlâ duyabilirsiniz. Ama otuz yıl önce aynı düdük, kıyıda yaşayan binlerce insan için saati gösteriyordu. Bu bölümde bir semtin hafızasını beş kaybolan sesin peşinden arıyoruz.",
    finalHeading: "Kayıt öncesi editoryal kontrolü yap",
    finalIntro: "Metin, kaynak ve ses planını birlikte temizle.",
    finalItems: [
      { title: "Kaynak kontrolü", text: "İddialar doğrulanmış ve notlanmış mı?" },
      { title: "Telaffuz", text: "İsim ve terimler prova edildi mi?" },
      { title: "Süre", text: "Segmentler hedef bölüm süresine uyuyor mu?" },
      { title: "Prova kayıt", text: "Metin mikrofonda doğal duyuluyor mu?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Podcast fikrini kayda hazır bölüme dönüştür.",
    outputItems: [
      { title: "1 bölüm sorusu", text: "Dinleyici vaadini tek cümlede yaz." },
      { title: "1 segment haritası", text: "Bölümü bloklara ayır." },
      { title: "1 kaynak listesi", text: "Temel iddiaları dayanaklarıyla eşleştir." },
      { title: "1 açılış metni", text: "İlk 60–90 saniyeyi yaz." },
    ],
    mastersIntro: "Anlatıcı sesi, araştırma örgüsü ve işitsel bölüm yapısını başarılı podcastlerden çözümle.",
    masters: [
      { title: "This American Life", text: "Hikâye segmentleri, anlatıcı köprüleri ve karakter sesini incele." },
      { title: "Radiolab", text: "Karmaşık bilgiyi ses tasarımı ve soru akışıyla açmayı incele." },
      { title: "99% Invisible", text: "Araştırma, merak ve gündelik ayrıntıdan bölüm kurmayı incele." },
    ],
    faq: [
      { question: "Podcast senaryosu kelimesi kelimesine okunmalı mı?", answer: "Formatına bağlı. Anlatıcı bölümleri tam yazılabilir; röportaj ve sohbet kısımlarında daha esnek beat notları kullanılabilir." },
      { question: "Müzik her geçişte gerekli mi?", answer: "Hayır. Müzik yapısal veya duygusal işlev taşıdığında kullan; sırf boşluğu doldurmak için değil." },
    ],
    finalCaption: "Podcast senaryosu, araştırmayı konuşulabilir ve dinlenebilir bir ritme dönüştürdüğünde güçlenir.",
    ctaHeading: "İlk podcast bölümünün akışını kur",
    ctaText: "Bölüm sorun ve segment haritan hazırsa, İlkOku Yazar Alanı'nda senaryonu oluşturmaya başla.",
  },
  {
    category: "Senaryo ve Sahne",
    slug: "belgesel-senaryosu",
    label: "Belgesel Senaryosu",
    title: "Belgesel Senaryosu Nasıl Yazılır?",
    description: "Araştırma sorusundan kanıta, röportaj ve arşivden sahne planı, etik ve kurgu revizyonuna kadar adım adım belgesel senaryosu eğitimi.",
    summary: "Gerçeği dramatikleştirirken uydurma; araştırma sorusunu kanıt, tanık, arşiv ve sahne gözlemiyle görünür bir anlatıya dönüştür.",
    alts: alts("Belgesel Senaryosu", "Kıyının Hafızası"),
    orientationHeading: "Belgesel senaryosu gerçeği icat etmez; araştırılmış gerçeğe anlatı düzeni verir",
    orientationBody: "Belgeselde dramatik yapı kurmak, olguları senaryoya uydurmak değildir. Soru, kaynak, tanık, gözlem ve arşiv malzemesini dürüst biçimde seçer; izleyicinin kanıtı hangi sırayla göreceğini planlarsın.",
    ideaHeading: "Belgesel fikrini araştırılabilir sorudan çıkar",
    ideaIntro: "Güçlü konu, çekilebilir ve kanıtlanabilir bir soruya dönüşmelidir.",
    ideaItems: [
      { title: "Değişen yer", text: "Bir mahalle, kıyı, fabrika veya doğal alanın dönüşümünü izle." },
      { title: "Görünmeyen emek", text: "Gündelik hayatın arkasındaki işi ve insanları görünür kıl." },
      { title: "Çelişen hafıza", text: "Aynı olayı farklı tanıkların nasıl hatırladığını araştır." },
      { title: "Belge izi", text: "Fotoğraf, harita, tutanak veya kayıt üzerinden geçmişi takip et." },
    ],
    ideaFlowHeading: "Konuyu araştırma sorusuna dönüştür",
    ideaFlowBody: "‘Bir sahil kasabasının değişimi’ konu başlığıdır. ‘Son on yılda kıyının turizme açılması balıkçıların çalışma ve yaşam alanını nasıl değiştirdi?’ ise araştırılabilir belgesel sorusudur. Kaynak ve çekim planı bu sorudan çıkar.",
    contrastHeading: "Belgesel senaryosunu haber ve kurmacadan ayır",
    contrastIntro: "Gerçek malzeme anlatı ister ama sınırları vardır.",
    contrastItems: [
      { title: "Belgesel ≠ haber özeti", text: "Tek bilgi aktarmak yerine süreç, karakter ve bağlam kurar." },
      { title: "Belgesel ≠ kurmaca", text: "Dramatik boşluğu uydurma olayla dolduramaz; belirsizliği açıkça korur." },
      { title: "Röportaj ≠ belgesel", text: "Konuşan kişiler anlatının malzemesidir; yapı yalnız soru-cevap dizisi değildir." },
    ],
    routeHeading: "Belgesel projesini 8 aşamada kur",
    routeIntro: "Araştırma ve çekim planını paralel geliştir.",
    routeItems: [
      { title: "1 · Araştırma sorusu", text: "Tek ve araştırılabilir ana soruyu yaz." },
      { title: "2 · Kaynak haritası", text: "Belge, uzman, tanık ve karşıt görüşleri belirle." },
      { title: "3 · Etik sınırlar", text: "Onam, temsil ve hassas bilgiyi nasıl yöneteceğini planla." },
      { title: "4 · Karakter / izlek", text: "Soruyu insan deneyimi üzerinden takip edecek kişileri seç." },
      { title: "5 · Çekim sahneleri", text: "Gözlemlenecek gerçek eylem ve mekânları planla." },
      { title: "6 · Röportaj planı", text: "Bilgi değil deneyim ve kanıt açacak sorular hazırla." },
      { title: "7 · Paper edit", text: "Çekim sonrası malzemeyi tematik ve dramatik sıraya diz." },
      { title: "8 · Gerçeklik kontrolü", text: "Final kurgunun kanıtları çarpıtıp çarpıtmadığını yeniden denetle." },
    ],
    structureHeading: "Belgeseli kanıt ve keşif sırasıyla kur",
    structureIntro: "İzleyici sonucu baştan almak yerine araştırmanın ilerleyişini takip etsin.",
    structureItems: [
      { title: "Soru", text: "Filmin araştırdığı gerilimi açıkla." },
      { title: "İlk gözlem", text: "Konuyu yaşayan bir sahneyle somutlaştır." },
      { title: "Bağlam", text: "Tarih, veri veya belgeyle alanı genişlet." },
      { title: "Karşıt kanıt", text: "İlk yorumu zorlayan başka ses veya belge getir." },
      { title: "Derinleşme", text: "İnsan bedeli veya sistem etkisini görünür kıl." },
      { title: "Sonuç / açık soru", text: "Kanıtın götürdüğü yere kadar git; bilmediğini uydurma." },
    ],
    structureCaption: "Belgesel yapısı, gerçeği değiştirmeden kanıtın keşfedilme sırasını düzenler.",
    anatomyHeading: "Belgesel anatomisi: soru, kanıt, tanık, gözlem ve etik",
    anatomyBody: "- **Araştırma sorusu:** Film neyi gerçekten öğrenmeye çalışıyor?\n- **Gözlem sahnesi:** Gerçek hayat kamera önünde ne gösteriyor?\n- **Tanık:** Deneyim ve hafıza.\n- **Uzman:** Bağlam ve yorum.\n- **Belge / arşiv:** Doğrulanabilir kayıt.\n- **Karşıt görüş:** Tek taraflı anlatıyı sınar.\n- **Etik:** Onam, temsil, zarar ve bağlam sorumluluğu.",
    practiceHeading: "Belgesel için dört araştırma dosyası tut",
    practiceIntro: "Kaynak, çekim ve anlatı kararlarını birbirinden ayır.",
    practiceItems: [
      { title: "Kaynak matrisi", text: "Her iddianın belge, tanık veya uzman dayanağını yaz." },
      { title: "Çekim listesi", text: "Gerçek eylem, mekân ve zaman fırsatlarını planla." },
      { title: "Röportaj kartı", text: "Kişi, amaç, hassas alan ve doğrulama sorularını tut." },
      { title: "Etik notu", text: "Onam, anonimlik ve zarar risklerini kayıt altına al." },
    ],
    pageSetupCaption: "Belgesel çalışma düzeni, iddia ile kaynağı ve anlatı kararıyla etik kararı yan yana görünür tutar.",
    workspaceHeading: "Belgesel dosyanı kanıt izlenebilirliğiyle düzenle",
    workspaceIntro: "Kurgu sırasında hangi cümlenin hangi malzemeye dayandığını kaybetme.",
    workspaceItems: [
      { title: "Kaynak kodu", text: "Her belge ve röportaja sabit referans ver." },
      { title: "Timecode", text: "Güçlü alıntı ve gözlem anlarını süre koduyla kaydet." },
      { title: "Doğrulama durumu", text: "Teyit edilmiş, tartışmalı ve yalnız tanık anlatısı olan bilgiyi ayır." },
      { title: "Paper edit", text: "Kurguya girmeden önce metin üzerinde malzeme sırasını test et." },
    ],
    craftHeading: "Belgeselin asıl zanaatı: dramatik dürüstlük",
    craftBody: "Belgesel gerilim ister ama bu gerilim gerçeğin önüne geçmemelidir. Çelişen tanıklıkları saklama; doğrulanamayan iddiayı kesin cümleye dönüştürme; kurgu sırasıyla neden-sonuç ilişkisi uydurma.",
    draftHeading: "İlk taslakta kesin cevap vermek zorunda değilsin",
    draftIntro: "Araştırmanın belirsizliğini metinde dürüstçe taşı.",
    draftItems: [
      { title: "Soruyla ilerle", text: "Önceden istediğin sonucu kanıtlama yerine malzemeyi izle." },
      { title: "Sahneye yer ver", text: "Yalnız röportaj değil gerçek eylem ve gözlem kullan." },
      { title: "Karşı kanıtı koru", text: "Tezini zorlayan malzemeyi sırf rahatsız ettiği için çıkarma." },
      { title: "Belirsizliği etiketle", text: "Doğrulanmayan noktaları kesinmiş gibi yazma." },
    ],
    revisionHeading: "Belgesel revizyonunu gerçeklik ve anlatı birlikte belirlesin",
    revisionIntro: "Daha etkileyici olması, daha doğru olduğu anlamına gelmez.",
    revisionItems: [
      { title: "Kanıt testi", text: "Her güçlü iddia gerçekten gösterilen malzemeden çıkıyor mu?" },
      { title: "Bağlam testi", text: "Alıntı veya görüntü bağlamından koparılmış mı?" },
      { title: "Temsil testi", text: "Kişi ve gruplar tek boyutlu bir işleve indirgenmiş mi?" },
      { title: "Kurgu testi", text: "Sıralama yanlış neden-sonuç izlenimi yaratıyor mu?" },
    ],
    projectName: "Kıyının Hafızası",
    projectBody: "**Araştırma sorusu:** Küçük bir kıyı kasabasında son on yıldaki turizm yatırımları, balıkçıların çalışma alanını nasıl değiştirdi?\n\n**Karakterler:** Üç kuşak balıkçı ailesi, belediye şehir plancısı, yeni marina işletmecisi.\n\n**Arşiv:** Eski kıyı haritaları, ruhsat planları, aile fotoğrafları.\n\n**Gözlem:** Sabah ağı toplama, marina giriş kontrolü, eski çekek alanının bugünkü kullanımı.\n\n**Etik soru:** Geçim kaybını romantikleştirmeden, yatırımın savunusunu da karikatürleştirmeden nasıl anlatılır?",
    projectCaption: "Kıyının Hafızası, araştırma sorusunu tanık, belge, karşıt görüş ve gözlem sahneleriyle birlikte kurar.",
    sampleHeading: "Örnek belgesel sahne planı: önce gözlem, sonra yorum",
    sampleBody: "GÜN DOĞUMU. Hasan teknesini marinadan çıkarmak için güvenlik bariyerinde kartını üç kez okutur. Kart reddedilir. Kamera bekler. Kesme yok. Hasan telefona uzanır. Sonraki sahnede eski 2012 haritasında aynı noktanın ‘ortak çekek alanı’ olarak işaretli olduğunu görürüz.",
    finalHeading: "Yayın öncesi gerçeklik ve etik kontrolü yap",
    finalIntro: "Final kurguda her iddia ve temsil kararını yeniden denetle.",
    finalItems: [
      { title: "Kaynak", text: "İddiaların dayanakları kayıtlı mı?" },
      { title: "Onam", text: "Katılımcı izinleri ve hassas kullanım kararları net mi?" },
      { title: "Bağlam", text: "Alıntı ve görüntüler bağlamı koruyor mu?" },
      { title: "Karşı görüş", text: "Önemli çelişen bilgi adil biçimde temsil edildi mi?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Belgesel fikrini araştırılabilir ve çekilebilir hale getir.",
    outputItems: [
      { title: "1 araştırma sorusu", text: "Belgeselin gerçekten öğrenmek istediği şeyi yaz." },
      { title: "1 kaynak matrisi", text: "Tanık, uzman, belge ve karşı görüşü eşleştir." },
      { title: "1 çekim listesi", text: "Gözlemlenecek gerçek sahneleri sırala." },
      { title: "1 röportaj planı", text: "Kişi başına amaç ve soru seti hazırla." },
    ],
    mastersIntro: "Araştırma etiği, gözlem, arşiv ve kurgu yapısını farklı belgesel yaklaşımlarında incele.",
    masters: [
      { title: "Agnès Varda", text: "Kişisel bakış ile gözlemsel gerçekliği birlikte kurmayı incele." },
      { title: "Frederick Wiseman", text: "Gözlem, kurum ve açıklamasız sahne örgüsünü incele." },
      { title: "Asif Kapadia", text: "Arşiv malzemesini dramatik ama kaynaklı yapı içinde kullanmayı incele." },
    ],
    faq: [
      { question: "Belgeselde sahneleri önceden yazabilir miyim?", answer: "Çekim hedefini ve olası dramatik işlevi planlayabilirsin; fakat gerçek olayın nasıl gelişeceğini kurmaca gibi dayatamazsın." },
      { question: "Belgeselde anlatıcı şart mı?", answer: "Hayır. Gözlem, röportaj, arşiv ve yazılar yeterliyse anlatıcı kullanmadan da yapı kurulabilir." },
    ],
    finalCaption: "Belgesel senaryosu, gerçeği zorlamadan araştırma malzemesine güçlü ve dürüst bir izleme yolu verdiğinde tamamlanır.",
    ctaHeading: "Belgesel araştırma dosyanı kur",
    ctaText: "Sorun, kaynak haritan ve çekim planın hazırsa, İlkOku Yazar Alanı'nda belgesel projenin taslağını oluşturmaya başla.",
  },
];

export function getEducationGuideDefinition(slug: string): EducationGuideDefinition {
  const definition = definitions.find((item) => item.slug === slug);
  if (!definition) throw new Error(`Stage education guide definition missing: ${slug}`);
  return definition;
}

export const STAGE_GUIDE_DEFINITIONS = definitions;
