import type { EducationGuideDefinition, GuideItem } from "@/lib/education-guide-batch";

type YouthExtraSection = {
  id: string;
  type: "text" | "cards" | "steps";
  heading: string;
  intro?: string;
  body?: string;
  items?: GuideItem[];
};

type YouthGuideDefinition = EducationGuideDefinition & {
  extraSections: YouthExtraSection[];
};

function alts(label: string, project: string): EducationGuideDefinition["alts"] {
  return {
    hero: `${label} yazarlığı için yaş grubu, karakter, bölüm ve okuma notları bulunan İlkOku çalışma masası`,
    ideaFlow: `${label} fikrinin okur ihtiyacı ve anlatı çekirdeğinden esere dönüşümünü gösteren eğitim akışı`,
    structure: `${label} eserinin yaşa ve türe uygun yapısal aşamalarını gösteren eğitim diyagramı`,
    anatomy: `${label} eserinin okur, ses, karakter, yapı ve dil parçalarını gösteren eser anatomisi`,
    pageSetup: `${label} yazımı için yaş grubu, taslak, sahne ve revizyon notlarının düzenlendiği çalışma alanı`,
    project: `${project} adlı örnek projenin okur, yapı ve taslak kararlarını gösteren çalışma panosu`,
    finalCta: `${label} taslağını tamamlayıp İlkOku Yazar Alanı'nda üretime geçmeye hazırlanan çalışma ortamı`,
  };
}

const definitions: YouthGuideDefinition[] = [
  {
    category: "Çocuk ve Gençlik",
    slug: "masal",
    label: "Masal",
    title: "Masal Nasıl Yazılır?",
    description: "Merak çekirdeğinden büyülü kurala, tekrar ve sınavlardan dönüş ve sesli okumaya kadar adım adım masal yazarlığı eğitimi.",
    summary: "Çocuğa ders vermek için değil, merak ve dönüşüm yaşatmak için yaz; büyülü dünyayı kendi kuralı, ritmi ve duygusal güvenliğiyle kur.",
    alts: alts("Masal", "Ayı Saklayan Değirmen"),
    orientationHeading: "Masal, gerçeği terk etmek değil duyguyu büyülü bir kuralla görünür kılmaktır",
    orientationBody: "Masalda konuşan hayvanlar, sihirli nesneler ve imkânsız yolculuklar olabilir; fakat anlatı rastgele işlemez. Okur, dünyanın hangi kuralla çalıştığını ve kahramanın ne istediğini erken anlamalıdır. Masalın gücü nasihat cümlesinden değil, seçim ve dönüşümden gelir.",
    ideaHeading: "Masal fikrini dört güçlü kaynaktan çıkar",
    ideaIntro: "Önce çocuğun hissedebileceği bir merak veya korku çekirdeği bul, sonra ona büyülü karşılık ver.",
    ideaItems: [
      { title: "İmkânsız soru", text: "Ay kaybolsa, gölgeler konuşsa veya zaman bir sandığa kilitlense ne olur?" },
      { title: "Gündelik korku", text: "Yalnız uyumak, ayrılık, kıskançlık veya hata yapmak gibi duyguyu büyülü bir probleme dönüştür." },
      { title: "Tek sihirli kural", text: "Her gece yalnız bir kez çalışan bir anahtar gibi sınırı olan bir büyü seç." },
      { title: "Sözlü motif", text: "Tekrar edilebilecek bir cümle, sayı, tekerleme veya ses motifi bul." },
    ],
    ideaFlowHeading: "Duygudan büyülü probleme, oradan seçime git",
    ideaFlowBody: "‘Karanlıktan korkan çocuk’ bir konu başlangıcıdır. Bunu ‘Her gece evin gölgesini değirmenine çeken yaşlı değirmenci yüzünden kasaba karanlıksız kalır; küçük Ela kendi gölgesini geri istemek için değirmene gider’ gibi görünür bir masal motoruna dönüştür. Duygu, büyülü kural ve eylem aynı çekirdekte buluşsun.",
    contrastHeading: "Masalı yakın türlerden ayır",
    contrastIntro: "Çocuk okuru hedefleyen her kısa anlatı masal değildir.",
    contrastItems: [
      { title: "Masal ≠ fabl", text: "Fabl çoğunlukla tek davranış ve sonuç üzerinden özlü bir ders kurar; masal dönüşüm ve yolculuğa daha geniş yer verir." },
      { title: "Masal ≠ çocuk hikâyesi", text: "Çocuk hikâyesi gündelik gerçeklikte kalabilir; masal olağanüstüyü anlatının doğal kuralı yapar." },
      { title: "Masal ≠ nasihat metni", text: "Sonuç kahramanın yaşadığı deneyimden doğmalı; yazarın yukarıdan verdiği ders anlatının yerini tutmamalı." },
    ],
    routeHeading: "Masalını 8 aşamada kur",
    routeIntro: "Önce okuru ve büyülü kuralı sabitle, sonra sınavları yaz.",
    routeItems: [
      { title: "1 · Okur bağlamı", text: "Metnin daha çok dinlenmek için mi, bağımsız okunmak için mi tasarlandığını belirle." },
      { title: "2 · Merak çekirdeği", text: "Tek cümlelik imkânsız sorunu yaz." },
      { title: "3 · Kahraman arzusu", text: "Çocuğun takip edebileceği somut isteği belirle." },
      { title: "4 · Büyülü kural", text: "Sihir ne yapabilir, ne yapamaz ve bedeli nedir yaz." },
      { title: "5 · Tekrar / üç sınav", text: "Benzer desenin giderek zorlaşan tekrarlarını kur." },
      { title: "6 · Ana seçim", text: "Kahramanın öğrendiğini eylemle göstereceği kararı yaz." },
      { title: "7 · Dönüş", text: "Dünya ve kahraman başlangıca göre nasıl değişti?" },
      { title: "8 · Sesli okuma", text: "Ritim, tekrar, korku yoğunluğu ve gereksiz açıklamayı yüksek sesle sınay." },
    ],
    structureHeading: "Masal yapısını eşik ve dönüşüm üzerinden kur",
    structureIntro: "Klasik iskeleti kullanabilirsin; ama her aşamanın kahramanı değiştirmesi gerekir.",
    structureItems: [
      { title: "Eksik denge", text: "Kahramanın dünyasında bir eksiklik veya yasak vardır." },
      { title: "Çağrı", text: "Büyülü sorun kahramanı harekete geçirir." },
      { title: "Eşik", text: "Gündelik dünya ile masal alanı arasındaki sınır geçilir." },
      { title: "Sınavlar", text: "Tekrar eden desen her turda yeni karar ister." },
      { title: "Yardım / bedel", text: "Yardımcı, nesne veya bilgi gelir; ama bedelsiz çözüm olmaz." },
      { title: "Ana seçim", text: "Kahraman başta veremeyeceği bir kararı verir." },
      { title: "Dönüş", text: "Son yalnız ‘mutlu’ değil, yaşanan değişimin sonucu olmalıdır." },
    ],
    structureCaption: "Masal yapısı, büyülü olayların sırasından çok kahramanın eşiği geçip değişmesine dayanır.",
    anatomyHeading: "Masalın anatomisi: arzu, büyülü kural, tekrar ve dönüş",
    anatomyBody: "- **Okur / dinleyici:** Dil ve korku yoğunluğunu belirler.\n- **Kahraman:** Somut bir şey ister.\n- **Büyülü kural:** Dünya tutarlı biçimde işler.\n- **Yardımcı / engelleyici:** Kahramanın kararını sınar.\n- **Tekrar:** Hafıza ve beklenti kurar.\n- **Motif:** Nesne, sayı veya söz anlatıyı birbirine bağlar.\n- **Ana seçim:** Dönüşümü gösterir.\n- **Kapanış:** Güvenli dönüş veya bilinçli açık uç bırakır.",
    practiceHeading: "Masal yazarken dört çalışma dosyası tut",
    practiceIntro: "Büyülü dünyanın tutarlılığını ve okur deneyimini taslaktan önce görünür kıl.",
    practiceItems: [
      { title: "Büyü kuralı kartı", text: "Sihirin gücü, sınırı ve bedelini tek sayfada tut." },
      { title: "Tekrar haritası", text: "Tekrarlanan cümle veya sınavın her turda neyi değiştirdiğini yaz." },
      { title: "Duygu termometresi", text: "Korku, merak ve rahatlamanın sahneler boyunca nasıl değiştiğini izle." },
      { title: "Sesli okuma notu", text: "Takılan kelimeleri, uzun cümleleri ve ritmi bozan yerleri işaretle." },
    ],
    pageSetupCaption: "Masal çalışma düzeni, büyülü kuralı, tekrar desenini ve sesli okuma revizyonunu yan yana izler.",
    workspaceHeading: "Masal dosyanı büyü ve ritim üzerinden düzenle",
    workspaceIntro: "Kısa anlatıda bile kural, motif ve dönüşüm izlenebilir olmalı.",
    workspaceItems: [
      { title: "Sahne sırası", text: "Her sahneyi tek cümlelik işlevle sırala." },
      { title: "Motif listesi", text: "Tekrarlanan nesne, sayı ve sözleri takip et." },
      { title: "Kelime düzeyi", text: "Güçlü ama anlaşılmaz olmayan sözcükleri bilinçli seç." },
      { title: "Okuma turu", text: "Her büyük revizyonda metni sesli oku veya bir başkasına okut." },
    ],
    craftHeading: "Masalın asıl zanaatı: büyülü mantık ile sözlü ritmi aynı anda korumak",
    craftBody: "Çocuk okur olağanüstü olana kolayca inanabilir; tutarsızlığa ise hemen takılır. Büyü yalnız gerektiğinde yeni güç kazanmasın. Tekrarları da kopya gibi değil, beklenti kurup her turda küçük fark yaratan ritmik araçlar olarak kullan.",
    extraSections: [
      { id: "yas-ve-dinleme", type: "cards", heading: "Yaş grubunu kelime listesinden daha geniş düşün", intro: "Yaş uygunluğu yalnız cümle uzunluğu değildir.", items: [
        { title: "Dinleme / bağımsız okuma", text: "Yetişkin eşliğinde dinlenen metin ile çocuğun tek başına okuyacağı metnin sözdizimi ve açıklama ihtiyacı farklıdır." },
        { title: "Duygusal yük", text: "Kaybolma, ölüm veya terk edilme gibi konularda yalnız yaş değil anlatım mesafesi de önemlidir." },
        { title: "Bilgi yükü", text: "Yeni kavramları aynı sahnede yığma; bağlamla anlamlandır." },
      ]},
      { id: "sozlu-ritim", type: "steps", heading: "Masalı ağızdan çıkacak biçimde yeniden yaz", items: [
        { title: "Nefes", text: "Cümleleri bir yetişkinin doğal nefesle okuyabileceği uzunlukta sınay." },
        { title: "Tekrar", text: "Çocuğun önceden tahmin edip katılabileceği söz kalıpları kur." },
        { title: "Ses", text: "Aliterasyon ve tekerlemeyi anlamı boğmadan kullan." },
      ]},
      { id: "korku-ve-guven", type: "cards", heading: "Korkuyu steril etme; ama çaresizliği de sınırsız bırakma", items: [
        { title: "Kontrol noktası", text: "Kahramanın en karanlık anda bile seçebileceği küçük bir eylem bırak." },
        { title: "Görsel ayrıntı", text: "Yoğun şiddeti ayrıntılandırmak yerine atmosfer ve sonuç üzerinden çalış." },
        { title: "Dönüş yolu", text: "Özellikle küçük okurda finalin duygusal olarak nereye indiğini bilinçli seç." },
      ]},
      { id: "kultur-ve-motif", type: "cards", heading: "Geleneksel motifi kaynaksız ve tek kültüre aitmiş gibi kullanma", items: [
        { title: "Kaynak izi", text: "Halk anlatısından aldığın motifin varyasyonlarını araştır." },
        { title: "Adlandırma", text: "Yaşayan kültürlere ait unsur kullanıyorsan doğru adlandır ve bağlamını bozma." },
        { title: "Dönüştürme", text: "Esinlenme ile birebir kopyalamayı ayır; kendi anlatı işlevini kur." },
      ]},
      { id: "resim-iliskisi", type: "cards", heading: "Resimlenecek masalda metin her şeyi tarif etmek zorunda değildir", items: [
        { title: "Boşluk bırak", text: "Görselin taşıyabileceği ayrıntıyı metinde iki kez açıklama." },
        { title: "Sayfa dönüşü", text: "Sürpriz, tekrar veya keşif anını sayfa dönüşü ritmiyle düşün." },
        { title: "Çelişki alanı", text: "Resim, metne yeni mizah veya anlam katmanı ekleyebilir." },
      ]},
    ],
    draftHeading: "İlk taslakta masalın tamamını gör",
    draftIntro: "İlk turda kusursuz dil yerine büyülü kural ve dönüşüm zincirini bitir.",
    draftItems: [
      { title: "Kuralı bozma", text: "Çözüm kolaylaşsın diye sona yeni büyü ekleme." },
      { title: "Sınavı büyüt", text: "Tekrarların her biri öncekinin kopyası değil, daha zor bir karar olsun." },
      { title: "Yetişkini geri çek", text: "Ana çözümü çocuğun veya masal kahramanının seçimine bırak." },
      { title: "Sonu erken açıklama", text: "Dersi söylemek yerine sonucu göster." },
    ],
    revisionHeading: "Masal revizyonunu kulak, kural ve duygu üzerinden yap",
    revisionIntro: "Her turda başka bir soruyu sınamak daha temiz sonuç verir.",
    revisionItems: [
      { title: "Kural testi", text: "Büyü baştan sona aynı mantıkla mı çalışıyor?" },
      { title: "Ritim testi", text: "Tekrarlar beklenen yerde mi ve her turda yeni iş yapıyor mu?" },
      { title: "Korku testi", text: "Gerilim yaşa uygun biçimde yönetiliyor mu, gereksiz ayrıntı var mı?" },
      { title: "Ders testi", text: "Final deneyimden mi çıkıyor, yazar sonradan açıklama mı ekliyor?" },
    ],
    projectName: "Ayı Saklayan Değirmen",
    projectBody: "**Kahraman:** 8 yaşındaki Ela.\n\n**Sorun:** Kasabanın gölgeleri her gece biraz daha kısalır; son gece ay da görünmez olur.\n\n**Büyülü kural:** Değirmen, yalnız sahipleri vazgeçtiğinde gölge öğütebilir.\n\n**Tekrar:** Ela üç kişiye gölgesini neden verdiğini sorar; her cevap başka bir korkuyu açar.\n\n**Ana seçim:** Ela kendi gölgesini geri almak için başkasının gölgesini feda etmeyi reddeder.\n\n**Dönüş:** Kasabalılar gölgelerini geri ister; değirmen ay ışığıyla çalışmayı bırakır.",
    projectCaption: "Ayı Saklayan Değirmen, tek büyülü kuralı tekrar, korku ve ahlaki seçimle birleştirir.",
    sampleHeading: "Örnek masal anı: kuralı açıklama yerine göster",
    sampleBody: "Ela elini torbaya soktuğunda kumaşın içi buz gibiydi. Değirmenci, ‘Bir gölge ancak sahibi artık istemiyorsa hafifler,’ dedi. Ela torbayı kaldırmaya çalıştı. Kımıldamadı. ‘Demek ki annem hâlâ istiyor,’ dedi ve ilk kez gülümsedi.",
    finalHeading: "Masalı paylaşmadan önce son kontrolü yap",
    finalIntro: "Okur deneyimini metin kadar önemse.",
    finalItems: [
      { title: "Sesli okuma", text: "Takılan cümleleri ve yapay tekrarları düzelt." },
      { title: "Büyü kuralı", text: "Çözümün önceden kurulmuş kurallardan çıktığını doğrula." },
      { title: "Çocuk ajansı", text: "Ana değişimi kahramanın seçimi mi yaratıyor?" },
      { title: "Duygusal iniş", text: "Final gerilimden sonra okura yeterli kapanış veriyor mu?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Masal fikrini hemen yazılabilir hale getir.",
    outputItems: [
      { title: "1 büyülü kural", text: "Güç, sınır ve bedeli tek paragrafta yaz." },
      { title: "1 tekrar haritası", text: "Üç sınavın nasıl zorlaştığını göster." },
      { title: "1 kahraman seçimi", text: "Finaldeki ana ahlaki eylemi yaz." },
      { title: "1 açılış sahnesi", text: "Gündelik dünya ile büyülü çatlağın karşılaştığı ilk sahneyi yaz." },
    ],
    mastersIntro: "Farklı masal geleneklerinde ritim, dönüşüm ve olağanüstü kuralın nasıl kurulduğunu incele.",
    masters: [
      { title: "Hans Christian Andersen", text: "Duygusal dönüşüm ile olağanüstü unsuru nasıl birleştirdiğini incele." },
      { title: "Grimm Kardeşler", text: "Tekrar, üçlü yapı ve sözlü anlatı ritmini karşılaştırmalı oku." },
      { title: "Angela Carter", text: "Geleneksel masal motiflerinin yeniden yorumlanırken nasıl dönüştürüldüğünü incele." },
    ],
    faq: [
      { question: "Masal mutlaka mutlu bitmeli mi?", answer: "Hayır. Ancak hedef yaş ve anlatının duygusal yükü düşünülerek finalin bıraktığı güven, anlam ve belirsizlik bilinçli seçilmelidir." },
      { question: "Masalda ders vermek zorunda mıyım?", answer: "Hayır. Tema ve değer, kahramanın eyleminden çıkabilir; açık nasihat şart değildir." },
      { question: "Eski masalı yeniden yazabilir miyim?", answer: "Kamu malı ve geleneksel kaynaklarda mümkün olabilir; yine de hangi varyanttan esinlendiğini araştırmak ve yaşayan kültürlerin bağlamına saygı göstermek gerekir." },
    ],
    finalCaption: "Masal, büyülü dünyanın kuralı ile çocuğun duygusal yolculuğu aynı ritimde tamamlandığında güçlenir.",
    ctaHeading: "İlk masalının büyülü kuralını kur",
    ctaText: "Merak çekirdeğin, büyülü kuralın ve kahraman seçimin hazırsa İlkOku Yazar Alanı'nda masal taslağını oluşturmaya başla.",
  },
  {
    category: "Çocuk ve Gençlik",
    slug: "fabl",
    label: "Fabl",
    title: "Fabl Nasıl Yazılır?",
    description: "Davranış çatışmasından kişileştirmeye, kısa olay zincirinden sonuç ve ahlaki yankıya kadar adım adım fabl yazarlığı eğitimi.",
    summary: "Bir davranışı vaazla değil sonuçla sınay; hayvan veya nesne karakterlerin doğasını tutarlı kullanarak kısa, keskin ve hatırlanabilir fabl yaz.",
    alts: alts("Fabl", "Karga ile Pusula"),
    orientationHeading: "Fablın kalbi hayvan karakter değil davranış ile sonuç arasındaki ilişkidir",
    orientationBody: "Fabl çoğu zaman hayvanları veya nesneleri kişileştirir; fakat bunun amacı sevimli karakter üretmek değildir. Kısa bir çatışma içinde kibir, acelecilik, açgözlülük, dayanışma veya önyargı gibi bir davranışın sonucunu görünür kılar. Ders, olayın içinden çıkmalıdır.",
    ideaHeading: "Fabl fikrini davranış çelişkisinden çıkar",
    ideaIntro: "Önce hangi davranışı sınamak istediğini, sonra bunu gösterecek karşıt karakterleri seç.",
    ideaItems: [
      { title: "Yanlış avantaj", text: "Karakterin güçlü sandığı özellik hangi koşulda zayıflığa dönüşür?" },
      { title: "İki yöntem", text: "Aynı hedefe biri hızlı, biri sabırlı iki karakter nasıl yaklaşır?" },
      { title: "Yanlış yargı", text: "Bir karakter diğerini görünüşüne göre küçümserse sonuç ne olur?" },
      { title: "Paylaşım sorunu", text: "Sınırlı yiyecek, su veya alan iki karakterin değerini nasıl açığa çıkarır?" },
    ],
    ideaFlowHeading: "Temadan önce davranışı yaz",
    ideaFlowBody: "‘Kibir kötüdür’ bir sonuç cümlesidir. Bunun yerine yüksekten uçtuğu için her yolu bildiğini sanan karga ile yalnız kuzeyi gösteren ama hiç şaşmayan eski pusulayı karşılaştır. Okur, davranışın sonucunu olaydan çıkarabilsin.",
    contrastHeading: "Fablın sınırlarını netleştir",
    contrastIntro: "Kısalık ve hayvan karakter tek başına fabl yapmaz.",
    contrastItems: [
      { title: "Fabl ≠ masal", text: "Masal geniş büyülü yolculuğa açılabilir; fabl çoğunlukla tek davranış gerilimini ekonomik biçimde sınar." },
      { title: "Fabl ≠ fıkra", text: "Komik final olabilir ama amaç yalnız şaka değil, davranışın sonucunu görünür kılmaktır." },
      { title: "Fabl ≠ ders notu", text: "Ahlaki fikir olaydan doğmalı; karakterler sadece öğretmenin ağzı olmamalı." },
    ],
    routeHeading: "Fablı 7 aşamada kur",
    routeIntro: "Kısa metinde her öğe aynı merkezi davranışa hizmet etsin.",
    routeItems: [
      { title: "1 · Davranış sorusu", text: "Hangi tutumu sınayacağını soru halinde yaz." },
      { title: "2 · Karşıt karakter", text: "İki farklı yöntem veya değer seç." },
      { title: "3 · Somut hedef", text: "Yiyecek, yol, barınak, yarış veya paylaşım gibi görünür amaç belirle." },
      { title: "4 · Tek çatışma", text: "Karakterleri aynı problemde karşı karşıya getir." },
      { title: "5 · Dönüm", text: "Baskı altında gerçek davranış ortaya çıksın." },
      { title: "6 · Sonuç", text: "Seçimin doğal sonucu gerçekleşsin." },
      { title: "7 · Ahlaki yankı", text: "Gerekliyse kısa sonuç cümlesi ekle; olayın zaten söylediğini tekrar etme." },
    ],
    structureHeading: "Fablı tek gerilim çizgisinde tut",
    structureIntro: "Yan olaylar değil karşılaştırma netliği önemlidir.",
    structureItems: [
      { title: "Tanıtım", text: "Karakterlerin belirleyici özelliklerini eylem içinde göster." },
      { title: "Ortak problem", text: "İki karakteri aynı hedefe bağla." },
      { title: "Farklı yöntem", text: "Değer farkı görünür hale gelsin." },
      { title: "Beklenmedik sonuç", text: "İlk bakışta avantajlı görünen yöntem sınansın." },
      { title: "Yankı", text: "Okurun çıkarımı için kısa alan bırak." },
    ],
    structureCaption: "Fabl yapısı, tek davranış karşılaştırmasını mümkün olduğunca temiz ve ekonomik tutar.",
    anatomyHeading: "Fabl anatomisi: karakter özelliği, karşıtlık, eylem ve sonuç",
    anatomyBody: "- **Davranış sorusu:** Metin hangi tutumu sınar?\n- **Kişileştirme:** Hayvan veya nesne hangi insan davranışını taşıyor?\n- **Karşıtlık:** İki yöntem nasıl ayrılıyor?\n- **Somut hedef:** Tartışma hangi eylem etrafında dönüyor?\n- **Dönüm:** Yanlış varsayım ne zaman açığa çıkıyor?\n- **Sonuç:** Kararın bedeli veya kazancı ne?\n- **Ahlaki yankı:** Okura ne kadarını kendisinin bulması için bırakıyorsun?",
    practiceHeading: "Fabl için dört kısa çalışma kartı kullan",
    practiceIntro: "Kısalık, hazırlıksız yazmak anlamına gelmez.",
    practiceItems: [
      { title: "Özellik kartı", text: "Her karakterin tek baskın davranışını ve karşıtını yaz." },
      { title: "Doğa kartı", text: "Seçtiğin hayvan veya nesnenin gerçek özelliklerinden hangisini anlatıda kullandığını belirt." },
      { title: "Sonuç zinciri", text: "Seçim → eylem → sonuç bağlantısını üç satırda kur." },
      { title: "Kesme turu", text: "Merkezi davranışa hizmet etmeyen yan bilgi ve açıklamayı çıkar." },
    ],
    pageSetupCaption: "Fabl çalışma düzeni, karakter özelliği ile olay sonucunu tek bakışta karşılaştırmayı sağlar.",
    workspaceHeading: "Fablı tek sayfada görünür tut",
    workspaceIntro: "Metin uzadıkça ana davranış gerilimini kaybetmemek için sade bir düzen kullan.",
    workspaceItems: [
      { title: "Tek problem", text: "Yeni yan çatışma açmak yerine mevcut problemi derinleştir." },
      { title: "Kısa sahne", text: "Her bölüm karar veya sonuç üretmeli." },
      { title: "Diyalog işlevi", text: "Konuşma karakteri göstermeli; açıklama yükünü büyütmemeli." },
      { title: "Final notu", text: "Ahlaki cümlenin gerçekten gerekli olup olmadığını ayrı değerlendir." },
    ],
    craftHeading: "Fablın asıl zanaatı: davranışı karakter özelliğiyle tek hamlede görünür kılmak",
    craftBody: "Tilkinin kurnaz, kaplumbağanın sabırlı olması gibi hazır kalıpları otomatik kullanmak yerine seçtiğin canlı veya nesnenin anlatıya gerçekten ne kattığını düşün. Kişileştirme tutarlı olmalı; karakter yalnız finalde ders verebilmek için kişilik değiştirmemelidir.",
    extraSections: [
      { id: "kisilestirme", type: "cards", heading: "Kişileştirmeyi tutarlı bir davranış sistemi olarak kur", items: [
        { title: "Doğal özellik", text: "Hayvanın veya nesnenin gerçek özelliğini anlatı işlevine dönüştür." },
        { title: "İnsan davranışı", text: "Taşıdığı insan özelliğini tek ve anlaşılır tut." },
        { title: "Tutarlılık", text: "Final için karakteri sebepsizce başka bir tipe dönüştürme." },
      ]},
      { id: "ahlak-vaaz", type: "cards", heading: "Ahlaki fikri olaydan çıkar, vaazdan değil", items: [
        { title: "Önce sonuç", text: "Okur davranışın bedelini görsün." },
        { title: "Sonra cümle", text: "Açık ders ekleyeceksen metnin zaten söylediğini gereksizce tekrar etme." },
        { title: "Çok anlam", text: "Her fabl tek doğru slogan üretmek zorunda değildir." },
      ]},
      { id: "ekonomi", type: "steps", heading: "Fablı gereksiz yükten arındır", items: [
        { title: "Tek hedef", text: "Yan görevleri çıkar." },
        { title: "İki ana karakter", text: "Yeni karakter yalnız merkezi karşılaştırmaya hizmet ediyorsa ekle." },
        { title: "Tek dönüm", text: "Finale giden en güçlü dönüşü koru." },
      ]},
      { id: "kalip-ve-stereotip", type: "cards", heading: "Hayvan kalıbını önyargıya dönüştürme", items: [
        { title: "Hazır rol", text: "‘Tilki her zaman kötüdür’ gibi otomatik eşleşmeleri sorgula." },
        { title: "İnsan grubu", text: "Hayvan özelliğini gerçek insan topluluğuna aşağılayıcı gönderme olarak kullanma." },
        { title: "Çeşitlilik", text: "Aynı hayvan tipini farklı fabllarda farklı davranışlarla düşün." },
      ]},
      { id: "kaynak-gelenek", type: "cards", heading: "Klasik fabl geleneğini kaynak bilinciyle kullan", items: [
        { title: "Varyant", text: "Aynı fablın Ezop, La Fontaine veya yerel anlatılardaki farklarını araştır." },
        { title: "Uyarlama", text: "Klasik iskeleti yeni bağlama taşıyorsan değişimin nedenini görünür kıl." },
        { title: "Atıf", text: "Doğrudan yeniden anlatımda esin kaynağını saklama." },
      ]},
    ],
    draftHeading: "İlk taslakta tek davranış zincirini tamamla",
    draftIntro: "Kısa olduğu için her cümleyi ilk turda cilalamaya çalışma.",
    draftItems: [
      { title: "Karakterleri hızla kur", text: "Özelliği açıklamak yerine ilk eylemde göster." },
      { title: "Problemi erken getir", text: "Uzun dünya kurulumunu atla." },
      { title: "Sonucu zorlamama", text: "Ders çıkarmak için mantıksız tesadüf yaratma." },
      { title: "Finali kısa tut", text: "Sonuçtan sonra ikinci bir açıklama sahnesi ekleme." },
    ],
    revisionHeading: "Fabl revizyonunda netlik ve ekonomi ara",
    revisionIntro: "Metnin kısa olması, yüzeysel olması anlamına gelmez.",
    revisionItems: [
      { title: "Davranış testi", text: "Karakter seçimi tek bakışta anlaşılabiliyor mu?" },
      { title: "Neden-sonuç testi", text: "Final gerçekten önceki kararlardan mı doğuyor?" },
      { title: "Stereotip testi", text: "Kişileştirme tembel veya aşağılayıcı kalıba mı yaslanıyor?" },
      { title: "Ahlak testi", text: "Son cümle metni güçlendiriyor mu, açıklıyor mu?" },
    ],
    projectName: "Karga ile Pusula",
    projectBody: "**Karakter 1:** Karga, yüksekten baktığı için her yolu bildiğini düşünür.\n\n**Karakter 2:** Eski pusula yalnız kuzeyi gösterebilir ama yönünü değiştirmez.\n\n**Problem:** Sis bastığında ikisi de göl kıyısındaki ceviz ağacına ulaşmak ister.\n\n**Dönüm:** Karga yüksekten uçmayı sürdürüp daire çizer; pusula sınırlı bilgisini kabul ederek kıyı çizgisini takip eder.\n\n**Yankı:** Her şeyi bildiğini sanmak, neyi bildiğini bilmekten daha az işe yarar.",
    projectCaption: "Karga ile Pusula, kibir ile sınırını bilme davranışını tek yolculuk problemi içinde karşılaştırır.",
    sampleHeading: "Örnek fabl anı: karakteri açıklamadan göster",
    sampleBody: "Karga üçüncü kez aynı sazlığın üzerinden geçince pusula seslendi: ‘Ben yalnız kuzeyi bilirim.’ Karga kanadını silkerek, ‘Ben göğün tamamını,’ dedi. Sis biraz daha kalınlaştı.",
    finalHeading: "Fablı paylaşmadan önce dört kontrol yap",
    finalIntro: "Kısa metnin her parçası merkezi davranışa hizmet etsin.",
    finalItems: [
      { title: "Tek soru", text: "Metnin hangi davranışı sınadığını söyleyebiliyor musun?" },
      { title: "Kişileştirme", text: "Karakter özelliği olay boyunca tutarlı mı?" },
      { title: "Doğal sonuç", text: "Final tesadüften değil seçimden mi doğuyor?" },
      { title: "Son cümle", text: "Ahlaki cümle gerekliyse kısa ve açık mı?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Bir davranış fikrini kısa ve tamamlanabilir fabla dönüştür.",
    outputItems: [
      { title: "1 davranış sorusu", text: "Sınayacağın tutumu soru halinde yaz." },
      { title: "2 karakter kartı", text: "Karşıt yöntem ve özellikleri belirle." },
      { title: "1 neden-sonuç zinciri", text: "Seçimden finale giden üç adımı yaz." },
      { title: "1 tam fabl taslağı", text: "Kısa metni baştan sona tamamla." },
    ],
    mastersIntro: "Klasik ve farklı kültürel fabl geleneklerinde kısalık, kişileştirme ve sonuç ilişkisini incele.",
    masters: [
      { title: "Ezop", text: "Davranış çatışmasını son derece ekonomik olay örgüsüyle kurma biçimini incele." },
      { title: "Jean de La Fontaine", text: "Fablın ritim, ironi ve toplumsal gözlemle nasıl genişletildiğini incele." },
      { title: "Beydeba", text: "Hayvan anlatısını siyaset, ahlak ve karar ilişkisi içinde nasıl kullandığını incele." },
    ],
    faq: [
      { question: "Fablda mutlaka hayvan mı olmalı?", answer: "Hayır. Nesneler veya insanlar da kullanılabilir; belirleyici olan kısa davranış çatışması ve sonuç ilişkisidir." },
      { question: "Dersi en sonda açıkça yazmalı mıyım?", answer: "Şart değil. Olay yeterince açıksa okura çıkarım alanı bırakabilirsin." },
      { question: "Fabl komik olabilir mi?", answer: "Evet. Mizah davranışın sonucunu keskinleştirebilir; ancak yalnız şakaya dönüşmemeli." },
    ],
    finalCaption: "Fabl, davranış ile sonucu en az araçla en net biçimde bağladığında hatırlanır.",
    ctaHeading: "İlk fablının davranış çatışmasını kur",
    ctaText: "Karşıt karakterlerin ve sonuç zincirin hazırsa İlkOku Yazar Alanı'nda fabl taslağını oluşturmaya başla.",
  },
  {
    category: "Çocuk ve Gençlik",
    slug: "cocuk-hikayesi",
    label: "Çocuk Hikâyesi",
    title: "Çocuk Hikâyesi Nasıl Yazılır?",
    description: "Çocuk bakış açısından gündelik çatışmaya, karakter ajansından duygu, diyalog ve sayfa ritmine kadar adım adım çocuk hikâyesi eğitimi.",
    summary: "Çocuk karakteri yetişkinlerin taşıdığı bir nesne değil, karar veren özne yap; yaşa uygun ama küçümsemeyen bir dille somut, duygusal ve tamamlanabilir hikâye kur.",
    alts: alts("Çocuk Hikâyesi", "Kayıp Kırmızı Eldiven"),
    orientationHeading: "Çocuk hikâyesi küçük konu değil, çocuğun dünyasında büyük anlam taşıyan hikâyedir",
    orientationBody: "Bir eldivenin kaybolması, sınıfta yanlış cevap vermek veya yeni komşuyla tanışmak yetişkine küçük görünebilir; çocuk karakter için kimlik, aidiyet ve cesaret meselesine dönüşebilir. Hikâye çocuğun algısına yaklaşmalı ama onu basitleştirmemelidir.",
    ideaHeading: "Çocuk hikâyesi fikrini çocuğun gerçek gündeminden çıkar",
    ideaIntro: "Önce yetişkinin önemli bulduğu şeyi değil, çocuk karakterin gerçekten önemsediği şeyi seç.",
    ideaItems: [
      { title: "İlk kez", text: "İlk yalnız yolculuk, ilk gece başka evde kalma, ilk sunum veya ilk kayıp gibi eşikleri yaz." },
      { title: "Küçük sır", text: "Saklanan bir hata veya yanlış anlaşılma, çocuğu aktif karar vermeye zorlayabilir." },
      { title: "Arkadaşlık gerilimi", text: "Katılma, dışlanma, kıskançlık veya barışma gibi sosyal problemi somutlaştır." },
      { title: "Gündelik keşif", text: "Sıradan mekânda çocuğun fark ettiği ama yetişkinin görmediği ayrıntıdan hikâye çıkar." },
    ],
    ideaFlowHeading: "Problemi çocuğun isteği ve seçimiyle bağla",
    ideaFlowBody: "‘Okulda zorlanan çocuk’ geniş bir konudur. ‘Defterini evde unuttuğunu söylemeye utanan Deniz, arkadaşının kayıp defterini kendi defteri gibi teslim edince gün boyu büyüyen bir yalanı düzeltmek zorunda kalır’ gibi somut seçim zinciri hikâye motoru yaratır.",
    contrastHeading: "Çocuk hikâyesini komşu biçimlerden ayır",
    contrastIntro: "Yaş grubu kadar anlatı ölçeği ve gerçeklik düzeyi de türü belirler.",
    contrastItems: [
      { title: "Çocuk hikâyesi ≠ masal", text: "Olağanüstü şart değildir; gündelik gerçeklik kendi başına yeterli olabilir." },
      { title: "Çocuk hikâyesi ≠ çocuk romanı", text: "Tek ana çatışma ve daha kısa zaman aralığıyla çalışabilir." },
      { title: "Çocuk hikâyesi ≠ yetişkin öğüdü", text: "Çocuk karakterin çözümde gerçek payı olmalıdır." },
    ],
    routeHeading: "Çocuk hikâyesini 8 aşamada kur",
    routeIntro: "Okur yaşı, karakter arzusu ve tek merkez çatışmayı birlikte planla.",
    routeItems: [
      { title: "1 · Hedef okur", text: "Dinleme mi bağımsız okuma mı, yaklaşık okuma yetkinliği ne?" },
      { title: "2 · Çocuk arzusu", text: "Kahramanın o gün en çok ne istediğini yaz." },
      { title: "3 · Engel", text: "İsteği zorlaştıran kişi, kural, hata veya korkuyu belirle." },
      { title: "4 · Yanlış ilk çözüm", text: "Çocuk karakterin kendi seçimiyle problemi büyütmesine izin ver." },
      { title: "5 · Duygusal dönüm", text: "Karakter neyi yeni biçimde anlar?" },
      { title: "6 · Ana seçim", text: "Çözümü yetişkin değil çocuk başlatsın." },
      { title: "7 · Sonuç", text: "Dünya tamamen düzelmese bile ilişki veya karakter değişsin." },
      { title: "8 · Okuma revizyonu", text: "Dil, ritim ve duygusal güvenliği hedef okurla sınay." },
    ],
    structureHeading: "Kısa çocuk hikâyesini karar ve sonuç zinciriyle kur",
    structureIntro: "Az sahnede belirgin değişim yarat.",
    structureItems: [
      { title: "Normal gün", text: "Çocuğun düzenini kısa ama canlı bir ayrıntıyla aç." },
      { title: "Sorun", text: "Gündelik dengeyi bozan olay hemen görünür olsun." },
      { title: "İlk deneme", text: "Çocuk kendi yöntemiyle çözmeye çalışsın." },
      { title: "Büyüyen sonuç", text: "Yanlış veya eksik çözüm yeni sorun yaratsın." },
      { title: "Fark ediş", text: "Karakter başka bir seçenek görsün." },
      { title: "Ana seçim", text: "Duygusal değişim eyleme dönüşsün." },
      { title: "Yeni denge", text: "Küçük ama gerçek bir değişimle bitir." },
    ],
    structureCaption: "Çocuk hikâyesi, yetişkin müdahalesi yerine çocuğun kararlarının sonuç ürettiği kısa bir değişim yayı kurar.",
    anatomyHeading: "Çocuk hikâyesinin anatomisi: bakış, arzu, ajans ve güven",
    anatomyBody: "- **Hedef okur:** Dil ve anlatım yükünü etkiler.\n- **Çocuk bakışı:** Dünya ne kadarını çocuğun algısından görüyor?\n- **Arzu:** Somut ve duygusal hedef.\n- **Engel:** Çocuğun çözebileceği ölçekte problem.\n- **Ajans:** Çocuk hangi kararı kendisi veriyor?\n- **Yetişkin rolü:** Destek olabilir ama ana çözümü çalmamalı.\n- **Duygusal sonuç:** Çocuk neyi yeni biçimde anlıyor?",
    practiceHeading: "Çocuk hikâyesi için dört çalışma dosyası tut",
    practiceIntro: "Yaş uygunluğu ve çocuk bakışını taslak boyunca kaybetme.",
    practiceItems: [
      { title: "Okur kartı", text: "Yaklaşık yaş, okuma bağlamı ve bilmesi gerekmeyen ön bilgileri yaz." },
      { title: "Ajans çizgisi", text: "Her sahnede çocuğun verdiği kararı işaretle." },
      { title: "Duygu sözlüğü", text: "Duyguyu isimle değil davranış ve beden üzerinden gösterecek örnekler biriktir." },
      { title: "Yetişkin filtresi", text: "Yetişkin karakterlerin gereğinden fazla açıklama veya çözüm yaptığı yerleri işaretle." },
    ],
    pageSetupCaption: "Çocuk hikâyesi çalışma düzeni, okur seviyesi ve çocuk ajansını sahne sahne takip eder.",
    workspaceHeading: "Taslağı çocuk bakışını kaybetmeyecek biçimde düzenle",
    workspaceIntro: "Her sahnede kimin bildiğini ve kimin karar verdiğini görünür tut.",
    workspaceItems: [
      { title: "Bakış notu", text: "Çocuk karakterin o sahnede ne bildiğini yaz." },
      { title: "Yeni kelime sınırı", text: "Aynı paragrafta gereksiz kavram yükü oluşturma." },
      { title: "Diyalog okuması", text: "Çocukların yetişkin makalesi gibi konuştuğu cümleleri yakala." },
      { title: "Sayfa / sahne ritmi", text: "Keşif ve sürpriz anlarını görsel sayfa dönüşü ihtimaliyle düşün." },
    ],
    craftHeading: "Çocuk hikâyesinin asıl zanaatı: çocuğun bakışına yaklaşmak, çocuksulaşmamak",
    craftBody: "Kısa cümle kullanmak çocuk sesi değildir. Çocuğun dikkat ettiği ayrıntıyı, yanlış anladığı şeyi, saklamak istediği duyguyu ve yetişkinlerden farklı önceliğini kur. Kelimeyi basitleştirirken düşünceyi basitleştirme.",
    extraSections: [
      { id: "yas-okuma", type: "cards", heading: "Yaş bandı ile okuma becerisini aynı şey sanma", items: [
        { title: "Okuma bağlamı", text: "Yetişkinle okuma, sınıf okuması ve bağımsız okuma farklı metin yükü kaldırır." },
        { title: "Cümle karmaşıklığı", text: "Yalnız kelime uzunluğunu değil yan cümle, zaman sıçraması ve anlatıcı bilgisini de ayarla." },
        { title: "İlgi yaşı", text: "Okurun anlayabildiği konu ile okumak istediği konu her zaman aynı değildir." },
      ]},
      { id: "cocuk-ajansi", type: "steps", heading: "Çocuğa gerçek karar alanı ver", items: [
        { title: "Problemi yaşasın", text: "Yetişkin problemi çocuktan önce teşhis etmesin." },
        { title: "Yanlış denesin", text: "Kahramanın kendi hatası hikâyeyi büyütebilsin." },
        { title: "Çözümü başlatsın", text: "Yetişkin destek verse bile dönüşüm kararını çocuk versin." },
      ]},
      { id: "zor-duygular", type: "cards", heading: "Zor konuları küçümsemeden ama güvenli anlat", items: [
        { title: "Adlandır", text: "Kayıp, ayrılık, hastalık veya korkuyu tamamen gizlemek zorunda değilsin." },
        { title: "Ayrıntı sınırı", text: "Grafik veya aşırı yoğun ayrıntı yerine çocuğun yaşayabileceği deneyime odaklan." },
        { title: "Destek izi", text: "Çocuğun güvenebileceği ilişki, rutin veya yardım yolu görünür olsun." },
      ]},
      { id: "diyalog", type: "cards", heading: "Çocuk diyaloğunu yaşa özgü ama karikatürsüz yaz", items: [
        { title: "Kısaltma", text: "Çocuklar her duyguyu açıklayan uzun konuşmalar yapmaz." },
        { title: "Yan anlam", text: "Ne düşündüğü ile ne söylediği arasında fark bırak." },
        { title: "Gözlem", text: "Gerçek konuşma ritmini dinle; moda ifadeyi aşırı kullanma." },
      ]},
      { id: "resim-sayfa", type: "cards", heading: "Resimli anlatıda metin ile görsel görev paylaşsın", items: [
        { title: "Tekrar etme", text: "Resimde görünen her şeyi metinde yeniden sayma." },
        { title: "Sayfa dönüşü", text: "Merak veya komik sonucu yeni sayfaya saklayabilirsin." },
        { title: "Görsel bilgi", text: "Yan karakter veya arka plan hikâyesinin bir kısmını görsele bırak." },
      ]},
      { id: "kapsayicilik", type: "cards", heading: "Çeşitliliği yalnız işaret kutusuna dönüştürme", items: [
        { title: "Karakter derinliği", text: "Kimlik özelliği karakterin tek kişilik özeti olmasın." },
        { title: "Araştırma", text: "Bilmediğin yaşam deneyimini yazarken güvenilir kaynak ve duyarlılık okuması kullan." },
        { title: "Normalleştirme", text: "Farklılık her zaman hikâyenin problemi olmak zorunda değildir." },
      ]},
    ],
    draftHeading: "İlk taslakta çocuğun yolunu yetişkinden koru",
    draftIntro: "Önce karar zincirini bitir, sonra dil seviyesini incelt.",
    draftItems: [
      { title: "Çocuk hedefini koru", text: "Sahne yetişkinin gündemine kayarsa geri dön." },
      { title: "Hata yapmasına izin ver", text: "Kahramanı sürekli doğru ve örnek çocuk yapma." },
      { title: "Açıklamayı kıs", text: "Duyguyu davranışta gösterebildiğin yerde anlatıcı açıklamasını azalt." },
      { title: "Çözümü çalmama", text: "Yetişkinin son anda her şeyi halletmesine izin verme." },
    ],
    revisionHeading: "Çocuk hikâyesini gerçek okur deneyimiyle sınay",
    revisionIntro: "Yalnız yetişkin editör gözü yeterli olmayabilir.",
    revisionItems: [
      { title: "Bakış testi", text: "Metin çocuğun bilmeyeceği bilgilerle mi dolu?" },
      { title: "Dil testi", text: "Zor kelime bağlamdan anlaşılabiliyor mu?" },
      { title: "Ajans testi", text: "Kahramanın kararları olayları gerçekten değiştiriyor mu?" },
      { title: "Okuma testi", text: "Hedef yaşa yakın okur veya deneyimli eğitimci nerede sıkılıyor, şaşırıyor, merak ediyor?" },
    ],
    projectName: "Kayıp Kırmızı Eldiven",
    projectBody: "**Kahraman:** 9 yaşındaki Deniz.\n\n**İstek:** Anneannesinin ördüğü kırmızı eldivenin eşini okul çıkmadan bulmak.\n\n**Hata:** Kayıp eşya kutusunda benzer bir eldiveni kendi eldiveni sanıp alır.\n\n**Büyüyen sorun:** Eldivenin başka bir öğrenciye ait olduğunu öğrenir ama geri vermeye utanır.\n\n**Ana seçim:** Kendi eldivenini bulma şansını kaybetse bile yanlış aldığı eldiveni sahibine teslim eder.\n\n**Yeni denge:** Kayıp eldiven bulunmaz; ama Deniz anneannesine gerçeği anlatır ve birlikte yeni bir çift örmeye karar verirler.",
    projectCaption: "Kayıp Kırmızı Eldiven, küçük görünen bir eşya kaybını utanç, dürüstlük ve çocuk ajansı üzerinden büyütür.",
    sampleHeading: "Örnek çocuk hikâyesi anı: duyguyu davranışla göster",
    sampleBody: "Deniz eldiveni montunun cebine daha derine itti. Koridorda Ece ağlıyordu. ‘Üzerinde sarı bir yıldız vardı,’ dedi Ece. Deniz elini cebinden çıkaramadı.",
    finalHeading: "Hikâyeyi paylaşmadan önce çocuk okur kontrolü yap",
    finalIntro: "Metin hem anlaşılır hem saygılı hem de çocuğun kararına dayalı olsun.",
    finalItems: [
      { title: "Okur", text: "Dil ve konu hedef okura uygun mu?" },
      { title: "Ajans", text: "Çocuk karakter ana çözümde aktif mi?" },
      { title: "Yetişkin", text: "Destek veriyor ama hikâyeyi ele geçirmiyor mu?" },
      { title: "Duygu", text: "Zor konu gereksiz korku veya utanç üretmeden işlenmiş mi?" },
    ],
    outputsHeading: "Bu eğitimden dört somut çıktı ile çık",
    outputsIntro: "Çocuk karakterinin hikâyesini hemen yazmaya başla.",
    outputItems: [
      { title: "1 okur kartı", text: "Okuma bağlamı ve yaklaşık hedef yaşı yaz." },
      { title: "1 çocuk arzusu", text: "Kahramanın somut hedefini tek cümlede yaz." },
      { title: "1 karar zinciri", text: "Hata → sonuç → ana seçim akışını kur." },
      { title: "1 açılış sahnesi", text: "Çocuğun dünyasını kendi bakışından göster." },
    ],
    mastersIntro: "Çocuk karakterin ajansı, mizahı ve duygusal ciddiyeti nasıl birlikte taşıdığını farklı yazarlarda incele.",
    masters: [
      { title: "Astrid Lindgren", text: "Çocuk karaktere bağımsızlık, mizah ve güçlü kişilik verme biçimini incele." },
      { title: "Behiç Ak", text: "Gündelik çocuk deneyimini merak, şehir yaşamı ve mizahla kurma biçimine bak." },
      { title: "Roald Dahl", text: "Çocuk bakışı, abartı ve yetişkin dünyasına eleştirel mesafenin nasıl çalıştığını incele." },
    ],
    faq: [
      { question: "Çocuk hikâyesinde zor konu olabilir mi?", answer: "Evet. Önemli olan konuyu yok saymak değil, hedef yaşın duygusal kapasitesine uygun ayrıntı, destek ve anlatım mesafesi kurmaktır." },
      { question: "Çocuk karakter hep iyi örnek olmalı mı?", answer: "Hayır. Hata, çelişki ve yanlış seçim karakteri canlı kılar; önemli olan sonuçların dürüst işlenmesidir." },
      { question: "Zor kelime hiç kullanmamalı mıyım?", answer: "Kullanabilirsin. Bağlam, tekrar veya görsel destekle anlamlandırılabilen yeni kelimeler okuru geliştirebilir." },
    ],
    finalCaption: "Çocuk hikâyesi, çocuk karakterin dünyasını ciddiye alıp çözümde ona gerçek pay verdiğinde inandırıcı olur.",
    ctaHeading: "İlk çocuk hikâyenin karar zincirini kur",
    ctaText: "Okur kartın ve çocuk karakterinin hedefi hazırsa İlkOku Yazar Alanı'nda hikâye taslağını oluşturmaya başla.",
  },
  {
    category: "Çocuk ve Gençlik",
    slug: "cocuk-romani",
    label: "Çocuk Romanı",
    title: "Çocuk Romanı Nasıl Yazılır?",
    description: "Yaş bandı ve ana çatışmadan bölüm motoru, karakter yayı, yan hikâye ve uzun taslak revizyonuna kadar adım adım çocuk romanı eğitimi.",
    summary: "Uzun anlatıyı yetişkin romanının küçültülmüş hali gibi değil; çocuk okurun hafızası, merakı ve ajansıyla çalışan bölüm bölüm ilerleyen bir dünya olarak kur.",
    alts: alts("Çocuk Romanı", "Mavi Apartmanın Çatı Katı"),
    orientationHeading: "Çocuk romanı uzunluk değil, sürdürülebilir çocuk bakışı ve bölüm motorudur",
    orientationBody: "Roman ölçeği daha fazla karakter ve olay taşır; fakat çocuk okurun izlemesi gereken bağlantıların açık olması gerekir. Ana karakterin isteği ve kararları bölümler boyunca kaybolmamalı, yan hikâyeler ana duygusal yayı desteklemelidir.",
    ideaHeading: "Çocuk romanı fikrini uzun süre taşıyacak motordan çıkar",
    ideaIntro: "Tek olay değil, her bölüm yeni soru üretecek bir durum ara.",
    ideaItems: [
      { title: "Mekân sırrı", text: "Apartman, okul, mahalle veya yazlık gibi tekrar dönebileceğin bir alan kur." },
      { title: "Uzun hedef", text: "Takım kurmak, kayıp geçmişi bulmak veya bir projeyi tamamlamak gibi çok adımlı amaç seç." },
      { title: "İlişki değişimi", text: "Arkadaşlık, kardeşlik veya aile ilişkisinin bölüm bölüm dönüşebileceği gerilim kur." },
      { title: "Seri problem", text: "Her çözümün yeni bir soru açabildiği oyun, kulüp veya gizem motoru tasarla." },
    ],
    ideaFlowHeading: "Tek fikri bölüm üreten motora dönüştür",
    ideaFlowBody: "‘Eski apartmanda gizem’ tek başına roman taşımaz. ‘Üç çocuk, apartmanın çatı katında her dairenin geçmişine ait bir eşya bulur; her eşya bugünkü bir komşuluk sorununu açar ve finalde binanın yıkım kararına bağlanır’ gibi tekrar üretilebilen bir bölüm motoru kur.",
    contrastHeading: "Çocuk romanını yakın türlerden ayır",
    contrastIntro: "Uzunluk arttıkça yalnız sahne sayısı değil yapı sorumluluğu da büyür.",
    contrastItems: [
      { title: "Çocuk romanı ≠ uzun çocuk hikâyesi", text: "Bölüm motoru, yan karakter gelişimi ve orta bölüm dönüşleri gerekir." },
      { title: "Çocuk romanı ≠ yetişkin romanını sadeleştirmek", text: "Bakış, bilgi yükü ve problem ölçeği çocuk okura göre yeniden tasarlanır." },
      { title: "Çocuk romanı ≠ YA", text: "Yaş, bağımsızlık alanı, ilişki yoğunluğu ve tema işleme biçimi farklı olabilir." },
    ],
    routeHeading: "Çocuk romanını 9 aşamada kur",
    routeIntro: "Uzun metinde önce omurgayı ve bölüm motorunu kur.",
    routeItems: [
      { title: "1 · Okur ve ton", text: "Okuma seviyesi, mizah ve duygusal yoğunluğu belirle." },
      { title: "2 · Ana arzu", text: "Roman boyunca kahramanı taşıyacak hedefi seç." },
      { title: "3 · Dünya / mekân", text: "Tekrar döneceğin alanların kurallarını yaz." },
      { title: "4 · Karakter ekibi", text: "Her ana karaktere farklı işlev, arzu ve çatışma ver." },
      { title: "5 · Bölüm motoru", text: "Her bölümün yeni problem ve sonuç üretme mantığını kur." },
      { title: "6 · Orta dönüş", text: "Romanın ortasında hedef veya bilgi dengesini değiştir." },
      { title: "7 · Ana kriz", text: "Kahramanın değerini test eden zor seçimi getir." },
      { title: "8 · İlk taslak", text: "Bölüm bölüm sona ulaş." },
      { title: "9 · Büyük revizyon", text: "Yapı, yaş uygunluğu, süreklilik ve karakter yayı turu yap." },
    ],
    structureHeading: "Çocuk romanını bölüm sözleriyle kur",
    structureIntro: "Her bölüm okura küçük bir sonuç ve yeni bir merak borçludur.",
    structureItems: [
      { title: "Kurulum bölümleri", text: "Kahraman, dünya ve ana problem hızlıca yerleşir." },
      { title: "İlk girişim", text: "Çocuk ekibi hedefe kendi yöntemiyle yaklaşır." },
      { title: "Büyüyen ağ", text: "Yan karakterler ve alt sorunlar ana hedefe bağlanır." },
      { title: "Orta kırılma", text: "Yeni bilgi eski planı geçersiz kılar." },
      { title: "Ayrışma", text: "Arkadaşlık veya ekip içinde değer çatışması görünür olur." },
      { title: "Kriz", text: "Kahraman yalnız becerisini değil değerini de seçmek zorunda kalır." },
      { title: "Final ve yankı", text: "Ana problem çözülürken karakter ilişkileri yeni dengeye gelir." },
    ],
    structureCaption: "Çocuk romanında bölüm ritmi, büyük olay örgüsünü küçük merak ve sonuç birimleriyle taşır.",
    anatomyHeading: "Çocuk romanının anatomisi: ana arzu, bölüm motoru, ekip ve hafıza yükü",
    anatomyBody: "- **Hedef okur:** Dil, tema ve bölüm uzunluğunu etkiler.\n- **Ana arzu:** Roman boyunca yön kaybolmaz.\n- **Bölüm motoru:** Her bölümün ürettiği soru ve sonuç.\n- **Karakter ekibi:** Farklı işlev ve çatışmalar.\n- **Yan hikâye:** Ana temayı destekler.\n- **Orta dönüş:** Okurun beklentisini yeniler.\n- **Süreklilik:** Nesne, zaman, mekân ve bilgi takibi.\n- **Final seçimi:** Çocuğun gelişimini eylemde gösterir.",
    practiceHeading: "Çocuk romanı için beş çalışma dosyası tut",
    practiceIntro: "Uzun metinde hafıza yükünü yazara bırakma; sistemi dışarı taşı.",
    practiceItems: [
      { title: "Bölüm tablosu", text: "Her bölümün amaç, engel, sonuç ve yeni sorusunu yaz." },
      { title: "Karakter kartı", text: "Arzu, korku, değişim ve ilişkileri takip et." },
      { title: "Süreklilik listesi", text: "Gün, saat, eşya, mekân ve kim-ne-biliyor bilgisini kaydet." },
      { title: "Okur yükü", text: "Yeni isim, kavram ve bilgilerin hangi bölümde tanıtıldığını izle." },
      { title: "Duygu yayı", text: "Gerilim ile rahatlama bölümlerini dengeli dağıt." },
    ],
    pageSetupCaption: "Çocuk romanı çalışma düzeni, bölüm motorunu, karakter ilişkilerini ve süreklilik bilgisini birlikte görünür tutar.",
    workspaceHeading: "Uzun taslağı bölüm ve süreklilik sistemiyle yönet",
    workspaceIntro: "Roman büyüdükçe hafızaya güvenme.",
    workspaceItems: [
      { title: "Bölüm özeti", text: "Her bölüm bittikten sonra 2–3 cümlelik gerçekleşen olay kaydı tut." },
      { title: "Açık soru listesi", text: "Okura verdiğin sözleri ve cevaplanmamış gizemleri yaz." },
      { title: "Karakter ilişkisi", text: "Dostluk, rekabet ve güven değişimini bölüm numarasıyla izle." },
      { title: "Revizyon turu", text: "Yapı, dil, süreklilik ve hassas içerik kontrollerini ayrı geçişlerde yap." },
    ],
    craftHeading: "Çocuk romanının asıl zanaatı: uzun anlatıda merakı ve çocuğun karar gücünü kaybetmemek",
    craftBody: "Bölümleri yalnız ‘sonunda sürpriz olsun’ diye kurma. Her bölüm kahramanın planını, ilişkisini veya bilgisini değiştirsin. Yetişkinler dünyada bulunsun ama ana araştırmayı, riski ve çözümü sürekli onların devralmasına izin verme.",
    extraSections: [
      { id: "yas-bolum", type: "cards", heading: "Yaş bandını bölüm mimarisine kadar taşı", items: [
        { title: "Bölüm uzunluğu", text: "Tek bir sabit sayı yoktur; hedef okurun okuma akışı ve sahne yoğunluğuyla birlikte değerlendir." },
        { title: "Hatırlatma", text: "Uzun aradan sonra dönen bilgi için doğal bağlam hatırlatması kullan." },
        { title: "İsim yükü", text: "Aynı anda çok sayıda yeni karakter ve terim tanıtma." },
      ]},
      { id: "bolum-motoru", type: "steps", heading: "Her bölümün küçük bir dramatik sözünü kur", items: [
        { title: "Soru", text: "Bölüm başında okur neyi merak ediyor?" },
        { title: "Değişim", text: "Bölüm sonunda bilgi, ilişki veya hedef nasıl değişiyor?" },
        { title: "Devam enerjisi", text: "Yeni soru doğal olarak bir sonraki bölümü çağırıyor mu?" },
      ]},
      { id: "sureklilik", type: "cards", heading: "Sürekliliği editörlük aşamasına bırakma", items: [
        { title: "Zaman", text: "Okul günü, hafta sonu, tatil ve gece-gündüz akışını kaydet." },
        { title: "Bilgi", text: "Karakterin henüz öğrenmediği şeyi biliyormuş gibi davranmasını önle." },
        { title: "Nesne", text: "Anahtar, telefon, mektup gibi olay nesnelerinin nerede olduğunu takip et." },
      ]},
      { id: "ajans-ve-yetiskin", type: "cards", heading: "Uzun anlatıda yetişkin yardımını sınırla", items: [
        { title: "Destek", text: "Yetişkin bilgi veya güvenlik sağlayabilir." },
        { title: "Seçim", text: "Ana ahlaki ve dramatik seçimi çocuk versin." },
        { title: "Sonuç", text: "Çocuğun kararının gerçek sonucu olsun; yetişkin her bedeli silmesin." },
      ]},
      { id: "zor-temalar", type: "cards", heading: "Uzun metinde zor temayı tek sahnede çözme", items: [
        { title: "İşleme süresi", text: "Kayıp, boşanma, zorbalık veya korkunun etkisi sonraki bölümlerde de sürsün." },
        { title: "Destek ağı", text: "Çocuğun güvenilir kişi ve kurumlarla ilişki kurabilmesini görünür kıl." },
        { title: "Sorumluluk", text: "Çocuğu yetişkin sorunlarının tek kurtarıcısı haline getirme." },
      ]},
      { id: "seri-potansiyeli", type: "cards", heading: "Seri düşünüyorsan ilk kitabı yarım bırakma", items: [
        { title: "Kitap yayı", text: "Ana duygusal ve dramatik problem ilk kitapta karşılık bulsun." },
        { title: "Açık kapı", text: "Dünya veya ilişki düzeyinde yeni soru bırakabilirsin." },
        { title: "Tekrar motoru", text: "Sonraki kitapta neyin doğal olarak yeniden üretilebileceğini tanımla." },
      ]},
    ],
    draftHeading: "İlk taslakta bölüm bölüm sona ulaş",
    draftIntro: "Orta bölümleri sürekli yeniden yazmak yerine bütün yayı gör.",
    draftItems: [
      { title: "Bölüm sözü", text: "Her bölüme başlamadan o bölümün değişimini tek cümlede yaz." },
      { title: "Sona işaret koy", text: "Eksik araştırma veya kelime için not bırakıp ilerle." },
      { title: "Orta kısmı geç", text: "Enerji düştüğünde yeni olay eklemek yerine hedef ve baskıyı netleştir." },
      { title: "Finale ulaş", text: "Romanın tamamını görmeden ilk üç bölümü sonsuz cilalama." },
    ],
    revisionHeading: "Çocuk romanını dört ayrı turda yeniden yaz",
    revisionIntro: "Uzun metinde her sorunu aynı anda çözmeye çalışma.",
    revisionItems: [
      { title: "Yapı turu", text: "Bölüm motoru ve ana arzu kesintisiz mi?" },
      { title: "Karakter turu", text: "İlişkiler ve çocuk ajansı gerçekten değişiyor mu?" },
      { title: "Süreklilik turu", text: "Zaman, bilgi ve nesne hatalarını temizle." },
      { title: "Okur turu", text: "Dil, duygusal yoğunluk ve bilgi yükü hedef okura uygun mu?" },
    ],
    projectName: "Mavi Apartmanın Çatı Katı",
    projectBody: "**Kahraman:** 11 yaşındaki Duru ve iki arkadaşı.\n\n**Motor:** Çatı katında buldukları her eşya, apartmandaki bir dairenin geçmişine açılır.\n\n**Ana hedef:** Binanın neden yıkılmak istendiğini ve eski ortak alanların neden kaybolduğunu anlamak.\n\n**Orta dönüş:** Çocuklar, Duru'nun dedesinin eski yönetim kurulunda olduğunu öğrenir.\n\n**Kriz:** Buldukları belgeleri yayımlamak apartmandaki bir komşunun mahremiyetini ihlal edecektir.\n\n**Final seçimi:** Belgeleri ifşa etmek yerine komşuları açık toplantıya çağıracak kanıtları seçerler.",
    projectCaption: "Mavi Apartmanın Çatı Katı, bölüm bölüm keşif motorunu daha büyük bir komşuluk ve etik seçime bağlar.",
    sampleHeading: "Örnek bölüm çıkışı: cevap + yeni soru",
    sampleBody: "Duru kasetin üzerine yazılmış tarihi deftere geçirdi: 14 Mayıs 1987. Tam kutuyu kapatırken kapağın iç tarafında kendi soyadını gördü. Bu kez çatıdaki sır başkasının ailesine ait değildi.",
    finalHeading: "Romanı paylaşmadan önce büyük resim kontrolü yap",
    finalIntro: "Bölümlerin tek tek iyi olması yetmez; bütün roman aynı sözü tutmalı.",
    finalItems: [
      { title: "Ana arzu", text: "Kahramanın hedefi ortada kayboluyor mu?" },
      { title: "Bölüm motoru", text: "Her bölüm sonuç ve yeni merak üretiyor mu?" },
      { title: "Ajans", text: "Final çözümünde çocuk karakter belirleyici mi?" },
      { title: "Süreklilik", text: "Zaman, bilgi ve eşya izleri temiz mi?" },
    ],
    outputsHeading: "Bu eğitimden beş somut çıktı ile çık",
    outputsIntro: "Roman fikrini bölüm üretmeye hazır hale getir.",
    outputItems: [
      { title: "1 okur kartı", text: "Dil, ton ve okuma bağlamını tanımla." },
      { title: "1 ana arzu", text: "Romanı taşıyan hedefi yaz." },
      { title: "1 bölüm motoru", text: "Her bölümün nasıl yeni soru üreteceğini tanımla." },
      { title: "10 bölüm özeti", text: "İlk on bölümün amaç ve sonuçlarını sırala." },
      { title: "1 açılış bölümü", text: "Çocuk bakışı ve ana problemi başlat." },
    ],
    mastersIntro: "Uzun çocuk anlatısında bölüm ritmi, karakter ajansı ve duygusal ciddiyeti birlikte taşıyan eserleri incele.",
    masters: [
      { title: "Michael Ende", text: "Çocuk okura açık fantastik dünyada büyük temaları küçümsemeden işleme biçimini incele." },
      { title: "Gülten Dayıoğlu", text: "Çocuk ve genç karakterleri toplumsal çevre, macera ve gelişim içinde kurma biçimine bak." },
      { title: "Katherine Paterson", text: "Dostluk, kayıp ve büyüme gibi ağır temaları çocuk bakışıyla işleme yöntemini incele." },
    ],
    faq: [
      { question: "Çocuk romanında bölüm ne kadar uzun olmalı?", answer: "Tek doğru uzunluk yoktur. Hedef okurun okuma akışı, sahne yoğunluğu ve bölümün dramatik işlevi birlikte belirler." },
      { question: "Yan hikâye kullanabilir miyim?", answer: "Evet; ana karakter yayı veya temayı desteklemeli ve okurun takip yükünü gereksiz artırmamalıdır." },
      { question: "Seri için açık final bırakabilir miyim?", answer: "Bırakabilirsin; ama ilk kitabın ana dramatik ve duygusal vaadi karşılık bulmalıdır." },
    ],
    finalCaption: "Çocuk romanı, uzun anlatı boyunca çocuğun merakını, karar gücünü ve duygusal yolunu kaybetmediğinde bütünleşir.",
    ctaHeading: "Çocuk romanının bölüm motorunu kur",
    ctaText: "Ana arzun ve ilk bölüm haritan hazırsa İlkOku Yazar Alanı'nda roman taslağını oluşturmaya başla.",
  },
  {
    category: "Çocuk ve Gençlik",
    slug: "genc-yetiskin",
    label: "Genç Yetişkin",
    title: "Genç Yetişkin Romanı Nasıl Yazılır?",
    description: "Genç özne ve kimlik çatışmasından ilişki, bağımsızlık, yüksek duygusal risk ve hassas tema revizyonuna kadar adım adım genç yetişkin yazarlığı eğitimi.",
    summary: "Genç karakteri yetişkinliğe geçişin nesnesi değil kendi kararlarının öznesi yap; kimlik, aidiyet, ilişki ve gelecek baskısını sahici bir genç bakışla anlat.",
    alts: alts("Genç Yetişkin", "Kırık Frekans"),
    orientationHeading: "Genç yetişkin anlatı, yalnız kahramanın yaşına değil bakış ve bağımsızlık mücadelesine dayanır",
    orientationBody: "YA metni yetişkin romanına genç karakter eklemek değildir. Aile, okul, arkadaşlık, aşk, gelecek ve kimlik kararları karakterin bugünkü hayatında yüksek risk taşır. Yetişkin anlatıcı geriye bakıp her şeyi çözmüş gibi konuşmamalı; belirsizlik karakter için gerçekten şimdi yaşanmalıdır.",
    ideaHeading: "YA fikrini kimlik ve bağımsızlık basıncından çıkar",
    ideaIntro: "Dış problem ile karakterin kim olacağı sorusunu aynı eksende buluştur.",
    ideaItems: [
      { title: "Gelecek eşiği", text: "Sınav, mezuniyet, taşınma veya meslek seçimi gibi geri dönüşsüz görünen karar seç." },
      { title: "Aidiyet", text: "Arkadaş grubu, aile, okul veya çevrimiçi topluluk arasında kalma gerilimi kur." },
      { title: "İlk büyük sınır", text: "Karakter ilk kez yetişkin otoritesine açıkça karşı çıkmak veya kendi sınırını koymak zorunda kalsın." },
      { title: "Saklanan gerçek", text: "Kimlik, aile geçmişi veya ilişki hakkında saklanan bilgi dış çatışmayı tetiklesin." },
    ],
    ideaFlowHeading: "Dış problemi kimlik seçimine bağla",
    ideaFlowBody: "‘Genç bir müzisyen yarışmaya hazırlanır’ temel durumdur. ‘Okul radyosunu kapatmamak için ulusal yarışmaya girmesi gereken 17 yaşındaki Ada, finale kalmak için yıllardır sakladığı işitme kaybını ekip arkadaşlarına açıklamak zorunda kalır’ gibi dış hedef ile kimlik ve güven çatışmasını aynı motora bağla.",
    contrastHeading: "YA anlatıyı çocuk ve yetişkin kurmacasından ayır",
    contrastIntro: "Sınır yalnız yaş etiketi değildir.",
    contrastItems: [
      { title: "YA ≠ çocuk romanı", text: "Bağımsızlık alanı, ilişki karmaşıklığı ve kimlik baskısı genellikle daha yoğun çalışır." },
      { title: "YA ≠ yetişkin romanı", text: "Gelecek seçimleri karakter için ilk kez ve şimdi yaşanan yüksek risklerdir; yetişkin geriye bakışı baskın değildir." },
      { title: "YA ≠ gençlik dersi", text: "Metin okura ‘doğru genç nasıl olunur’ anlatmak yerine karakterin çelişkisini yaşatır." },
    ],
    routeHeading: "YA romanını 9 aşamada kur",
    routeIntro: "Dış hedef, kimlik sorusu ve ilişki ağını birlikte planla.",
    routeItems: [
      { title: "1 · Genç özne", text: "Karakterin kendi isteğini ve başkasından devraldığı beklentiyi ayır." },
      { title: "2 · Kimlik sorusu", text: "Roman boyunca hangi ‘Ben kimim / kim olacağım?’ gerilimi çalışacak?" },
      { title: "3 · Dış hedef", text: "Somut ve ölçülebilir amacı belirle." },
      { title: "4 · İlişki ağı", text: "Arkadaş, aile, aşk, rakip ve yetişkin otoritesiyle farklı gerilimler kur." },
      { title: "5 · Sınır ihlali", text: "Karakter bir kuralı çiğner veya kendi sınırını ilk kez açıklar." },
      { title: "6 · Orta bedel", text: "İlk yöntem ciddi kayıp veya ilişki kırılması yaratsın." },
      { title: "7 · Kimlik seçimi", text: "Finale doğru karakter başkasının beklentisi ile kendi değeri arasında karar verir." },
      { title: "8 · İlk taslak", text: "Duygusal yoğunluğu ve olay akışını sona taşı." },
      { title: "9 · Hassasiyet revizyonu", text: "İlişki, ruh sağlığı, şiddet ve kimlik temsilini ayrıca gözden geçir." },
    ],
    structureHeading: "YA yapısını bağımsızlık kazanımı üzerinden kur",
    structureIntro: "Dış olaylar karakterin kendi hayatı üzerinde söz sahibi olma mücadelesini sıkıştırmalı.",
    structureItems: [
      { title: "Baskı alanı", text: "Aile, okul veya toplumun karakterden beklediğini kur." },
      { title: "Kendi arzusu", text: "Karakterin farklı istediği şeyi görünür kıl." },
      { title: "İlk kopuş", text: "Küçük ama geri alınması zor bir karar verdir." },
      { title: "Yeni aidiyet", text: "Arkadaşlık veya ilişki ağı alternatif kimlik alanı açsın." },
      { title: "Bedel", text: "Bağımsızlığın gerçek kaybı olsun." },
      { title: "Kriz", text: "Karakter hem dış hedef hem özsaygı arasında sıkışsın." },
      { title: "Kendi seçimi", text: "Final, yetişkin onayı almak değil kendi değerini eylemle seçmek üzerine kurulsun." },
    ],
    structureCaption: "YA yapısı, olay örgüsünü genç karakterin kimlik ve bağımsızlık kararlarıyla aynı çizgide ilerletir.",
    anatomyHeading: "YA anatomisi: şimdi duygusu, kimlik, ilişki ve güç",
    anatomyBody: "- **Genç özne:** Kendi arzusu var.\n- **Şimdi duygusu:** Sorun gelecekte küçülecek olsa bile bugün gerçektir.\n- **Kimlik:** Karakter kendini hangi adlarla tanımlıyor?\n- **Aidiyet:** Hangi gruba girmek veya hangi gruptan çıkmak istiyor?\n- **İlişki:** Arkadaşlık, aşk ve aile güç dengeleri.\n- **Otorite:** Yetişkinin gerçek gücü ve sınırı.\n- **Bedel:** Kararın sosyal, duygusal veya somut sonucu.\n- **Final seçimi:** Kendi hayatı üzerinde yeni söz hakkı.",
    practiceHeading: "YA yazarken beş izleme dosyası tut",
    practiceIntro: "Duygusal yoğunluğu klişe ve tutarsızlıktan koru.",
    practiceItems: [
      { title: "Arzu / beklenti", text: "Karakterin istediği ile ailesi/okulun beklediğini ayrı sütunlarda tut." },
      { title: "İlişki gücü", text: "Kim kimden ne istiyor, kim hangi bilgiyi veya statüyü kontrol ediyor?" },
      { title: "Dijital iz", text: "Mesaj, sosyal medya ve çevrimiçi kimlik olay örgüsünü etkiliyorsa sürekliliğini kaydet." },
      { title: "Hassas konu notu", text: "Ruh sağlığı, şiddet, cinsellik veya madde kullanımı varsa araştırma ve temsil risklerini yaz." },
      { title: "Ses sözlüğü", text: "Karakterin tekrar eden kelime, mizah ve düşünme biçimini takip et." },
    ],
    pageSetupCaption: "YA çalışma düzeni, dış hedefi kimlik ve ilişki güç dengeleriyle yan yana izler.",
    workspaceHeading: "YA taslağını olay kadar ilişki değişimiyle de takip et",
    workspaceIntro: "Kim kime ne kadar güveniyor ve bu hangi bölümde değişiyor, görünür kıl.",
    workspaceItems: [
      { title: "Bölüm duygu notu", text: "Sahnenin başı ve sonunda karakterin duygusal konumunu yaz." },
      { title: "Güç dengesi", text: "İlişkide karar hakkının kimde olduğunu takip et." },
      { title: "Ses kontrolü", text: "Yetişkin yazarın açıklaması genç karakterin sesini bastırıyor mu işaretle." },
      { title: "Gerçeklik kontrolü", text: "Okul, sınav, dijital platform veya kurum ayrıntılarını güncel tut." },
    ],
    craftHeading: "YA'nın asıl zanaatı: genç karakterin duygusunu küçümsemeden anlatıcı mesafesini korumak",
    craftBody: "‘Büyüyünce geçecek’ bilgisi yazarın sahip olduğu ama karakterin yaşamadığı bir üstünlüktür. Ayrılık, sınav, arkadaş grubu veya aile çatışması karakter için bugün gerçek risk taşımalıdır. Yazar bu duyguyu küçümsemeden, onu melodramatik garantiye de çevirmeden yazmalıdır.",
    extraSections: [
      { id: "genc-ses", type: "cards", heading: "Genç sesi argo listesi sanma", items: [
        { title: "Bakış", text: "Ses, karakterin neye dikkat ettiği ve neyi önemsemediğiyle kurulur." },
        { title: "Dil", text: "Güncel ifadeyi aşırı kullanmak metni hızlı eskitebilir." },
        { title: "Çelişki", text: "Karakter kendini olduğundan daha güçlü veya kayıtsız göstermeye çalışabilir." },
      ]},
      { id: "rizaya-dayali-iliski", type: "cards", heading: "Romantik ve cinsel ilişkilerde rıza ve güç farkını görünür kıl", items: [
        { title: "Rıza", text: "Sessizlik, baskı veya statü farkını otomatik onay gibi yazma." },
        { title: "Güç", text: "Yaş, öğretmenlik, iş, popülerlik veya ekonomik bağımlılık ilişkiyi etkileyebilir." },
        { title: "Sonuç", text: "Sınır ihlalini yalnız romantik yoğunluk olarak ödüllendirme." },
      ]},
      { id: "ruh-sagligi", type: "cards", heading: "Ruh sağlığı ve kriz temasında dramatik etki uğruna zarar üretme", items: [
        { title: "Tanı", text: "Belirtiyi gelişigüzel tanı etiketi olarak kullanma." },
        { title: "Kriz ayrıntısı", text: "Kendine zarar davranışını öğretici yöntem ayrıntısıyla anlatma." },
        { title: "Destek", text: "Yardım aramayı zayıflık veya anlatı cezası gibi çerçeveleme." },
      ]},
      { id: "dijital-hayat", type: "cards", heading: "Dijital hayatı yalnız telefon dekoru olarak kullanma", items: [
        { title: "Süreklilik", text: "Mesaj, ekran görüntüsü ve paylaşımın kim tarafından görüldüğünü takip et." },
        { title: "Mahremiyet", text: "Dijital ifşa ve zorbalığın gerçek sosyal sonucunu düşün." },
        { title: "Platform ömrü", text: "Markaya bağımlı ayrıntı yerine davranış mantığını önceliklendir." },
      ]},
      { id: "yetiskin-gucu", type: "cards", heading: "Yetişkin otoritesini ne şeytanlaştır ne görünmez yap", items: [
        { title: "Gerçek güç", text: "Aile, okul ve hukuk genç karakterin seçeneklerini gerçekten sınırlayabilir." },
        { title: "Destek yetişkini", text: "Her yetişkin düşman olmak zorunda değildir." },
        { title: "Ajans", text: "Destek alsa bile ana kararı genç karakter versin." },
      ]},
      { id: "tempo-duygu", type: "steps", heading: "Yüksek duyguyu sürekli zirvede tutma", items: [
        { title: "Baskı", text: "Gerilimi yükselt." },
        { title: "İşleme", text: "Karaktere sonucu hissetme ve ilişkiyi değerlendirme alanı ver." },
        { title: "Yeni karar", text: "Bir sonraki olay önceki duygusal sonuçtan doğsun." },
      ]},
      { id: "temsil-arastirma", type: "cards", heading: "Kimlik ve yaşam deneyiminde araştırma sorumluluğunu artır", items: [
        { title: "Tek örnek", text: "Bir kişinin deneyimini bütün kimliğe genelleme." },
        { title: "Birincil ses", text: "Mümkün olduğunda o deneyimi yaşayan kişilerin yazı ve anlatılarını oku." },
        { title: "Duyarlılık", text: "Yüksek riskli temsil alanında ek okur veya uzman geri bildirimi düşün." },
      ]},
    ],
    draftHeading: "İlk YA taslağında duyguyu sansürleme, yapıyı tamamla",
    draftIntro: "Karakterin yoğunluğunu koru ama her sahneyi aynı tonda yazma.",
    draftItems: [
      { title: "Şimdi kal", text: "Yetişkin anlatıcının ‘aslında önemsizdi’ bakışını metne sokma." },
      { title: "İlişkiyi eylemle göster", text: "Güven ve kırgınlığı yalnız iç monologla açıklama." },
      { title: "Bedeli gerçek bırak", text: "Zor kararın sonucu bir sonraki bölümde kaybolmasın." },
      { title: "Finali onay arayışına bağlama", text: "Karakterin değişimini yalnız ebeveyn veya öğretmen kabulüyle ölçme." },
    ],
    revisionHeading: "YA revizyonunu ses, güç ve hassasiyet turlarıyla yap",
    revisionIntro: "Olay örgüsü çalışsa bile temsil ve ilişki dengesi ayrıca kontrol ister.",
    revisionItems: [
      { title: "Ses testi", text: "Anlatıcı genç karakterin bilgisi ve duygusuyla tutarlı mı?" },
      { title: "Güç testi", text: "Romantik, ailevi ve kurumsal güç farkları görünür mü?" },
      { title: "Hassasiyet testi", text: "Kriz, şiddet veya ruh sağlığı dramatik araç gibi sömürülüyor mu?" },
      { title: "Final testi", text: "Karakter gerçekten kendi seçimini mi yapıyor?" },
    ],
    projectName: "Kırık Frekans",
    projectBody: "**Kahraman:** 17 yaşındaki Ada, okul radyosunun sunucusu ve müzik yarışması adayı.\n\n**Dış hedef:** Ulusal yarışmada finale kalıp okul radyosuna yeni stüdyo desteği kazanmak.\n\n**Gizli baskı:** Ada ilerleyen işitme kaybını yalnız ailesiyle paylaşmıştır.\n\n**İlişki gerilimi:** Ekip arkadaşı Mert onun kararlarını kontrol etmeye başladıkça destek ile sahiplenme arasındaki sınır bulanıklaşır.\n\n**Orta bedel:** Canlı yayında bir frekans hatası olur ve Ada suçu teknik ekibe atar.\n\n**Final seçimi:** Yarışma öncesi durumunu açıklayıp ekibin çalışma biçimini birlikte değiştirmek veya rolünü korumak için saklamaya devam etmek.",
    projectCaption: "Kırık Frekans, dış başarı hedefini kimlik, mahremiyet, ilişki gücü ve kendi sınırını koyma kararıyla birleştirir.",
    sampleHeading: "Örnek YA anı: duygu ile güç dengesini aynı sahnede göster",
    sampleBody: "Mert kulaklığını Ada'nın başından aldı. ‘Ben ayarlarım,’ dedi. Ada elini uzatmadı. Geçen hafta bu cümle rahatlatıcı gelmişti. Bugün, masadaki kendi mikrofonunun bile ona ait olmadığını düşündürdü.",
    finalHeading: "YA romanını paylaşmadan önce kapsamlı son kontrol yap",
    finalIntro: "Ses, ilişki ve hassas konu doğruluğunu olay örgüsü kadar ciddiye al.",
    finalItems: [
      { title: "Genç ses", text: "Karakter kendi dünyasını mı anlatıyor, yetişkin yazar mı açıklıyor?" },
      { title: "Ajans", text: "Ana seçim gerçekten genç karaktere mi ait?" },
      { title: "Güç ilişkileri", text: "Rıza, otorite ve bağımlılık sınırları görünür mü?" },
      { title: "Hassas içerik", text: "Ruh sağlığı, şiddet veya kimlik temsili araştırılmış ve sorumlu mu?" },
    ],
    outputsHeading: "Bu eğitimden beş somut çıktı ile çık",
    outputsIntro: "YA fikrini ses ve ilişki sistemiyle birlikte kur.",
    outputItems: [
      { title: "1 kimlik sorusu", text: "Karakterin roman boyunca cevap aradığı ‘Ben kimim?’ gerilimini yaz." },
      { title: "1 dış hedef", text: "Somut amacı belirle." },
      { title: "1 ilişki güç haritası", text: "Aile, arkadaş, aşk ve otorite ilişkilerini çıkar." },
      { title: "1 hassasiyet planı", text: "Araştırma ve temsil gerektiren konuları listele." },
      { title: "1 açılış bölümü", text: "Genç sesi ve bugünkü yüksek riski başlat." },
    ],
    mastersIntro: "Genç karakterin sesi, aidiyeti ve bağımsızlık mücadelesini farklı dönem ve bağlamlarda kuran eserleri incele.",
    masters: [
      { title: "S. E. Hinton", text: "Genç karakter sesinin sınıf, aidiyet ve grup çatışmasıyla nasıl kurulduğunu incele." },
      { title: "Angie Thomas", text: "Genç öznenin aile, toplum, kimlik ve kamusal baskı arasında karar alma biçimini incele." },
      { title: "John Green", text: "Yoğun duygu, mizah, ilişki ve genç anlatıcı sesinin ritmine bak; aynı zamanda idealizasyon risklerini eleştirel değerlendir." },
    ],
    faq: [
      { question: "YA için kahraman mutlaka lise çağında mı olmalı?", answer: "YA yayıncılık geleneklerinde genç kahraman merkezîdir; kesin sınırlar pazara göre değişebilir. Esas olan genç öznenin bugünkü kimlik ve bağımsızlık deneyimidir." },
      { question: "Aşk hikâyesi şart mı?", answer: "Hayır. Arkadaşlık, aile, kimlik, gelecek ve toplumsal aidiyet tek başına güçlü YA motorlarıdır." },
      { question: "Zor ve karanlık konular yazılabilir mi?", answer: "Evet; ancak yöntem ayrıntısı, romantizasyon, rıza, güç ve yardım arama temsili ayrıca dikkat ister." },
    ],
    finalCaption: "YA anlatı, genç karakterin bugünkü duygusunu ciddiye alıp kendi hayatı üzerinde gerçek karar alanı kurduğunda güçlenir.",
    ctaHeading: "YA romanının kimlik ve karar haritasını kur",
    ctaText: "Genç karakterinin dış hedefi ve kimlik sorusu hazırsa İlkOku Yazar Alanı'nda taslağını oluşturmaya başla.",
  },
  {
    category: "Çocuk ve Gençlik",
    slug: "egitici-cocuk-kitabi",
    label: "Eğitici Çocuk Kitabı",
    title: "Eğitici Çocuk Kitabı Nasıl Yazılır?",
    description: "Öğrenme hedefinden kavram sıralamasına, yaşa uygun açıklamadan doğruluk, etkinlik güvenliği ve görsel öğretime kadar adım adım eğitici çocuk kitabı eğitimi.",
    summary: "Dersi kitaba gizlemek yerine öğrenme yolunu tasarla; tek bir hedefi doğru bilgi, somut örnek, görsel açıklama ve güvenli uygulamayla çocuğun kendi keşfine dönüştür.",
    alts: alts("Eğitici Çocuk Kitabı", "Bir Damlanın Şehir Yolculuğu"),
    orientationHeading: "Eğitici çocuk kitabı bilgi yığını değil öğrenme deneyimidir",
    orientationBody: "Amaç çocuğa mümkün olan en çok bilgiyi vermek değildir. Kitap tek bir öğrenme hedefini seçer, ön bilgiyi hesaba katar, kavramları doğru sırayla açar ve çocuğun öğrendiğini yeni örneğe taşımasına yardım eder. Anlaşılır olmak doğruluktan vazgeçmek değildir.",
    ideaHeading: "Kitap fikrini öğrenme ihtiyacından çıkar",
    ideaIntro: "Önce konu başlığı değil, çocuğun kitap sonunda yapabileceği veya anlayabileceği şeyi yaz.",
    ideaItems: [
      { title: "Neden sorusu", text: "Yağmur neden yağar, köprü nasıl ayakta durur, arılar neden önemlidir gibi gözlenebilir soru seç." },
      { title: "Gündelik sistem", text: "Su, elektrik, çöp, ulaşım veya para gibi çocuğun çevresindeki sistemi aç." },
      { title: "Beceri", text: "Harita okumak, duygu adlandırmak veya güvenli internet davranışı gibi uygulanabilir hedef seç." },
      { title: "Yanlış kavrayış", text: "Çocukların sık yaptığı bir yanlış anlamayı araştırıp kitap motoruna dönüştür." },
    ],
    ideaFlowHeading: "Konuyu ölçülebilir öğrenme hedefine dönüştür",
    ideaFlowBody: "‘Su döngüsü kitabı’ yalnız konudur. ‘Okur kitap sonunda yağmur suyunun şehirde izlediği üç ana yolu açıklayabilecek ve bir yüzeyin suyu emip emmediğini gözlemle ayırt edebilecek’ ifadesi öğretim hedefidir. Bölüm ve görsel kararları bu hedeften çıkar.",
    contrastHeading: "Eğitici çocuk kitabını ders notundan ayır",
    contrastIntro: "Doğru bilgi tek başına iyi çocuk kitabı değildir.",
    contrastItems: [
      { title: "Eğitici kitap ≠ ders kitabı özeti", text: "Tek hedefe odaklanıp keşif, örnek ve soru ile öğrenme yolu kurar." },
      { title: "Eğitici kitap ≠ çocuk hikâyesine bilgi eklemek", text: "Kurgu kullanılsa bile bilgi ile olay birbirini gerçekten desteklemelidir." },
      { title: "Eğitici kitap ≠ basitleştirilmiş yetişkin makalesi", text: "Kavram sırası ve örnekler çocuk okurun ön bilgisine göre yeniden tasarlanır." },
    ],
    routeHeading: "Eğitici çocuk kitabını 9 aşamada kur",
    routeIntro: "Önce öğrenme hedefi ve doğruluk sistemi, sonra sayfa akışı.",
    routeItems: [
      { title: "1 · Hedef okur", text: "Yaş, okuma bağlamı ve ön bilgiyi tanımla." },
      { title: "2 · Öğrenme hedefi", text: "Kitap sonunda okurun ne anlayacağını veya yapacağını yaz." },
      { title: "3 · Kaynak havuzu", text: "Güvenilir ve güncel temel kaynakları topla." },
      { title: "4 · Kavram haritası", text: "Önce bilinmesi gereken ile sonra gelecek bilgiyi sırala." },
      { title: "5 · Somut örnek", text: "Her soyut kavrama gözlenebilir karşılık bul." },
      { title: "6 · Görsel plan", text: "Hangi bilginin metin, hangi bilginin çizim veya diyagramla daha iyi anlatılacağını seç." },
      { title: "7 · Etkinlik", text: "Varsa güvenli ve gerçekten hedefi pekiştiren uygulama tasarla." },
      { title: "8 · Çocuk okur testi", text: "Nerede anlam kaybı ve yanlış kavrayış oluştuğunu gözle." },
      { title: "9 · Uzman / doğruluk turu", text: "Bilgi, güvenlik ve güncelliği son kez doğrula." },
    ],
    structureHeading: "Öğrenmeyi bilinenden yeni kavrama doğru basamaklandır",
    structureIntro: "Sayfa sırası yalnız estetik değil bilişsel karardır.",
    structureItems: [
      { title: "Merak sorusu", text: "Çocuğun günlük deneyiminden giriş yap." },
      { title: "Ön bilgi", text: "Zaten bildiği şeyi hatırlat." },
      { title: "Yeni kavram", text: "Tek ana fikri açıkla." },
      { title: "Somut örnek", text: "Kavramı günlük olayla göster." },
      { title: "Karşı örnek", text: "Sınırı ve yanlış anlamayı görünür kıl." },
      { title: "Uygulama", text: "Çocuk kavramı kendi gözleminde kullansın." },
      { title: "Transfer", text: "Aynı fikri yeni duruma taşımasını iste." },
    ],
    structureCaption: "Eğitici çocuk kitabı, bilgiyi konu sırasıyla değil öğrenme basamaklarıyla düzenler.",
    anatomyHeading: "Eğitici çocuk kitabının anatomisi: hedef, doğruluk, somutlama ve transfer",
    anatomyBody: "- **Hedef okur:** Yaş ve ön bilgi.\n- **Öğrenme hedefi:** Kitap sonunda beklenen anlayış/beceri.\n- **Kaynak:** Doğrulanmış bilgi tabanı.\n- **Kavram sırası:** Önkoşul ve yeni bilgi ilişkisi.\n- **Somut örnek:** Soyut fikrin gözlenebilir karşılığı.\n- **Görsel:** Dekor değil bilgi taşıyıcısı.\n- **Etkinlik:** Güvenli uygulama.\n- **Transfer:** Öğrenileni yeni örnekte kullanma.",
    practiceHeading: "Eğitici kitap için beş üretim dosyası tut",
    practiceIntro: "Bilginin doğruluğu ile anlatım sadeliğini ayrı ayrı izlemek gerekir.",
    practiceItems: [
      { title: "Kaynak defteri", text: "Her temel iddianın güvenilir kaynağını ve tarihini kaydet." },
      { title: "Kavram haritası", text: "Hangi kavramın hangisine bağlı olduğunu çiz." },
      { title: "Yanlış anlama listesi", text: "Çocukların sık karıştırdığı noktaları araştır." },
      { title: "Görsel brief", text: "Her çizimin ne öğreteceğini tek cümlede belirt." },
      { title: "Test notu", text: "Çocuk okurun sorularını ve yanlış çıkarımlarını kaydet." },
    ],
    pageSetupCaption: "Eğitici kitap çalışma düzeni, kaynak, kavram sırası, görsel işlev ve çocuk testini aynı üretim sisteminde toplar.",
    workspaceHeading: "Metni kaynak ve sayfa işleviyle birlikte yönet",
    workspaceIntro: "Her sayfanın yalnız ne söylediğini değil ne öğrettiğini de yaz.",
    workspaceItems: [
      { title: "Sayfa amacı", text: "Her çift sayfanın tek öğrenme işlevini belirle." },
      { title: "Kaynak kodu", text: "İddiaları kaynak notuyla eşleştir." },
      { title: "Görsel görevi", text: "Çizimin dekor, örnek, karşılaştırma veya süreç açıklaması olduğunu işaretle." },
      { title: "Revizyon tarihi", text: "Hızla değişen bilim/teknoloji bilgisinde güncelleme ihtiyacını kaydet." },
    ],
    craftHeading: "Eğitici çocuk kitabının asıl zanaatı: basitleştirirken yanlışlaştırmamak",
    craftBody: "‘Çocuk anlamaz’ diye önemli koşulları silmek kavram yanılgısı yaratabilir. Önce bilimsel veya olgusal çekirdeği doğru anla; sonra ayrıntı düzeyini azalt, somut örnek ver ve gerekirse ‘şimdilik böyle düşünebilirsin’ gibi aşamalı açıklama kullan.",
    extraSections: [
      { id: "ogrenme-hedefi", type: "steps", heading: "Konuyu öğrenme hedefine dönüştür", items: [
        { title: "Fiil", text: "‘Öğrensin’ yerine açıklayabilsin, ayırt edebilsin, sıralayabilsin gibi gözlenebilir fiil seç." },
        { title: "Koşul", text: "Hangi örnek veya araçla yapacağını belirt." },
        { title: "Sınır", text: "Tek kitapta kaç hedefin gerçekçi olduğunu sınırla." },
      ]},
      { id: "kavram-sirasi", type: "cards", heading: "Bilgiyi mantıksal önkoşullara göre sırala", items: [
        { title: "Ön bilgi", text: "Yeni kavram için önce hangi fikir bilinmeli?" },
        { title: "Tek yeni yük", text: "Bir sayfada çok sayıda yeni terim açma." },
        { title: "Geri çağırma", text: "Önceki kavramı yeni örnekte tekrar kullandır." },
      ]},
      { id: "dogruluk-kaynak", type: "cards", heading: "Çocuk metninde kaynak disiplini yetişkin metninden daha az önemli değildir", items: [
        { title: "Birincil / güvenilir kaynak", text: "Sağlık, bilim ve güvenlik bilgisini blog zincirinden değil güvenilir kurumlardan doğrula." },
        { title: "Tarih", text: "Değişebilen bilgide kaynak ve revizyon tarihini kaydet." },
        { title: "Belirsizlik", text: "Bilimsel tartışmayı kesin gerçek diye kapatma." },
      ]},
      { id: "bilissel-yuk", type: "cards", heading: "Okurun çalışma belleğini gereksiz yükleme", items: [
        { title: "Terim sayısı", text: "Yeni kavramları parçalara böl." },
        { title: "Cümle", text: "Uzun tanımı örnek ve görselle paylaş." },
        { title: "Dekor", text: "Öğretici diyagramın yanına dikkat dağıtan gereksiz görsel kalabalık ekleme." },
      ]},
      { id: "etkinlik-guvenligi", type: "cards", heading: "Etkinlik ve deneyde güvenlik tasarımın parçasıdır", items: [
        { title: "Risk", text: "Isı, kesici araç, kimyasal, elektrik, alerjen veya dış mekân riski var mı kontrol et." },
        { title: "Yetişkin desteği", text: "Gerekli yerde açıkça yetişkin eşliği belirt." },
        { title: "Alternatif", text: "Ekipman veya erişim sorunu olan çocuk için daha güvenli eşdeğer yol düşün." },
      ]},
      { id: "gorsel-ogretim", type: "cards", heading: "Görseli süs değil öğretim aracı olarak briefle", items: [
        { title: "Süreç", text: "Zaman sırasını ok ve aşamalarla göstermek metinden daha iyi olabilir." },
        { title: "Ölçek", text: "Mikro/makro farkında ölçek ve oran yanılsamasını açıklığa kavuştur." },
        { title: "Etiket", text: "Görseldeki her etiket gerçekten gerekli ve okunabilir olsun." },
      ]},
      { id: "anlama-transfer", type: "steps", heading: "Ezberi değil transferi kontrol et", items: [
        { title: "Aynı örnek", text: "Çocuk anlatılan örneği tekrar edebiliyor mu?" },
        { title: "Yeni örnek", text: "Kavramı farklı durumda tanıyabiliyor mu?" },
        { title: "Kendi sorusu", text: "Öğrendiği fikirle yeni bir soru üretebiliyor mu?" },
      ]},
    ],
    draftHeading: "İlk taslakta önce öğrenme yolunu tamamla",
    draftIntro: "Bilgiyi süslemekten önce kavram sırasının çalıştığını gör.",
    draftItems: [
      { title: "Hedefi görünür tut", text: "Her bölümün öğrenme hedefine hizmet edip etmediğini işaretle." },
      { title: "Kaynağı erteleme", text: "Doğrulayamadığın bilgiyi ‘sonra bakarım’ diye kesin cümleyle bırakma." },
      { title: "Somut örnek ekle", text: "Her soyut açıklamadan sonra gözlenebilir örnek ara." },
      { title: "Etkinliği test et", text: "Gerçekte uygulanmamış etkinliği doğrudan yayıma bırakma." },
    ],
    revisionHeading: "Eğitici kitabı dört ayrı gözle revize et",
    revisionIntro: "Doğru, anlaşılır, güvenli ve ilgi çekici olma hedeflerini ayrı kontrol et.",
    revisionItems: [
      { title: "Uzman testi", text: "Bilgi doğru ve güncel mi?" },
      { title: "Çocuk testi", text: "Okur nerede yanlış anlıyor veya kopuyor?" },
      { title: "Görsel testi", text: "Çizim gerçekten açıklıyor mu, yalnız dekor mu?" },
      { title: "Güvenlik testi", text: "Etkinlik ve öneriler yaşa uygun ve güvenli mi?" },
    ],
    projectName: "Bir Damlanın Şehir Yolculuğu",
    projectBody: "**Hedef okur:** 9–11 yaş, bağımsız okuma.\n\n**Öğrenme hedefi:** Okur, yağmur suyunun şehirde toprağa emilme, yüzey akışı ve drenaj yolunu ayırt edebilecek.\n\n**Merak sorusu:** Aynı yağmur neden parkta kayboluyor ama asfaltta birikiyor?\n\n**Görsel plan:** İki kesit çizimi — park zemini ve asfalt sokak.\n\n**Etkinlik:** Yetişkin eşliğinde iki farklı yüzeye az miktarda su damlatıp emilimi gözleme.\n\n**Transfer:** Okur kendi sokağında suyun nereye gittiğini haritada işaretleyecek.",
    projectCaption: "Bir Damlanın Şehir Yolculuğu, tek öğrenme hedefini kaynak, görsel karşılaştırma ve güvenli gözlem etkinliğiyle birleştirir.",
    sampleHeading: "Örnek eğitici paragraf: basitleştir ama yanlışlaştırma",
    sampleBody: "Yağmur suyu her yüzeyde aynı davranmaz. Toprakta küçük boşluklardan aşağı süzülebilir; asfalt gibi geçirimsiz yüzeylerde ise çoğunlukla yüzeyde ilerler. Bu yüzden aynı yağmur parkta hızla kaybolurken sokakta su birikintisi oluşturabilir.",
    finalHeading: "Yayın öncesi doğruluk ve öğrenme kontrolü yap",
    finalIntro: "Çocuk kitabında yanlış bilgi yalnız editoryal değil öğrenme sorunudur.",
    finalItems: [
      { title: "Hedef", text: "Kitap sonunda beklenen öğrenme açık mı?" },
      { title: "Kaynak", text: "Temel iddialar güncel ve güvenilir kaynağa bağlı mı?" },
      { title: "Çocuk testi", text: "Gerçek okurda yanlış anlama noktaları gözlendi mi?" },
      { title: "Güvenlik", text: "Etkinlik ve öneriler risk açısından kontrol edildi mi?" },
    ],
    outputsHeading: "Bu eğitimden beş somut çıktı ile çık",
    outputsIntro: "Konuyu doğrudan üretilebilir öğrenme tasarımına dönüştür.",
    outputItems: [
      { title: "1 öğrenme hedefi", text: "Ölçülebilir fiille yaz." },
      { title: "1 kavram haritası", text: "Ön bilgi ve yeni kavram sırasını göster." },
      { title: "1 kaynak listesi", text: "Temel iddiaları güvenilir kaynaklarla eşleştir." },
      { title: "1 görsel brief", text: "En az üç görselin ne öğreteceğini yaz." },
      { title: "1 örnek çift sayfa", text: "Merak sorusu, açıklama ve uygulamayı tek akışta kur." },
    ],
    mastersIntro: "Bilgiyi çocuk için erişilebilir hale getirirken doğruluk ve görsel düşünmeyi koruyan eserleri incele.",
    masters: [
      { title: "David Macaulay", text: "Karmaşık sistemleri kesit, süreç ve görsel açıklamayla anlaşılır kılma biçimini incele." },
      { title: "Gail Gibbons", text: "Çocuk kurgu dışı kitaplarında kavram sıralaması, açıklık ve görsel destek kullanımını incele." },
      { title: "DK editoryal yaklaşımı", text: "Bilgiyi görsel hiyerarşi, kısa açıklama ve referans yapısıyla katmanlama biçimini eleştirel incele." },
    ],
    faq: [
      { question: "Eğitici kitapta hikâye kullanmalı mıyım?", answer: "Şart değil. Hikâye kullanıyorsan öğrenme hedefini gerçekten desteklemeli; bilgiyi yalnız dekor olarak taşımamalıdır." },
      { question: "Bilgiyi ne kadar basitleştirebilirim?", answer: "Ayrıntı düzeyini azaltabilirsin ama nedensellik veya temel doğruluğu bozacak kadar değil. Gerekirse aşamalı açıklama kullan." },
      { question: "Kaynakça çocuk kitabında gerekli mi?", answer: "Okura nasıl sunulacağı değişebilir; fakat yazar/editör üretim dosyasında temel iddiaların kaynak izi mutlaka tutulmalıdır." },
    ],
    finalCaption: "Eğitici çocuk kitabı, doğru bilgiyi çocuğun kendi gözlem ve düşünmesine dönüşen bir öğrenme yoluna çevirdiğinde değer kazanır.",
    ctaHeading: "İlk eğitici kitabının öğrenme hedefini kur",
    ctaText: "Hedef okurun, öğrenme hedefin ve kavram haritan hazırsa İlkOku Yazar Alanı'nda kitabının taslağını oluşturmaya başla.",
  },
];

export function getEducationGuideDefinition(slug: string): EducationGuideDefinition {
  const definition = definitions.find((item) => item.slug === slug);
  if (!definition) throw new Error(`Child and Youth education guide definition missing: ${slug}`);
  return definition;
}

export const YOUTH_GUIDE_DEFINITIONS = definitions;
