CREATE TABLE `BookIndexSource` (
  `id` CHAR(36) NOT NULL,
  `code` VARCHAR(40) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `marketCode` VARCHAR(16) NOT NULL,
  `countryCode` CHAR(2) NOT NULL,
  `baseUrl` VARCHAR(500) NOT NULL,
  `includeInTurkeyIndex` BOOLEAN NOT NULL DEFAULT false,
  `status` ENUM('active','paused','blocked') NOT NULL DEFAULT 'active',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `BookIndexSource_code_key`(`code`),
  INDEX `BookIndexSource_marketCode_status_idx`(`marketCode`, `status`),
  INDEX `BookIndexSource_includeInTurkeyIndex_status_idx`(`includeInTurkeyIndex`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BookIndexList` (
  `id` CHAR(36) NOT NULL,
  `sourceId` CHAR(36) NOT NULL,
  `code` VARCHAR(80) NOT NULL,
  `title` VARCHAR(180) NOT NULL,
  `categoryKey` VARCHAR(120) NOT NULL DEFAULT 'general',
  `period` ENUM('live','daily','weekly','monthly','yearly') NOT NULL,
  `sourceUrl` VARCHAR(1000) NOT NULL,
  `maxRank` SMALLINT UNSIGNED NULL,
  `includeInComposite` BOOLEAN NOT NULL DEFAULT false,
  `collectionEveryMinutes` SMALLINT UNSIGNED NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `BookIndexList_sourceId_code_key`(`sourceId`, `code`),
  INDEX `BookIndexList_sourceId_active_period_idx`(`sourceId`, `active`, `period`),
  INDEX `BookIndexList_categoryKey_period_active_idx`(`categoryKey`, `period`, `active`),
  INDEX `BookIndexList_includeInComposite_active_idx`(`includeInComposite`, `active`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BookIndexList_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `BookIndexSource`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BookIndexBook` (
  `id` CHAR(36) NOT NULL,
  `slug` VARCHAR(260) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `normalizedTitle` VARCHAR(300) NOT NULL,
  `authorName` VARCHAR(220) NULL,
  `normalizedAuthor` VARCHAR(220) NULL,
  `publisherName` VARCHAR(220) NULL,
  `isbn13` CHAR(13) NULL,
  `isbn10` CHAR(10) NULL,
  `coverUrl` VARCHAR(1000) NULL,
  `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `BookIndexBook_slug_key`(`slug`),
  UNIQUE INDEX `BookIndexBook_isbn13_key`(`isbn13`),
  UNIQUE INDEX `BookIndexBook_isbn10_key`(`isbn10`),
  INDEX `BookIndexBook_normalizedTitle_idx`(`normalizedTitle`),
  INDEX `BookIndexBook_normalizedAuthor_idx`(`normalizedAuthor`),
  INDEX `BookIndexBook_lastSeenAt_idx`(`lastSeenAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BookIndexExternalBook` (
  `id` CHAR(36) NOT NULL,
  `sourceId` CHAR(36) NOT NULL,
  `sourceKey` VARCHAR(255) NOT NULL,
  `sourceExternalId` VARCHAR(180) NULL,
  `title` VARCHAR(300) NOT NULL,
  `normalizedTitle` VARCHAR(300) NOT NULL,
  `authorName` VARCHAR(220) NULL,
  `normalizedAuthor` VARCHAR(220) NULL,
  `publisherName` VARCHAR(220) NULL,
  `isbn13` CHAR(13) NULL,
  `isbn10` CHAR(10) NULL,
  `productUrl` VARCHAR(1200) NOT NULL,
  `imageUrl` VARCHAR(1200) NULL,
  `masterBookId` CHAR(36) NULL,
  `matchStatus` ENUM('unmatched','auto_matched','manual_matched','rejected') NOT NULL DEFAULT 'unmatched',
  `matchConfidence` DOUBLE NULL,
  `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `BookIndexExternalBook_sourceId_sourceKey_key`(`sourceId`, `sourceKey`),
  INDEX `BookIndexExternalBook_sourceId_matchStatus_lastSeenAt_idx`(`sourceId`, `matchStatus`, `lastSeenAt`),
  INDEX `BookIndexExternalBook_masterBookId_lastSeenAt_idx`(`masterBookId`, `lastSeenAt`),
  INDEX `BookIndexExternalBook_isbn13_idx`(`isbn13`),
  INDEX `BookIndexExternalBook_normalizedTitle_normalizedAuthor_idx`(`normalizedTitle`, `normalizedAuthor`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BookIndexExternalBook_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `BookIndexSource`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BookIndexExternalBook_masterBookId_fkey` FOREIGN KEY (`masterBookId`) REFERENCES `BookIndexBook`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BookIndexFetchRun` (
  `id` CHAR(36) NOT NULL,
  `listId` CHAR(36) NOT NULL,
  `status` ENUM('running','success','no_change','partial','failed') NOT NULL DEFAULT 'running',
  `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completedAt` DATETIME(3) NULL,
  `itemsFound` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `itemsStored` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `fingerprint` CHAR(64) NULL,
  `errorCode` VARCHAR(80) NULL,
  `errorMessage` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `BookIndexFetchRun_listId_startedAt_idx`(`listId`, `startedAt`),
  INDEX `BookIndexFetchRun_status_startedAt_idx`(`status`, `startedAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BookIndexFetchRun_listId_fkey` FOREIGN KEY (`listId`) REFERENCES `BookIndexList`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BookIndexObservation` (
  `id` CHAR(36) NOT NULL,
  `fetchRunId` CHAR(36) NOT NULL,
  `externalBookId` CHAR(36) NOT NULL,
  `rank` SMALLINT UNSIGNED NOT NULL,
  `priceAmount` BIGINT UNSIGNED NULL,
  `currency` CHAR(3) NULL,
  `observedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `BookIndexObservation_fetchRunId_externalBookId_key`(`fetchRunId`, `externalBookId`),
  INDEX `BookIndexObservation_fetchRunId_rank_idx`(`fetchRunId`, `rank`),
  INDEX `BookIndexObservation_externalBookId_observedAt_idx`(`externalBookId`, `observedAt`),
  INDEX `BookIndexObservation_observedAt_idx`(`observedAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BookIndexObservation_fetchRunId_fkey` FOREIGN KEY (`fetchRunId`) REFERENCES `BookIndexFetchRun`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BookIndexObservation_externalBookId_fkey` FOREIGN KEY (`externalBookId`) REFERENCES `BookIndexExternalBook`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
