CREATE TABLE `EmailDelivery` (
  `id` CHAR(36) NOT NULL,
  `channel` VARCHAR(32) NOT NULL,
  `deliveryMode` ENUM('local', 'smtp') NOT NULL,
  `status` ENUM('pending', 'sent', 'failed') NOT NULL DEFAULT 'pending',
  `fromAddress` VARCHAR(320) NOT NULL,
  `fromName` VARCHAR(120) NOT NULL,
  `replyTo` VARCHAR(320) NOT NULL,
  `toAddress` VARCHAR(320) NOT NULL,
  `subject` VARCHAR(500) NOT NULL,
  `template` VARCHAR(120) NOT NULL,
  `providerMessageId` VARCHAR(500) NULL,
  `failureCode` VARCHAR(120) NULL,
  `failureMessage` VARCHAR(1000) NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 1,
  `attemptedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `sentAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  INDEX `EmailDelivery_status_createdAt_idx`(`status`, `createdAt`),
  INDEX `EmailDelivery_deliveryMode_createdAt_idx`(`deliveryMode`, `createdAt`),
  INDEX `EmailDelivery_channel_createdAt_idx`(`channel`, `createdAt`),
  INDEX `EmailDelivery_template_createdAt_idx`(`template`, `createdAt`),
  INDEX `EmailDelivery_toAddress_createdAt_idx`(`toAddress`, `createdAt`),
  INDEX `EmailDelivery_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
