export const softContractDraftCatalog = [
  {
    area: "Ortak",
    code: "SOFT_GENERAL_NDA",
    title: "Genel Gizlilik ve Eser Bilgisi Koruma Taslağı",
    targetRole: "any",
    reason: "Eser, dosya, editoryal not veya yayın görüşmesi sırasında paylaşılan kamuya açık olmayan bilgileri korumak için.",
    trigger: "Özel dosya veya yayınlanmamış eser içeriği kullanıcıyla paylaşılmadan önce.",
  },
  {
    area: "Yazar",
    code: "SOFT_WRITER_PLATFORM_LICENSE",
    title: "Yazar Eser Yayınlama ve Platform Lisansı Taslağı",
    targetRole: "writer",
    reason: "Yazarın eserin hak sahibi olduğunu beyan etmesi ve İlkOku üzerinde gösterim için sınırlı platform izninin çerçevesini belirlemek için.",
    trigger: "Eserin platformda yayınlanması veya görünür hale getirilmesi öncesinde.",
  },
  {
    area: "Yazar",
    code: "SOFT_WRITER_EDITOR_REVIEW",
    title: "Editör İnceleme Süreci Onay Taslağı",
    targetRole: "writer",
    reason: "Eserin bağımsız editörlerce okunması, notlanması ve değerlendirme sonucunun yazara iletilmesi sürecini açıklaştırmak için.",
    trigger: "Yazar editör incelemesi talep ettiğinde.",
  },
  {
    area: "Editör",
    code: "SOFT_EDITOR_REVIEW_ETHICS",
    title: "Editör İnceleme, Gizlilik ve Tarafsızlık Taslağı",
    targetRole: "editor",
    reason: "Editörün eriştiği yayınlanmamış eserleri koruması, çıkar çatışmasını bildirmesi ve bağımsız değerlendirme yapması için.",
    trigger: "Editör ilk kez inceleme havuzuna veya yayınevi editör talebine erişmeden önce.",
  },
  {
    area: "Editör",
    code: "SOFT_EDITOR_CANDIDATE_NDA",
    title: "Editör Adayı ve Dış Editör Gizlilik Taslağı",
    targetRole: "editor_pending",
    reason: "Henüz tam editör rolü verilmemiş aday veya davetli kişinin sınırlı erişim sırasında gördüğü eser ve kullanıcı bilgisini korumak için.",
    trigger: "Editör adayı veya dış editör daveti üzerinden içerik erişimi verilmeden önce.",
  },
  {
    area: "Yayınevi",
    code: "SOFT_PUBLISHER_DISCOVERY_NDA",
    title: "Yayınevi Eser Keşif ve Gizlilik Taslağı",
    targetRole: "publisher",
    reason: "Yayınevinin keşif, paylaşım ve başvuru akışlarında gördüğü eser/yazar bilgisini yalnız değerlendirme amacıyla kullanmasını çerçevelemek için.",
    trigger: "Yayınevine yayınlanmamış veya sınırlı erişimli eser/dosya gösterilmeden önce.",
  },
  {
    area: "Yayınevi",
    code: "SOFT_PUBLISHER_TEAM_CONFIDENTIALITY",
    title: "Yayınevi Ekip Yetki ve Gizlilik Taahhüdü Taslağı",
    targetRole: "publisher",
    reason: "Yayınevi ekip üyelerinin kişi bazlı yetkileri, dosya erişimi ve kurum içi paylaşım sorumluluğunu görünür hale getirmek için.",
    trigger: "Yayınevi ekip üyesine eser, dosya, editör talebi veya sözleşme verisi erişimi verildiğinde.",
  },
  {
    area: "Yayın Ön Mutabakatı",
    code: "SOFT_PUBLICATION_INTENT_WRITER",
    title: "Yazar Yayın Niyeti ve Ön Mutabakat Taslağı",
    targetRole: "writer",
    reason: "Bir yayınevi ile somut yayın sürecine geçmeden önce kapsam, takvim ve müzakere başlıklarını bağlayıcı nihai telif devri oluşturmadan kayda almak için.",
    trigger: "Yayınevi eseri değerlendirdikten sonra yayın planı konuşulmaya başlandığında.",
  },
  {
    area: "Yayın Ön Mutabakatı",
    code: "SOFT_PUBLICATION_INTENT_PUBLISHER",
    title: "Yayınevi Yayın Niyeti ve Ön Mutabakat Taslağı",
    targetRole: "publisher",
    reason: "Yayınevinin yayın niyetini, planlama sorumluluklarını ve nihai sözleşmeden önce açık kalan ticari/hukuki başlıkları kayıt altına almak için.",
    trigger: "Yayın planı oluşturulmadan veya üretim aşamasına geçilmeden önce.",
  },
] as const;

export const softContractDraftCodes = new Set(softContractDraftCatalog.map((item) => item.code));
