import { commonContent } from "./navigation";

export const authContent = {
  common: {
    skipToContent: commonContent.skipToContent,
    homeLabel: commonContent.homeLabel,
    tagline: commonContent.tagline,
    quote: "İyi bir hikâyenin ilk adımı, kendine ait bir yer bulmaktır.",
    secureAuthentication: "Güvenli kimlik doğrulama",
    email: "E-posta",
    emailPlaceholder: "ornek@ilkoku.com",
    password: "Şifre",
    logout: "Çıkış Yap",
    shortLogout: "Çıkış",
    roleAccount: (role: string) => `${role} hesabı`,
    profilePhoto: (name: string) => `${name} profil fotoğrafı`,
    profilePlaceholder: (name: string) => `${name} için profil yer tutucusu`,
    fallbackUserName: "İlkOku kullanıcısı",
  },
  shell: {
    contentArea: (title: string) => `${title} alanı`,
  },
  login: {
    metadataTitle: "Giriş Yap | İlkOku",
    metadataDescription: "İlkOku hesabına giriş yap ve hikâyene devam et.",
    eyebrow: "Yolculuğuna devam et",
    title: "Hikâyen seni bekliyor.",
    description: "Eserlerine, okuma listene ve İlkOku topluluğuna yeniden bağlan.",
    cardEyebrow: "Tekrar hoş geldin",
    cardTitle: "Hesabına giriş yap",
    cardDescription: "Yazmaya veya okumaya kaldığın yerden devam et.",
    passwordPlaceholder: "Şifreni gir",
    rememberMe: "Beni hatırla",
    forgotPassword: "Şifremi unuttum",
    submit: "Giriş Yap",
    noAccount: "Hesabın yok mu?",
    createAccount: "Hesap oluştur",
  },
  register: {
    metadataTitle: "Hesap Oluştur | İlkOku",
    metadataDescription: "İlkOku topluluğuna katıl ve hikâyene yer aç.",
    eyebrow: "İlk cümlene yer aç",
    title: "Burada herkesin bir hikâyesi var.",
    description: "Okur, yazar, editör veya yayınevi olarak İlkOku deneyimine katıl.",
    cardEyebrow: "İlk adım",
    cardTitle: "Hesabını oluştur",
    cardDescription: "E-posta adresini doğruladıktan sonra rolünü seçebilirsin.",
    fullName: "Ad Soyad",
    fullNamePlaceholder: "Adın ve soyadın",
    passwordPlaceholder: "En az 8 karakter, harf ve sayı",
    passwordConfirmation: "Şifre Tekrar",
    passwordConfirmationPlaceholder: "Şifreni yeniden gir",
    terms: "Devam ederek kullanım koşullarını ve gizlilik politikasını kabul etmiş olursun.",
    submit: "Devam",
    hasAccount: "Zaten hesabın var mı?",
    login: "Giriş yap",
  },
  forgotPassword: {
    metadataTitle: "Şifremi Unuttum | İlkOku",
    metadataDescription: "İlkOku şifren için güvenli yenileme bağlantısı iste.",
    eyebrow: "Güvenli dönüş",
    title: "Hesabına yeniden ulaş.",
    description: "E-posta adresini gir; güvenli bağlantıyla şifreni yenile.",
    cardEyebrow: "Hesap kurtarma",
    cardTitle: "Şifreni yenile",
    cardDescription:
      "Hesabına bağlı e-posta adresine güvenli bir yenileme bağlantısı göndereceğiz.",
    submit: "Yenileme Bağlantısı Gönder",
    backToLogin: "Giriş ekranına dön",
  },
  updatePassword: {
    metadataTitle: "Yeni Şifre | İlkOku",
    metadataDescription: "İlkOku hesabın için yeni bir şifre belirle.",
    eyebrow: "Son adım",
    title: "Yeni şifreni belirle.",
    description: "Güçlü ve yalnızca bu hesapta kullandığın bir şifre seç.",
    cardEyebrow: "Yeni şifre",
    cardTitle: "Güvenliğini yenile",
    cardDescription: "En az 8 karakter, bir harf ve bir sayı kullan.",
    password: "Yeni Şifre",
    passwordPlaceholder: "Yeni şifren",
    confirmation: "Yeni Şifre Tekrar",
    confirmationPlaceholder: "Yeni şifreni yeniden gir",
    submit: "Şifreyi Güncelle",
  },
  roleSelection: {
    metadataTitle: "Rolünü Seç | İlkOku",
    metadataDescription: "İlkOku deneyimindeki rolünü seç ve çalışma alanını önizle.",
    eyebrow: "Sana ait bir başlangıç",
    title: "İlkOku'da seni nasıl görmek isteriz?",
    description: "Rolünü seç; çalışma alanının sana nasıl görüneceğini hemen önizle.",
    legend: "İlkOku rolünü seç",
    previewEyebrow: "Seçiminin önizlemesi",
    changeLater: "Rolünü daha sonra profil ayarlarından değiştirebilirsin.",
    options: [
      {
        id: "reader",
        icon: "📖",
        title: "Okur",
        description: "Yeni hikâyeler keşfet, bölümleri oku ve yazarlara görüşlerini ilet.",
        previewTitle: "Okur keşif alanı",
        previewDescription:
          "İlgini çeken eserleri takip et, kaldığın yerden okumaya devam et ve düşüncelerini paylaş.",
        highlights: ["Kişisel okuma listesi", "Yeni bölüm takibi", "Yazar geri bildirimleri"],
        href: "/kitap/kayip-sehir",
        actionLabel: "Okur görünümünü keşfet",
      },
      {
        id: "writer",
        icon: "✍️",
        title: "Yazar",
        description: "Eserini oluştur, bölümlerini geliştir ve ilk okurlarınla buluş.",
        previewTitle: "Yazar çalışma alanı",
        previewDescription:
          "Günlük hedefini takip et, eserlerine devam et ve okur geri bildirimlerini tek yerde gör.",
        highlights: ["Odaklı yazma editörü", "Eser gelişim takibi", "Okur ve editör görüşleri"],
        href: "/yazar",
        actionLabel: "Yazar paneline geç",
      },
      {
        id: "editor",
        icon: "📝",
        title: "Editör",
        description: "Uzmanlığını paylaş, eserleri değerlendir ve yazarların gelişimine eşlik et.",
        previewTitle: "Editör çalışma alanı",
        previewDescription:
          "Uzmanlık profilini görünür kıl, değerlendirme taleplerini incele ve yazarlara yol göster.",
        highlights: ["Mesleki profil", "Değerlendirme talepleri", "Yazar iletişimi"],
        href: "/editörler",
        actionLabel: "Editör rolü talep et",
      },
      {
        id: "publisher",
        icon: "🏢",
        title: "Yayınevi",
        description: "Yeni yazarları gelişim, okur ve editör verileriyle keşfet.",
        previewTitle: "Yayınevi çalışma alanı",
        previewDescription:
          "Popülerliğin ötesine geç, eser potansiyelini dengeli verilerle değerlendir.",
        highlights: ["Gelişim odaklı keşif", "İnceleme listesi", "Yazar iletişim talepleri"],
        href: "/yayinevi",
        actionLabel: "Yayınevi rolü talep et",
      },
    ],
  },
  accessDenied: {
    metadataTitle: "Erişim Reddedildi | İlkOku",
    metadataDescription: "Bu İlkOku alanına erişmek için hesabında uygun rol bulunmalıdır.",
    eyebrow: "Güvenli alan",
    title: "Bu alana erişemezsin.",
    description:
      "Hesabındaki rol veya onay durumu bu çalışma alanıyla eşleşmiyor. Rol seçimine dönerek uygun rolü seçebilir ya da onay talebi oluşturabilirsin.",
    cardEyebrow: "Yetki kontrolü",
    cardTitle: "Erişim reddedildi",
    cardDescription: "İçeriğin ve hesap güvenliğin için rol tabanlı erişim uygulanıyor.",
    roleSelection: "Rol seçimine dön",
    home: commonContent.homeAction,
  },
  roles: {
    editor: "Editör",
    publisher: "Yayınevi",
    reader: "Okur",
    writer: "Yazar",
  },
} as const;
