import { commonContent } from "./navigation";

export const dashboardContent = {
  metadataTitle: "Yazar Paneli | İlkOku",
  metadataDescription: "Eserlerini ve günlük yazma hedefini yönet.",
  eyebrow: "Yazar Paneli",
  greeting: "Günaydın, Ersin",
  newWork: "Yeni Eser",
  dailyGoal: "Bugünkü Yazma Hedefi",
  wordUnit: "Kelime",
  dailyGoalLabel: "Bugünkü yazma hedefi",
  dailyGoalTarget: 1000,
  latestWorkTitle: "Son çalışılan eser",
  originalNovel: "Bir İlkOku Romanı",
  brandName: commonContent.brandName,
  lastEdited: "Son düzenleme",
  progress: "İlerleme",
  continue: "Devam Et",
  writingSummary: "Yazma özeti",
  fromEditors: "Editörlerinden",
  latestFeedback: "Son Geri Bildirimler",
  newSuffix: "yeni",
  library: "Kütüphanen",
  myWorks: "Eserlerim",
  workSuffix: "eser",
  emptyWorksTitle: "Henüz bir eserin yok.",
  emptyWorksDescription: "İlk eserini oluşturduğunda burada görünecek.",
  emptyFeedback: "Henüz bekleyen editör geri bildirimi yok.",
  chapterSuffix: "bölüm",
  wordSuffix: "kelime",
  archive: "Arşivle",
  edit: "Düzenle",
  statusLabels: {
    archived: "Arşivlendi",
    completed: "Tamamlandı",
    draft: "Taslak",
    in_progress: "Devam ediyor",
    published: "Yayınlandı",
  },
  dailySummary: "Günlük özet",
  motivationTitle: "Bugünün Motivasyonu",
  motivation: "Küçük bir bölüm de ilerlemedir.",
  streakTitle: "Yazma Serisi",
  streak: "8 Gün",
  streakMessage: "Ritmini koruyorsun.",
  feedbackListLabel: "Son geri bildirimler",
} as const;
