import { commonContent } from "./navigation";
import { notificationContent } from "./notifications";

export const editorsContent = {
  metadataTitle: "Editörler | İlkOku",
  metadataDescription: "Eserini gerçek bir editörün deneyimiyle geliştir.",
  notFoundTitle: "Editör bulunamadı",
  profileDescription: (name: string) =>
    `${name} adlı editörün uzmanlıklarını ve değerlendirme yaklaşımını incele.`,
  homeLabel: commonContent.homeLabel,
  back: commonContent.back,
  defaultBackLabel: commonContent.homeAction,
  tools: "Editör sayfası araçları",
  directory: {
    skip: "Editör listesine geç",
    eyebrow: "Editoryal yol arkadaşın",
    title: "Editörler",
    description: "Eserini gerçek bir editörün deneyimiyle geliştir.",
    humanTitle: "İnsan değerlendirmesi",
    humanDescription: "Her değerlendirme, seçtiğin editör tarafından hazırlanır.",
    filterEyebrow: "Doğru eşleşmeyi bul",
    filtersTitle: "Filtreler",
    filters: [
      { label: "Uzmanlık alanı", values: ["Tüm uzmanlıklar", "Kurgu yapısı", "Dil ve üslup", "Karakter gelişimi", "Gerilim kurgusu"] },
      { label: "Deneyim seviyesi", values: ["Tüm seviyeler", "5–8 yıl", "9–12 yıl", "13 yıl ve üzeri"] },
      { label: "Değerlendirme türü", values: ["Tüm değerlendirmeler", "Genel dosya değerlendirmesi", "İlk bölüm değerlendirmesi", "Dil ve üslup değerlendirmesi"] },
      { label: "Uygunluk durumu", values: ["Tüm durumlar", "Yeni talep alıyor", "Sınırlı uygunluk", "Yakında uygun"] },
    ],
    listEyebrow: "Deneyim ve yaklaşım",
    listTitle: "Editörleri keşfet",
    editorSuffix: "editör",
    specialties: (name: string) => `${name} uzmanlık alanları`,
    experience: "Deneyim",
    review: "Değerlendirme",
    satisfaction: "Yazar memnuniyeti",
    years: "yıl",
    inspectProfile: "Profili İncele",
  },
  profile: {
    skip: "Editör profiline geç",
    backLabel: "Editörler sayfasına dön",
    eyebrow: "Editör profili",
    biographyEyebrow: "Mesleki yolculuk",
    biographyTitle: "Kısa biyografi",
    approachEyebrow: "Birlikte çalışma biçimi",
    approachTitle: "Değerlendirme yaklaşımı",
    topicsEyebrow: "Değerlendirme kapsamı",
    topicsTitle: "Örnek değerlendirme başlıkları",
    reviewsEyebrow: "Yazar deneyimleri",
    reviewsTitle: "Yazar yorumları",
    summaryLabel: "Editör uzmanlık ve deneyim özeti",
    experience: "Deneyim",
    completedReviews: "tamamlanan değerlendirme",
    specialties: "Uzmanlık alanları",
    genres: "Çalıştığı eser türleri",
    assuranceTitle: "Doğrudan editör değerlendirmesi",
    assuranceDescription:
      "Notların seçtiğin editör tarafından hazırlanır ve editoryal sorumluluk kendisine aittir.",
    allEditors: "← Tüm editörleri gör",
  },
  request: {
    trigger: "Değerlendirme Talep Et",
    closeLabel: "Talep penceresini kapat",
    eyebrow: "İlk adım",
    title: "Değerlendirme talebi",
    description: (name: string) =>
      `${name} ile çalışmak istediğin eseri ve beklentini paylaş.`,
    workLabel: "Eser seçimi",
    workPlaceholder: "Bir eser seç",
    works: ["Kayıp Şehir", "Gölgelerin Ardında", "Zamanın İzleri"],
    typeLabel: "Değerlendirme türü",
    typePlaceholder: "Bir değerlendirme seç",
    types: ["Genel dosya değerlendirmesi", "İlk bölüm değerlendirmesi", "Karakter ve kurgu değerlendirmesi", "Dil ve üslup değerlendirmesi"],
    expectationLabel: "Beklenti notu",
    expectationPlaceholder: "Editörün özellikle odaklanmasını istediğin konuları yaz.",
    deliveryLabel: "Tercih edilen teslim süresi",
    deliveryPlaceholder: "Bir süre seç",
    deliveryOptions: ["7 gün", "14 gün", "21 gün", "Esnek"],
    note: "Bu adım yalnızca talep önizlemesidir. Ödeme veya gerçek gönderim yapılmaz.",
    submit: notificationContent.request.submit,
    successEyebrow: notificationContent.request.ready,
    successTitle: "Değerlendirme talebin oluşturuldu.",
    successDescription:
      "Bu bir örnek akıştır; editöre bildirim veya eser gönderimi yapılmadı.",
    done: notificationContent.request.done,
  },
  data: [
    {
      id: "editor-1",
      slug: "merve-kaya",
      name: "Merve Kaya",
      initials: "MK",
      title: "Roman Editörü ve Yayın Danışmanı",
      experienceYears: 11,
      specialties: ["Kurgu yapısı", "Karakter gelişimi", "Anlatı ritmi"],
      genres: ["Roman", "Fantastik", "Polisiye", "Genç yetişkin"],
      completedReviews: 186,
      satisfaction: 98,
      availability: "Yeni talep alıyor",
      biography:
        "On bir yıldır yayınevleri ve bağımsız yazarlarla çalışan Merve, bir metnin özgün sesini koruyarak yapısını güçlendirmeye odaklanır. İlk taslaktan yayıma hazırlık aşamasına kadar farklı olgunluktaki eserlerle çalışır.",
      approach:
        "Önce yazarın niyetini ve eserin okurda bırakmak istediği duyguyu dinler. Ardından büyük resimden sahne düzeyine ilerleyen, gerekçeli ve uygulanabilir notlar hazırlar. Değerlendirmelerinde yazarın sesini değiştirmek yerine o sesi daha görünür kılmayı amaçlar.",
      sampleTopics: ["Açılış bölümünün anlatı vaadi", "Karakter motivasyonlarının tutarlılığı", "Orta bölümde tempo ve gerilim", "Finale hazırlanan dramatik eşikler"],
      authorReviews: [
        { id: "merve-review-1", author: "Ersin Uzun", work: "Kayıp Şehir", comment: "Merve’nin notları metnin kalbini değiştirmeden sorunlu bölümleri görmemi sağladı. Her önerisinin arkasında açık bir gerekçe vardı." },
        { id: "merve-review-2", author: "Selin Kara", work: "Gölgelerin Ardında", comment: "Karakter motivasyonlarına dair değerlendirmesi ikinci taslağın yönünü tamamen netleştirdi. Süreç boyunca çok dikkatli ve yapıcıydı." },
      ],
    },
    {
      id: "editor-2",
      slug: "baris-erdem",
      name: "Barış Erdem",
      initials: "BE",
      title: "Öykü ve Dil Editörü",
      experienceYears: 8,
      specialties: ["Dil ve üslup", "Öykü", "Diyalog"],
      genres: ["Öykü", "Edebî kurgu", "Deneme"],
      completedReviews: 142,
      satisfaction: 96,
      availability: "Sınırlı uygunluk",
      biography: "Kısa anlatılarda ses, ritim ve sözcük ekonomisi üzerine çalışır.",
      approach: "Metnin kendi dilini koruyan, satır düzeyinde açıklayıcı notlar sunar.",
      sampleTopics: ["Anlatıcı sesi", "Diyalog ritmi"],
      authorReviews: [],
    },
    {
      id: "editor-3",
      slug: "derya-unal",
      name: "Derya Ünal",
      initials: "DÜ",
      title: "Çocuk ve Gençlik Edebiyatı Editörü",
      experienceYears: 13,
      specialties: ["Yaşa uygunluk", "Dünya kurma", "Duygusal gelişim"],
      genres: ["Çocuk", "Genç yetişkin", "Fantastik"],
      completedReviews: 214,
      satisfaction: 99,
      availability: "Yakında uygun",
      biography: "Çocuk ve genç okurlar için güvenli, güçlü ve sahici anlatılar üzerine çalışır.",
      approach: "Okur yaşını, anlatı güvenliğini ve karakterlerin duygusal yolculuğunu birlikte değerlendirir.",
      sampleTopics: ["Okur yaşına uygunluk", "Duygusal eşikler"],
      authorReviews: [],
    },
    {
      id: "editor-4",
      slug: "kaan-sahin",
      name: "Kaan Şahin",
      initials: "KŞ",
      title: "Polisiye ve Gerilim Editörü",
      experienceYears: 9,
      specialties: ["Gerilim kurgusu", "İpucu dengesi", "Tempo"],
      genres: ["Polisiye", "Gerilim", "Gizem"],
      completedReviews: 129,
      satisfaction: 97,
      availability: "Yeni talep alıyor",
      biography: "Gizem örgüsünün adil, sürükleyici ve tutarlı çalışmasına odaklanır.",
      approach: "İpuçlarını, yanlış yönlendirmeleri ve dramatik gerilimi bölüm bölüm haritalandırır.",
      sampleTopics: ["İpucu dağılımı", "Gerilim eğrisi"],
      authorReviews: [],
    },
  ],
} as const;
