export const feedbackContent = {
  metadataTitle: "Geri Bildirimler | İlkOku",
  metadataDescription: "Editör geri bildirimlerini tek merkezden görüntüle ve yönet.",
  eyebrow: "Yazar Çalışma Alanı",
  title: "Geri Bildirimler",
  description: "Eserlerin için gerçek editörlerden gelen değerlendirmeleri takip et.",
  stats: {
    unread: "Okunmamış",
    total: "Toplam geri bildirim",
    important: "Önemli",
    archived: "Arşivlenmiş",
  },
  tabs: { unread: "Okunmamış", all: "Tümü", archived: "Arşiv" },
  filters: {
    work: "Eser",
    allWorks: "Tüm eserler",
    category: "Kategori",
    allCategories: "Tüm kategoriler",
    order: "Tarih sıralaması",
    newest: "En yeni",
    oldest: "En eski",
    importantOnly: "Yalnızca önemli olanları göster",
    area: "Geri bildirim filtreleri",
  },
  categories: {
    genel: "Genel",
    kurgu: "Kurgu",
    karakter: "Karakter",
    anlatım: "Anlatım",
    dil: "Dil",
    yapı: "Yapı",
    yayın_hazırlığı: "Yayın hazırlığı",
  },
  priority: { important: "Önemli", normal: "Normal" },
  status: { unread: "Okunmamış", read: "Okundu", archived: "Arşivlendi" },
  actions: {
    detail: "Detayı Gör",
    openWork: "Eseri Aç",
    openChapter: "Bölüme Git",
    markRead: "Okundu Olarak İşaretle",
    archive: "Arşivle",
    close: "Kapat",
    viewAll: "Tümünü Gör",
  },
  labels: {
    editorNote: "Editör Notu",
    generalReview: "Genel Değerlendirme",
    workGeneral: "Eser geneli",
    editor: "Editör",
    work: "Eser",
    chapter: "Bölüm",
    category: "Kategori",
    date: "Tarih",
    priority: "Öncelik",
    list: "Editör geri bildirimleri",
    loading: "Geri bildirimler yükleniyor…",
  },
  empty: {
    title: "Geri Bildirim Bulunamadı",
    description: "Henüz bir editör geri bildirimi almadınız.",
    filtered: "Seçtiğin filtrelerle eşleşen bir geri bildirim bulunmuyor.",
    dashboard: "Henüz editör geri bildirimi yok.",
  },
  errors: {
    load: "Geri bildirimler yüklenemedi. Lütfen daha sonra tekrar dene.",
    auth: "Bu işlem için yeniden giriş yapmalısın.",
    permission: "Bu geri bildirimi değiştirme yetkin yok.",
    update: "Geri bildirim durumu güncellenemedi.",
    create: "Geri bildirim oluşturulamadı.",
    invalid: "Geri bildirim bilgileri geçersiz.",
    retry: "Tekrar Dene",
  },
  success: {
    read: "Geri bildirim okundu olarak işaretlendi.",
    archived: "Geri bildirim arşivlendi.",
    created: "Geri bildirim yazara iletildi.",
  },
  dashboard: { eyebrow: "Editörlerinden", title: "Son Geri Bildirimler", unreadSuffix: "okunmamış" },
} as const;
