export { authContent } from "./auth";
export { dashboardContent } from "./dashboard";
export { editorsContent } from "./editors";
export { feedbackContent } from "./feedback";
export { commonContent, navigationContent } from "./navigation";
export { notificationContent } from "./notifications";
export { publisherContent } from "./publisher";
export { publishersContent } from "./publishers";
export { readingContent } from "./reading";
export { tr } from "./tr";
export { validationContent } from "./validation";
export { writerContent } from "./writer";
export { workspaceContent } from "./workspace";
