import { commonContent } from "./navigation";
import { notificationContent } from "./notifications";

export const publisherContent = {
  homeLabel: commonContent.homeLabel,
  back: commonContent.back,
  backLabel: "Önceki sayfaya dön",
  tools: "Yayınevi sayfası araçları",
  dashboard: {
    metadataTitle: "Yayınevi Paneli | İlkOku",
    metadataDescription: "Yeni yazarları gelişim ve gerçek okur verileriyle keşfedin.",
    skip: commonContent.skipToContent,
    eyebrow: "Potansiyeli görünür kılan çalışma alanı",
    title: "Yayınevi Paneli",
    description: "Yeni yazarları gerçek okur verileriyle keşfedin.",
    principleLabel: "Keşif yaklaşımı",
    principleTitle: "Verinin ötesinde hikâye",
    principleDescription:
      "Okunma sayısından önce gelişim, devamlılık ve editoryal potansiyel değerlendirilir.",
    summaryLabel: "Yayınevi özeti",
    filterEyebrow: "Odaklı keşif",
    filterTitle: "Eserleri filtreleyin",
    listEyebrow: "Gelişen dosyalar",
    listTitle: "Keşfedilecek eserler",
    shownSuffix: "eser gösteriliyor",
    completion: "Tamamlanma",
    chapter: "Bölüm",
    reads: "Okunma",
    comments: "Yorum",
    update: "Güncelleme",
    humanReview: "Gerçek editör değerlendirmesi",
    waitingReview: "Değerlendirme bekliyor",
    noReview: "Henüz editör görüşü bulunmuyor.",
    inspectWork: "Eseri İncele",
    filters: [
      { label: "Tür", values: ["Tüm türler", "Fantastik", "Edebî Roman", "Bilim Kurgu"] },
      { label: "Alt tür", values: ["Tüm alt türler", "Macera", "Aile", "Genç yetişkin"] },
      { label: "Tamamlanma durumu", values: ["Tüm durumlar", "%50 üzeri", "%75 üzeri", "Tamamlandı"] },
      { label: "Bölüm sayısı", values: ["Tüm uzunluklar", "1–10 bölüm", "11–20 bölüm", "21+ bölüm"] },
      { label: "Okur yorumu sayısı", values: ["Tüm eserler", "25+ yorum", "50+ yorum", "100+ yorum"] },
      { label: "Editör değerlendirmesi", values: ["Tümü", "Değerlendirmesi var", "Değerlendirme bekliyor"] },
      { label: "Son güncelleme", values: ["Her zaman", "Son 24 saat", "Son 7 gün", "Son 30 gün"] },
      { label: "Yükseliş durumu", values: ["Tüm gelişimler", "Düzenli gelişim", "Yükselişte", "Finale yaklaşıyor"] },
    ],
  },
  reviewList: {
    added: "İnceleme Listesinde",
    add: "İnceleme Listesine Ekle",
    status: (title: string) => `${title} inceleme listesine eklendi.`,
  },
  contact: {
    trigger: "Yazarla İletişim Talebi Oluştur",
    closeLabel: "İletişim talebi penceresini kapat",
    eyebrow: "Yazarla ilk temas",
    title: "İletişim talebi",
    description: (name: string) =>
      `${name} ile görüşme amacınızı ve ihtiyaç duyduğunuz materyali belirtin.`,
    typeLabel: "Talep türü",
    typePlaceholder: "Bir talep türü seçin",
    types: ["Tanışma görüşmesi", "Dosya inceleme görüşmesi", "Yayın süreci görüşmesi"],
    messageLabel: "Kısa mesaj",
    messagePlaceholder: "Eserde gördüğünüz potansiyeli ve görüşme amacınızı yazın.",
    materialLabel: "İstenen materyal",
    materialPlaceholder: "Bir materyal seçin",
    materials: ["Tam dosya", "İlk üç bölüm", "Karakter ve olay örgüsü özeti"],
    meetingLabel: "Tercih edilen görüşme şekli",
    meetingPlaceholder: "Bir görüşme şekli seçin",
    meetingOptions: ["Görüntülü görüşme", "Telefon görüşmesi", "Yazılı görüşme"],
    note: "Bu bir örnek akıştır. Gerçek mesaj veya materyal gönderilmez.",
    submit: notificationContent.request.submit,
    successEyebrow: notificationContent.request.ready,
    successTitle: "İletişim talebiniz oluşturuldu.",
    successDescription:
      "Bu örnek akışta yazara bildirim veya materyal talebi gönderilmedi.",
    done: notificationContent.request.done,
  },
  detail: {
    metadataTitle: "Kayıp Şehir İncelemesi | İlkOku",
    metadataDescription:
      "Kayıp Şehir eserinin gelişim, okur ve editör verilerini inceleyin.",
    summary:
      "Yüzyıllardır haritalardan silinmiş bir şehrin kapısı yeniden açılır. Aras, ailesinin sakladığı gerçeğe uzanan yolculukta eski bir yeminin izini sürer.",
    tagsLabel: "Tür ve etiketler",
    tags: ["Gizem", "Kadim sırlar"],
    firstChapter: "İlk Bölümü Oku",
    developmentSummary: "Eser gelişim özeti",
    developmentStatus: "Gelişim durumu",
    lastUpdate: "Son güncelleme",
    structureEyebrow: "Dosya yapısı",
    chaptersTitle: "Bölüm listesi",
    readerEyebrow: "Gerçek okur geri bildirimi",
    readerSignals: "Okur sinyalleri",
    editorExperience: "Roman Editörü · 12 yıl deneyim",
    editorName: "Merve Kaya",
    humanReview: "Gerçek editör değerlendirmesi",
    reviewTitle: "Dünya inşası güçlü; anlatının kalbi karakterlerde büyüyor.",
    review:
      "İlk bölümlerde kurulan atmosfer tutarlı. Aras’ın iç çatışması görünür oldukça keşif hikâyesi daha kişisel ve güçlü bir zemine oturuyor. Orta bölümlerde yan karakterlerin amaçları biraz daha belirginleştirilebilir.",
    inspectEditor: "Editör profilini incele →",
    author: "Yazar",
    authorBiography:
      "Kayıp şehirler ve insanın eve dönüş arzusunu anlatan romanlar yazıyor.",
    authorProfile: "Yazar profiline git →",
    balancedView: "Dengeli görünüm",
    development: "Gelişim",
    balanceNote:
      "Popülerlik verileri, eserin tamamlanma ve gelişim sinyalleriyle birlikte değerlendirilir.",
  },
  data: {
    summaries: [
      { label: "Yeni eserler", value: "24", note: "Bu hafta 7 yeni dosya" },
      { label: "İnceleme listesi", value: "6", note: "3 eser güçlü gelişimde" },
      { label: "Tamamlanan eserler", value: "9", note: "Yayına hazırlık için uygun" },
      { label: "İletişim talepleri", value: "2", note: "Yanıt bekleyen görüşme" },
    ],
    works: [
      {
        slug: "kayip-sehir", title: "Kayıp Şehir", author: "Ersin Uzun", genre: "Fantastik Roman", subgenre: "Macera", completion: 68, chapters: 18, reads: "12,8 bin", comments: 124, updatedAt: "Bugün, 09.40", momentum: "Düzenli gelişim", potential: "Güçlü anlatı potansiyeli", coverVariant: "hero",
        editorReview: { editor: "Merve Kaya", summary: "Dünya inşası güçlü, karakter motivasyonu belirginleşiyor." },
      },
      {
        slug: "sessiz-kiyilar", title: "Sessiz Kıyılar", author: "Lale Deniz", genre: "Edebî Roman", subgenre: "Aile", completion: 92, chapters: 24, reads: "7,4 bin", comments: 86, updatedAt: "Dün", momentum: "Finale yaklaşıyor", potential: "Tutarlı karakter gelişimi", coverVariant: "one",
        editorReview: { editor: "Barış Erdem", summary: "Sessiz gerilim ve aile dinamikleri dengeli ilerliyor." },
      },
      {
        slug: "kuzeyin-son-isigi", title: "Kuzeyin Son Işığı", author: "Mira Aksoy", genre: "Fantastik", subgenre: "Genç yetişkin", completion: 54, chapters: 12, reads: "4,1 bin", comments: 53, updatedAt: "2 gün önce", momentum: "İstikrarlı üretim", potential: "Özgün evren ve güçlü ses", coverVariant: "three",
      },
      {
        slug: "zamanin-izleri", title: "Zamanın İzleri", author: "Deniz Yalın", genre: "Bilim Kurgu", subgenre: "Zaman yolculuğu", completion: 76, chapters: 21, reads: "9,2 bin", comments: 97, updatedAt: "3 gün önce", momentum: "Yükselişte", potential: "Yüksek kavramsal derinlik", coverVariant: "two",
        editorReview: { editor: "Derya Ekin", summary: "Merkez fikir güçlü; olay örgüsü giderek berraklaşıyor." },
      },
    ],
    chapters: [
      { number: 1, title: "Haritadaki Boşluk", words: "2.451 kelime", status: "Okunabilir" },
      { number: 2, title: "Taş Kapı", words: "2.806 kelime", status: "Okunabilir" },
      { number: 3, title: "Sessiz Muhafız", words: "3.014 kelime", status: "Okunabilir" },
      { number: 4, title: "Yeraltındaki Nehir", words: "2.672 kelime", status: "Okunabilir" },
      { number: 5, title: "Eski Yemin", words: "2.933 kelime", status: "Okunabilir" },
    ],
    readerSignals: [
      { label: "Dünya ve atmosfer", value: 92, note: "Okurlar mekân anlatımını özellikle güçlü buluyor." },
      { label: "Karakter bağı", value: 84, note: "Aras’ın motivasyonu son bölümlerde daha görünür." },
      { label: "Bölüm devamlılığı", value: 88, note: "Bölüm sonları okumaya devam etme isteği yaratıyor." },
    ],
  },
} as const;
