export const publishersContent = {
  metadataTitle: "Yayınevleri | İlkOku",
  metadataDescription: "Doğrulanmış yayınevlerini keşfedin ve mevcut yayın süreçlerinizi takip edin.",
  eyebrow: "Yayın yolculuğu",
  title: "Yayınevleri",
  description: "Doğrulanmış yayınevlerini inceleyin ve daha önce başlayan yayınevi süreçlerinizi tek yerden takip edin.",
  legacyNoticeTitle: "Başvuru modeli yenilendi",
  legacyNoticeDescription: "Yeni doğrudan yayınevi başvuruları kapalıdır. Yayınevleri eserleri İlkOku keşif alanından inceler; daha önce başlattığınız başvuru, sözleşme ve yayın planı süreçleri aşağıda korunur.",
  searchLabel: "Yayınevi ara",
  searchPlaceholder: "Yayınevi adına göre ara",
  filterLabel: "Yayınevlerini filtrele",
  filters: { all: "Tümü", applied: "Sürecim olanlar" },
  stats: { publishers: "Doğrulanmış yayınevi", active: "Aktif süreç" },
  verified: "Doğrulanmış",
  network: "İlkOku keşif ağı",
  website: "Web sitesini aç",
  noPublishersTitle: "Uygun yayınevi bulunamadı",
  noPublishersDescription: "Arama veya filtreyi değiştirerek yeniden deneyin.",
  submissionsTitle: "Mevcut süreçlerim",
  submissionsDescription: "Daha önce başlattığınız yayınevi değerlendirme, sözleşme ve yayın planı süreçlerini takip edin.",
  tabs: { all: "Tümü", pending: "Bekleyen", reviewing: "İnceleniyor", accepted: "Kabul Edilen", rejected: "Reddedilen", withdrawn: "Geri Çekilen" },
  statuses: { pending: "Bekliyor", reviewing: "İnceleniyor", accepted: "Kabul Edildi", rejected: "Reddedildi", withdrawn: "Geri Çekildi" },
  withdraw: "Geri Çek",
  withdrawConfirm: "Bu başvuruyu geri çekmek istediğinizden emin misiniz?",
  noSubmissionsTitle: "Geçmiş bir yayınevi süreciniz yok",
  noSubmissionsDescription: "Yayınevleri yeni eserleri İlkOku keşif alanından inceler. Burada yalnız daha önce başlamış süreçleriniz gösterilir.",
  dashboard: { title: "Yayınevi Süreçlerim", pending: "Bekleyen", reviewing: "İncelenen", accepted: "Kabul", all: "Tümünü Gör", empty: "Henüz bir yayınevi süreciniz bulunmuyor." },
} as const;
