export const publishersContent = {
  metadataTitle: "Yayınevleri | İlkOku",
  metadataDescription: "Doğrulanmış yayınevlerini keşfedin ve eser başvurularınızı yönetin.",
  eyebrow: "Yayın yolculuğu",
  title: "Yayınevleri",
  description: "Doğrulanmış yayınevlerini inceleyin, uygun eserinizle başvurun ve süreci tek yerden takip edin.",
  searchLabel: "Yayınevi ara",
  searchPlaceholder: "Yayınevi adına göre ara",
  filterLabel: "Yayınevlerini filtrele",
  filters: { all: "Tümü", available: "Başvuru kabul edenler", applied: "Başvuru yaptıklarım" },
  stats: { publishers: "Doğrulanmış yayınevi", active: "Aktif başvuru" },
  verified: "Doğrulanmış",
  accepts: "Başvuru kabul ediyor",
  website: "Web sitesini aç",
  apply: "Başvuru Yap",
  applied: "Başvuru yapıldı",
  noPublishersTitle: "Uygun yayınevi bulunamadı",
  noPublishersDescription: "Arama veya filtreyi değiştirerek yeniden deneyin.",
  submissionsTitle: "Başvurularım",
  submissionsDescription: "Gönderdiğiniz eserlerin yayınevi değerlendirme durumlarını takip edin.",
  tabs: { all: "Tümü", pending: "Bekleyen", reviewing: "İnceleniyor", accepted: "Kabul Edilen", rejected: "Reddedilen", withdrawn: "Geri Çekilen" },
  statuses: { pending: "Bekliyor", reviewing: "İnceleniyor", accepted: "Kabul Edildi", rejected: "Reddedildi", withdrawn: "Geri Çekildi" },
  modal: { title: "Yayınevine Başvur", work: "Başvurulacak eser", chooseWork: "Eser seçin", coverLetter: "Kısa ön yazı", coverLetterHint: "20–3000 karakter", cancel: "Vazgeç", submit: "Başvuruyu Gönder", close: "Başvuru penceresini kapat" },
  withdraw: "Geri Çek",
  withdrawConfirm: "Bu başvuruyu geri çekmek istediğinizden emin misiniz?",
  noSubmissionsTitle: "Henüz başvurunuz yok",
  noSubmissionsDescription: "Uygun bir yayınevi seçerek ilk eser başvurunuzu oluşturabilirsiniz.",
  dashboard: { title: "Yayınevi Başvurularım", pending: "Bekleyen", reviewing: "İncelenen", accepted: "Kabul", all: "Tümünü Gör", empty: "Henüz yayınevi başvurunuz bulunmuyor." },
} as const;
