import { commonContent } from "./navigation";

export const readingContent = {
  common: {
    homeLabel: commonContent.homeLabel,
    back: commonContent.back,
    share: "Paylaş",
    save: "Kaydet",
    category: "Kategori",
    completion: "Tamamlanma",
    totalChapters: "Toplam Bölüm",
    comments: "Yorumlar",
    bookCover: (title: string) => `${title} kitap kapağı`,
    completionLabel: (value: number) => `Kitabın tamamlanma oranı yüzde ${value}`,
  },
  chapter: {
    metadataTitle: "Bölüm Oku | İlkOku",
    metadataDescription: "Yayınlanmış bir eserin bölümünü İlkOku'da oku.",
    skip: "Bölüm metnine geç",
    tools: "Okuma araçları",
    shareLabel: "Bu bölümü paylaş",
    saveLabel: "Bu bölümü kaydet",
    experience: "Okuma deneyimi",
    readingTime: "Okuma süresi",
    readerOpinions: "Okur görüşleri",
    comments: "Yorumlar",
    writeOpinion: "Görüşünü Yaz",
    commentLabel: "Yorumun",
    commentPlaceholder: "Bu bölüm sende nasıl bir iz bıraktı?",
    submitComment: "Yorum Gönder",
    readerComments: "Okur yorumları",
    bookAndAuthorInfo: "Kitap ve yazar bilgileri",
    authorInfo: "Yazar Bilgisi",
    author: "Yazar",
    lastUpdate: "Son Güncelleme",
  },
  showcase: {
    metadataTitle: "Eser Vitrini | İlkOku",
    metadataDescription: "Yayınlanmış eserleri İlkOku'da keşfet.",
    skip: "Kitap bilgilerine geç",
    tools: "Kitap vitrini araçları",
    shareLabel: "Bu eseri paylaş",
    saveLabel: "Bu eseri kaydet",
    eyebrow: "Okurların keşfettiği hikâye",
    status: "Durum",
    reads: "Okunma",
    comment: "Yorum",
    publicationDate: "Yayın tarihi",
    firstChapter: "İlk Bölümü Oku",
    introduction: "Eser tanıtımı",
    backCover: "Arka kapak",
    tags: "Eser etiketleri",
    readerOpinions: "Okur görüşleri",
    latestComments: "Son yorumlar",
    latestFiveComments: "Son 5 okur yorumu",
    allComments: "Tüm yorumları gör",
    authorInfo: "Yazar bilgileri",
    author: "Yazar",
    novelist: "Roman yazarı",
    totalWorks: "Toplam eser",
    joinedPlatform: "Platforma katılım",
    otherWorks: "Diğer eserleri",
    continueReading: "Okumaya devam et",
    similarWorks: "Benzer eserler",
    originalWork: "İlkOku özgün eser",
    novelBy: "Bir İlkOku eseri",
  },
} as const;
