export const workspaceContent = {
  metadataTitle: "Eserlerim | İlkOku",
  metadataDescription: "Eserlerini, bölümlerini ve arşivini tek merkezden yönet.",
  eyebrow: "Yazar Çalışma Alanı",
  title: "Eserlerim",
  description: "Hikâyelerini düzenle, yazmaya kaldığın yerden devam et ve arşivini yönet.",
  activeTab: "Eserler",
  archiveTab: "Arşiv",
  searchLabel: "Eser ara",
  searchPlaceholder: "Başlığa göre ara",
  sortLabel: "Sıralama",
  sortOptions: {
    updated: "Son düzenlenen",
    oldest: "En eski",
    title: "Başlığa göre",
    chapters: "Bölüm sayısına göre",
  },
  stats: {
    total: "Toplam eser",
    active: "Arşiv dışı eser",
    archived: "Arşivdeki eser",
    chapters: "Toplam bölüm",
    words: "Toplam kelime",
  },
  edit: "Eseri İncele",
  continueWriting: "Yazmaya Devam Et",
  archive: "Arşivle",
  restore: "Arşivden Çıkar",
  chapter: "bölüm",
  word: "kelime",
  lastEdited: "Son düzenleme",
  emptyActive: "Aramana uyan eser bulunamadı.",
  emptyArchive: "Arşivinde eser bulunmuyor.",
  editTitle: "Eseri İncele",
  closeEdit: "Eser inceleme penceresini kapat",
  fields: {
    title: "Başlık",
    summary: "Özet",
    genre: "Tür",
    language: "Dil",
    coverUrl: "Kapak URL",
    status: "Yayın durumu",
  },
  statuses: {
    draft: "Taslak",
    in_progress: "Devam ediyor",
    published: "Yayında",
    completed: "Tamamlandı",
    archived: "Arşivlendi",
  },
  save: "Değişiklikleri Kaydet",
} as const;
