import { getBookIndexSource } from "./sources";

export type BookIndexListDefinition = {
  code: string;
  sourceCode: string;
  title: string;
  categoryKey: string;
  period: "live" | "daily" | "weekly" | "monthly" | "yearly";
  sourceUrl: string;
  maxRank: number | null;
  includeInComposite: boolean;
  collectionEveryMinutes: number | null;
  publiclyVisible: boolean;
  enabled: boolean;
};

export const BOOK_INDEX_LISTS: readonly BookIndexListDefinition[] = [
  {
    code: "remzi-tr-weekly",
    sourceCode: "remzi",
    title: "Remzi'de Çok Satanlar · Türkçe",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.remzi.com.tr/anasayfa",
    maxRank: 15,
    includeInComposite: true,
    collectionEveryMinutes: 1440,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "bkm-tr-weekly",
    sourceCode: "bkm",
    title: "BKM Kitap · Haftalık Çok Satanlar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.bkmkitap.com/cok-satan-kitaplar",
    maxRank: 50,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "bkm-tr-monthly",
    sourceCode: "bkm",
    title: "BKM Kitap · Aylık Çok Satanlar",
    categoryKey: "general",
    period: "monthly",
    sourceUrl: "https://www.bkmkitap.com/cok-satan-kitaplar",
    maxRank: 50,
    includeInComposite: false,
    collectionEveryMinutes: 720,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "bkm-tr-yearly",
    sourceCode: "bkm",
    title: "BKM Kitap · Yıllık Çok Satanlar",
    categoryKey: "general",
    period: "yearly",
    sourceUrl: "https://www.bkmkitap.com/cok-satan-kitaplar",
    maxRank: 50,
    includeInComposite: false,
    collectionEveryMinutes: 1440,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsepeti-tr-live",
    sourceCode: "kitapsepeti",
    title: "KitapSepeti · Çok Satan Kitaplar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapsepeti.com/cok-satan-kitaplar",
    maxRank: 60,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitaplarsepette-tr-live",
    sourceCode: "kitaplarsepette",
    title: "KitaplarSepette · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitaplarsepette.com/cok-satanlar",
    maxRank: 30,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapzen-tr-weekly",
    sourceCode: "kitapzen",
    title: "Kitapzen · Haftalık Çok Satanlar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.kitapzen.com/index.php?mod_id=41&p=ProductBestsellers&page=1&period=weekly",
    maxRank: 60,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapzen-tr-monthly",
    sourceCode: "kitapzen",
    title: "Kitapzen · Aylık Çok Satanlar",
    categoryKey: "general",
    period: "monthly",
    sourceUrl: "https://www.kitapzen.com/index.php?mod_id=41&p=ProductBestsellers&page=1&period=monthly",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 720,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapzen-tr-yearly",
    sourceCode: "kitapzen",
    title: "Kitapzen · Yıllık Çok Satanlar",
    categoryKey: "general",
    period: "yearly",
    sourceUrl: "https://www.kitapzen.com/index.php?mod_id=41&p=ProductBestsellers&page=1&period=yearly",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 1440,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "inkilap-tr-live",
    sourceCode: "inkilap",
    title: "İnkılâp Kitabevi · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.inkilap.com/cok-satanlar",
    maxRank: 60,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsec-edebiyat-live",
    sourceCode: "kitapsec",
    title: "KitapSeç · Edebiyat Çok Satan Kitaplar",
    categoryKey: "edebiyat",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Products/Edebiyat/Cok-Satan-Kitaplar/1-6-0a0-0-0-0-0-0.xhtml",
    maxRank: 48,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsec-cocuk-genclik-live",
    sourceCode: "kitapsec",
    title: "KitapSeç · Çocuk ve Gençlik Çok Satan Kitaplar",
    categoryKey: "cocuk-genclik",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Products/Cocuk-ve-Genclik-Kitaplari/Cok-Satan-Kitaplar/",
    maxRank: 48,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsec-general-live",
    sourceCode: "kitapsec",
    title: "KitapSeç · Genel Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Cok-Satanlar/1-6-0a0-0-0-0-0-0-4.xhtml",
    maxRank: 56,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  {
    code: "kitapsec-general-live-canary",
    sourceCode: "kitapsec",
    title: "KitapSeç · Genel Çok Satanlar · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Cok-Satanlar/1-6-0a0-0-0-0-0-0-4.xhtml",
    maxRank: 56,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "illakitap-tr-weekly",
    sourceCode: "illakitap",
    title: "İlla Kitap · Haftalık Çok Satanlar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.illakitap.com/en-cok-satanlar?period=weekly&rec_per_page=100&page=1",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "nobelkitap-tr-live",
    sourceCode: "nobelkitap",
    title: "NobelKitap · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.nobelkitap.com/cok-satanlar",
    maxRank: 50,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "idefix-tr-live",
    sourceCode: "idefix",
    title: "idefix · Çok Satan Kitaplar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.idefix.com/cok-satanlar-l-162",
    maxRank: 24,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "pandora-tr-live",
    sourceCode: "pandora",
    title: "Pandora Kitabevi · Çok Satanlar · Türkçe",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.pandora.com.tr/Cok_Satan_Kitaplar",
    maxRank: 50,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  // Historical qualification canary retained for audit; live source-only collection now uses pandora-tr-live.
  {
    code: "pandora-tr-live-canary",
    sourceCode: "pandora",
    title: "Pandora Kitabevi · Çok Satanlar · Türkçe · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.pandora.com.tr/Cok_Satan_Kitaplar",
    maxRank: 50,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  {
    code: "kitapambari-tr-live",
    sourceCode: "kitapambari",
    title: "Kitap Ambarı · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapambari.com/cok-satanlar-1",
    maxRank: null,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  // Source-only qualification canary. Operator bias keeps Turkey composite voting off.
  {
    code: "kitapambari-tr-live-canary",
    sourceCode: "kitapambari",
    title: "Kitap Ambarı · Çok Satanlar · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapambari.com/cok-satanlar-1",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "kitapstore-tr-live",
    sourceCode: "kitapstore",
    title: "KitapStore · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapstore.com/liste/2/cok-satanlar/!Sayfa=1",
    maxRank: null,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  // Shadow-only qualification list. It collects natural history but never votes.
  {
    code: "kitapstore-tr-live-canary",
    sourceCode: "kitapstore",
    title: "KitapStore · Çok Satanlar · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapstore.com/liste/2/cok-satanlar/!Sayfa=1",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "amazon-tr-live",
    sourceCode: "amazon-tr",
    title: "Amazon Türkiye · Kitap Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.amazon.com.tr/gp/bestsellers/books",
    maxRank: null,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: false,
  },
] as const;

export function getBookIndexList(code: string) {
  return BOOK_INDEX_LISTS.find((list) => list.code === code) ?? null;
}

export function validateBookIndexListRegistry() {
  for (const list of BOOK_INDEX_LISTS) {
    if (!getBookIndexSource(list.sourceCode)) {
      throw new Error(`BOOK_INDEX_UNKNOWN_SOURCE:${list.sourceCode}`);
    }
  }
}
