import { validateBookIndexNewReleaseSourceRegistry } from "./new-release-sources";
import { getBookIndexSource } from "./sources";

export type BookIndexListDefinition = {
  code: string;
  sourceCode: string;
  title: string;
  categoryKey: string;
  period: "live" | "daily" | "weekly" | "monthly" | "yearly";
  sourceUrl: string;
  maxRank: number | null;
  includeInComposite: boolean;
  collectionEveryMinutes: number | null;
  publiclyVisible: boolean;
  enabled: boolean;
};

export const BOOK_INDEX_LISTS: readonly BookIndexListDefinition[] = [
  {
    code: "remzi-tr-weekly",
    sourceCode: "remzi",
    title: "Remzi'de Çok Satanlar · Türkçe",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.remzi.com.tr/anasayfa",
    maxRank: 15,
    includeInComposite: true,
    collectionEveryMinutes: 1440,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "bkm-tr-weekly",
    sourceCode: "bkm",
    title: "BKM Kitap · Haftalık Çok Satanlar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.bkmkitap.com/cok-satan-kitaplar",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "bkm-tr-monthly",
    sourceCode: "bkm",
    title: "BKM Kitap · Aylık Çok Satanlar",
    categoryKey: "general",
    period: "monthly",
    sourceUrl: "https://www.bkmkitap.com/cok-satan-kitaplar",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 720,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "bkm-tr-yearly",
    sourceCode: "bkm",
    title: "BKM Kitap · Yıllık Çok Satanlar",
    categoryKey: "general",
    period: "yearly",
    sourceUrl: "https://www.bkmkitap.com/cok-satan-kitaplar",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 1440,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsepeti-tr-live",
    sourceCode: "kitapsepeti",
    title: "KitapSepeti · Çok Satan Kitaplar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapsepeti.com/cok-satan-kitaplar",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitaplarsepette-tr-live",
    sourceCode: "kitaplarsepette",
    title: "KitaplarSepette · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitaplarsepette.com/cok-satanlar",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapzen-tr-weekly",
    sourceCode: "kitapzen",
    title: "Kitapzen · Haftalık Çok Satanlar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.kitapzen.com/index.php?mod_id=41&p=ProductBestsellers&page=1&period=weekly",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapzen-tr-monthly",
    sourceCode: "kitapzen",
    title: "Kitapzen · Aylık Çok Satanlar",
    categoryKey: "general",
    period: "monthly",
    sourceUrl: "https://www.kitapzen.com/index.php?mod_id=41&p=ProductBestsellers&page=1&period=monthly",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 720,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapzen-tr-yearly",
    sourceCode: "kitapzen",
    title: "Kitapzen · Yıllık Çok Satanlar",
    categoryKey: "general",
    period: "yearly",
    sourceUrl: "https://www.kitapzen.com/index.php?mod_id=41&p=ProductBestsellers&page=1&period=yearly",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 1440,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "inkilap-tr-live",
    sourceCode: "inkilap",
    title: "İnkılâp Kitabevi · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.inkilap.com/cok-satanlar",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsec-edebiyat-live",
    sourceCode: "kitapsec",
    title: "KitapSeç · Edebiyat Çok Satan Kitaplar",
    categoryKey: "edebiyat",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Products/Edebiyat/Cok-Satan-Kitaplar/1-6-0a0-0-0-0-0-0.xhtml",
    maxRank: 48,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsec-cocuk-genclik-live",
    sourceCode: "kitapsec",
    title: "KitapSeç · Çocuk ve Gençlik Çok Satan Kitaplar",
    categoryKey: "cocuk-genclik",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Products/Cocuk-ve-Genclik-Kitaplari/Cok-Satan-Kitaplar/",
    maxRank: 48,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapsec-general-live",
    sourceCode: "kitapsec",
    title: "KitapSeç · Genel Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Cok-Satanlar/1-6-0a0-0-0-0-0-0-4.xhtml",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  // Historical qualification canary retained for evidence; live voter now owns collection.
  {
    code: "kitapsec-general-live-canary",
    sourceCode: "kitapsec",
    title: "KitapSeç · Genel Çok Satanlar · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapsec.com/Cok-Satanlar/1-6-0a0-0-0-0-0-0-4.xhtml",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  {
    code: "illakitap-tr-weekly",
    sourceCode: "illakitap",
    title: "İlla Kitap · Haftalık Çok Satanlar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://www.illakitap.com/en-cok-satanlar?period=weekly&rec_per_page=100&page=1",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "nobelkitap-tr-live",
    sourceCode: "nobelkitap",
    title: "NobelKitap · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.nobelkitap.com/cok-satanlar",
    maxRank: 50,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "idefix-tr-live",
    sourceCode: "idefix",
    title: "idefix · Çok Satan Kitaplar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.idefix.com/cok-satanlar-l-162",
    maxRank: 24,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "pandora-tr-live",
    sourceCode: "pandora",
    title: "Pandora Kitabevi · Çok Satanlar · Türkçe",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.pandora.com.tr/Cok_Satan_Kitaplar",
    maxRank: 50,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  // Historical qualification canary retained for evidence; live voter now owns collection.
  {
    code: "pandora-tr-live-canary",
    sourceCode: "pandora",
    title: "Pandora Kitabevi · Çok Satanlar · Türkçe · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.pandora.com.tr/Cok_Satan_Kitaplar",
    maxRank: 50,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  {
    code: "kitapambari-tr-live",
    sourceCode: "kitapambari",
    title: "Kitap Ambarı · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapambari.com/cok-satanlar-1",
    maxRank: null,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  // Source-only qualification canary. Operator bias keeps Turkey composite voting off.
  {
    code: "kitapambari-tr-live-canary",
    sourceCode: "kitapambari",
    title: "Kitap Ambarı · Çok Satanlar · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapambari.com/cok-satanlar-1",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "imge-tr-live",
    sourceCode: "imge",
    title: "İmge Kitabevi · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.imge.com.tr/etiket/cok-satanlar?sort_type=7&size=100",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  {
    code: "kitapstore-tr-live",
    sourceCode: "kitapstore",
    title: "KitapStore · Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapstore.com/liste/2/cok-satanlar/!Sayfa=1",
    maxRank: 100,
    includeInComposite: true,
    collectionEveryMinutes: 360,
    publiclyVisible: true,
    enabled: true,
  },
  // Historical qualification canary retained for evidence; live voter now owns collection.
  {
    code: "kitapstore-tr-live-canary",
    sourceCode: "kitapstore",
    title: "KitapStore · Çok Satanlar · Canary",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.kitapstore.com/liste/2/cok-satanlar/!Sayfa=1",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: null,
    publiclyVisible: false,
    enabled: false,
  },
  {
    code: "nobelkitap-tr-new-releases",
    sourceCode: "nobelkitap",
    title: "NobelKitap · Raflara Yeni Gelenler",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.nobelkitap.com/yeni-cikanlar",
    maxRank: 50,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "inkilap-tr-new-releases",
    sourceCode: "inkilap",
    title: "İnkılâp Kitabevi · Yeni Çıkanlar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.inkilap.com/en-yeniler",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "kitapsepeti-tr-new-releases",
    sourceCode: "kitapsepeti",
    title: "KitapSepeti · Yeni Çıkan Kitaplar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.kitapsepeti.com/yeni-cikan-kitaplar",
    maxRank: 40,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "kitapzen-tr-new-releases",
    sourceCode: "kitapzen",
    title: "Kitapzen · Yeni Çıkanlar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.kitapzen.com/yeni-cikanlar-np51-1.html",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "illakitap-tr-new-releases",
    sourceCode: "illakitap",
    title: "İlla Kitap · Yeni Çıkan Kitaplar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.illakitap.com/yeni-cikan-kitaplar",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "pandora-tr-new-releases",
    sourceCode: "pandora",
    title: "Pandora Kitabevi · Yeni Kitaplar · Türkçe",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.pandora.com.tr/Yeni_Kitaplar/Turkce",
    maxRank: 40,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "kitapstore-tr-new-releases",
    sourceCode: "kitapstore",
    title: "KitapStore · Yeni Çıkanlar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.kitapstore.com/liste/1/yeni-cikanlar/!Sayfa=1",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "remzi-tr-new-releases",
    sourceCode: "remzi",
    title: "Remzi Kitabevi · En Yeniler",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.remzi.com.tr/kitaplarimiz/en-yeniler/",
    maxRank: 15,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "bkm-tr-new-releases",
    sourceCode: "bkm",
    title: "BKM Kitap · Yeni Çıkan Kitaplar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.bkmkitap.com/yeni-cikan-kitaplar",
    maxRank: 100,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "kitaplarsepette-tr-new-releases",
    sourceCode: "kitaplarsepette",
    title: "KitaplarSepette · Yeni Çıkanlar",
    categoryKey: "new-releases",
    period: "live",
    sourceUrl: "https://www.kitaplarsepette.com/",
    maxRank: 30,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "amazon-us-live",
    sourceCode: "amazon-us",
    title: "Amazon US · Best Sellers in Books",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.amazon.com/Best-Sellers-Books/zgbs/books",
    maxRank: 30,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "amazon-uk-live",
    sourceCode: "amazon-uk",
    title: "Amazon UK · Best Sellers in Books",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.amazon.co.uk/Best-Sellers-Books/zgbs/books",
    maxRank: 30,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "ibs-it-daily",
    sourceCode: "ibs-it",
    title: "IBS İtalya · Günlük Çok Satan Kitaplar",
    categoryKey: "general",
    period: "daily",
    sourceUrl: "https://www.ibs.it/classifica/libri/1day/sold?defaultPage=1",
    maxRank: 40,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "rakuten-jp-weekly",
    sourceCode: "rakuten-jp",
    title: "Rakuten Books Japonya · Haftalık Çok Satan Kitaplar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://rdc-api-catalog-gateway-api.rakuten.co.jp/books/rank/001/weekly.json?hits=30&page=1&period=0&sid=10",
    maxRank: 30,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "kyobo-kr-weekly",
    sourceCode: "kyobo-kr",
    title: "Kyobo Güney Kore · Haftalık Çok Satan Kitaplar",
    categoryKey: "general",
    period: "weekly",
    sourceUrl: "https://store.kyobobook.co.kr/api/gw/best/best-seller/online?page=1&per=20&period=002&dsplDvsnCode=001&dsplTrgtDvsnCode=002&saleCmdtDsplDvsnCode=TOT",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: true,
  },
  {
    code: "readings-au-monthly",
    sourceCode: "readings-au",
    title: "Readings Avustralya · Aylık Çok Satan Kitaplar",
    categoryKey: "general",
    period: "monthly",
    sourceUrl: "https://www.readings.com.au/news/categories/australian-fiction",
    maxRank: 20,
    includeInComposite: false,
    collectionEveryMinutes: 720,
    publiclyVisible: false,
    enabled: true,
  },




  {
    code: "amazon-tr-live",
    sourceCode: "amazon-tr",
    title: "Amazon Türkiye · Kitap Çok Satanlar",
    categoryKey: "general",
    period: "live",
    sourceUrl: "https://www.amazon.com.tr/gp/bestsellers/books",
    maxRank: null,
    includeInComposite: false,
    collectionEveryMinutes: 360,
    publiclyVisible: false,
    enabled: false,
  },
] as const;

export function getBookIndexList(code: string) {
  return BOOK_INDEX_LISTS.find((list) => list.code === code) ?? null;
}

export function validateBookIndexListRegistry() {
  validateBookIndexNewReleaseSourceRegistry();

  for (const list of BOOK_INDEX_LISTS) {
    if (!getBookIndexSource(list.sourceCode)) {
      throw new Error(`BOOK_INDEX_UNKNOWN_SOURCE:${list.sourceCode}`);
    }
  }
}
