export type BookIndexMarket = "TR" | "US" | "UK" | "IT" | "JP" | "KR" | "AU" | "DE" | "FR" | "ES" | "CA" | "NL" | "BR" | "FI" | "DK" | "SE" | "NO";
export type BookIndexSourcePhase = "v1" | "phase_2";
export type BookIndexCollectionState =
  | "planned"
  | "researching"
  | "ready"
  | "active"
  | "paused"
  | "blocked";

export type BookIndexSourceDefinition = {
  code: string;
  name: string;
  market: BookIndexMarket;
  countryCode: "TR" | "US" | "UK" | "IT" | "JP" | "KR" | "AU" | "DE" | "FR" | "ES" | "CA" | "NL" | "BR" | "FI" | "DK" | "SE" | "NO";
  baseUrl: string;
  includeInTurkeyIndex: boolean;
  independenceGroup?: string;
  operatorName?: string;
  phase: BookIndexSourcePhase;
  collectionState: BookIndexCollectionState;
};

export const TURKEY_INDEX_MIN_SOURCES = 3;

export const BOOK_INDEX_SOURCES: readonly BookIndexSourceDefinition[] = [
  {
    code: "bkm",
    name: "BKM Kitap",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.bkmkitap.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
    independenceGroup: "point-internet",
    operatorName: "Point İnternet Teknolojileri ve Lojistik A.Ş.",
  },
  {
    code: "dr",
    name: "D&R",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.dr.com.tr",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "idefix",
    name: "idefix",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.idefix.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "penguen",
    name: "Penguen Kitap",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.penguenkitap.com.tr",
    includeInTurkeyIndex: true,
    independenceGroup: "penguen-kitap",
    operatorName: "Penguen Kitap",
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "remzi",
    name: "Remzi Kitabevi",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.remzi.com.tr",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "amazon-tr",
    name: "Amazon Türkiye",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.amazon.com.tr",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "amazon-us",
    name: "Amazon ABD",
    market: "US",
    countryCode: "US",
    baseUrl: "https://www.amazon.com",
    includeInTurkeyIndex: false,
    independenceGroup: "amazon-us",
    operatorName: "Amazon US",
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "amazon-uk",
    name: "Amazon UK",
    market: "UK",
    countryCode: "UK",
    baseUrl: "https://www.amazon.co.uk",
    includeInTurkeyIndex: false,
    independenceGroup: "amazon-uk",
    operatorName: "Amazon UK",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "ibs-it",
    name: "IBS İtalya",
    market: "IT",
    countryCode: "IT",
    baseUrl: "https://www.ibs.it",
    includeInTurkeyIndex: false,
    independenceGroup: "ibs-it",
    operatorName: "IBS.it",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "rakuten-jp",
    name: "Rakuten Books Japonya",
    market: "JP",
    countryCode: "JP",
    baseUrl: "https://books.rakuten.co.jp",
    includeInTurkeyIndex: false,
    independenceGroup: "rakuten-jp",
    operatorName: "Rakuten Books",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "kyobo-kr",
    name: "Kyobo Book Centre Güney Kore",
    market: "KR",
    countryCode: "KR",
    baseUrl: "https://store.kyobobook.co.kr",
    includeInTurkeyIndex: false,
    independenceGroup: "kyobo-kr",
    operatorName: "Kyobo Book Centre",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "readings-au",
    name: "Readings Avustralya",
    market: "AU",
    countryCode: "AU",
    baseUrl: "https://www.readings.com.au",
    includeInTurkeyIndex: false,
    independenceGroup: "readings-au",
    operatorName: "Readings",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "spiegel-de",
    name: "SPIEGEL Almanya · Kurgu Hardcover",
    market: "DE",
    countryCode: "DE",
    baseUrl: "https://shop.spiegel.de",
    includeInTurkeyIndex: false,
    independenceGroup: "spiegel-de",
    operatorName: "SPIEGEL Shop / BuchMarkt",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "amazon-fr",
    name: "Amazon Fransa",
    market: "FR",
    countryCode: "FR",
    baseUrl: "https://www.amazon.fr",
    includeInTurkeyIndex: false,
    independenceGroup: "amazon-fr",
    operatorName: "Amazon France",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "amazon-es",
    name: "Amazon İspanya",
    market: "ES",
    countryCode: "ES",
    baseUrl: "https://www.amazon.es",
    includeInTurkeyIndex: false,
    independenceGroup: "amazon-es",
    operatorName: "Amazon España",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "amazon-ca",
    name: "Amazon Kanada",
    market: "CA",
    countryCode: "CA",
    baseUrl: "https://www.amazon.ca",
    includeInTurkeyIndex: false,
    independenceGroup: "amazon-ca",
    operatorName: "Amazon Canada",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "amazon-br",
    name: "Amazon Brezilya",
    market: "BR",
    countryCode: "BR",
    baseUrl: "https://www.amazon.com.br",
    includeInTurkeyIndex: false,
    independenceGroup: "amazon-br",
    operatorName: "Amazon Brasil",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "bestseller60-nl",
    name: "De Bestseller 60 · Hollanda",
    market: "NL",
    countryCode: "NL",
    baseUrl: "https://www.debestseller60.nl",
    includeInTurkeyIndex: false,
    independenceGroup: "bestseller60-nl",
    operatorName: "Stichting CPNB",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "kirjakauppaliitto-fi",
    name: "Kirjakauppaliitto Finlandiya",
    market: "FI",
    countryCode: "FI",
    baseUrl: "https://kirjakauppaliitto.fi",
    includeInTurkeyIndex: false,
    independenceGroup: "kirjakauppaliitto-fi",
    operatorName: "Kirjakauppaliitto",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "pubhub-dk",
    name: "Publizon Pubhub Danimarka · E-kitap",
    market: "DK",
    countryCode: "DK",
    baseUrl: "https://service.pubhub.dk",
    includeInTurkeyIndex: false,
    independenceGroup: "pubhub-dk",
    operatorName: "Publizon A/S",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "forlaggare-se",
    name: "Svenska Förläggareföreningen İsveç · Kurgu",
    market: "SE",
    countryCode: "SE",
    baseUrl: "https://forlaggare.se",
    includeInTurkeyIndex: false,
    independenceGroup: "forlaggare-se",
    operatorName: "Svenska Förläggareföreningen",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "boklista-no",
    name: "Bokhandlerforeningen Norveç · Aylık Top 50",
    market: "NO",
    countryCode: "NO",
    baseUrl: "https://bokhandlerforeningen.no",
    includeInTurkeyIndex: false,
    independenceGroup: "boklista-no",
    operatorName: "Bokhandlerforeningen",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "abc-gfk-es",
    name: "ABC Cultural / GfK İspanya · Kurgu Top 10",
    market: "ES",
    countryCode: "ES",
    baseUrl: "https://www.abc.es/cultura/cultural/",
    includeInTurkeyIndex: false,
    independenceGroup: "abc-gfk-es",
    operatorName: "ABC Cultural / GfK-NIQ",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "globe-mail-ca",
    name: "The Globe and Mail Kanada · Hardcover Fiction",
    market: "CA",
    countryCode: "CA",
    baseUrl: "https://www.theglobeandmail.com",
    includeInTurkeyIndex: false,
    independenceGroup: "globe-mail-ca",
    operatorName: "The Globe and Mail",
    phase: "phase_2",
    collectionState: "ready",
  },




  {
    code: "kitapsepeti",
    name: "KitapSepeti",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.kitapsepeti.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
    independenceGroup: "point-internet",
    operatorName: "Point İnternet Teknolojileri ve Lojistik A.Ş.",
  },
  {
    code: "kitapsec",
    name: "KitapSeç",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.kitapsec.com",
    includeInTurkeyIndex: true,
    independenceGroup: "kitapsec",
    operatorName: "KİTAPSEÇ YAYINCILIK ELEKTRONİK NAKLİYE MAKİNA İNŞAAT TAAHHÜT SANAYİ VE TİCARET LİMİTED ŞİRKETİ",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "kitapzen",
    name: "Kitapzen",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.kitapzen.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "inkilap",
    name: "İnkılâp Kitabevi",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.inkilap.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "illakitap",
    name: "İlla Kitap",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.illakitap.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "nobelkitap",
    name: "NobelKitap",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.nobelkitap.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
  },
  {
    code: "kitaplarsepette",
    name: "KitaplarSepette",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.kitaplarsepette.com",
    includeInTurkeyIndex: true,
    phase: "v1",
    collectionState: "ready",
    independenceGroup: "iklim-grup",
    operatorName: "İklim Grup Kitap Satış Dağıtım Ltd. Şti.",
  },
  {
    code: "pandora",
    name: "Pandora Kitabevi",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.pandora.com.tr",
    includeInTurkeyIndex: true,
    independenceGroup: "pandora",
    operatorName: "Pandora Yayın ve Kitap Hizmetleri A.Ş.",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "kitapambari",
    name: "Kitap Ambarı",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.kitapambari.com",
    includeInTurkeyIndex: true,
    independenceGroup: "kitapambari",
    operatorName: "Ötüken Neşriyat A.Ş.",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "imge",
    name: "İmge Kitabevi",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.imge.com.tr",
    includeInTurkeyIndex: true,
    independenceGroup: "imge",
    operatorName: "İmge Yayıncılık Ltd. Şti.",
    phase: "phase_2",
    collectionState: "ready",
  },
  {
    code: "kitapstore",
    name: "KitapStore",
    market: "TR",
    countryCode: "TR",
    baseUrl: "https://www.kitapstore.com",
    includeInTurkeyIndex: true,
    independenceGroup: "vedat-akoglu-kitapstore",
    operatorName: "Vedat Akoğlu - KitapStore",
    phase: "phase_2",
    collectionState: "ready",
  },
] as const;

export const BOOK_INDEX_V1_SOURCES = BOOK_INDEX_SOURCES.filter(
  (source) => source.phase === "v1",
);

export const TURKEY_INDEX_V1_SOURCES = BOOK_INDEX_V1_SOURCES.filter(
  (source) => source.includeInTurkeyIndex,
);

export function getBookIndexSource(code: string) {
  return BOOK_INDEX_SOURCES.find((source) => source.code === code) ?? null;
}

export function getBookIndexSourceIndependenceGroup(code: string) {
  const source = getBookIndexSource(code);
  return source?.independenceGroup ?? source?.code ?? code;
}

export function getBookIndexSourceOperatorName(code: string) {
  const source = getBookIndexSource(code);
  return source?.operatorName ?? source?.name ?? code;
}
