import { normalizeBookIndexText } from "./html";

const TURKISH_TITLE_MEANINGS: Readonly<Record<string, string>> = {
  "The Steps: A Memoir": "Adımlar: Bir Anı",
  "Threshing Day (Standard Edition) (The Empyrean)": "Harman Günü",
  "A Court of Splintered Harmony: The Valkyrie Cycle, Movement I (A Court of Thorns and Roses, 6)": "Parçalanmış Uyum Sarayı",
  "Theo of Golden: A Novel": "Golden'lı Theo",
  "Protocols: An Operating Manual for the Human Body": "Protokoller: İnsan Bedeni İçin Bir Kullanım Kılavuzu",
  "Verity": "Hakikat",
  "The French Illusion: A Novel (The French Illusion Series)": "Fransız Yanılsaması",
  "Threshing Day (Wing and Claw Collection) (The Empyrean)": "Harman Günü",
  "The Calamity Club: A Novel": "Felaket Kulübü",
  "Paint by Sticker Kids (Official): Halloween: Create 10 Pictures One Sticker at a Time! Includes Glow-in-the-Dark Stickers": "Çıkartmayla Boyama Çocuklar: Cadılar Bayramı",
  "Swan Song: Diana, my sister": "Kuğu Şarkısı: Kız Kardeşim Diana",
  "Murdoku: 80 Murder Mystery Logic Puzzles": "Murdoku: 80 Cinayet Gizemi Mantık Bulmacası",
  "The Love Hypothesis": "Aşk Hipotezi",
  "A Court of Forgotten Melody: The Valkyrie Cycle, Movements II & III (A Court of Thorns and Roses, 7)": "Unutulmuş Melodi Sarayı",
  "The Witch (Deluxe Edition)": "Cadı",
  "The Long-Lived King: An Original The Owl House Graphic Novel": "Uzun Ömürlü Kral",
  "You're My Little Baby Boo (Board Book for Babies and Toddlers 0-2 years old)": "Benim Küçük Bebek Hayaletimsin",
  "The Leaf Thief: (The Perfect Fall Book for Children and Toddlers)": "Yaprak Hırsızı",
  "Biscuit Visits the Pumpkin Patch: A Fun and Friendly Adventure for Toddlers Celebrating Fall, Halloween, and Pumpkin Picking": "Biscuit Balkabağı Tarlasını Ziyaret Ediyor",
  "The Little Ghost Who Was a Quilt (A Little Ghost Quilt Book)": "Yorgan Olan Küçük Hayalet",
  "The Very Hungry Caterpillar's Peekaboo Halloween": "Çok Aç Tırtılın Cadılar Bayramı Saklambacı",
  "Whistler: A Novel": "Islıkçı",
  "The Very Hungry Caterpillar": "Çok Aç Tırtıl",
  "I Love You to the Moon and Back": "Seni Aya Kadar ve Geri Seviyorum",
  "Fight or Flight (Diary of a Wimpy Kid #21): A laugh-out-loud knockout from the #1 international bestselling Diary of a Wimpy": "Savaş ya da Kaçış",
  "PlantYou Quickies: 140+ Nourishing Plant-Based Recipes for Busy People": "PlantYou Hızlı Tarifler",
  "Yesteryear: A GMA Book Club Pick: A Novel": "Geçmiş Yıllar",
  "American Hagwon": "Amerikan Dershanesi",
  "The Two-Body Problem": "Üç Cisim Problemi",
  "Little Blue Truck's Halloween: A Fun And Interactive Lift-the-Flap Book For Kids Celebrating Halloween With Little Blue Truck": "Küçük Mavi Kamyon'un Cadılar Bayramı",
  "Threshing Day (Limited Deluxe Edition): Return to the Empyrean world with thirteen stories starring your favourite Fourth Win": "Harman Günü",
  "Gruffalo Granny: The brand new Gruffalo picture book adventure: 3 (The Gruffalo, 3)": "Gruffalo Büyükanne",
  "A Court of Splintered Harmony: The Valkyrie Cycle, Movement I (A Court of Thorns and Roses)": "Parçalanmış Uyum Sarayı",
  "Swan Song: Diana, my sister. Beautiful. Beloved. Hunted.": "Kuğu Şarkısı: Kız Kardeşim Diana",
  "Letters to Our Sons": "Oğullarımıza Mektuplar",
  "Verity: The thriller that will capture your heart and blow your mind, from the author of IT ENDS WITH US": "Hakikat",
  "A Court of Forgotten Melody: The Valkyrie Cycle, Movements II & III (A Court of Thorns and Roses)": "Unutulmuş Melodi Sarayı",
  "20 Minute Meals: Real Fast Food": "20 Dakikalık Yemekler",
  "We Chase Shadows: The latest novel in the new murder mystery series from the bestselling author of The Thursday Murder Club:": "Gölgeleri Kovalıyoruz",
  "The Steps: The powerful new memoir from the Academy Award-winning actor and icon": "Adımlar",
  "Adam and Eve: The new unforgettable final novel from the master storyteller – a gripping WWII historical fiction novel for 20": "Adem ve Havva",
  "Bunny vs Monkey: Day of the Heroes! (a Phoenix Comic book, from the multi-million-selling creative genius Jamie Smart)": "Tavşan Maymuna Karşı: Kahramanlar Günü!",
  "The Correspondent: Winner of the Women’s Prize for Fiction 2026": "Muhabir",
  "The Killer Isn't Alice: The Bestselling Interactive Murder Mystery Puzzle Book - 46,600 Suspects, 1 Killer. Can You Solve the": "Katil Alice Değil",
  "Diary of a Wimpy Kid: Fight or Flight (Book 21): THE NEXT HILARIOUS BOOK IN THE BESTSELLING SERIES": "Saftirik Greg'in Günlüğü: Savaş ya da Kaçış",
  "Ottolenghi SIMPLE TOO": "Ottolenghi BASİT 2",
  "Careless People: The #1 Sunday Times bestselling memoir that Meta doesn't want you to read": "Dikkatsiz İnsanlar",
  "The Ultimate Chinese Takeaway Bible: Over 150 classic recipes to make at home": "Çin Paket Servisi Mutfağının Büyük Kitabı",
  "One Christmas Eve: A brand-new picture book about Percy the Park Keeper for 2026. The perfect Christmas gift for toddlers and": "Bir Noel Arifesi",
  "Stick Man The Pumpkin Hunt: a lift-the-flap adventure by the number one bestselling author and illustrator of The Gruffalo, S": "Çöp Adam: Balkabağı Avı",
  "Lottie Brooks’s Twelve Disasters of Christmas: Twelve festive short stories from the mega-bestselling author of the Lottie Br": "Lottie Brooks'un Noel'in On İki Felaketi",
  "Guinness World Records 2027": "Guinness Dünya Rekorları 2027",
  "Spooky Cutie: A cute and comfy colouring book, perfect for Halloween (Coco Wyo)": "Sevimli Ürperti",
  "Protocols: Simple, essential tools to transform your health - the #1 Sunday Times bestseller from the creator of Huberman Lab": "Protokoller",
  "Murder at the Grand Alpine Hotel: Agatha Christie’s iconic Miss Marple, reimagined by the globally acclaimed and Sunday Times": "Büyük Alp Oteli'nde Cinayet",
  "Murdoku: 80 Murder Mystery Logic Puzzles: Volume 1 – The Perfect Gift for Puzzlers and Cosy Crime Fans!": "Murdoku: 80 Cinayet Gizemi Mantık Bulmacası",
  "The Names: 'The best debut novel in years' Sunday Times": "İsimler",
  "Pinch of Nom Meal Prep: Prep-Ahead & Quick Assembly Slimming Meals With 2 Weekly Meal Plans": "Pinch of Nom Yemek Hazırlığı",
  "Little Wandle at Home First Phonics Flashcards for Reception: Phases 2 and 3 (Big Cat Phonics for Little Wandle Letters and S": "Little Wandle Evde İlk Fonetik Kartları",
  "Phonics Flashcards - Read Write Inc Home - Set 1 Speed Sounds - Early Reading & Literacy for ages 4-6 - Ruth Miskin - EYFS &": "Fonetik Kartları: İlk Okuma ve Yazma",
  "L'inganno francese": "Fransız Aldatmacası",
  "Threshing day. Ediz. italiana": "Harman Günü",
  "L'uomo che inventò la politica. Inchiesta su Machiavelli": "Siyaseti İcat Eden Adam: Machiavelli Üzerine Soruşturma",
  "Quando l'Italia rinacque. Il nostro Rinascimento": "İtalya Yeniden Doğduğunda: Bizim Rönesansımız",
  "Canto del cigno. Diana, mia sorella": "Kuğu Şarkısı: Kız Kardeşim Diana",
  "Felice": "Mutlu",
  "Calde le pere! Storia di un fiume e di una integerrima fanciulla": "Sıcak Armutlar! Bir Nehir ve Tertemiz Bir Genç Kızın Hikâyesi",
  "Il gioco del gatto. Un'indagine dell'avvocato Meroni": "Kedi Oyunu: Avukat Meroni Soruşturması",
  "Quando c'era lei. L'Italia dopo Giorgia Meloni": "O Varken: Giorgia Meloni Sonrası İtalya",
  "Il libro segreto di Forza Nuova": "Forza Nuova'nın Gizli Kitabı",
  "Falsa pista": "Yanlış İz",
  "Le cose in natura semplicemente crescono": "Doğadaki Şeyler Sadece Büyür",
  "Le voci degli altri": "Başkalarının Sesleri",
  "L'amore è una banana": "Aşk Bir Muzdur",
  "Altri mondi oltre a questo": "Bunun Ötesindeki Dünyalar",
  "Magnifica humanitas. Lettera Enciclica sulla custodia della persona umana nel tempo dell’intelligenza artificiale": "Muhteşem İnsanlık: Yapay Zekâ Çağında İnsanı Korumak Üzerine Genelge",
  "Tutto qui. La costruzione di una vita": "Hepsi Bu: Bir Hayatın İnşası",
  "La scala di seta": "İpek Merdiven",
  "Il mestiere del buio": "Karanlığın Mesleği",
  "Malinconico Blues": "Melankolik Blues",
  "Essere nuvola": "Bulut Olmak",
  "L'ultimo turno": "Son Vardiya",
  "Liberi tutti. Con cartolina illustrata in omaggio": "Herkes Özgür",
  "The steps. Come sono diventato Rocky Balboa": "Adımlar: Nasıl Rocky Balboa Oldum",
  "Il ladro di zucche. Ediz. a colori": "Balkabağı Hırsızı",
  "Gli anni in bianco e nero": "Siyah Beyaz Yıllar",
  "Cafonal. Gli «italioni» nel mirino di «Dagospia». Ediz. illustrata": "Cafonal: Dagospia'nın Hedefindeki Büyük İtalyanlar",
  "L'età della prepotenza. Perché i nuovi imperi sono destinati a fallire": "Zorbalık Çağı: Yeni İmparatorluklar Neden Çökmeye Mahkûm",
  "Delitto e castigo": "Suç ve Ceza",
  "Io che ti ho voluto così bene": "Seni Böyle Çok İstedim",
  "Il fattore gatto": "Kedi Faktörü",
  "Oltre. Uno si ritira e gli succede di tutto. Che poi tocca pure raccontarlo": "Ötesi",
  "Il mio migliore amico è un fantasma": "En İyi Arkadaşım Bir Hayalet",
  "Falsi amici. Qualcosa che ho imparato su amore, violenza e altre sfumature del potere": "Sahte Dostlar",
  "I tramezzini di Rocco Schiavone": "Rocco Schiavone'nin Sandviçleri",
  "La nostra giovinezza": "Gençliğimiz",
  "Manuale di diritto civile": "Medeni Hukuk El Kitabı",
  "Codice civile 2026": "Medeni Kanun 2026",
  "Quando le gru volano a sud": "Turnalar Güneye Uçtuğunda",
  "Il cantico della terra": "Yeryüzünün Ezgisi",
  "【特典】パペットスンスン ガイドブック(シールシート)": "Puppet Sunsun Rehber Kitabı (Çıkartma Sayfalı)",
  "anan No.2518 Special Edition": "anan No.2518 Özel Baskı",
  "自分とか、ないから。 教養としての東洋哲学": "Ben Diye Bir Şey Yok: Genel Kültür Olarak Doğu Felsefesi",
  "パンどろぼうとさすらいラーメン": "Ekmek Hırsızı ve Gezgin Ramen",
  "子どもが喜ぶことだけすればいい": "Sadece Çocuğu Sevindiren Şeyleri Yap",
  "証券マンひりひり日記": "Bir Borsacının Yakıcı Günlüğü",
  "秘密にしたい魅惑のスイーツレシピ": "Gizli Tutmak İstediğim Büyüleyici Tatlı Tarifleri",
  "ダービースタリオン2 最速ガイドブック": "Derby Stallion 2 En Hızlı Rehber Kitabı",
  "【楽天ブックス限定デジタル特典】地球の歩き方 アニメ Dr．STONE(『地球の歩き方 アニメ Dr.STONE』楽天限定壁紙ダウンロード特典)": "Dünyayı Gezen Rehber: Dr. STONE Animesi",
  "これ、かなりマジです。時間・お金・心を整える365の言葉": "Bu Gerçekten Ciddi: Zamanı, Parayı ve Zihni Düzenleyen 365 Söz",
  "雨穴の家": "Uketsu'nun Evi",
  "日経エンタテインメント！ BIOHAZARD 30th Special": "Nikkei Entertainment! BIOHAZARD 30. Yıl Özel",
  "JR東日本版 みどりの駅時計BOOK2 暗闇で光る! 蛍光色Ver.": "JR East Yeşil İstasyon Saati BOOK2: Karanlıkta Parlayan Sürüm",
  "働きながら1億貯めるAI株式投資の全手順": "Çalışırken 100 Milyon Yen Biriktirmek: Yapay Zekâ ile Hisse Yatırımının Tüm Adımları",
  "CHEER Vol.74": "CHEER Cilt 74",
  "命の燃やし方": "Hayatı Yakma Biçimi",
  "タッチペンで音が聞ける！はじめてずかん1000 英語つき": "Dokunmatik Kalemle Sesleri Duy! İlk Resimli Sözlük 1000",
  "【特典】GIANNA Plus #12 cover 金城碧海＆佐藤景瑚（JO1）(片観音ピンナップ)": "GIANNA Plus #12 Özel Kapak",
  "ドラゴンボールスーパーダイバーズ スタートダイブガイド": "Dragon Ball Super Divers Başlangıç Dalış Rehberi",
  "80代になるとたいていボケるか死ぬ。70代は神様から与えられた特別な時間": "80'lerine Gelince İnsan Genelde Bunuyor ya da Ölüyor; 70'ler Tanrı'nın Verdiği Özel Zamandır",
  "「会社四季報」業界地図 2027年版": "Şirket Shikiho Sektör Haritası 2027",
  "【Amazon.co.jp&楽天ブックス限定付録付き特別定価版】 開運招福！桜井識子のパワースポットカレンダーBOOK2027": "İyi Şans ve Bereket! Sakurai Shiko'nun Güç Noktaları Takvimi 2027",
  "3秒でハッピーになる超名言100 20周年プレミアムカバー": "3 Saniyede Mutlu Eden 100 Efsane Söz",
  "【楽天ブックス限定特典】別冊カドカワ総力特集 SUPER BEAVER(限定ステッカー)": "SUPER BEAVER Özel Dosyası",
  "【特典】GIANNA Plus #12 cover 藤本洸大＆簡秀吉(オリジナルステッカー)": "GIANNA Plus #12 Özel Kapak",
  "くもんなぜなぜカレンダー2027年版・市販用": "Kumon Neden-Niçin Takvimi 2027",
  "密教徒の秘儀で運命を動かす！ 奇跡を起こす！": "Ezoterik Budistlerin Gizli Ritüelleriyle Kaderini Değiştir! Mucizeler Yarat!",
  "魔法使いの夜 下": "Büyücünün Gecesi – Alt Cilt",
  "【楽天ブックス限定特典】日向坂46金村美玖2nd写真集「機微」(限定カバー+楽天ブックス限定A5フォトカード)": "Hinatazaka46 Miku Kanemura 2. Fotoğraf Kitabı 'İncelikler'",
  "ちいかわ ダイカット（2027年1月始まりカレンダー）": "Chiikawa Kesimli Takvim 2027",
  "세네카, 오늘을 빼앗기고 있는 당신에게": "Seneca, Bugünü Elinden Alınan Sana",
  "가호": "Himaye",
  "한국사 이상현상 연구원(일반판)": "Kore Tarihi Anomali Araştırma Enstitüsü",
  "머니 트렌드 2027": "Para Trendleri 2027",
  "흔한남매 23": "Sıradan Kardeşler 23",
  "싯다르타": "Siddhartha",
  "마음의 어휘력": "Kalbin Kelime Hazinesi",
  "트렌드 코리아 2027": "Trend Kore 2027",
  "시대예보: 수고인류의 시간": "Çağ Tahmini: Emek İnsanlığının Zamanı",
  "군주론 : 쇼츠 에디션": "Hükümdar: Kısa Baskı",
  "돈의 흐름을 읽는 최소한의 경제 공부": "Para Akışını Okumak İçin Asgari Ekonomi Bilgisi",
  "쇼펜하우어 인생수업(30만 부 기념 개정증보판)": "Schopenhauer'dan Hayat Dersleri",
  "빵충 사육 준수 사항": "Ekmek Böceği Yetiştirme Kuralları",
  "룩 백 스페셜 에디션": "Look Back Özel Baskı",
  "모순": "Çelişki",
  "옥스브리지의 철학 수업": "Oxbridge Felsefe Dersleri",
  "테오": "Theo",
  "박완서의 낱말들": "Park Wan-suh'un Kelimeleri",
  "나의 첫 번째 부동산 교과서": "İlk Gayrimenkul Ders Kitabım",
  "니체의 초월자": "Nietzsche'nin Üstinsanı",
  "Fierceland": "Vahşi Diyar",
  "Sophie, Standing There": "Sophie, Orada Dururken",
  "The Odyssey": "Odysseia",
  "The Things We Never Say": "Asla Söylemediğimiz Şeyler",
  "London Falling": "Londra Düşerken",
  "Regime Change": "Rejim Değişikliği",
  "Whistler": "Islıkçı",
  "The Correspondent": "Muhabir",
  "Good Witch": "İyi Cadı",
  "Heresies": "Sapkınlıklar",
  "Taiwan Travelogue": "Tayvan Seyahatnamesi",
  "Kitchen Confidential": "Mutfak Sırları",
  "John of John": "John'un John'u",
  "East of Eden": "Cennetin Doğusu",
  "Circe": "Kirke",
  "Big Little Truths": "Büyük Küçük Gerçekler",
  "Ransom": "Fidye",
  "What It Takes": "Ne Gerekiyorsa",
  "Three Shocks": "Üç Şok",
  "Broder": "Broder",
  "Alles wird Asche": "Her Şey Küle Dönecek",
  "1999 Meter über dem Meer": "Denizden 1999 Metre Yukarıda",
  "Rites of the Starling": "Sığırcığın Ritüelleri",
  "Das Vogelhaus": "Kuş Evi",
  "Frankie und Freddie": "Frankie ve Freddie",
  "Memories of Heidelberg": "Heidelberg Anıları",
  "Anton und Alma": "Anton ve Alma",
  "Die Lücken": "Boşluklar",
  "Theo in Golden": "Golden'daki Theo",
  "Die Riesinnen": "Dev Kadınlar",
  "Hummerjahre": "Istakoz Yılları",
  "Die zweitgrößte Liebe": "İkinci En Büyük Aşk",
  "Fünf, sechs, sieben, acht": "Beş, Altı, Yedi, Sekiz",
  "Ms Atkins und die Bibliothek der Träume": "Bayan Atkins ve Düşler Kütüphanesi",
  "Juras letzter Winter": "Jura'nın Son Kışı",
  "Und es wird trotzdem wieder Sommer werden": "Ve Yine de Yaz Tekrar Gelecek",
  "Alleinruhelage": "Yalnızlıkta Huzur",
  "Hinaus in den Wind": "Rüzgâra Doğru",
  "Le Casse du siècle": "Yüzyılın Soygunu",
  "Je jure de dire toute la vérité": "Tüm Gerçeği Söyleyeceğime Yemin Ederim",
  "Homo occidentalis": "Batılı İnsan",
  "Cahiers de Douai (oeuvre au programme Bac de français 2027, 1re générale & techno): suivi du parcours « Émancipations créatri": "Douai Defterleri",
  "C'était ça ou mourir: Prix du roman Fnac 2026": "Ya Buydu ya Ölmek",
  "Votre assiette optimisée: 130 recettes qui vont changer votre vie": "Optimize Edilmiş Tabağınız: Hayatınızı Değiştirecek 130 Tarif",
  "Threshing Day - Version Française": "Harman Günü – Fransızca Baskı",
  "Frigobloc Mensuel 2027 - Calendrier organiseur familial (de sept. 2026 à déc. 2027)": "Aylık Frigobloc 2027 – Aile Düzenleme Takvimi",
  "Magnifica humanitas - Magnifique humanité: Encyclique": "Muhteşem İnsanlık",
  "Résurrection: Le retour de la France éternelle": "Diriliş: Ebedî Fransa'nın Dönüşü",
  "Diana, ma soeur: Le chant du cygne": "Diana, Kız Kardeşim: Kuğu Şarkısı",
  "Plan comptable général - PCG - 2026-2027: Liste intégrale des comptes": "Genel Hesap Planı 2026–2027",
  "Pluie et vent sur Télumée Miracle - Edition pédagogique": "Télumée Miracle Üzerine Yağmur ve Rüzgâr",
  "Bleach Deluxe - Tome 01": "Bleach Deluxe – Cilt 1",
  "One Piece - Édition originale - Tome 113": "One Piece – Orijinal Baskı – Cilt 113",
  "J'active mon pouvoir anti-inflammatoire: Recettes, conseils et nouveaux réflexes pour une santé durable": "İltihap Karşıtı Gücümü Harekete Geçiriyorum",
  "On ne badine pas avec l'amour (oeuvre au programme du Bac de français 2027, 1re générale & techno): suivi du parcours « Les j": "Aşkla Şaka Olmaz",
  "Antigone": "Antigone",
  "Organiseur familial Mémoniak 2027, calendrier organisation familiale mensuel (sept. 2026- déc. 2027)": "Mémoniak Aile Planlayıcısı 2027",
  "Petit Pays - Prix Goncourt des Lycéens 2016": "Küçük Ülke",
  "Une jeunesse au temps de la Shoah: Extraits d'Une vie": "Holokost Döneminde Bir Gençlik",
  "Coffret Lettres magnétiques \"Céline Alvarez Les Lectures naturelles\"": "Manyetik Harf Seti: Céline Alvarez Doğal Okumalar",
  "Code civil 2027 annoté. Édition limitée. 126e éd.": "Açıklamalı Medeni Kanun 2027",
  "Fichier photocopiable Histoire - Géographie Cycle 2 (CP - CE1 - CE2) conforme aux programmes 2026: Fiches prêtes à l’emploi p": "Fotokopilenebilir Tarih-Coğrafya Dosyası – 2. Kademe",
  "C'est MON corps !": "Bu BENİM Bedenim!",
  "A Dictionary of Color Combinations": "Renk Kombinasyonları Sözlüğü",
  "Le voleur de feuilles": "Yaprak Hırsızı",
  "La rivière à l'envers - tome 1: Tomek": "Tersine Akan Nehir – Cilt 1: Tomek",
  "L'Odyssée": "Odysseia",
  "El día de la Trilla (Empíreo) Edición limitada con cantos tintados (Planeta Internacional)": "Harman Günü",
  "Murdoku: 80 acertijos de lógica y asesinatos: 80 acertijos de lógica y asesinatos (Voces de hoy)": "Murdoku: 80 Mantık ve Cinayet Bulmacası",
  "MENTIRA: 71 (PREMIO EDEBÉ)": "YALAN",
  "Invisible (Nube de Tinta)": "Görünmez",
  "El día de la Trilla (Empíreo) (Planeta Internacional)": "Harman Günü",
  "La Celestina - Clasicos Adaptados N/c (Clásicos Adaptados) - 9788431615116": "Celestina (Çöpçatan Kadın)",
  "Murdoku: Viaje al pasado: 80 acertijos de lógica y asesinatos (Voces de hoy)": "Murdoku: Geçmişe Yolculuk",
  "BURLINGTON SKILLS FOR 2 BACH STUDENT'S BOOK (BACHILLERATO)": "Burlington Beceriler: 2. Bakalorya Öğrenci Kitabı",
  "Diccionario ilustrado latín-español/ español-latín (VOX - Lenguas clásicas)": "Resimli Latince-İspanyolca / İspanyolca-Latince Sözlük",
  "El príncipe de la niebla": "Sisler Prensi",
  "Redes (Invisible 2) (Nube de Tinta)": "Ağlar",
  "LAS LÁGRIMAS DE SHIVA: 1 (Premio Edebé Periscopio)": "Şiva'nın Gözyaşları",
  "El árbol de la ciencia (Letras Hispánicas)": "Bilgi Ağacı",
  "Los Huérfanos (Autores Españoles e Iberoamericanos)": "Yetimler",
  "El hombre ideal (Novela)": "İdeal Erkek",
  "La Humanidad en crisis: La Supraconciencia es la oportunidad para el cambio (No Ficción)": "İnsanlık Krizde: Değişim İçin Fırsat Olarak Üstbilinç",
  "El Hombre en busca de Sentido (fuera de colección)": "İnsanın Anlam Arayışı",
  "Finis mundi: 117 (El Barco de Vapor Roja)": "Dünyanın Sonu",
  "EDITO A1 ELEVE ED22": "Edito A1 Öğrenci Kitabı",
  "Synchronize 4 Workbook": "Synchronize 4 Çalışma Kitabı",
  "EL LADRÓN DE HOJAS (Miau)": "Yaprak Hırsızı",
  "Adolescencia: Comprender los cambios físicos, emocionales, cerebrales y sociales en la etapa más intensa y transformadora de": "Ergenlik: Fiziksel, Duygusal, Beyinsel ve Sosyal Değişimleri Anlamak",
  "English File 5th Edition B1. Student's Book and Workbook and digital with Key Pack": "English File 5. Baskı B1: Ders ve Çalışma Kitabı",
  "El fin del mundo tal y como lo conocíamos: La nueva era de la economía global: cómo entender lo que viene y proteger tu futur": "Bildiğimiz Dünyanın Sonu",
  "OPTIONS ESO 4 WB SPA (CHOICES)": "OPTIONS ESO 4 İspanyolca Çalışma Kitabı",
  "Marina: 5019 (Biblioteca Carlos Ruiz Zafón)": "Marina",
  "La psicología del dinero. Cómo piensan los ricos: 18 lecciones sobre riqueza y felicidad (Empresa y Talento)": "Paranın Psikolojisi: Zenginler Nasıl Düşünür",
  "La plaça del Diamant: 1 (Club Editor Jove)": "Elmas Meydanı",
  "Threshing Day (Wing and Claw Collection)": "Harman Günü",
  "A Court of Splintered Harmony: The Valkyrie Cycle, Movement I": "Parçalanmış Uyum Sarayı",
  "The Calamity Club": "Felaket Kulübü",
  "Fight or Flight (Diary of a Wimpy Kid #21) (Volume 21)": "Savaş ya da Kaçış",
  "Into the Breach: A Soldier's Journey": "Çatışmanın İçine: Bir Askerin Yolculuğu",
  "Strangers: A Memoir of Marriage": "Yabancılar: Bir Evlilik Anısı",
  "The Gate of the Feral Gods": "Vahşi Tanrıların Kapısı",
  "Yesteryear: A Novel": "Geçmiş Yıllar",
  "A Court of Forgotten Melody: The Valkyrie Cycle, Movements II and III (Volume 7)": "Unutulmuş Melodi Sarayı",
  "Little Blue Truck's Halloween: A Fun And Interactive Lift-the-Flap Book For Kids Celebrating Halloween With Little Blue Truck And Friends": "Küçük Mavi Kamyon'un Cadılar Bayramı",
  "Murdoku Volume 2: Back in Time: 80 Murder Mystery Logic Puzzles": "Murdoku Cilt 2: Geçmişe Dönüş",
  "A Parade of Horribles (Volume 8)": "Dehşetler Geçidi",
  "Trust Fall": "Güven Testi",
  "Carl's Doomsday Scenario": "Carl'ın Kıyamet Senaryosu",
  "The 48 Laws of Power": "İktidarın 48 Yasası",
  "The Pumpkin Thief": "Balkabağı Hırsızı",
  "Spooky Cutie: Coloring Book for Adults and Teens Featuring Adorable Creepy Creatures in Cozy Hygge Moments for Relaxation": "Sevimli Ürperti",
  "End Times Fascism: And the Fight for the Living World": "Son Zamanlar Faşizmi: Yaşayan Dünya İçin Mücadele",
  "The Dungeon Anarchist's Cookbook (Volume 3)": "Zindan Anarşistinin Yemek Kitabı",  "C'était ça ou mourir": "Ya Buydu ya Ölmek",
  "A Morte de Ivan Ilitch (2 ed.)": "İvan İlyiç'in Ölümü",
  "Corte de harmonias partidas (Vol. 6 Corte de espinhos e rosas) - acompanha sobrecapa e marcadores": "Parçalanmış Uyum Sarayı",
  "O Pequeno Príncipe – Edição de luxo com capa dura almofadada e aquarelas originais do autor": "Küçük Prens",
  "Box Clássicos de William Shakespeare - com 7 marcadores de páginas": "William Shakespeare Klasikleri Kutusu",
  "A hipótese do amor – Edição com sobrecapa do filme": "Aşk Hipotezi",
  "Jesus: O homem que dividiu o tempo": "İsa: Zamanı İkiye Bölen Adam",
  "Os irmãos Karamázov": "Karamazov Kardeşler",
  "Quando": "Ne Zaman",
  "Dia da Ceifa - no universo de o Empyriano (Coleção Asa e Garra)": "Harman Günü",
  "O diário de tarefas gnomosas do floreante viajante: Livro de bolso com chaveiro": "Gezgin Floreante'nin Cüce Görevleri Günlüğü",
  "A hora da estrela: Edição comemorativa": "Yıldızın Saati",
  "A cabeça do santo": "Aziz'in Başı",
  "Amor, teoricamente": "Teorik Olarak Aşk",
  "Dia da Ceifa – no universo de O Empyriano (Coleção Asa e Garra)": "Harman Günü",
  "As extraordinárias viagens de Júlio Verne - Box com 6 livros": "Jules Verne'in Olağanüstü Yolculukları",
  "Rita, não grita!": "Rita, Bağırma!",
  "O massacre da família Hope": "Hope Ailesi Katliamı",
  "Vidas secas": "Kurak Hayatlar",
  "As aventuras de Nando - Os mistérios da ilha": "Nando'nun Maceraları - Adanın Gizemleri",
  "A estranha na cama": "Yataktaki Yabancı",
  "Eu duvido você terminar este livro": "Bu Kitabı Bitirebileceğine İnanmıyorum",
  "O Show da Luna - Descobrindo os dinossauros": "Luna'nın Gösterisi - Dinozorları Keşfetmek",
  "Murdoku: 80 mistérios para resolver usando a lógica": "Murdoku: Mantıkla Çözülecek 80 Gizem",
  "A montanha mágica": "Büyülü Dağ",
  "De quanta terra precisa um homem? e outras histórias": "Bir İnsana Ne Kadar Toprak Gerekir? ve Diğer Öyküler",
  "Bons tempos: Yesteryear": "Güzel Günler: Geçmiş Yıllar",
  "Patrulha Canina - Verdadeiros campeões": "Paw Patrol - Gerçek Şampiyonlar",
  "A última carta": "Son Mektup",

  "De wereld rond met Project Gezond": "Project Gezond ile Dünya Turu",
  "Zwanenzang": "Kuğu Şarkısı",
  "De babyboomerbiljoenen": "Baby Boomer Trilyonları",
  "Het Belachelijk Fijne Boek voor Bange Dagen": "Korkulu Günler İçin İnanılmaz Güzel Kitap",
  "Het Waterpark": "Su Parkı",
  "De ongelooflijke geschiedenis": "İnanılmaz Tarih",
  "Johnnie Walker": "Johnnie Walker",
  "Ali Niknam": "Ali Niknam",
  "Lord M.": "Lord M.",
  "Gruffaloma": "Gruffaloma",
  "Takkie": "Takkie",
  "Agrippa": "Agrippa",
  "Solonaise": "Solonaise",
  "Even simpel": "Bir O Kadar Basit",
  "Dit wordt toch niks": "Bundan Bir Şey Olmaz",
  "Zwemmen in het geld": "Para İçinde Yüzmek",
  "Food = Fuel": "Yiyecek = Yakıt",
  "Met de trein door Europa": "Trenle Avrupa'yı Dolaşmak",
  "Je geld of je gegevens": "Paran mı, Verilerin mi",
  "De Zoete Zusjes stelen de show": "Tatlı Kız Kardeşler Gösteriyi Ele Geçiriyor",
  "Maantje verhuist de zee": "Maantje Denizi Taşıyor",
  "Yesteryear": "Geçmiş Yıllar",
  "De correspondente": "Muhabir",
  "Al het blauw van de hemel": "Gökyüzünün Tüm Mavisi",
  "Atlas van het dialect in Nederland": "Hollanda Lehçeleri Atlası",
  "De kreeftenvrouwen": "Istakoz Kadınları",
  "In het licht van de leugen": "Yalanın Işığında",
  "Ingesneeuwd in de Apple Spice B&B": "Apple Spice B&B'de Kar Altında Mahsur",
  "Rare jongens, die Tukkers": "Şu Tukkers da Tuhaf İnsanlar",
  "Als het thuis niet veilig is": "Ev Güvenli Değilse",
  "Baby ziet…": "Bebek Görüyor…",
  "Agent en Boef en het boefvangfeest": "Polis ve Hırsız ve Hırsız Yakalama Partisi",
  "De pompoendief": "Balkabağı Hırsızı",
  "Onderstroom": "Dip Akıntısı",
  "Terugkeer": "Dönüş",
  "Alex en de gemene tweelingbroer": "Alex ve Kötü Kalpli İkiz Kardeş",
  "Project RUST": "Huzur Projesi",
  "Schiet op, schildpadjes": "Hadi, Kaplumbağacıklar",
  "Geheimen van Rosewell Castle": "Rosewell Şatosu'nun Sırları",
  "Stille geheimen": "Sessiz Sırlar",
  "Protocols": "Protokoller",
  "Eindtijdfascisme": "Son Zamanlar Faşizmi",
  "Vergelding": "Misilleme",
  "De dichter en de duivel": "Şair ve Şeytan",
  "Aan het einde van de oorlog": "Savaşın Sonunda",
  "Hoofd boven water": "Başını Suyun Üstünde Tutmak",
  "Dit is AI": "Bu Yapay Zekâ",
  "Wat psychisch lijden is": "Ruhsal Acı Nedir",
  "De Griezels": "İğrençler",
  "Een haas in huis": "Evde Bir Tavşan",
  "Het Pumpkin Spice Latte drama": "Pumpkin Spice Latte Dramı",
  "Onthoud dit altijd": "Bunu Daima Hatırla",
  "The Let Them Theory": "Bırak Onları Teorisi",
  "Het ultieme geheim": "Nihai Sır",
  "Verder dan vrijheid": "Özgürlüğün Ötesinde",
  "Wen er maar aan": "Alışsan İyi Olur",
  "Rupsje Nooitgenoeg": "Hiç Doymayan Tırtıl",
  "De beer en de piano": "Ayı ve Piyano",
  "Rust, Regelmaat, Recepten": "Dinlenme, Düzen, Tarifler",

  "Tandfeen": "Diş Perisi",
  "1%": "Yüzde 1",
  "Ti vilde heste": "On Vahşi At",
  "Tata": "Tata",
  "Fra det dybe råber jeg": "Derinlerden Haykırıyorum",
  "Skyggen af et bedrag": "Bir Aldatmacanın Gölgesi",
  "Sommerfugleøen": "Kelebek Adası",
  "Muskelmad": "Kas Beslenmesi",
  "Styx": "Styx",

  "Hollow Bones": "İçi Boş Kemikler",
  "Dead Beat": "İşe Yaramaz",
  "Exit Party": "Çıkış Partisi",
  "We Chase Shadows": "Gölgeleri Kovalıyoruz",
  "The Knave and the Moon": "Düzenbaz ve Ay",
  "Our Noble Selves": "Asil Benliklerimiz",
  "Taipei Story": "Taipei Hikâyesi",
  "Tempest": "Fırtına",
  "The Dungeon Anarchist's Cookbook": "Zindan Anarşistinin Yemek Kitabı",

  "Systrarna på Sophiahemmet": "Sophiahemmet'teki Kız Kardeşler",
  "Medusa": "Medusa",
  "Blackout": "Karartma",
  "Domino": "Domino",
  "Slam": "Çamur",

  "Lähtölaukaus": "Başlangıç Atışı",
  "Kätketty": "Saklı",
  "Pronssiyö": "Bronz Gece",
  "Hydra": "Hidra",
  "Eilisvuosi": "Geçmiş Yıllar",
  "Vuokralainen": "Kiracı",
  "Minun Amerikkani": "Benim Amerikam",
  "Umpikujia ja ukkoskuuroja": "Çıkmaz Sokaklar ve Gök Gürültülü Sağanaklar",
  "Orkideahuijaus": "Orkide Dolandırıcılığı",
  "Nico Lingman: Sodassa ja rakkaudessa": "Nico Lingman: Savaşta ve Aşkta",
  "Kani joka tahtoi nukahtaa": "Uyumak İsteyen Tavşan",
  "Halla": "Kırağı",
  "Varjeltu": "Korunan",
  "Kissa ja hiiri": "Kedi ve Fare",
  "Joka yksin jää": "Yalnız Kalan",
  "Itsekkyyden aika : Miten yltiöyksilöllinen kulttuurimme sai meidät voimaan pahoin": "Bencillik Çağı: Aşırı Bireyci Kültürümüz Bizi Nasıl Kötü Hissettirdi",
  "Johtaja ja meedio - Tiina Lindforsin tarina": "Yönetici ve Medyum - Tiina Lindfors'un Hikâyesi",
  "Sopimus": "Anlaşma",
  "Valheiden vyyhti": "Yalanlar Yumağı",
  "Hillittömän hulluja satuja": "Çılgın mı Çılgın Masallar",

};

const NORMALIZED_TURKISH_TITLE_MEANINGS = new Map(
  Object.entries(TURKISH_TITLE_MEANINGS).map(([title, meaning]) => [
    normalizeBookIndexText(title),
    meaning,
  ]),
);

export function getBookIndexTurkishTitleMeaning(title: string) {
  return NORMALIZED_TURKISH_TITLE_MEANINGS.get(normalizeBookIndexText(title)) ?? null;
}
